### ISSUE TITLE
Oneplus Nord android 11, 22000 works, but 22005 failed to "repack"

### ISSUE THREAD

**Issue by Kylejustknows** [topjohnwu/Magisk#4074] opened 2021-03-21 16:38 UTC
Device: Oneplus Nord
Android version: Android 11
Magisk version name:  
Magisk version code: 22005 failed. 22000 passed. 22001~22004 not tested.

Oneplus Nord android 11, 22000 works, but 22005 failed to "repack"

Tested using both "TWRP" method and in-APP install/update method.

22005 keeps throwing me the "unable to repack boot image" error. 

22000 (the website download one, renamed apk to zip) works, with a minor bug as the "the bootloader is unlocked" warning stuck for >30 seconds every time reboot. I have to wait for a minute or so and it boots into the system normally and magisk function fully.

**Comment by osm0sis** [comment] 2021-03-21 19:31
You haven't provided an installation log. Sounds like it's probably just a duplicate of #4049.

**Closed by osm0sis** 2021-03-21 19:31 UTC
Labels: duplicate
