### ISSUE TITLE
Magisk fails to patch firmware file.

### ISSUE THREAD

**Issue by abdulhkeemGit** [topjohnwu/Magisk#8171] opened 2024-06-30 06:37 UTC
Device: SM-S918B
Android version: 14
Magisk version name: debug
Magisk version code: 27003 ([45fa1fce](https://github.com/topjohnwu/Magisk/commit/45fa1fce7009a43637d621411b8b95891bbcdfdc))

so patching file in magisk fails when it writes boot image, it says unpacking boot image then installation failed here is the log file.
firmware trying to patch is S918BXXS5CXE7.
[magisk_install_log_2024-06-30T10.29.48.log](https://github.com/user-attachments/files/16043470/magisk_install_log_2024-06-30T10.29.48.log)

**Comment by yujincheng08** [comment] 2024-06-30 10:20
Duplicate of #8083

**Closed by yujincheng08** 2024-06-30 10:20 UTC
