### ISSUE TITLE
v20 causes twrp and stock recovery not to boot (pie, op7 pro)

### ISSUE THREAD

**Issue by Ae3NerdGod** [topjohnwu/Magisk#1938] opened 2019-10-15 11:13 UTC
steps to reproduce:

1. msmdownloadtool or fastboot flash stock rom
2. fastboot boot twrp,  (optional) install twrp using zip (official or unofficial)
3. install magisk v20 zip
4. reboot recovery

boots to fastboot instead of recovery

only tried pie OOS 9.5.13

magisk19.3 works normally, rom boots fine on both versions

**Comment by Henrocker** [comment] 2019-10-15 11:23
Same on Sony J9110 with Pie

**Comment by osm0sis** [comment] 2019-10-15 12:05
Duplicate of #1920 ?

**Comment by Ae3NerdGod** [comment] 2019-10-15 12:12
@osm0sis
Whoops, seems to be. My bad, go ahead and close

**Comment by osm0sis** [comment] 2019-10-15 12:18
You can close it too. 😉

**Closed** 2019-10-15 12:20 UTC
