### ISSUE TITLE
late_start scripts never run

### ISSUE THREAD

**Issue by eebssk1** [topjohnwu/Magisk#1864] opened 2019-09-23 12:27 UTC
Device:Xiaomi Mi6 (sagit)
ROM:RR v7.0.2 (Android 9)
Magisk: magisk 19.4 manager 7.3.4 (tried last canary,same problem)

Problem:Scripts in /data/adb/service.d and service.sh in modules never run.It looks like magisk can not find scripts,but they are really present...

Magisk log > https://pastebin.com/gEQf1qb7
Things in /data/adb/service.d > https://paste.pics/6RSX8

Other:I remember that any scripts executed will be logged.Also there should be a log in /data/local if my scripts running normally.
I don't known what time the problem actully happenes,I just flashed the newest canany version and then found these aren't running anymore.

**Comment by Didgeridoohan** [comment] 2019-09-23 14:28
You have EdXposed installed and it is known to sometimes break the Magisk boot process (which is the case for you). Most likely not a Magisk issue, even though some users are reporting that they have not experienced the issue until Magisk v19.4.

**Comment by eebssk1** [comment] 2019-09-23 22:54
It's weired that manually run "magisk --service" in juicessh will work...

**Comment by neekless** [comment] 2019-09-24 01:33
For some reason your late_start service is running too early (line 14 in your magisk log)

**Comment by Didgeridoohan** [comment] 2019-09-24 04:08
> It's weired that manually run "magisk --service" in juicessh will work...

Not really... Like I said, the Magisk boot process is being broken by EdXposed. As pointed out by @neekless, it is causing the late_start service to run way too early, making the scripts in there useless. If you then run it manually, they'll of course work since there's nothing wrong with the scripts (just EdXposed).

**Comment by topjohnwu** [comment] 2019-09-24 06:52
Closed as issue is pointed out by @Didgeridoohan

**Closed by topjohnwu** 2019-09-24 06:52 UTC

**Comment by eebssk1** [comment] 2019-09-24 08:31
Hi.As you say it may caused by EdXp.Then i enabled Core Only mode and cleaned art cache.Unfortunately my scripts still won't run.

Log 下
`--------- beginning of main
--------- beginning of system
10-25 16:04:17.623  2469  2469 I Magisk  : Magisk v19.5-debd1d7d(19403) daemon started
10-25 16:04:17.624  2469  2469 I Magisk  : * Device API level: 28
10-25 16:04:17.659  2469  2471 I Magisk  : ** post-fs-data mode running
10-25 16:04:17.662  2469  2471 I Magisk  : * Initializing Magisk environment
10-25 16:04:17.664  2469  2471 I Magisk  : * Mounting mirrors
10-25 16:04:17.664  2469  2471 I Magisk  : mount: /sbin/.magisk/mirror/vendor
10-25 16:04:17.665  2469  2471 I Magisk  : mount: /sbin/.magisk/mirror/data
10-25 16:04:17.665  2469  2471 I Magisk  : link: /sbin/.magisk/mirror/system
10-25 16:04:17.665  2469  2471 I Magisk  : link: /sbin/.magisk/mirror/product
10-25 16:04:17.665  2469  2471 I Magisk  : * Setting up internal busybox
10-25 16:04:17.683  2469  2471 I Magisk  : * Running post-fs-data.d scripts
10-25 16:04:17.683  2469  2471 I Magisk  : post-fs-data.d: exec [kryoart.sh]
09-24 16:24:21.287  2469  3282 I Magisk  : ** late_start service mode running
09-24 16:24:22.427  2469  3533 I Magisk  : * Starting MagiskHide
09-24 16:24:22.427  2469  3533 I Magisk  : hide_policy: Hiding sensitive props
09-24 16:24:22.428  2469  3533 I Magisk  : hide_list init: [com.google.android.gms/com.google.android.gms.unstable]
09-24 16:24:22.449  2469  3533 I Magisk  : hide_list init: [org.microg.gms.droidguard/com.google.android.gms.unstable]
09-24 16:24:57.072  2469  5726 I Magisk  : ** boot_complete triggered
`

**Comment by Didgeridoohan** [comment] 2019-09-24 08:55
That log is pretty much unreadable...

But, it could very well be that your issue is caused by one of the scripts in post-fs-data.d. Those still run in Core Only Mode.

**Comment by eebssk1** [comment] 2019-09-24 09:09
if you want i can catch a full MB-sized log by using logcat in  post-fs-data.d with CoreOnly.Maybe it well be helpfull i think?

**Comment by Didgeridoohan** [comment] 2019-09-24 09:21
If I were you, I would run a completely clean Magisk installation (no modules installed, no boot scripts) and a test script in service.d. If that still fails there could actually be something about Magisk causing it... If it works, there's something else going on.

And the log is unreadable because you've just pasted it without any line breaks. It does look like the boot process isn't messed up without EdXposed active though...

**Comment by eebssk1** [comment] 2019-09-24 09:25
> If I were you, I would run a completely clean Magisk installation (no modules installed, no boot scripts) and a test script in service.d. If that still fails there could actually be something about Magisk causing it... If it works, there's something else going on.
> 
> And the log is unreadable because you've just pasted it without any line breaks. It does look like the boot process isn't messed up without EdXposed active though...

Thanks for the suggestion.I'll try it soon.

**Comment by eebssk1** [comment] 2019-09-24 10:45
@Didgeridoohan  Hi.After a lot of trying.I would say you're right.My scripts just blocked the whole post-fs-data.d and also influenced service.d.But it's a bit weired since the script does not have blocking process and it works well before.

Script if you want to know ↓
`#!/system/bin/sh
setprop dalvik.vm.isa.arm.variant kryo
setprop dalvik.vm.isa.arm64.variant kryo

setprop dalvik.vm.isa.arm.features armv8a
setprop dalvik.vm.isa.arm64.features -a53`

I just added "setsid" and "&",and now magisk works well now(with EdXposed lmao)

**Comment by jamesli1258** [comment] 2019-09-27 05:00
So a fresh install of magisk canary worked for you?

**Comment by eebssk1** [comment] 2019-09-27 07:29
> 
> 
> So a fresh install of magisk canary worked for you?

Nope.Actually it's just my scripts' fault.......
