### ISSUE TITLE
隱藏 Magisk Manager 失敗

### ISSUE THREAD

**Issue by Trevor1112** [topjohnwu/Magisk#2999] opened 2020-07-19 11:05 UTC
Pixel 4 XL Android 11 beta 隱藏 Magisk Manager 失敗
Log: [https://drive.google.com/file/d/10n8IR-NAqaiumHJudLizLqyp1LottA38/view?usp=drivesdk](https://drive.google.com/file/d/10n8IR-NAqaiumHJudLizLqyp1LottA38/view?usp=drivesdk)

**Comment by Didgeridoohan** [comment] 2020-07-19 14:25
Duplicate of #2975 

Please close

**Comment by Trevor1112** [comment] 2020-07-19 14:37
Manager Canary is failure for me too

**Closed** 2020-07-19 14:43 UTC
