### ISSUE TITLE
Realme 3 bootloop on RUI, but work on latest color os

### ISSUE THREAD

**Issue by haditriw** [topjohnwu/Magisk#2864] opened 2020-06-05 05:56 UTC
i only can upload boot stock and magisk patched boot with canary apk,, but still  got bootloop,, its canary on 20.4 because i dont know how to patch with old magisk zip ,, thanks 

[boot_stock_C11.zip](https://github.com/topjohnwu/Magisk/files/4734175/boot_stock_C11.zip)

[magisk_patched_C11.zip](https://github.com/topjohnwu/Magisk/files/4734180/magisk_patched_C11.zip)

**Comment by osm0sis** [comment] 2020-06-07 11:33
Your report isn't really understandable. It works on some ROMs but not others on your device?

**Comment by haditriw** [comment] 2020-06-07 11:36
I mean patchboot work on color os 6.0 android 9.0, and not work on realme ui based andeoid 10.. device is still same, realme 3 mediatek p60.. i pull stock boot.img from official firmware realme on their website.. both android version

**Comment by osm0sis** [comment] 2020-06-07 11:39
Upload the working stock boot.img for Android 9 and the not working one for Android 10.

**Comment by haditriw** [comment] 2020-06-07 11:47
[StockNPatchedA28.zip](https://github.com/topjohnwu/Magisk/files/4741988/StockNPatchedA28.zip)

This is working patched boot on android 9.0 color os version 6.0 last firmware version a.28

And android 10 has uploaded above.. when i install stock boot.img, its booting work on homescreen, but not for magisk patched boot.img

**Comment by osm0sis** [comment] 2020-06-07 11:58
Ah, I see it's A-only SAR with no ramdisk in the stock boot.img on Android 9, then with Android 10 it became A-only SAR with a 2SI ramdisk.

Have you tried patching and booting recovery.img instead? There are reports some other OEMs are taking Samsung's lead and making their boot.img not able to work patched with Android 10.

**Comment by haditriw** [comment] 2020-06-07 12:03
Ahhh.. its problem.. i dont have any stock recovery on android 10 😂

**Comment by osm0sis** [comment] 2020-06-07 12:05
What do you have for recovery? TWRP? Patch it instead then.

**Comment by haditriw** [comment] 2020-06-07 12:07
We dont have any recovery, twrp or stock because realme not release yet.. on android 9, they release it .. but on android 10 still not yet

**Comment by osm0sis** [comment] 2020-06-07 12:09
Not sure what to tell you.. Maybe try `fastboot boot  recovery.img` with a TWRP that worked on Android 9 or something so that you can dump your current recovery partition?

**Comment by 01soni247** [comment] 2020-06-07 12:15
> Not sure what to tell you.. Maybe try `fastboot boot twrp.img` with a TWRP that worked on Android 9 or something so that you can dump your current recovery partition?
> 
> Then you could patch that dumped recovery.img with Manager per those instructions.

It works fine but a problem on Android 10

**Comment by 01soni247** [comment] 2020-06-07 12:22
> What do you have for recovery? TWRP? Patch it instead then. See instructions here: https://topjohnwu.github.io/Magisk/install.html#magisk-in-recovery

how to take? if not root access?

**Comment by osm0sis** [comment] 2020-06-07 20:59
TWRP = root access, so if you have a TWRP that at least boots you should be able to get partition dumps.

**Comment by osm0sis** [comment] 2020-06-08 12:48
I think we'll consider this yet another duplicate of #2695. Follow along over there for potential workarounds and progress on the issue.

**Closed by osm0sis** 2020-06-08 12:48 UTC
Labels: duplicate

**Comment by 01soni247** [comment] 2020-06-14 08:09
> TWRP = root access, so if you have a TWRP that at least boots you should be able to get partition dumps.

we haven't found the appropriate twrp tree
