### ISSUE TITLE
Failed to update in recovery patch mode

### ISSUE THREAD

**Issue by NULL0B** [topjohnwu/Magisk#5673] opened 2022-04-01 03:41 UTC
Device:  Galaxy S10
Android version: 12 One UI 4.1
Magisk version name:  canary https://github.com/topjohnwu/Magisk/commit/704f91545e8433c382af25c136d06bee07684d7e
Magisk version code:  24305 

First the installer is not detecting that is installed in recovery mode and not marking the check box

![photo_2022-03-31_23-32-24](https://user-images.githubusercontent.com/26231330/161190038-e3ddf1d7-4ee0-4d00-ae27-9695bb6166e7.jpg)

So I'm marking it and selecting direct install here are the logs

[magisk_install_log_2022-03-31T23_35_19.log](https://github.com/topjohnwu/Magisk/files/8394516/magisk_install_log_2022-03-31T23_35_19.log)

After reboot the device stills in same old version and shows the following prompt

![photo_2022-03-31_23-32-15](https://user-images.githubusercontent.com/26231330/161190707-a9562ee8-9506-4b84-b167-74e18f433643.jpg)

Wich gets me to the first screenshoot  screen after accepting

Here are the current flashed boot.img and recovery,img, extracted from AP.tar patched  file using canary 24304 cause stable 24.3 was giving me vmbeta download mode error.

[recovery.img-boot.img-magisk_patched-24304.zip](https://github.com/topjohnwu/Magisk/files/8401039/recovery.img-boot.img-magisk_patched-24304.zip)

**Comment by luca990** [comment] 2022-04-01 21:53
If it can be useful I have the same problem on Samsung S5e (tablet) android 10, on other samsung devices where the ramdisk is present I had no problems.  With the previous version I solved it by re-patching the boot file and re-flashing with odin.  I have this error from the change: "Patch monolithic sepolicy only if not treble".

**Comment by NULL0B** [comment] 2022-04-02 15:37
If need more info just ask and I will provide instantly.

**Comment by VladWinner** [comment] 2022-04-03 16:22
I confirm this on Xiaomi Mi 9 SE (Android 11, Stable MIUI 12.5.4.0)

**Comment by NULL0B** [comment] 2022-04-08 16:38
Update:
The issue persists in canary 24306
 It says that aditional instllation needs to be performed(screenshot 2) and then takes me to the install screen(screenshoot 1)

**Comment by shivagnihotri** [comment] 2022-04-11 06:07
Thanks for mentioning #5693, it is related. I've been using canary 24306 and patched with `fastboot flash recovery magisk_patched-24306.img`. Nevertheless, Root is still gone when restarting my [SHIFT6mq](https://shop.shiftphones.com/shift6mq.html). To help with resolving this Issue and improving Magisk, I ran an `adb logcat -d > magisklog.txt` while restarting. [Here it is](https://github.com/topjohnwu/Magisk/files/8461423/magisklog.txt), dear @topjohnwu.

**Comment by shivagnihotri** [comment] 2022-04-17 14:49
Issue is still present using the latest canary build and the latest [LineageOS recovery for the SHIFT6mq](https://download.lineageos.org/axolotl). Which other logfiles may I provide so that developers can fix this Issue? I'd love to be rooted again. Greetings from Germany! ;-)

**Comment by rmjspaz7284** [comment] 2022-04-18 12:29
#

> Device: Galaxy S10 Android version: 12 One UI 4.1 Magisk version name: canary [704f915](https://github.com/topjohnwu/Magisk/commit/704f91545e8433c382af25c136d06bee07684d7e) Magisk version code: 24305
> 
> First the installer is not detecting that is installed in recovery mode and not marking the check box
> 
> ![photo_2022-03-31_23-32-24](https://user-images.githubusercontent.com/26231330/161190038-e3ddf1d7-4ee0-4d00-ae27-9695bb6166e7.jpg)
> 
> So I'm marking it and selecting direct install here are the logs
> 
> [magisk_install_log_2022-03-31T23_35_19.log](https://github.com/topjohnwu/Magisk/files/8394516/magisk_install_log_2022-03-31T23_35_19.log)
> 
> After reboot the device stills in same old version and shows the following prompt
> 
> ![photo_2022-03-31_23-32-15](https://user-images.githubusercontent.com/26231330/161190707-a9562ee8-9506-4b84-b167-74e18f433643.jpg)
> 
> Wich gets me to the first screenshoot screen after accepting
> 
> Here are the current flashed boot.img and recovery,img, extracted from AP.tar patched file using canary 24304 cause stable 24.3 was giving me vmbeta download mode error.
> 
> [recovery.img-boot.img-magisk_patched-24304.zip](https://github.com/topjohnwu/Magisk/files/8401039/recovery.img-boot.img-magisk_patched-24304.zip)

**Comment by rmjspaz7284** [comment] 2022-04-18 12:29
- [ ]

**Comment by rmjspaz7284** [comment] 2022-04-18 12:29
> * [ ]

**Comment by Swordfishx86** [comment] 2022-04-22 16:36
Same situation here. Samsung Galaxy S10e, shouldn't make a difference. Patched the AP-File with Magisk app and flashed with Odin. Made sure to not automatically reboot and rebootet manually, made sure to reboot in recovery by having USB connected and press Power-on, Bixby and volume-up (after manually exiting upload mode with Power-on, Bixby and volume-down). Result:

![image](https://user-images.githubusercontent.com/41929723/164757046-a27c7233-8752-4276-84d3-87ddb37f9bf1.png)

**Comment by NULL0B** [comment] 2022-04-22 16:44
> Same situation here. Samsung Galaxy S10e, shouldn't make a difference. Patched the AP-File with Magisk app and flashed with Odin (BL, AP, CP, HOME_CSC). Made sure to not automatically reboot by Odin but rebooted manually. Made sure to reboot into recovery by having USB connected and pressing Power-on, Bixby and volume-up (after manually exiting upload mode with Power-on, Bixby and volume-down). Result:
> 
> ![image](https://user-images.githubusercontent.com/41929723/164757046-a27c7233-8752-4276-84d3-87ddb37f9bf1.png)

Yes, fresh install is workin with canaries, stable produces vmbeta error i think. Or stable is not patching correctly if magisk is obfuscsted. Well if you fresh install with canaries it will work. The problem is when updating in app in derect install, recovery patch mode

**Comment by Swordfishx86** [comment] 2022-04-22 16:51
Please remove the full-quote. i had scruples posting the screenshot in the first place due to it's size (and i admit that i was too lazy to scale it down).
As I understand Stable won't work with A12 anyway. What does "Magisk is obfuscated" mean?
You are right, trying to update with Recovery-Checkmark ticked was what got me into this trouble in the first place. It's a shame that I don't remember if the first attempt was with the 24304 or with the 24306-App :(

**Comment by Peter0x44** [comment] 2022-04-22 22:39
I am having a similar issue on my Samsung Galaxy S2 SGH-T989
Renaming the apk to zip and (attempting to) flash it with twrp did not work.

Extracting the boot.img from my rom, patching it, flashing it with TWRP, results in the same prompt to reboot, every single time I open the magisk app. Rebooting makes absolutely no difference.
Though, superuser access appears to be working in this case.
adb shell, then su, then whoami does print root.

**Comment by oblus** [comment] 2022-04-24 23:45
Same fo mine S10e (a10). Root w Zygisk but cant flash 306. Stuck on 304 with same dialog at starup. Sometimes daemon crashes and I need to power off and power on (+Bxb+Vup).

[magisk_log_2022-04-25T01:29:27.log](https://github.com/topjohnwu/Magisk/files/8550720/magisk_log_2022-04-25T01.29.27.log)

**Comment by NULL0B** [comment] 2022-04-25 00:00
> Same fo mine S10e (a10). Root w Zygisk but cant flash 306. Stuck on 304 with same dialog at starup. Sometimes daemon crashes and I need to power off and power on (+Bxb+Vup).
> 
> [magisk_log_2022-04-25T01:29:27.log](https://github.com/topjohnwu/Magisk/files/8550720/magisk_log_2022-04-25T01.29.27.log)

I started noticing this in 304 and then repatched with 306 when was reñeased over the wrong patched 304 and i got a bootloop. I had to patch ap and reflash.

**Comment by oblus** [comment] 2022-04-25 14:16
> > Same fo mine S10e (a10). Root w Zygisk but cant flash 306. Stuck on 304 with same dialog at starup. Sometimes daemon crashes and I need to power off and power on (+Bxb+Vup).
> > [magisk_log_2022-04-25T01:29:27.log](https://github.com/topjohnwu/Magisk/files/8550720/magisk_log_2022-04-25T01.29.27.log)
> 
> I started noticing this in 304 and then repatched with 306 when was released over the wrong patched 304 and i got a bootloop. I had to patch ap and reflash.

ok. 
does patching ap and reflashing by odin mean factory reset?? coz this is too much :/

what I've tried:
I have old TWRP backup with older magisk, I patched boot.emmc.win (magisk 306 said "it went ok")
then I change name newly created img to boot.emmc.win and make sha2 file (sha256?).
I put back to my backup folder boot.emmc.win and boot.emmc.win.sha2 and change hash in recovery.log
and then restore only boot partition... twrp says "OK" - after reboot same thing :(

I think this should work but now Im confused...

**Comment by canyie** [comment] 2022-04-27 04:30
Upload installation log?

**Comment by oblus** [comment] 2022-04-27 11:10
> Upload installation log?
[magisk_log_2022-04-27T114755.log](https://github.com/topjohnwu/Magisk/files/8571414/magisk_log_2022-04-27T114755.log)
[magisk_log_2022-04-27T114720.log](https://github.com/topjohnwu/Magisk/files/8571415/magisk_log_2022-04-27T114720.log)

I've delete all modules (even disabled) and reboot my phone - I had to turn it off and power on (+Bxb+Vup) - simple reboot from magisk is not work.
I've attached my logs before and after installation from app. Ive checked "Recovery" option. Reboot and still same behaviour.

**Comment by oblus** [comment] 2022-04-27 14:07
> Does downgrade works? Try installing 24303, do direct install, save and send the installation log, reboot and see if the downgrade succeeded?

I think downgrade didnt work :/ or Im doin smth wrong?

[magisk_log_2022-04-27T155932.log](https://github.com/topjohnwu/Magisk/files/8572675/magisk_log_2022-04-27T155932.log)
[magisk_log_2022-04-27T155434.log](https://github.com/topjohnwu/Magisk/files/8572676/magisk_log_2022-04-27T155434.log)
[magisk_install_log_2022-04-27T155430.log](https://github.com/topjohnwu/Magisk/files/8572677/magisk_install_log_2022-04-27T155430.log)
[magisk_log_2022-04-27T155340.log](https://github.com/topjohnwu/Magisk/files/8572679/magisk_log_2022-04-27T155340.log)

![Screenshot_20220427-155906](https://user-images.githubusercontent.com/5584031/165537270-d0b7aa68-e0f0-4170-9e6e-ae1dd51e03ee.jpg)
![Screenshot_20220427-155917](https://user-images.githubusercontent.com/5584031/165537274-08318c98-c70b-4624-9fd1-ae935f38c75d.jpg)

**Comment by oblus** [comment] 2022-04-27 19:36
> @oblus [#5673 (comment)](https://github.com/topjohnwu/Magisk/issues/5673#issuecomment-1106681080)

@Swordfishx86 [#5678 (comment)](https://github.com/topjohnwu/Magisk/issues/5673#issuecomment-1106687155)

**Comment by canyie** [comment] 2022-04-28 09:20
Had you installed 24303 successfully in the old days? 
Will flash 24303/24306 via fastboot/odin work? You mentioned you get a bootloop when try to flash 24304, can you upload /sys/fs/pstore via TWRP when it bootloop, or grab a bug report?

**Comment by oblus** [comment] 2022-04-28 14:17
OK, I think I have it! 

I was doin everything wrong to get it to work again (like a gorilla in fog!).
Since I have S10e and TWRP I need to patch my recovery again not boot. So I downloaded fresh TWRP (twrp-beyond0lte-3.4.0-4_ianmacd.img), patched it by 24306 app with "recovery" option and in TWRP by cable and adb shell run this:
`f=/sdcard/magisk_patched-24306_80FWh.img; dd if=$f of=/dev/block/sda15 bs=$(stat -c%s $f)`

and Im in this:
![Screenshot_20220428-160619](https://user-images.githubusercontent.com/5584031/165771198-ab89d746-7e14-48a2-9654-cb09c103d262.jpg)

**but still we dont know what went wrong earlier and does this will happen again with future magisk release...**

thanks all

**Comment by canyie** [comment] 2022-04-29 01:53
You mean "reboot to recovery" from Magisk no longer works?

**Comment by NULL0B** [comment] 2022-04-29 02:12
If the question is with me... I mean updating magisk via direct install on a device previously correctly rooted via flashing ap file wich uses recovery partition to boot.
I think magisk should detect I booted from recovery and mark the checkmark on my device. Also when I marked it  and chose direct install in the next reboot the magisk version stills the same plus asking to finish installation with a dialog that takes me to the patch screen again. So I'm in a loop magisk showing same version and unfinished installation

**Comment by oblus** [comment] 2022-04-29 06:29
> You mean "reboot to recovery" from Magisk no longer works?

I mean "Reboot" - first position ( reboot through recovery i think ) it works without Vol+ BxB & Power keys

**Comment by DeltaOn3X** [comment] 2022-05-19 09:45
Same problem with version 24312. When i patch the AP file with the latest version (24312) and update my Note 10+ (A12) with the patched AP and home_csc its working fine. I also disabled auto reboot and rebooted manually like @Swordfishx86 said :)

**Comment by canyie** [comment] 2022-05-30 09:48
Any luck with Canary 24314?
1. Check if the installer can correctly detect recovery mode
2. Check if you can update magisk via direct install
3. Check if "Reboot" (first position) work
4. if the installer still does not detecting recovery mode, manually tick the check box and retry 2 and 3

**Comment by DeltaOn3X** [comment] 2022-06-01 06:56
> Any luck with Canary 24314?
> 
> 1. Check if the installer can correctly detect recovery mode
> 2. Check if you can update magisk via direct install
> 3. Check if "Reboot" (first position) work
> 4. if the installer still does not detecting recovery mode, manually tick the check box and retry 2 and 3

Same problem with 24314, when i update it always ask for the additional setup. When i patch the latest AP and update via Odin, everything works perfectly, this time even without turning off autoreboot. :)

**Comment by canyie** [comment] 2022-06-01 13:45
> What do you mean with "reboot" ? 

The blue reboot button at the buttom right, or the first "Reboot" button in the reboot menu.

**Comment by DeltaOn3X** [comment] 2022-06-02 08:53
Sorry for my late reply.

The first reboot button in the reboot menu works.
I sadly cant get ur Magisk version installed, the app-debug.apk is installable but it doesnt show up. App-release doesnt install at all.

**Comment by canyie** [comment] 2022-06-02 09:03
you need to switch to official debug builds before installing my build because of signature verification 🤔

**Comment by DeltaOn3X** [comment] 2022-06-02 09:13
i already did that :D Ive deleted my magisk app and installed the debug version. When i hit install i need to check the recovery box and when i hit direct install and reboot with the blue button at the buttom right (which works) im not in the additional setup loop. 



Im not even sure if im using ur build. Ive uninstalled my magisk app and installed ur app-debug version. Hit direct install and rebooted with the blue reboot button. No additional setup, everything is working.

![Screenshot_20220602-111246](https://user-images.githubusercontent.com/58166551/171597326-b609d1cf-38d9-45b0-8dfc-c37e07bf4656.jpg)

**Comment by canyie** [comment] 2022-06-02 11:03
So the installer still not detecting recovery mode? "Direct install" and "Reboot" is working again?
The version in the screenshot is not mine. Switch to "debug channel" in settings, install official debug app (you will see "(D)" in the app's version if you are already using it), install Magisk debug via "Direct Install". After reboot you will be able to install my build. 👍

**Comment by DeltaOn3X** [comment] 2022-06-02 12:29
Im so sorry, i thought i would see the (D) in the app version right after i change to the debug channel but i had to install it first. I just installed the debug version with direct install and rebooted with the blue reboot button at the buttom right. (reboot button worked and its not asking for additional setup)

After the reboot ive tried to install ur build (app-debug) but i cant open it. Whenever i open your build it closes again and than the app vanishes

when i first restore the original magisk, try to install ur version so it just updates the app, the app again vanishes. I really dont know if im just stupid right now.

Whatever i do, i end up in the canary version.

This is where i am right know after changing to debug channel, installing the debug app version and doing a direct install with a reboot:

![Screenshot_20220602-142845](https://user-images.githubusercontent.com/58166551/171629316-da49c29c-61a9-40d6-abd1-251bf658626d.jpg)

**Comment by canyie** [comment] 2022-06-03 12:31
Try patching image via debug app then flash it? "Direct Install" seems to be broken again

**Comment by DeltaOn3X** [comment] 2022-06-04 11:18
> Try patching image via debug app then flash it? "Direct Install" seems to be broken again

I flashed a patched image via the debug app and this is the result:

![Screenshot_20220604-131809](https://user-images.githubusercontent.com/58166551/171996745-e98222c0-9f6f-42c1-8ea4-280ad697d529.jpg)

**Comment by canyie** [comment] 2022-06-04 12:04
> do i have to delete my magisk app first and than install your debug version ?

yes

**Comment by DeltaOn3X** [comment] 2022-06-04 12:28
I have installed your old build (24314) and when i click on install the recovery box is ticked automatically. 

I can try this build from you if you want 

https://github.com/canyie/Magisk/actions/runs/2435472957

**Comment by canyie** [comment] 2022-06-05 08:28
can you update magisk via "Direct Install" in this build? can you take a screenshot after direct install and reboot?

**Comment by DeltaOn3X** [comment] 2022-06-05 10:40
I get the "additional setup" loop after hitting direct install with ur build (your build that can detect recovery)
Btw i forgot that my phone is on german language, i can change it for you to english ?

![Screenshot_20220605-123848](https://user-images.githubusercontent.com/58166551/172046638-8fb5581b-6fb1-4a00-b402-9ec0d64e3cf1.jpg)

**Comment by NULL0B** [comment] 2022-06-05 19:17
> I get the "additional setup" loop after hitting direct install with ur build (your build that can detect recovery) Btw i forgot that my phone is on german language, i can change it for you to english ?
> 
But if you click ok it will redirect you to the install screen again ending in a loop whitout being able to complete the full install process?

**Comment by DeltaOn3X** [comment] 2022-06-06 00:37
> > I get the "additional setup" loop after hitting direct install with ur build (your build that can detect recovery) Btw i forgot that my phone is on german language, i can change it for you to english ?
> 
> But if you click ok it redirects you to the install screen again ending in a loop whitout being able to complete the full install process?

When i do that i still end up in the loop, it just detects recovery on his build. The loop is still present :(

**Comment by canyie** [comment] 2022-06-06 03:32
Hmmm, so yes there are multi problems here. Needs more investigations to find out what's happening. 👍

**Comment by canyie** [comment] 2022-06-06 04:17
My guess is busybox broken on some special devices/kernel again (#5620)? Will send a build that revert busybox binary for testing. 👍

**Comment by canyie** [comment] 2022-06-06 14:12
[app-debug-2_sign.zip](https://github.com/topjohnwu/Magisk/files/8844941/app-debug-2_sign.zip)
Try this?

**Comment by DeltaOn3X** [comment] 2022-06-06 14:23
> [app-debug-2_sign.zip](https://github.com/topjohnwu/Magisk/files/8844941/app-debug-2_sign.zip) Try this?

That build doesnt detect recovery but when i tick it manually and hit direct install with reboot i dont end up in the loop

**Comment by canyie** [comment] 2022-06-06 15:32
> > [app-debug-2_sign.zip](https://github.com/topjohnwu/Magisk/files/8844941/app-debug-2_sign.zip) Try this?
> 
> That build doesnt detect recovery but when i tick it manually and hit direct install with reboot i dont end up in the loop

screenshot?

**Comment by DeltaOn3X** [comment] 2022-06-06 15:38
> > > [app-debug-2_sign.zip](https://github.com/topjohnwu/Magisk/files/8844941/app-debug-2_sign.zip) Try this?
> > 
> > 
> > That build doesnt detect recovery but when i tick it manually and hit direct install with reboot i dont end up in the loop
> 
> screenshot?
![Screenshot_20220606-173715](https://user-images.githubusercontent.com/58166551/172194719-13ccf9e4-2dc9-4e50-aade-a00646ba29f9.jpg)

**Comment by canyie** [comment] 2022-06-07 09:31
[app-debug3_sign.zip](https://github.com/topjohnwu/Magisk/files/8851961/app-debug3_sign.zip)
Try this and take a screenshot after direct install and reboot?

**Comment by DeltaOn3X** [comment] 2022-06-08 19:00
Sorry, i just came home now. 

Ive tried ur latest build.

Detect recovery = no

Additional setup loop = yes
![Screenshot_20220608-205900](https://user-images.githubusercontent.com/58166551/172695600-96a14993-1b83-4976-89ba-13d6d24353fd.jpg)

![Screenshot_20220608-205902](https://user-images.githubusercontent.com/58166551/172695609-9991eb01-97a8-4969-a3c9-8c3f4b981724.jpg)

**Comment by dr4go** [comment] 2022-06-09 03:21
@canyie Thanks for trying to solve this issue. I have a Samsung G973F (using Android 12) and I'm also affected by it. I'm not an such a highly gifted developer, but what I just wanted to add is, that those Samsung devices react quite sensible to Selinux changes / issues. That's why I expect(ed) the error to be in any of the commits from March 19, 2022 or the one from March 20.

**Comment by DeltaOn3X** [comment] 2022-06-09 14:32
> Hmmm, don't think this is a SELinux-related issue since manually flash patched image works.
> 
> @DeltaOn3X attach magisk logs here?

Should i flash first (with a reboot) and than copy the logs ?

**Comment by canyie** [comment] 2022-06-09 14:34
> > Hmmm, don't think this is a SELinux-related issue since manually flash patched image works.
> > @DeltaOn3X attach magisk logs here?
> 
> Should i flash first (with a reboot) and than copy the logs ?

No, just open the app, click "Logs", and click "Save".

**Comment by DeltaOn3X** [comment] 2022-06-09 16:22
> Magisk app seems detected recovery mode, but not ticking checkbox because of some UI issues?
> Try this: https://github.com/canyie/Magisk/actions/runs/2469519890

Weird, I always have to tick the checkbox.

i will try that when I’m home again and reply the results :)
 and btw thank you very much for the help :)

**Comment by DeltaOn3X** [comment] 2022-06-09 18:41
I just tried that build

detect recovery = yes (box is ticked auto)

additional setup loop = no
This build seems to be working fine!

![Screenshot_20220609-204105](https://user-images.githubusercontent.com/58166551/172920857-30b31d2f-bd60-44fd-abe1-7152c2c9816f.jpg)

**Comment by canyie** [comment] 2022-06-09 23:38
Can you try this official build? Maybe fixed by some upstream changes?
If ths build does not detect recovery mode, manually tick the checkbox then "direct install".
https://github.com/topjohnwu/Magisk/actions/runs/2466415364

**Comment by DeltaOn3X** [comment] 2022-06-10 06:29
> Can you try this official build? Maybe fixed by some upstream changes? If ths build does not detect recovery mode, manually tick the checkbox then "direct install". https://github.com/topjohnwu/Magisk/actions/runs/2466415364

Again additional setup loop with this build :( checkbox was also not ticked auto

![Screenshot_20220610-082825](https://user-images.githubusercontent.com/58166551/173004439-1f2c6016-4dbb-4062-a7de-4f6f554f7749.jpg)

![Screenshot_20220610-082832](https://user-images.githubusercontent.com/58166551/173004473-5c7587fa-5dd0-4173-a1e5-1b3eca4fbe77.jpg)

**Comment by canyie** [comment] 2022-06-10 09:03
`cat $(magisk --path)/.magisk/config`
What's the output of this command?

**Comment by canyie** [comment] 2022-06-10 10:03
Sorry i made a typo, it should be `cat $(magisk --path)/config`

**Comment by DeltaOn3X** [comment] 2022-06-10 10:05
![Screenshot_20220610-120438_Termux](https://user-images.githubusercontent.com/58166551/173042622-0fe68132-cedb-47dd-b817-454aa3bcb659.jpg)

**Comment by canyie** [comment] 2022-06-10 10:37
Ah, my first command is correct, but you wrote "./magisk" instead of "/.magisk"

**Comment by DeltaOn3X** [comment] 2022-06-10 10:50
> Ah, my first command is correct, but you wrote "./magisk" instead of "/.magisk"

Sorry, it was my fault.

![Screenshot_20220610-124952_Termux](https://user-images.githubusercontent.com/58166551/173049815-b46c8ec4-1f5b-4a44-92f6-a2b20b012447.jpg)

**Comment by canyie** [comment] 2022-06-10 13:40
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8879249/app-debug.zip)
Try this? Try "Direct Install" with "Install to Recovery" checkbox not checked, installation will not succeed, save log, then retry with checkbox checked, save log. Both logs need to be attached.

**Comment by DeltaOn3X** [comment] 2022-06-10 14:04
> 
[magisk_install_log_2022-06-10T16.03.30.log](https://github.com/topjohnwu/Magisk/files/8879509/magisk_install_log_2022-06-10T16.03.30.log)
[magisk_install_log_2022-06-10T16.03.46.log](https://github.com/topjohnwu/Magisk/files/8879510/magisk_install_log_2022-06-10T16.03.46.log)

**Comment by canyie** [comment] 2022-06-10 14:32
Does it detect recovery mode? The checkbox seems not taking any effect

**Comment by canyie** [comment] 2022-06-10 16:52
Tick the check box,  click direct install and DON'T reboot, press back and click "install" again, is that checkbox gets reset to unchecked?

**Comment by DeltaOn3X** [comment] 2022-06-10 17:07
> Tick the check box, click direct install and DON'T reboot, press back and click "install" again, is that checkbox gets reset to unchecked?

No the box will remain ticked

**Comment by canyie** [comment] 2022-06-11 05:05
Hmmm, weird.
Try it again, but force-stop the app after the first installation and before doing the second installation, and attach logs?

**Comment by DeltaOn3X** [comment] 2022-06-11 11:17
> Hmmm, weird.
> Try it again, but force-stop the app after the first installation and before doing the second installation, and attach logs?

What do you exactly mean by force stop ? Like hit direct install and than save logs? Or should I start direct install and stop it while it’s installing ? 

Im gonna stop it while installing and attaching logs.

**Comment by canyie** [comment] 2022-06-11 11:19
> > Hmmm, weird.
> > Try it again, but force-stop the app after the first installation and before doing the second installation, and attach logs?
> 
> What do you exactly mean by force stop ? Like hit direct install and than save logs? Or should I start direct install and stop it while it’s installing ?
> 
> Im gonna stop it while installing and attaching logs.

start direct install, wait it to complete (or fail), save log, force-stop the app and start the 2nd installation

**Comment by DeltaOn3X** [comment] 2022-06-11 11:48
> > > Hmmm, weird.
> > > Try it again, but force-stop the app after the first installation and before doing the second installation, and attach logs?
> > 
> > 
> > What do you exactly mean by force stop ? Like hit direct install and than save logs? Or should I start direct install and stop it while it’s installing ?
> > Im gonna stop it while installing and attaching logs.
> 
> start direct install, wait it to complete (or fail), save log, force-stop the app and start the 2nd installation

I started the first installation, saved logs and force stoped the app.

At the second installation the recovery box was not checked and the installation failed too.

The first log is the first installation.
I can provide you the second log to after force stoping the app and installing again

[magisk_install_log_2022-06-11T13.46.02.log](https://github.com/topjohnwu/Magisk/files/8883775/magisk_install_log_2022-06-11T13.46.02.log)

**Comment by canyie** [comment] 2022-06-11 12:01
have you ticked the checkbod in first installation?

**Comment by DeltaOn3X** [comment] 2022-06-11 12:27
> have you ticked the checkbox in first installation?

Yes

**Comment by canyie** [comment] 2022-06-11 14:26
try direct install with checkbox unselected and save log?

**Comment by DeltaOn3X** [comment] 2022-06-11 17:21
> Contributor
[magisk_install_log_2022-06-11T19.20.43.log](https://github.com/topjohnwu/Magisk/files/8884423/magisk_install_log_2022-06-11T19.20.43.log)

**Closed** 2022-06-12 07:32 UTC
Labels: regression

**Comment by canyie** [comment] 2022-06-12 07:36
Hmmm, the checkbox seems to be working again 🤔  can't reproduce the bug anymore so i guess the checkbox was also fixed. Thanks for your help and testing!
