### ISSUE TITLE
Galaxy S21 (Snapdragon) Bootloop

### ISSUE THREAD

**Issue by EntityBug** [topjohnwu/Magisk#5248] opened 2022-01-22 12:33 UTC
Device: Samsung Galaxy S21 (Snapdragon)
Android version:12
Magisk version name: canary
Magisk version code: 23017

Magisk worked well on OneUI4 but after I flash pixel experience gsi(based on phh's gsi) and flash magisk it bootloops.
There isn't anything about magisk in dmesg, but I find something about magisk in the result of cat /proc/last_kmsg.
[log.txt](https://github.com/topjohnwu/Magisk/files/7918313/log.txt)

**Comment by yujincheng08** [comment] 2022-01-22 17:57
Duplicate of #5156.

**Closed** 2022-01-23 11:33 UTC
