### ISSUE TITLE
Modules no longer working

### ISSUE THREAD

**Issue by Efpophis** [topjohnwu/Magisk#6758] opened 2023-03-17 19:46 UTC
Device: OnePlus 8T
Android version: 13
Magisk version name:  debug
Magisk version code: 25210

Magisk modules fail to load on startup, have no runtime effect. Logs show a "no such come or directory" error when attempting to mount mirrors.
[magisk_log_2023-03-17T15.39.55.log](https://github.com/topjohnwu/Magisk/files/11005317/magisk_log_2023-03-17T15.39.55.log)

**Comment by Efpophis** [comment] 2023-03-17 19:52
I should mention that, inspecting the mount paths shown in the logs, there is no modules director under /dev/{random garbage}/.magisk. Lots of other magisk stuff in there, but no modules.

**Comment by Efpophis** [comment] 2023-03-17 20:38
Further troubleshooting shows that only modules that overlay the filesystem seem to be impacted. For example, universal safety net fix seems to work, but the systemless hosts module from within magisk itself fails to even install. I can install a module I made that puts some files into /system, but it doesn't actually end up putting them there.

**Comment by canyie** [comment] 2023-03-18 00:55
Duplicate of #6688

**Closed by canyie** 2023-03-18 00:55 UTC
