### ISSUE TITLE
Oppo A83 CPH1729 - bootloop

### ISSUE THREAD

**Issue by sosadsonar** [topjohnwu/Magisk#6566] opened 2023-01-25 08:21 UTC
**I tried to root this old device using patch boot image technique but ended up bootlooping**

**These options are ticked when patching:**
- Preserve force encryption
- Patch vbmeta in boot image

**Some information about this device:**
- Device: Oppo A83
- Model: CPH1729
- Android version: 7.1.1
- Kernel version: 4.4.22-G202009032342
- Android Security Patch Level: October 5, 2019
- Magisk version name: 25.2 (25206)
- Magisk version code: 831a398b (25206) (D)
- Ramdisk: Yes
- A/B partition: No

**Files**

- Stock boot image: [here](https://drive.google.com/file/d/1NrAsuLtidvfgvBOvI2nN-QgkXxtswI13/view?usp=sharing)

- Patched boot image: [here](https://drive.google.com/file/d/1hZP0v8DIBkr8cDOj1U87kzNDRGesqKWH/view?usp=sharing)

- Log file after patching boot image: [here](https://drive.google.com/file/d/1QR5BVw6LX9RRdQyai1qWEtSQXARaoO7w/view?usp=sharing)

- Bug report file: [here](https://drive.google.com/file/d/1yMJCT3kd_gCxJnN5WbZAGPDBb0jNzMki/view?usp=sharing) (contains last_kmsg and dmesg)

- /proc/mounts: [here](https://drive.google.com/file/d/1Owx74615jPQv5NDIsPR-EZph6CI_QlOJ/view?usp=sharing)
___
Device: Oppo A83
Android version: 7.1.1
Magisk version name: 25.2
Magisk version code: 25206

**Comment by canyie** [comment] 2023-01-25 09:18
```
------ 0.002s was the duration of 'QTAGUID STATS INFO' ------
------ LAST KMSG (/proc/last_kmsg) ------
ram console header, hw_status: 2, fiq step 0.
Not Clear, old status is 2.
```

Hmmm, just noticed that Oppo A83 uses MT6763T so I think this is a duplicate of #5124

**Comment by sosadsonar** [comment] 2023-02-09 12:13
Dunno why but Magisk working flawlessly in v14.0 (Magisk Manager v5.8.2) for my device :(). Newer versions cause bootloop. I think old devices are only compatible with older versions of Magisk

**Comment by canyie** [comment] 2023-02-09 13:38
Maybe newer zlib produces different gzip file that can't be handled by the buggy bootloader? So the only option is to add a switch to let magiskboot do not repack the kernel?

**Comment by sosadsonar** [comment] 2023-02-10 05:20
Here's the patched boot image of Magisk v14.0 version for reference. If you need any further details I'll try my best to provide information
[boot.zip](https://github.com/topjohnwu/Magisk/files/10703921/boot.zip)

**Comment by canyie** [comment] 2023-02-10 09:11
Can you send /proc/cpuinfo ?

**Comment by sosadsonar** [comment] 2023-02-10 10:43
Here it is
[cpuinfo.zip](https://github.com/topjohnwu/Magisk/files/10706467/cpuinfo.zip)

**Comment by canyie** [comment] 2023-02-11 07:18
Can you try this build?https://github.com/canyie/Magisk/actions/runs/4150249379

**Comment by sosadsonar** [comment] 2023-02-11 10:49
Thank you, it worked like a charm, every features worked normally. I think you've figured out the solution for this problem

**Comment by canyie** [comment] 2023-02-11 10:58
Ok, then I will mark this as a duplicate since all related devices use similar SoC and have the same behavior

**Closed by canyie** 2023-02-11 10:58 UTC
Labels: duplicate

**Comment by yujincheng08** [comment] 2023-02-11 10:59
Duplicate of #5124
