### ISSUE TITLE
Magisk module does not support replacing files in odm partition

### ISSUE THREAD

**Issue by yuanwofei** [topjohnwu/Magisk#4970] opened 2021-11-23 09:52 UTC
Device: Google Pixel 3 XL
Android version:12
Magisk version name: 7e9d4512
Magisk version code: 23014

I want to replace some files in the odm partition, such as /odm/etc/build.prop，and i tried to put the file to be replaced in the /system/odm/etc/build.prop directory of magisk module, but it didn't take effect, does the Magisk module support replacing files in the odm partition?

**Comment by osm0sis** [comment] 2021-11-23 14:50
/system on a live device does not contain /system/odm, /odm only exists in the root / directory with no /system/odm symlink or anything to it. Magisk does not currently support this kind of partition.

**Comment by osm0sis** [comment] 2021-11-23 14:55
Let's call this a duplicate of #3338 and follow along there.

**Closed by osm0sis** 2021-11-23 14:55 UTC
Labels: duplicate
