### ISSUE TITLE
Apps are crashed when they are in denylist

### ISSUE THREAD

**Issue by Dima-diep** [topjohnwu/Magisk#7468] opened 2023-11-01 18:02 UTC
Device: Xiaomi Mi Note 3 (jason)
Android version: 10
Magisk version name: 0352ea2c
Magisk version code: 26302

Apps which are in "Denylist" are crashed when opens. If app is not in "Denylist" or Zygisk is disabled, then apps works normally.
[logcat.log](https://github.com/topjohnwu/Magisk/files/13230291/logcat.log)
[magisk.log](https://github.com/topjohnwu/Magisk/files/13230294/magisk.log)

**Comment by canyie** [comment] 2023-11-01 22:36
Duplicate of #7448

**Closed by canyie** 2023-11-01 22:36 UTC
