### ISSUE TITLE
Internal storage shrunk from 1 Tb to 32 Gb - only Magisk used and all 4 files transfered via Odin

### ISSUE THREAD

**Issue by Rubbydubb** [topjohnwu/Magisk#3827] opened 2021-02-08 09:58 UTC
Dear Mr. Wu,
Dear all,

although I followed the instructions and only used Magisk (no TWRP or anything else) the internal storage of my mobile was shrunk from 1 TB to 32 GB. I would like to support you with additional files but need some help here as I'm not the most advanced user here... Please send me what files you need and where to find them / how to get them if you could spare the time to help me.

My mobile is a SM-G975F/DS, serial number R58M37Z5XMM
Software Version S975FXXU9EUA4. The firmware I used to patch was downloaded via Frija: 
SM-G975F_2_20210121031504_sc4h52ctko_fac.zip
the AP_Version I used to patch was the AP_G975FXXU9EUA4_CL20606551_QB3761373_REV01_user_low_ship_meta_OS11.tar.md5
I used Magisk 21.4 (21400) and Magisk Manager 8.0.7 (4834)(15)

I did the following:
Installed Magisk
Uploaded the AP-file to the phone
patched the AP-file with Magisk (Recovery option set)
Downloaded the magisk_patched_*****.tar back to the PC
Installed all 4 files with Odin (BL, patched tar, CP, and CSC), only unchecked the auto reboot here.
Rebooted to Recovery

First i did the transfers via cable back and forth, but I saw your hint to use adb. Then I used the SD-Card. After I discovered, that the internal storage shrunk to 32GB I first thought it was a crappy app, so I started over again from scratch but without the SD-Card and with adb push / pull. I screened the original system, it showed 1TB (attached a screenshot). Directly after uploading via Odin and rebooting in recovery, setting up the phone, the internal storage was reduced to 32GB (also attached as a screenshot). I did the final installation of Magisk afterwards without change or the internal storage. Still 32GB.
![internal_storage](https://user-images.githubusercontent.com/78720997/107204102-92c52200-69fc-11eb-875a-41c525bd421e.jpg)
![internal_storage_now](https://user-images.githubusercontent.com/78720997/107204119-96f13f80-69fc-11eb-8ce6-64be938de135.jpg)

Any help would be appreciated!
Thanks a lot in advance!!
Best,
Sven alias Rubbydubb

**Comment by umitpolat** [comment] 2021-02-14 09:13
Hi bro,

I could not solve this problem, but found the cause.

I accidentally pressed the update with the smart switch software and forgot. Of course, then events ...

Then I installed this version downloaded **975FXXU9EUA4** with **Odin 3.14.1**. I then installed **Magisk Manager 8.0.7** and installed again with **Odin 3.14.1**. I thought I probably made a mistake when I couldn't see root access. I tried it with **Odin 3.14.4**, **3.14.1**, **3.13.1** versions but still could not get root access.

Now is a surprise time, young people :)

I installed the Samsung stock rom with **Odin 3.13.1**. I then patched **Magisk Manager 8.0.7** in recovery mode. This time I installed magisk_patched_xxxx.tar with **Odin 3.14.1**, but still could not get root access.

If I install magisk_patched_xxxx.tar with **Odin 3.14.4**. I can get root access. This time, the S10 +, which is 128 GB, seems to have decreased to 32 GB. 

I try **Magisk Manager Stable**, **Beta** and **Canary** versions.

Because of this bullshit, I haven't been playing pubg mobile for three days. If I can get successful results by trying new methods, I will report here.

Kind Regards :)

**Comment by umitpolat** [comment] 2021-02-14 11:58
@Rubbydubb bro,

Completely **remove** all **adb.exe** files or **adb installs** present in the PC.
Uninstall **HTC Sync software** if you have one because I think it contains a lot of adb files and restart the PC.
Reinstall the samsung usb drivers software using Samsung Smart Switch.
Open Android SDK Manager. You have **Android 10** and **Android 10+** installed in the SDK Platforms tab. 
Completely remove SDK Platform Tools and new install SDK Platform Tools version 30.0.5 in Android SDK Manager.
Flash stock rom files to the device with **Odin 3.14.4** and complete the setup.
Install **Magisk Manager 8.0.7**. In recovery mode, select the AP file and wait for the process to finish.

**IMPORTANT**
When loading the magisk_patched_xxxx.tar file with **Odin 3.14.4**, select **HOME_CSC** in the CSC field and **Auto Reboot** is checked.
After the process is finished, it will be in bootloop. Restart the device with **Power + volume down** and when the screen turns black, release your hands and quickly press **power + volume up + bixby** keys again at the first vibration, release **power + bixby** and **hold the volume up** key until the recovery screen comes up.
Factory data reset select and continue android installation. Install magisk manager apk after installation is finished, you will see that you cannot get root access. Turn off the device and **press power + volume up + bixby** keys together while turning it on, release all keys at the first vibration.

You will get root access. Your internal storage don't reduce.

Good Luck. :)

**Comment by Rubbydubb** [comment] 2021-02-15 20:40
Dear umitpolat,

although I had to do it slightly different, you are my hero of the day! I finally got root access and full storage.

I had some problems in getting magisk to run with root. Although I followed your steps. The difference was when keeping the vol-up after auto reboot. There was no option for a factory reset. The android robot showed up and the word "erase" and than it rebooted again. Now it was possible to "factory reset" like you wrote. After the reboot I installed magisk again and rebooted to recovery. Without succes, no root. Following these steps also did not give me the option to go into factory reset again (keep vol-up pressed after reboot) afterwards. The mobile (after a while keeping vol-up pressed) just vibrated a bit longer than the initial vibration and then started "normally". 

But then I flashed it via Odin again with the patched magisk-tar-file Home-CSC etc. and auto reboot (...and just ignored it at first, because I thought it would result in the mentioned boot loop - but no!!) It restarted and when I opened magisk manager it installed everything and rebooted the mobile. Now I have root and my 1TB!

I really thank you a lot! Great work!!

Best,
Rubbydubb

**Closed** 2021-02-20 10:50 UTC

**Comment by Tribanj** [comment] 2021-05-16 22:04
This is working for me on SM-G973F. I have not installed TWRP. How I can install TWRP, but to I save root?

**Comment by twiice** [comment] 2023-07-21 09:15
I had the same problem on my G9750 1TB snapdragon.

Also couldn't enter recovery and had the 'erasing' after first flash. Went in anyway and reinstalled magisk, then flashed  the magisk AP again with CSC home and this time was allowed into stock recovery. Factory reset, install magisk again, power off -> bixby+power+vol up all released on first vibration, back into android where magisk prompted finishing setup. Now have 1TB again. Also don't need twrp, root sticks fine.

Made an account here just to say thank you to posters for the information provided. After many many hours of reading and flashing all kinds of unnecessary stuff to get root (with 32G hah) this thread saved me from further suffering. 

Kind regards
