### ISSUE TITLE
Magisk 26.1 loses root on Redmi 5A (riva) on Android 13 (crDroid 9.5)

### ISSUE THREAD

**Issue by morturio** [topjohnwu/Magisk#7059] opened 2023-06-09 09:05 UTC
Device: Xiaomi Redmi 5A (riva)
Android version: 13
Magisk version name: 26.1
Magisk version code: 26102

Magisk 26.1 loses root on Redmi 5A (riva) on Android 13 (crDroid 9.5)

`---Magisk Logs---
47d2d4e3 (-1)

---Manager Logs---
47d2d4e3 (26102)

--------- beginning of main
06-09 10:53:25.435 23095 23095 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
06-09 10:53:25.492 23095 23095 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
06-09 10:53:25.596 23095 23095 W opjohnwu.magisk: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
06-09 10:53:25.597 23095 23095 W opjohnwu.magisk: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
06-09 10:53:25.661 23095 23127 D CompatibilityChangeReporter: Compat change id reported: 194532703; UID 10377; state: ENABLED
06-09 10:53:25.696 23095 24209 I AdrenoGLES-0: QUALCOMM build                   : 17c3781a1c, Ied085aa59b
06-09 10:53:25.696 23095 24209 I AdrenoGLES-0: Build Date                       : 03/30/22
06-09 10:53:25.696 23095 24209 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.17
06-09 10:53:25.696 23095 24209 I AdrenoGLES-0: Local Branch                     : 
06-09 10:53:25.696 23095 24209 I AdrenoGLES-0: Remote Branch                    : 
06-09 10:53:25.696 23095 24209 I AdrenoGLES-0: Remote Branch                    : 
06-09 10:53:25.696 23095 24209 I AdrenoGLES-0: Reconstruct Branch               : 
06-09 10:53:25.696 23095 24209 I AdrenoGLES-0: Build Config                     : S L 10.0.7 AArch64
06-09 10:53:25.696 23095 24209 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
06-09 10:53:25.733 23095 24209 I AdrenoGLES-0: PFP: 0x00c60400, ME: 0x003ff041
06-09 10:53:25.810 23095 24209 E OpenGLRenderer: Unable to match the desired swap behavior.
06-09 10:53:25.821 23095 23095 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
06-09 10:53:25.821 23095 23095 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
06-09 10:53:25.822 23095 24221 I Gralloc4: Adding additional valid usage bits: 0x202000
06-09 10:53:25.953 23095 23095 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10377; state: ENABLED
06-09 10:53:25.983 23095 23095 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10377; state: ENABLED
06-09 10:53:26.600 23095 24224 I okhttp.OkHttpClient: --> GET https://topjohnwu.github.io/magisk-files/beta.json
06-09 10:53:26.970 23095 23095 I Choreographer: Skipped 72 frames!  The application may be doing too much work on its main thread.
06-09 10:53:27.174 23095 24224 I okhttp.OkHttpClient: <-- 200 https://topjohnwu.github.io/magisk-files/beta.json (573ms, unknown-length body)
06-09 10:53:27.715 23095 24209 W Parcel  : Expecting binder but got null!
06-09 10:53:27.719 23095 23095 I Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
06-09 10:53:27.745 23095 23122 I OpenGLRenderer: Davey! duration=1958ms; Flags=1, FrameTimelineVsyncId=811304, IntendedVsync=6620805350937, Vsync=6622008201369, InputEventId=0, HandleInputStart=6622010343982, AnimationStart=6622010353305, PerformTraversalsStart=6622109499191, DrawStart=6622335857940, FrameDeadline=6620826017603, FrameInterval=6622010109868, FrameStartTime=16706256, SyncQueued=6622418573617, SyncStart=6622418952836, IssueDrawCommandsStart=6622420541951, SwapBuffers=6622748812419, FrameCompleted=6622764242888, DequeueBufferDuration=48073, QueueBufferDuration=480782, GpuCompleted=6622764242888, SwapBuffersCompleted=6622751136065, DisplayPresentTime=0, CommandSubmissionCompleted=6622748812419, 
06-09 10:53:38.888 23095 23095 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
06-09 10:53:38.888 23095 23095 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
06-09 10:53:40.332 23095 23095 I Choreographer: Skipped 53 frames!  The application may be doing too much work on its main thread.
06-09 10:53:40.428 23095 23122 I OpenGLRenderer: Davey! duration=973ms; Flags=0, FrameTimelineVsyncId=812573, IntendedVsync=6634472985013, Vsync=6635358508059, InputEventId=0, HandleInputStart=6635371850904, AnimationStart=6635371857154, PerformTraversalsStart=6635375963300, DrawStart=6635376526113, FrameDeadline=6635412672818, FrameInterval=6635371638300, FrameStartTime=16704011, SyncQueued=6635377551008, SyncStart=6635377834550, IssueDrawCommandsStart=6635378182727, SwapBuffers=6635436146738, FrameCompleted=6635447136738, DequeueBufferDuration=5255573, QueueBufferDuration=599479, GpuCompleted=6635447136738, SwapBuffersCompleted=6635437633613, DisplayPresentTime=5353185677972949590, CommandSubmissionCompleted=6635436146738, `

**Comment by canyie** [comment] 2023-06-09 10:46
Duplicate of #6914

**Closed** 2023-06-09 10:46 UTC
