### ISSUE TITLE
Magiskinit fails mount init.rc on SAR device 

### ISSUE THREAD

**Issue by olbb** [topjohnwu/Magisk#5971] opened 2022-06-13 04:05 UTC
Device:ViVo IQOO(PD1824)

Android version:Android 11 

Magisk version name:71205bc5

Magisk version code:25001

-----

Hello.

IQOO is a system-as-root device. The best practice as suggested are flashing the recovery.img with magisk, I'm sorry but I can't because the device dosen't have a hot key to boot into recovery mode.

I found that 'want_initramfs kernel patch works on the device. So I tried modified boot_patch.sh added 

```
touch ramdisk.cpio
```
before
```
./magiskboot cpio ramdisk.cpio 
```

Then I patched boot.img with magisk and flash it.

The phone successful boot with magiskinit but not works as expected.

I found those in kernel log may be useful.

```
04-10 13:04:06.832555     0     0 W magiskinit: Hijack [/sys/fs/selinux/enforce]
04-10 13:04:06.832562     0     0 I do_mount pid: 1 comm:magiskinit mount .magisk/selinux/enforce at //enforce, flags:4096
04-10 13:04:06.832802     0     0 W magiskinit: opendir: /dev/NFuU/.magisk/mirror/data/unencrypted/magisk failed with 2: No such file or directory
04-10 13:04:06.832928     0     0 W magiskinit: Mount [.magisk/rootdir/system/etc/init/hw/init.rc] -> [/system/etc/init/hw/init.rc]
04-10 13:04:06.832931     0     0 I do_mount pid: 1 comm:magiskinit mount .magisk/rootdir/system/etc/init/hw/init.rc at hw/init.rc, flags:4096
04-10 13:04:06.832940     0     0 W magiskinit: mount .magisk/rootdir/system/etc/init/hw/init.rc->/system/etc/init/hw/init.rc failed with 1: Operation not permitted
04-10 13:04:06.832964     0     0 I SYSC_umount pid: 1 comm:magiskinit umount ///, flags:2
04-10 13:04:06.832981     0     0 E EXT4-fs (sda15): errors=remount-ro for active namespaces on umount 2
04-10 13:04:06.832985     0     0 W magiskinit: Unmount [/dev/NFuU/.magisk/mirror/system_root]
04-10 13:04:06.832988     0     0 I SYSC_umount pid: 1 comm:magiskinit umount ///, flags:2
04-10 13:04:06.833141     0     0 E evict_inodes: -------- (sda18) evice inode count is 2
04-10 13:04:06.834085     0     0 W magiskinit: Unmount [/dev/NFuU/.magisk/mirror/data]
```

The full log is below. Thank you for your time.

[proc_mounts.log](https://github.com/topjohnwu/Magisk/files/8887803/proc_mounts.log)
[kernel_log_2022_0613_104245.curf.log](https://github.com/topjohnwu/Magisk/files/8887805/kernel_log_2022_0613_104245.curf.log)
[main_log_2022_0613_104245.curf.log](https://github.com/topjohnwu/Magisk/files/8887808/main_log_2022_0613_104245.curf.log)

**Comment by canyie** [comment] 2022-06-13 04:14
Duplicate of #5148

**Closed** 2022-06-13 04:35 UTC
