### ISSUE TITLE
Can't uninstall Magisk

### ISSUE THREAD

**Issue by toorich** [topjohnwu/Magisk#747] opened 2018-10-30 13:16 UTC
It will try to download uninstaller.zip, but result error(404).

**Comment by DenyDarko** [comment] 2018-10-30 13:53
[Magisk-uninstaller-20181022.zip](https://github.com/topjohnwu/Magisk/files/2529869/Magisk-uninstaller-20181022.zip)

I've attached it for you on my message. 

Close the issue though, this is not a bug, the link is fine, I just used it to get the attached Uninstaller.
You probably have a wrong link.

**Closed** 2018-10-30 19:07 UTC

**Comment by toorich** [comment] 2018-10-31 03:39
According my download manager, it shows this link: https://github.com/topjohnwu/Magisk/releases/download/v17.3/Magisk-uninstaller-20181020.zip

**Comment by neekless** [comment] 2018-10-31 04:47
@topjohnwu in the [stable channel](https://raw.githubusercontent.com/topjohnwu/magisk_files/master/stable.json) the uninstaller indeed points to /v17.3/Magisk-uninstaller-20181020.zip which doesn't exist. Seems you dismissed this too quickly.
