### ISSUE TITLE
magisk root auth issue

### ISSUE THREAD

**Issue by wjpdeveloper** [topjohnwu/Magisk#3577] opened 2020-12-16 23:04 UTC
After I rename Magisk package name to mmmmanger,  while it processing (stay a long time), the app was killed by my hand using other app tool. 

but when I enter into Magisk app next, I lose the root authority，(It was auto rejected by itself? what!) and I can't find important menu to operate root grant again  and others.

I reinstall the magisk  manager, but not solved.  So how can I do next to restore It. 

thank you.

![Screenshot_20201217-064750](https://user-images.githubusercontent.com/29764862/102416972-c8b9db80-4035-11eb-8f70-8b32c5c01a4c.jpg)

![Screenshot_20201217-064758](https://user-images.githubusercontent.com/29764862/102416988-d0798000-4035-11eb-9d5b-13787b7451fb.jpg)

**Comment by unixandria-xda** [comment] 2020-12-16 23:14
I'm having this issue as well. 

Provided you've granted root to a terminal or file manager, delete /data/adb/magisk/magisk.db and reboot then reinstall default manager. You'll lose your magiskhide and root granted settings mind you

**Comment by wjpdeveloper** [comment] 2020-12-17 00:32
@unixandria-xda thank you for your reply so quickly, magisk have back to work well, it is great! 😍

**Comment by Didgeridoohan** [comment] 2020-12-17 10:31
For future reference, you probably didn't need to delete the magisk.db (and in the process loosing all superuser permissions and such). It would most likely have been enough to uninstall the Magisk Manager and try to open the hidden app named (in your case) "mmmmanger" (that has the default Android icon). If that app didn't work you would have needed to uninstall that as well and just reinstalled the regular Manager.

@wjpdeveloper By the way, since this doesn't seem to be an ongoing issue you can close this issue...

**Comment by mdkcore0** [comment] 2020-12-17 13:15
@Didgeridoohan tip worked for me, thanks!

**Comment by unixandria-xda** [comment] 2020-12-17 14:35
> For future reference, you probably didn't need to delete the magisk.db (and in the process loosing all superuser permissions and such). It would most likely have been enough to uninstall the Magisk Manager and try to open the hidden app named (in your case) "mmmmanger" (that has the default Android icon). If that app didn't work you would have needed to uninstall that as well and just reinstalled the regular Manager.
> 
> @wjpdeveloper By the way, since this doesn't seem to be an ongoing issue you can close this issue...

Won't work, the new app just crashes after getting denied root access

**Comment by unixandria-xda** [comment] 2020-12-17 14:35
> For future reference, you probably didn't need to delete the magisk.db (and in the process loosing all superuser permissions and such). It would most likely have been enough to uninstall the Magisk Manager and try to open the hidden app named (in your case) "mmmmanger" (that has the default Android icon). If that app didn't work you would have needed to uninstall that as well and just reinstalled the regular Manager.
> 
> @wjpdeveloper By the way, since this doesn't seem to be an ongoing issue you can close this issue...

And this issue should stay open, I can consistently reproduce

**Comment by Didgeridoohan** [comment] 2020-12-17 14:55
> Won't work, the new app just crashes after getting denied root access

Like I said, if neither if the apps work you uninstall both of them (both the regular Manager and the one that failed to hide) and start over.

If you continue to have issues with hiding the Manager then this issue either needs to be updated to reflect that (it's not about root authorisation) or you open one of your own that describes the actual issue.

**Comment by unixandria-xda** [comment] 2020-12-17 19:55
> > Won't work, the new app just crashes after getting denied root access
> 
> Like I said, if neither if the apps work you uninstall both of them (both the regular Manager and the one that failed to hide) and start over.
> 
> If you continue to have issues with hiding the Manager then this issue either needs to be updated to reflect that (it's not about root authorisation) or you open one of your own that describes the actual issue.

My point is the root authorisation stops working for BOTH of the managers and uninstalling or reinstalling EITHER does absolutely zero good. The only way short of a data wipe to get manager working again is deleting the database

**Comment by unixandria-xda** [comment] 2020-12-17 19:55
As in neither manager _itself_ can get root the _manager_ is denied root

**Comment by unixandria-xda** [comment] 2020-12-17 19:57
_Neither normal manager nor hidden one work_ and _neither_ can get root access and the only method that works is the one I tried

**Comment by Didgeridoohan** [comment] 2020-12-17 20:00
If that's the situation the solution is to delete the database, yes. Sounds like the database entry for the Manager package name simply got corrupted in your case. Most of the time, uninstalling one or both of the Managers is enough.

And, again, if that is a 100% reproducible thing on your device (and with the Canary Manager) you might want to gather the necesary logs and make a proper bug report.

**Comment by unixandria-xda** [comment] 2020-12-17 20:06
I can only reproduce on stock and I'm not on stock as of this moment
Manager endlessly loads on hiding and then eventually crashes, and then the new app just crashes and the old one can't get roott. Reproduced several times in a row. 

I don't plan to go back to stock until OOS 11 releases for my device so if @wjpdeveloper can't get logs it'll be a month or so

**Closed** 2020-12-20 06:33 UTC
