### ISSUE TITLE
Can't activate any modules on SM-P355Y

### ISSUE THREAD

**Issue by Bob-YsPan** [topjohnwu/Magisk#6703] opened 2023-03-08 07:09 UTC
Device: Galaxy Tab A 8.0(SM-P355Y)
Android version: 6.0.1
Magisk version name: 981ccabb
Magisk version code: 25210

I install the newer canary version of Magisk.
After reboot the SuperSU works but the all modules installed but not activate

The log of the Magisk(also attach below)

```
06-03 22:08:56.852   262   262 I : Magisk 981ccabb(25210) daemon started
06-03 22:08:56.860   262   262 I : * Device API level: 23
06-03 22:08:56.863   262   264 I : ** post-fs-data mode running
06-03 22:08:56.863   262   264 I : * Mounting mirrors
06-03 22:08:56.863   262   264 E : mount /data/adb/modules -> /sbin/.magisk/modules failed with 2: No such file or directory
06-03 22:08:56.863   262   264 E : mount (null) -> /sbin/.magisk/modules failed with 2: No such file or directory
06-03 22:08:56.863   262   264 E : mount (null) -> /sbin/.magisk/modules failed with 2: No such file or directory
06-03 22:08:56.888   262   264 I : fallback to mount subtree
06-03 22:08:57.030   262   264 I : * Initializing Magisk environment
06-03 22:08:59.280   262   264 I : * Running post-fs-data.d scripts
06-03 22:08:59.281   330   330 I : post-fs-data.d: exec [00000000apps2sd.sh]
06-03 22:08:59.303   330   330 I : post-fs-data.d: exec [0000000000fixapps2sd.sh]
06-03 22:09:34.282   330   330 W : * post-fs-data scripts blocking phase timeout
06-03 22:09:34.286   262   264 I : * Enable DenyList
06-03 22:09:34.286   262   264 I : denylist: initializing internal data structures
06-03 22:09:34.293   262   264 I : denylist add: [com.google.android.instantapps.supervisor/com.google.android.instantapps.supervisor]
06-03 22:09:34.295   262   264 I : denylist add: [isolated/com.google.android.instantapps.supervisor.isolated1]

.......
```

The root system use `ls -al`

```
root@gt5note8ltechn:/data/data/com.termux/files/home # ls -al /
drwxr-xr-x root     root              2015-06-04 06:08 .system
drwxr-xr-x root     root              2015-06-04 06:08 acct
drwxrwx--- system   cache             2015-06-04 06:08 cache
dr-x------ root     root              2015-06-04 06:08 config
lrwxrwxrwx root     root              2015-06-04 06:08 d -> /sys/kernel/debug
drwxrwx--x system   system            2023-03-08 14:45 data
-rw-r--r-- root     root          820 1970-01-01 08:00 default.prop
drwxr-xr-x root     root              2023-03-08 14:45 dev
drwxrwx--x system   radio             2023-03-08 14:45 efs
lrwxrwxrwx root     root              2015-06-04 06:08 etc -> /system/etc
-rw-r--r-- root     root       134242 1970-01-01 08:00 file_contexts
dr-xr-x--- system   system            2015-06-04 06:08 firmware
dr-xr-x--- system   system            2015-06-04 06:08 firmware-modem
-rw-r----- root     root         1511 1970-01-01 08:00 fstab.qcom
-rwxr-x--- root     root       805756 1970-01-01 08:00 init
-rwxr-x--- root     root         3454 1970-01-01 08:00 init.carrier.rc
-rwxr-x--- root     root         3696 1970-01-01 08:00 init.class_main.sh
-rwxr-x--- root     root         3221 1970-01-01 08:00 init.container.rc
-rwxr-x--- root     root         1556 1970-01-01 08:00 init.environ.rc
-rwxr-x--- root     root         1730 1970-01-01 08:00 init.mdm.sh
-rwxr-x--- root     root         2078 1970-01-01 08:00 init.qcom.bms.sh
-rwxr-x--- root     root         7054 1970-01-01 08:00 init.qcom.class_core.sh
-rwxr-x--- root     root         9057 1970-01-01 08:00 init.qcom.early_boot.sh
-rwxr-x--- root     root        13675 1970-01-01 08:00 init.qcom.factory.rc
-rwxr-x--- root     root        31757 1970-01-01 08:00 init.qcom.rc
-rwxr-x--- root     root         8043 1970-01-01 08:00 init.qcom.sh
-rwxr-x--- root     root         2962 1970-01-01 08:00 init.qcom.syspart_fixup.sh
-rwxr-x--- root     root        73870 1970-01-01 08:00 init.qcom.usb.rc
-rwxr-x--- root     root         9564 1970-01-01 08:00 init.qcom.usb.sh
-rwxr-x--- root     root        53537 2015-06-04 06:08 init.rc
-rwxr-x--- root     root         2049 1970-01-01 08:00 init.rilchip.rc
-rwxr-x--- root     root         1010 1970-01-01 08:00 init.rilcommon.rc
-rwxr-x--- root     root         9118 1970-01-01 08:00 init.target.rc
-rwxr-x--- root     root         2089 1970-01-01 08:00 init.trace.rc
-rwxr-x--- root     root         9283 1970-01-01 08:00 init.usb.configfs.rc
-rwxr-x--- root     root         5339 1970-01-01 08:00 init.usb.rc
-rwxr-x--- root     root          376 1970-01-01 08:00 init.zygote32.rc
drwxrwxr-x root     system            2015-06-04 06:08 knox_data
drwxr-xr-x root     system            2015-06-04 06:08 mnt
drwxr-xr-x root     root              1970-01-01 08:00 oem
drwxr-xr-x system   system            2015-06-04 06:08 persdata
drwxrwx--x system   system            2015-01-01 08:00 persist
-rw-r--r-- root     root         2088 1970-01-01 08:00 postrecovery.do
drwxr-xr-x root     root              1970-01-01 08:00 preload
dr-xr-xr-x root     root              1970-01-01 08:00 proc
-rw-r--r-- root     root        22403 1970-01-01 08:00 property_contexts
-rw-r--r-- root     root         1509 1970-01-01 08:00 publiccert.pem
drwxr-x--- root     root              2015-06-04 06:08 root
drwxr-xr-x root     root              2015-06-04 06:08 sbin
lrwxrwxrwx root     root              2015-06-04 06:08 sdcard -> /storage/self/primary
-rw-r--r-- root     root        11653 1970-01-01 08:00 seapp_contexts
-rw-r--r-- root     root       961847 2015-06-04 06:08 sepolicy
-rw-r--r-- root     root          487 1970-01-01 08:00 sepolicy_version
-rw-r--r-- root     root        38090 1970-01-01 08:00 service_contexts
drwxr-xr-x root     root              2023-03-08 14:45 storage
dr-xr-xr-x root     root              2015-06-04 06:08 sys
drwxr-xr-x root     root              2022-11-24 16:49 system
lrwxrwxrwx root     root              2015-06-04 06:08 tombstones -> /data/tombstones
-rw-r--r-- root     root        13033 1970-01-01 08:00 ueventd.qcom.rc
-rw-r--r-- root     root         5256 1970-01-01 08:00 ueventd.rc
lrwxrwxrwx root     root              2015-06-04 06:08 vendor -> /system/vendor
```

The log:
[magisk_log_2023-03-08T15.03.12.log](https://github.com/topjohnwu/Magisk/files/10918073/magisk_log_2023-03-08T15.03.12.log)

**Comment by canyie** [comment] 2023-03-08 07:17
Duplicate of #6688

**Closed by canyie** 2023-03-08 07:17 UTC
