### ISSUE TITLE
Canary Release JSON installs Debug Manager and Magisk

### ISSUE THREAD

**Issue by zgfg** [topjohnwu/Magisk#2902] opened 2020-06-20 16:19 UTC
https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/release.json
points to Canary debug Manager 285 and debug Magisk 20416
![IMG_20200620_180806](https://user-images.githubusercontent.com/51943147/85206461-93506180-b322-11ea-99ab-cde2bfacd616.jpg)

**Comment by Fox2Code** [comment] 2020-06-20 16:59
This is not a bug this is completely normal because the release canary channel has been deleted.
Now all canary builds are debug builds.
See: https://github.com/topjohnwu/Magisk/commit/45b5e89912d9514cc2f131e32eb2602be4be0ad4

**Comment by zgfg** [comment] 2020-06-20 17:14
Ok, but it's just 'new normal' since of today's:
https://mobile.twitter.com/topjohnwu/status/1274313463825752064

**Comment by Didgeridoohan** [comment] 2020-06-20 18:08
@zgfg As you've found, it's by design. Soooo.... Maybe close the issue?

**Comment by zgfg** [comment] 2020-06-20 18:21
> @zgfg As you've found, it's by design. Soooo.... Maybe close the issue?

Yeah, you can close it. Should be no different thoughts also by design

**Comment by Didgeridoohan** [comment] 2020-06-20 18:22
I don't have admin rights to the Magisk repo, but you can close your own issue. Please do so that John or Chris doesn't have to.

**Closed** 2020-06-20 19:06 UTC
