### ISSUE TITLE
Magisk 21.1 & Screen2Auto

### ISSUE THREAD

**Issue by Akkor70** [topjohnwu/Magisk#3545] opened 2020-12-02 20:17 UTC
I have flashed MagiskR and Magisk 21.1 on Mi 9T AOSP Rom Android 11
In Android 10 with Magisk 20.4 Screen2Auto let me add the apps that I need to control in AndroidAuto display
Now with Magisk 21.1 Screen2Auto doesn't show me the apps to add......before I can add Plex, Whatsapp, Gmail, Chrome and more..............
This is the page of Screen2Auto developer
https://forum.xda-developers.com/t/screen2auto-new-app-for-aa-smartphone-mirroring-only-for-root-devices.4062787/
How to solve ?

**Comment by wangdaning** [comment] 2020-12-03 09:28
This is not a magisk issue. You should close it.

**Comment by Akkor70** [comment] 2020-12-03 14:28
> This is not a magisk issue. You should close it.

But if with 20.4 had no problem and issue appears with 21.1 why are you so sure ?

**Comment by wangdaning** [comment] 2020-12-03 21:42
Magisk simply gets the app root access, is that being denied? I think it is the app not being compatible with android 11.

**Closed** 2020-12-03 22:28 UTC

**Comment by Creatik** [comment] 2021-02-09 14:40
the problem is not with Screen2Auto but with the new magisk security policy.  now blocking socket connections.
