### ISSUE TITLE
[ERROR] Magisk Manager 22.0+ doesn't detect Magisk installation on J3 2016 (SM-J320H)

### ISSUE THREAD

**Issue by FrannDzs** [topjohnwu/Magisk#4495] opened 2021-07-12 21:01 UTC
Device: SM-J320H
Android version: 5.1.1
Magisk version name: V23
Magisk version code: 23001

Hi, good evening, sorry for the inconvenience, I am having trouble installing Magisk with a Samsung J3 (SM-J320H).
I have tried patching the BOOT image and patching the full firmware and have done hard reset. I am attaching the logs, and the boot.img. I hope you have the solution, greetings!

PD:
I have also tried renaming the apk to .zip and flashing it and it didn't work either. I also did it by patching and flashing the recovery partition but it didn't work either, I think I used all methods. Kernel is configured with SELINUX set to permissive
PD2:
Today I checked that I have root access thanks to Magisk but the application still shows that Magisk is not installed on the system, so the Magisk app functions are not enabled.
PD3:
We do not have the method of flashing by fastboot because some samsung phones do not support fastboot...

Related issues:
#4174
#4464

Boot image:
[boot.zip](https://github.com/topjohnwu/Magisk/files/6804309/boot.zip)

With patch file mode:
[magisk_install_log_2021-07-12T17_24_46Z[1].log](https://github.com/topjohnwu/Magisk/files/6804312/magisk_install_log_2021-07-12T17_24_46Z.1.log)

With direct install:
[magisk_install_log_2021-07-12T17_44_46Z[1].log](https://github.com/topjohnwu/Magisk/files/6804313/magisk_install_log_2021-07-12T17_44_46Z.1.log)

**Comment by FrannDzs** [comment] 2021-07-23 22:50
The magisk manager is broken @osm0sis

**Comment by osm0sis** [comment] 2021-07-23 22:56
I don't have anything to do with the Magisk app, pinging me is pointless.

**Comment by osm0sis** [comment] 2021-07-25 11:46
You already pointed to the issue this is likely a duplicate of.. Follow any progress there.

**Closed by osm0sis** 2021-07-25 11:46 UTC
Labels: duplicate

**Comment by FrannDzs** [comment] 2021-07-26 12:47
> You already pointed to the issue this is likely a duplicate of.. Follow any progress there.

Good morning, sorry for the inconvenience I caused you the other day, I was a little drunk :(. So topjohnwu is the one in charge of the app, a thousand apologies again, best regards!
