### ISSUE TITLE
bootloop on magisk 17

### ISSUE THREAD

**Issue by achozex** [topjohnwu/Magisk#529] opened 2018-09-01 10:01 UTC
device oneplus 3t 
android 8.0
the latest beta was working perfectly

log : 
https://drive.google.com/open?id=1ZAlSYL47wsekpJrdHQ9AuFIykR3Top4C

**Comment by sqdesign** [comment] 2018-09-01 10:44
Same here on Oneplus 3 RR official nougat 7.1.2 build final.

**Comment by bogdan-radocea** [comment] 2018-09-01 10:54
Same on pixel xl with android 9.

**Comment by mmihirr** [comment] 2018-09-01 10:57
same on mi A1 stock oreo 8.1

**Comment by Wandang** [comment] 2018-09-01 11:43
Just for the sake of completeness: Same on HTC 10

**Comment by bogdan-radocea** [comment] 2018-09-01 11:47
Well, the issue is that you need the magisk uninstaller, even if you do a full flash (dirty)/upgrade over the older version. The v16.0 worked just fine in the past, but now it seems that v17.0 corrupts the system or boot partition somehow.

**Comment by Skimige** [comment] 2018-09-01 12:41
Maybe a way to temporarily out:
1. Go to your recovery. 
2. Flash Magisk uninstaller (Backup your modules!), then reboot. Your device should boot normally without root & modules. If not, find your stock boot.img then flash it.
3. Delete all lockscreen security.
4. Reboot to recovery, flash Magisk v17.0
5. Reset lockscreen security & your modules.

**Comment by Larpon** [comment] 2018-09-01 13:09
Got my Pixel working again with no fuzz following the Linux instructions from [Bootloop after magisk update](https://forum.xda-developers.com/apps/magisk/bootloop-magisk-update-t3836904)
![image](https://user-images.githubusercontent.com/768942/44946214-64d55f80-adf8-11e8-857a-a7f82b07718c.png)
Using twrp image from `twrp-pixel-installer-sailfish-3.2.3-0.zip` and the downloads from the [releases in this repo](https://github.com/topjohnwu/Magisk/releases)

Thanks guys!

**Comment by Jviix** [comment] 2018-09-01 13:54
Had the same issue, just uninstall Magisk with Magisk uninstaller and then install Magisk 17, also clean cache & Dalvik

**Comment by topjohnwu** [comment] 2018-09-01 14:49
Fixed in ff3dad245721c7d01f2c4772c700dafbc6ba9ef9

**Closed by topjohnwu** 2018-09-01 14:49 UTC

**Comment by mikehardy** [comment] 2018-09-01 16:15
@topjohnwu Resolved but it looks from the patch that anyone who installed MagiskManager v5.9.0 prior to installing Magisk v17 will need to uninstall then install cleanly, yes? Or does Magisk v17.1 install cleanly over Magisk v16 even if MagiskManager v5.9.0 was installed first?

**Comment by CrescendoFang** [comment] 2018-11-30 08:55
> 3. Remove all lockscreen security.

why remove the lockscreen security?
