### ISSUE TITLE
When the lsposed module is opened, open the magiskmanager freeze in the mask icon interface

### ISSUE THREAD

**Issue by badnng** [topjohnwu/Magisk#7206] opened 2023-08-03 13:38 UTC
Device:Redmi Note12 Turbo
Android version:13
Magisk version name:Debug
Magisk version code:d390ca2f(26104)
Logs:
[magisk.log](https://github.com/topjohnwu/Magisk/files/12251390/magisk.log)
LogCat:
[logcat.log](https://github.com/topjohnwu/Magisk/files/12251452/logcat.log)

Sorry, my English is not good, so I can only use the machine to communicate with you, sorry

One time, I'm going to open the magisk install module, But magiskmanager is stuck in the mask icon interface (pictured below) but I just have to turn lsposd off and can open it. Neither release nor debug versions are useful, even using the newly built debug version of LSPoesd, Still isn't work

![Screenshot_2023-08-03-21-24-31-192_com.topjohnwu.magisk.jpg](https://github.com/topjohnwu/Magisk/assets/115983722/5a73487a-dd2b-4254-b63a-8bfb4554c2a0)

So, I had to use a third-party manager to turn this module on and off, just turn off lspoesd and go to magiskmanager

![Screenshot_2023-08-03-21-32-57-402_com.byyoung.setting.jpg](https://github.com/topjohnwu/Magisk/assets/115983722/e1d6e1ee-5ba2-4e91-8448-575db217ddfa)

**Comment by yujincheng08** [comment] 2023-08-04 15:56
Duplicate of #7164

**Closed by yujincheng08** 2023-08-04 15:56 UTC
