### ISSUE TITLE
Canary build does not keep time limit for root request

### ISSUE THREAD

**Issue by bege10** [topjohnwu/Magisk#3677] opened 2021-01-12 17:26 UTC
- Fairphone 3
- TWRP recovery 3.4.0-0
- Magisk Canary 6d88d8ad (21201)
- OS: /e/OS 0.12 (Android 10)

I installed Canary to report another issue and noticed that the time limit for root requests is only a few seconds (most times too few to answer) no matter what time I set in the app settings. (With Magisk 21.2 this is not the case.)
[magisk_log_2021-01-12T18_11_10Z.log](https://github.com/topjohnwu/Magisk/files/5803747/magisk_log_2021-01-12T18_11_10Z.log)

**Comment by Didgeridoohan** [comment] 2021-01-12 17:30
Duplicate of #3644

**Closed** 2021-01-14 03:40 UTC
