### ISSUE TITLE
Bug in Magisk Manager

### ISSUE THREAD

**Issue by SachseConstruct** [topjohnwu/Magisk#2534] opened 2020-03-12 16:35 UTC
Hello, my name is Todd Sachse, I'm CEO at Sachse Construction. 

There's a bug in Magisk Manager. I was using it before and everything was fine until today. My banking apps stopped working and now I locked down from my financial operations. Very disturbing.

I request to fix this issue within 48 hours or I will take legal action against this modification and it's author due my financial and moral damage.

Kind regards,
Todd

**Comment by Justsnoopy30** [comment] 2020-03-12 16:49
Lol. Why are you accusing Magisk of damage to you without researching the issue? See issue #2530 . It's not even Magisk's fault, and Magisk can't do anything about it. It's because of Google's recent changes to safetynet making it trigger cts profile fail when your bootloader unlocked. So, it's because your bootloader is unlocked, and this can't be hidden because of a special security chip in your device sending a cryptographically-protected status that Magisk can't modify or decrypt.

**Comment by osm0sis** [comment] 2020-03-12 17:48
```
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
```

Have fun with your ridiculous legal threats.

**Comment by Justsnoopy30** [comment] 2020-03-12 18:28
> ```
> This program is distributed in the hope that it will be useful,
> but WITHOUT ANY WARRANTY; without even the implied warranty of
> MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> GNU General Public License for more details.
> ```
> 
> Have fun with your ridiculous legal threats.

And that too.

**Comment by linuxandria** [comment] 2020-03-12 18:31
> ```
> This program is distributed in the hope that it will be useful,
> but WITHOUT ANY WARRANTY; without even the implied warranty of
> MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> GNU General Public License for more details.
> ```
> 
> Have fun with your ridiculous legal threats.

I ❤️ licensing and people who don't bother to read them 😆

**Comment by SachseConstruct** [comment] 2020-03-12 20:56
@osm0sis I suggest you not to doubt abilities of my lawyers team. They are professionals and consult me on every way.

I really don't want to take it to the court, but if I have to, I will.

Best of luck,
Todd

**Comment by Justsnoopy30** [comment] 2020-03-12 21:26
I guess I need to spell it out for you in big letters @SachseConstruct.
# This issue is **NOT** caused by Magisk or it's author.
# This issue is caused by **YOU** having an unlocked bootloader on your phone. **YOU** chose to do that.
# Even if it was Magisk's fault (which it's not), you cannot sue or take legal action against Magisk or it's authors because of the license stating that this has no warranties whatsoever, and this has and will stand up in court.

**Comment by SachseConstruct** [comment] 2020-03-12 21:37
@Justsnoopy30 I understand your frustration, you are young man and can be edgy, but please, have to respect while talking to adult. Everything was working before and I didn't change anything. So I request a fix for that problem my financial operations are currently blocked.

It doesn't matter if licence has no warranty, I suffered moral and financial damage because of this issue and we can prevent more damage to happen if fix is provided within given time. All financial and moral damage after 48 hour period will be counted and attached to the lawsuit.

With respect,
Todd

**Comment by osm0sis** [comment] 2020-03-12 21:52
You might as well try to sue Google for changing SafetyNet, since nobody can fix it except them.

Unroot your device, relock your bootloader, and kindly fuck off.

@topjohnwu, lock and close this idiocy please.

**Comment by groozchique** [comment] 2020-03-12 21:54
@osm0sis be every careful with your words. I might not sue you, but I might make dead moose meat out of you in no time.

Best regards,
Todd

**Comment by SachseConstruct** [comment] 2020-03-12 22:06
Yes, @topjohnwu I expect an answer from you, not from those uneducated gentlemen, who think they can insult a respectable businessman on the internet.

With all due respect,
Todd

**Comment by Justsnoopy30** [comment] 2020-03-12 22:15
I wonder why you're getting downvotes and laughs every time you comment...

**Comment by S555555** [comment] 2020-03-12 22:30
> @Justsnoopy30 I understand your frustration, you are young man and can be edgy, but please, have some respect while talking to adult. Everything was working before and I didn't change anything. So I request a fix for that problem because my financial operations are currently blocked.
> 
> It doesn't matter if licence has no warranty, I suffered moral and financial damage because of this issue and we can prevent more damage to happen if fix is provided within given time. All financial and moral damage after 48 hour period will be counted and attached to the lawsuit.
> 
> With respect,
> Todd

**Comment by DanGLES3** [comment] 2020-03-12 22:33
@SachseConstruct the problems you are having are due to a change Google made to Safetynet, it now enforces checks through the device's TEE (Trusted Execution Environment), this makes hiding the bootloader unlock status pretty much impossible, thus there is nothing Magisk can do to fix this as the verification is made internally on Google's own servers

The damages you suffered are really unfortunate but they were not caused by Magisk but rather the act of you unlocking your device's bootloader, after doing such thing you accepted (whether knowingly or not) that things may stop working as intended.

If after that clarification you still wish to take legal action against someone you should take it against Google as they are the ones responsible for Safetynet.

With all due respect,
Daniel

**Comment by linuxandria** [comment] 2020-03-13 01:10
> You might as well try to sue Google for changing SafetyNet, since nobody can fix it except them.
> 
> Unroot your device, relock your bootloader, and kindly fuck off.
> 
> @topjohnwu, lock and close this idiocy please.

Couldn't have said it better, this made my day thank you!

**Comment by linuxandria** [comment] 2020-03-13 01:11
> @SachseConstruct the problems you are having are due to a change Google made to Safetynet, it now enforces checks through the device's TEE (Trusted Execution Environment), this makes hiding the bootloader unlock status pretty much impossible, thus there is nothing Magisk can do to fix this as the verification is made internally on Google's own servers
> 
> The damages you suffered are really unfortunate but they were not caused by Magisk but rather the act of you unlocking your device's bootloader, after doing such thing you accepted (whether knowingly or not) that things may stop working as intended.
> 
> If after that clarification you still wish to take legal action against someone you should take it against Google as they are the ones responsible for Safetynet.
> 
> With all due respect,
> Daniel

What a diplomatic response

**Comment by Justsnoopy30** [comment] 2020-03-13 01:39
This may not do much, but starting the issue about this on the Android issue tracker that includes possible solutions for Google may help bring attention to it, linked below:
https://issuetracker.google.com/issues/151316418

**Closed** 2020-03-13 04:36 UTC

**Comment by topjohnwu** [comment] 2020-03-13 08:05
@SachseConstruct in case you are not a troll, I'll reply to make things clear.

First, unlocking your bootloader immediately throws the security of your phone down the road, and for a lot of times voids your warranty. That is why so many banking apps tries to detect root and unlocked bootloaders. If you care about security of your phone and actual proper support for the device you spend money on, you should not be unlocking your bootloader in the first place.

Second, the reason why your bank app suddenly no longer works is most likely because Google has updated their SafetyNet detection system, which the bank app in question is using for verifying whether your device is safe to run on.

Lastly, when you downloaded and installed Magisk on your device, it means you agree on the license of the software you are using. Magisk is an open source software using the GPL license, which comes with no warranty. And also, there is no place Magisk guarantees that SafetyNet bypass will work **forever**.
