### ISSUE TITLE
Chroot freeze from broken pts handling on Magisk Android 9 and Android 10

### ISSUE THREAD

**Issue by NH-Killer** [topjohnwu/Magisk#2834] opened 2020-05-26 12:39 UTC
Hi, i have a system who use chroot to start a container but in some roms with Android 9 and Android 10 magisk not start the chroot...

Only keep it freeze...

Any idea?

If i try use strace the result is the same, without error, only freeze...

**Comment by osm0sis** [comment] 2020-05-31 07:41
I see you provided appropriate info in this one. Definitely unexpected behavior from chroot.

How are you running chroot? Did you check SELinux for denials? Does Magisk's busybox chroot work?

**Comment by NH-Killer** [comment] 2020-05-31 13:43
`[ 1651.366204] type=1400 audit(1590784663.621:109): avc: denied { ioctl } for comm="su" path="pipe:[161023]" dev="pipefs" ino=161023 ioctlcmd=0x5413 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:r:untrusted_app_27:s0:c512,c768 tclass=fifo_file permissive=1
[ 1663.581766] type=1400 audit(1590784665.511:110): avc: denied { ioctl } for comm="su" path="pipe:[161023]" dev="pipefs" ino=161023 ioctlcmd=0x5413 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:r:untrusted_app_27:s0:c512,c768 tclass=fifo_file permissive=1
[ 2341.124244] type=1400 audit(1590785353.381:180): avc: denied { ioctl } for comm="su" path="pipe:[181005]" dev="pipefs" ino=181005 ioctlcmd=0x5413 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:r:untrusted_app_27:s0:c512,c768 tclass=fifo_file permissive=1
[ 2349.014415] type=1400 audit(1590785353.381:180): avc: denied { ioctl } for comm="su" path="pipe:[181005]" dev="pipefs" ino=181005 ioctlcmd=0x5413 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:r:untrusted_app_27:s0:c512,c768 tclass=fifo_file permissive=1
[ 3543.669525] type=1400 audit(1590786555.931:354): avc: denied { ioctl } for comm="su" path="pipe:[329419]" dev="pipefs" ino=329419 ioctlcmd=0x5413 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:r:untrusted_app_27:s0:c512,c768 tclass=fifo_file permissive=1
`

But SELinux is in permissive, this is from one my users device.

**Comment by NH-Killer** [comment] 2020-05-31 13:53
And chroot from magisk busybox not work too, i tried a cross compiled version of GNU chroot from core-utils and not work too...

**Comment by osm0sis** [comment] 2020-05-31 16:30
Hmm. Is it a regression? What was the last Magisk version that worked?

**Comment by NH-Killer** [comment] 2020-05-31 16:37
> Hmm. Is it a regression? What was the last Magisk version that worked?

I build the version from github and send to my users who has problem not worked too... in some roms with Android 9 and Android 10 work as well...

Users report that don't work since the first version of Magisk for Android 10.

I think that is problem in sepolicy from untrusted_app... I'll check this creating a flashable zip of my interface system and check if running with the priv context it will work.

**Comment by osm0sis** [comment] 2020-05-31 16:41
If some still have it working then that's pretty confusing.

**Comment by NH-Killer** [comment] 2020-05-31 16:45
> If some still have it working then that's pretty confusing.

Exactly, but if work as a system app will be the confirmation that is a lack in sepolicy of some roms, one dev say me that some developers is enforcing SELinux, turn it persistent...

I'm building a now test version right now, i'll let you know the result.

**Comment by osm0sis** [comment] 2020-06-02 20:14
@NH-Killer, tell your users on TG to stop spamming (#2856), since you and I are working here.

**Comment by NH-Killer** [comment] 2020-06-02 20:34
> @NH-Killer, tell your users on TG to stop spamming (see #2856), since you and I are working here. I'll officially reopen while you test further.

Done, about the testing make a system app appear not work too...

I'm packing a new build with some changes and desesperating actions trying disable the magisk policy and trying force the context for su that only appear be "untrusted_app_27" or priv-app if as system app...

**Comment by topjohnwu** [comment] 2020-06-02 22:03
@NH-Killer if this is strictly a selinux issue, it could be fixed with one of the changes that is currently in the works, please stay tuned

**Comment by topjohnwu** [comment] 2020-06-03 21:30
Yes, that is certainly something that should be fixed in Magisk's rules

**Comment by NH-Killer** [comment] 2020-06-03 22:15
> Yes, that is certainly something that should be fixed in Magisk's rules, however that shouldn't be an issue for most phones because the `u:r:magisk:s0` domain is permissive anyways.

For test, has something that i can do to turn my app temporaly fully permissive?

**Comment by NH-Killer** [comment] 2020-06-04 17:58
I contacted my users running Android 9 and 10... the results are really alarming, around 70% of people who are running in Android 9 or 10 have this problem... this is a lot, i only contacted 100 peoples to measure the impact, is 19 different devices models, i receive more than 20 messages per day of new people with this problem...

For test my users disabled SELinux completely in the device, no effect... but the more strange thing is that have some users with the same device, using the same rom, for one works , for other the error appear...

I tried a lot of busybox versions, Magisk busybox, toybox, GNU coreutils chroot...

I'm still playing with magisk rules but these results sounds really crazy to me.

**Comment by osm0sis** [comment] 2020-06-04 21:44
Could it be memory constraints preventing the chroot container?

**Comment by NH-Killer** [comment] 2020-06-04 22:07
> Could it be memory constraints preventing the chroot container?

Sorry, you mean RAM? or Space left? 

Because i use in this way, we have a dir called "tmpsystem" who store the full chroot structure and "ANDRAX", we bind tmpsystem to ANDRAX dir (to allow suid and others flags).

Look at this attached image, everything that we try run in devices with this problem appear like this...

![chroot](https://user-images.githubusercontent.com/65501946/83815447-972f8300-a696-11ea-8efd-b9c7c875ad58.jpg)

**Comment by NH-Killer** [comment] 2020-06-04 22:09
I have a binary statically compiled in /bin/andrax of chroot, it not load if i target it too, so this eliminates possible problems with libs too.

**Comment by NH-Killer** [comment] 2020-06-04 22:10
> Could it be memory constraints preventing the chroot container?

Do you have idea about some tests that i can do in these devices?

**Comment by NH-Killer** [comment] 2020-06-05 00:40
To let you know...

If users type: `su -c busybox chroot / /bin/id` (the command doesn't matter) the same error occur, so the problem is not only in my system.

**Comment by NH-Killer** [comment] 2020-06-07 12:31
@osm0sis @topjohnwu 
Hi, i'm here again to relate new experiences, i made a build using proot container and it not worked too... so the problem is not on chroot syscall... now i'll try create a build to run inside magisk /sbin tmpfs to see if will work, maybe is a problem in the partitioning system (i hope so), in some hours i'll relate the results...

**Comment by NH-Killer** [comment] 2020-06-07 15:30
> @osm0sis @topjohnwu
> Hi, i'm here again to relate new experiences, i made a build using proot container and it not worked too... so the problem is not on chroot syscall... now i'll try create a build to run inside magisk /sbin tmpfs to see if will work, maybe is a problem in the partitioning system (i hope so), in some hours i'll relate the results...

Use /sbin tmpfs not work too...

**Comment by NH-Killer** [comment] 2020-06-08 22:20
@osm0sis @topjohnwu 
I found the problem but i don't know how to solve it...
Appear that is not chroot but su, when the ANDRAX core is extracted to /data... or any local in device storage the su command not work if is called from our app id, our terminal or anything inside ANDRAX app... the su only keep in a loading state, doesn't matter the command, "su" alone freeze... 

If the core is removed the su works again...

The core size is around 10GB...

strace return: "unexpected wait status 0x1f"

**Comment by NH-Killer** [comment] 2020-06-08 22:21
Su is granded, user can see the toast but su never load

**Comment by osm0sis** [comment] 2020-06-09 01:57
Why closed? Sounds like a problem still, no?

**Comment by NH-Killer** [comment] 2020-06-09 02:11
Yes, but opening this issue did not help me at all, but I believe the problem is related to pts...

A log of magisk:
![magiskptserror](https://user-images.githubusercontent.com/65501946/84098320-56f53b00-a9dd-11ea-8718-a1d2571ffbe9.jpg)

**Comment by osm0sis** [comment] 2020-06-09 02:40
If it's a bug with Magisk then it should stay open..

**Comment by NH-Killer** [comment] 2020-06-09 13:34
Why need stay open? No one reply, no one know why magisk cannot access pts sockets when has big files in /data... so i think this issue is useless, i'm working on this problem 13 hours per day during 35 days because this affects a lot of users and i'm a developer who has respect to this users!

But here, i'm talking alone!

**Comment by osm0sis** [comment] 2020-06-09 13:52
Aren't you a developer? Then you should understand why an active bug issue remains open.

@topjohnwu has a full time job at Apple, don't expect him to drop everything in his life to fix your bug immediately. He's only one man, with only so much free time.

I'll reopen this issue for you so that it can hopefully eventually be fixed, but, check your entitlement please.

**Comment by linuxandria** [comment] 2020-06-09 13:54
@osm0sis I knew he was a traitor! 😂
Inb4 magisk for iPhone

Anyhow

_Sent from my VIEW 1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NH-Killer** [comment] 2020-06-09 14:21
I just found the problem and fixed it, Now everything works on my system and i'll share to my users, to not leave you blind... is a lack on way that Android 9 and Androi 10 manage pts due to new kernel versions... bye

**Comment by osm0sis** [comment] 2020-06-09 15:02
So is it a problem on Magisk's side or yours?

**Comment by NH-Killer** [comment] 2020-06-09 15:29
> So is it a problem on Magisk's side or yours?
> 
> Because, again, if there is an issue on Magisk's part then this issue will remain open until fixed, and as a developer this concept should not be hard for you to grasp..

Magisk side...

I created a internal lib in my exec wrapper to make the compatibility in new Android Kernel to act like old kernel when spawn a pts from ptmx.

**Comment by osm0sis** [comment] 2020-06-09 15:48
Thank you for the details. I will reopen this and it will be gotten to and fixed when @topjohnwu can check out the ptr issue you identified.

Alternately you can check out the Magisk source and submit a PR in the meantime if you can figure out how to fix the handling Magisk-side. :+1:

**Closed** 2020-06-28 14:07 UTC
Labels: bug

**Comment by osm0sis** [comment] 2020-06-28 18:27
@NH-Killer can you confirm the ptr issue is fixed on 20417?

**Comment by osm0sis** [comment] 2020-07-06 17:45
@NH-Killer,

@topjohnwu was telling me the pts code is basically unchanged since the CM su days and pts shouldn't have anything to do with containerization, so your explanation is still fairly confusing. Please submit a PR to fix Magisk if you can identify where the true issue lies. :+1:

**Comment by ajvand6** [comment] 2022-10-10 10:48
Was this ever fixed? I believe I've had this issue on multiple devices on Android 11 or later.
