### ISSUE TITLE
Magisk doesn't install on Samsung Galaxy Tab S6 Lite

### ISSUE THREAD

**Issue by Fede2782** [topjohnwu/Magisk#6990] opened 2023-05-13 12:39 UTC
I'm trying to install Magisk on my Samsung Galaxy Tab S6 Lite LTE (2020). I tried Stable and Debug build however I always get this VBMETA error. I tried to patch:
- Only "boot"
- Only "boot" and "vbmeta"
- Only "boot" and "vbmeta" and "vbmeta_samsung"
- Entire AP file

Initially I had a block of UNOFFICIAL BINARIES however I removed it following a tutorial (KG/RMM Status)
Now I can flash however the device has a blue screen (Download mode) with a VBMETA error. 

There is no TWRP available for this device so I can't try the recovery method (unrecommended)

![20230513_142113](https://github.com/topjohnwu/Magisk/assets/78815152/c6d59e6c-55c5-47ec-b62d-7f084ee7da3b)

Device: Galaxy Tab S6 Lite LTE 2020 (SM-P615)
Android version: 13 official build P615XXU4FWC5 (One Ui 5.1)
Magisk version name: Debug
Magisk version code: d0c93842 (26101)

[stock boot and vbmeta.zip](https://github.com/topjohnwu/Magisk/files/11469655/stock.boot.and.vbmeta.zip)
[magisk tar of patched files.zip](https://github.com/topjohnwu/Magisk/files/11469656/magisk.tar.of.patched.files.zip)

**Comment by pndwal** [comment] 2023-05-13 13:02
Are your images entirely stock?... Flashing all patched AP along with other binaries (not on its own)... Transferred files using ADB, not MTP?...

**Comment by Fede2782** [comment] 2023-05-13 13:03
> Are your images entirely stock?... Flashing patched AP along with all other binaries (not on its own)... Transferred files using ADB, not MTP?...

yes of course: stock images. ADB always used

**Comment by pndwal** [comment] 2023-05-13 13:11
Wondering why seems you first seemed to try patching only boot... When flashing AP + other binaries, are you using CSC (wiping data)?

**Comment by Fede2782** [comment] 2023-05-13 13:19
I tried full flash (with CSC_) so Wipe data and full patched AP. Then stock flash and only boot. Same thing with boot+vbmeta and boot+vbmeta+vbmeta_samsung

**Comment by Fede2782** [comment] 2023-05-13 13:21
WHY SAMSUNG MAKES FLASHING UNOFFICIAL FIRMWARE SO HARD ON KNOX DEVICES, ESPECIALLY S SERIES ONES. Last month I rooted A22 5G and it was so easy and quick

**Comment by AByakugans** [comment] 2023-05-14 16:55
I found this topic: https://forum.xda-developers.com/t/guide-how-to-update-without-losing-data-when-rooted.4437615/#post-88336809 maybe it will help you here as well.

My questions are basically the same like from that topic - Does newest Magisk 26.1 include all changes from Canary version? Is it safe to use Magisk 26.1 for Patching Samsung Image including vbmeta and how can I know it really patched the file and not just writing it during the process? I have also A51 and getting the same vbmeta error after patching it with Magisk in AP slot - Do I need to use these "vbmeta_disabled" files?

Or what is the correct manual now with Magisk 26.1 or any other version when I already have rooted official ROM and want to update it to newest official firmware which I want to root using Magisk without getting this vbmeta error?

Already have unlocked bootloader, working Magisk in my currect firmware/version etc.

Thank you all!

**Comment by Fede2782** [comment] 2023-05-15 06:05
I found a solution for me. Patch only boot.img uncompressed. The result is a patched boot.img. add this to a tar archive. Flash stock, don't Reboot, then Flash tar with patched boot only. Now Reboot. It worked for me. Stable magisk and Debug magisk. 

Maybe for A51 is the same thing. In a few days a new updade for Tab s6 Lite will roll out and I can test it better. It is strange but vbmeta remains stock

**Comment by Fede2782** [comment] 2023-05-15 17:38
Today Samsung released the update. I patched only boot. Then I flashed Stock and immediately the patched boot. It worked, I successfully updated the firmware. However it differs from the Magisk official procedure for Samsung devices. However there were problems with Odin because it has blocked flashing unofficial boot after the stock one.

**Comment by BlackMesa123** [comment] 2023-06-27 12:45
Looks like an issue specific to your device, would be great to see your set of props and all the values displayed in Download mode to understand what's going on.

**Comment by Fede2782** [comment] 2023-07-07 17:36
Hi, which props would you like to see? I put everything i see in DL mode in the main post. I solved this with the method written in my old comment. It seems that magisk doesn't patch this tablet image if it is compressed or inside a tar file

**Comment by BlackMesa123** [comment] 2023-07-08 12:02
> Hi, which props would you like to see? I put everything i see in DL mode in the main post.

I don't see the edits in the main post you're talking about. I'd like to see the Download mode page and the output of the `getprop` cmd in your device via `adb shell`.

> I solved this with the method written in my old comment. It seems that magisk doesn't patch this tablet image if it is compressed or inside a tar file

Imho it's an issue with your device itself rather than Magisk. Magisk only patches boot/init_boot/recovery to install itself and vbmeta.img to disable AVB checks, the vbmeta_samsung file you shared in your issue is ignored by the app and not necessary to be patched.

**Comment by Fede2782** [comment] 2023-07-08 19:01
I'm now using stock vbmeta. The only thing Magisk modifed is boot.img and it disabled vbmeta from boot.img. the strange thing is that magisk doesn't patch Tab S6 Lite's boot.img when it is compressed

**Comment by BlackMesa123** [comment] 2023-07-08 22:20
> The only thing Magisk modifed is boot.img and it disabled vbmeta from boot.img.

I'm not quite sure about this. I checked the images you posted and the AVB footer is the exact same (flags haven't been patched). Did you purposefully patched the boot.img AVB header by enabling the toggle/manually by any chance? Because there's no way you're able to boot a custom boot.img without disabling AVB.

> the strange thing is that magisk doesn't patch Tab S6 Lite's boot.img when it is compressed

What do you mean by compressed? You mean the stock .lz4 boot.img in the firmware tar? The one you posted looks fine to me...

**Comment by Fede2782** [comment] 2023-07-09 05:07
I now have only modified boot.img I simply put that in Magisk install without enabling any toggle. I don't know however this solved my issue. It seems that when boot.img is in an .lz4 or .tar file Magisk has some problems. The only way to make it work is by patching directly boot.img

**Comment by BlackMesa123** [comment] 2023-07-09 06:39
> I now have only modified boot.img I simply put that in Magisk install without enabling any toggle. I don't know however this solved my issue.

The error you're getting is clearly caused by the AVB-disabled vbmeta.img patched by Magisk, not by the Magisk'd boot.img. Again, booting a custom boot.img without disabling AVB should be impossible, it might be possible due to a broken AVB implementation in your device's bootloader (another guy reported this https://github.com/topjohnwu/Magisk/issues/6230#issuecomment-1432836572 for another device) since with AVB you should get a similar AVB Fail error. Again, I'd like to see the parameters in your device's Download Mode to better understand what's going on.

> It seems that when boot.img is in an .lz4 or .tar file Magisk has some problems. The only way to make it work is by patching directly boot.img

Have you tried patching a tar with **only** the boot.img.lz4 file inside? It's very unlikely that Magisk can't patch correctly your boot.img. Again, the error you were getting is caused by the AVB-disabled vbmeta.img, not by your boot.img.

**Comment by Fede2782** [comment] 2023-07-09 08:02
I already tried but the only way remains patching only boot.img no vbmeta or anything else. I never tried patching boot.img uncompressed in .tar

**Closed** 2023-08-19 00:24 UTC
Labels: needs investigation
