### ISSUE TITLE
After flashing Magisk v20, my device's TWRP doesn't stay installed

### ISSUE THREAD

**Issue by rfgamaral** [topjohnwu/Magisk#1920] opened 2019-10-12 09:35 UTC
I have a OnePlus 7 Pro with Pie (9.0) and before updating to the latest Magisk I was using:

- TWRP v3.3.1-70 from [this topic](https://forum.xda-developers.com/oneplus-7-pro/development/recovery-unofficial-twrp-recovery-t3931322).
- Magisk v19.4

Everything was working and I was able to reboot into recovery from Magisk Manager, the power button extended menu and the bootloader. Everything was fine.

I've since flashed the latest Magisk v20.0 on my Pie device and now TWRP doesn't remain installed. Rebooting to recovery from any of the 3 methods mentioned above, actually boots into bootloader, not recovery.

I tried to fix the problem by reverting:

- `fastboot boot twrp-3.3.1-70-guacamole-unified-Pie.img`
- flashed `twrp-installer-3.3.1-70-guacamole-unified.zip` (installs to both slots)
- flashed `Magisk-v19.4.zip` (reverting, just in case)

If I try to reboot from within TWRP to recovery, I'm rebooted to the bootloader instead. If I reboot the device, everything is working as expected but if I try to reboot to recovery, again, I end up in the bootloader instead.

Somehow, Magisk v20.0 changed something in the boot partition that doesn't allow me to flash TWRP and have it remain installed. The question now is, is this a bug in Magisk v20.0 or something changed in Magisk v20.0 and the TWRP version I use needs to be updated to be compatible with Magisk v20.0?

In the mean time, do you have any recommendation to work around the issue?

**Comment by gumball3000ro** [comment] 2019-10-12 09:40
Bug Report:
Oneplus 7 GM1900
Android 9, Oxygen OS 9.5.8GM57BA

The latest Magisk 20 breaks TWRP recovery from sticking after reboot.

I've also tried to downgrade to my previous twrp recovery (twrp-3.3.1-52-guacamole-unified.img) and magisk versions (19.3 and 19.4) but I still have the same problem, after reboot, twrp recovery is gone.

steps:
1) fastboot boot twrp-3.3.1-70-guacamole-unified-Pie-mauronofrio.img
2) flashed twrp installer
3) then flashed magisk 20 from twrp
4) reboot
5) reboot recovery (from extended power menu)
6) It ends up in fastboot mode, twrp is gone


There is also another person which reported the same issue: https://t.me/twrp_Mauronofrio/2292

**Comment by HagenTronje** [comment] 2019-10-13 13:17
Same here.

OnePlus 7
9.5.8.GM57BA
twrp-3.3.1-1-guacamoleb
Magisk-v19.4

I was able to reboot into recovery from Magisk Manager, the power button extended menu and the bootloader.

Since i flashed the latest Magisk v20.0 TWRP doesn't remain installed. Rebooting to recovery from any of the 3 methods mentioned above, boots into bootloader (there seems to bee no recovery).

My attempt to fix the problem by

    fastboot boot twrp-3.3.1-4-guacamole.img
    install twrp-installer-3.3.1-4-guacamole.zip
    install Magisk-v20.0.zip

did not help.

When I try to reboot from within TWRP to recovery, the bootloader is booted instead.

I can reboot the device and it is working as expected but if I try to reboot to recovery I always end up in the bootloader instead.

**Comment by ColOfAbRiX** [comment] 2019-10-14 07:09
Me too and I reported the error here: https://forum.xda-developers.com/oneplus-7/help/run-twrp-installing-magisk-t3983065
I first had this problem with Magisk 19.1

**Comment by ColOfAbRiX** [comment] 2019-10-14 10:46
Now tried with twrp-3.3.1-70-guacamole-unified-installer-mauronofrio.zip and Magisk-v19.3.zip same result

**Comment by gumball3000ro** [comment] 2019-10-14 11:34
I've just factory resetted mine, and installed twrp-3.3.1-70-guacamole-unified-Pie-mauronofrio.img with Magisk v19.4, now everything is fine.

**Comment by lee0525** [comment] 2019-10-15 07:12
> I've just factory resetted mine, and installed twrp-3.3.1-70-guacamole-unified-Pie-mauronofrio.img with Magisk v19.4, now everything is fine.

Do you mean the factory reset in oos system settings? or the twrp settings?

**Comment by gumball3000ro** [comment] 2019-10-15 07:29
factory reset from twrp, I've only kept my files in the internal storage

**Comment by rfgamaral** [comment] 2019-10-15 10:22
Based on that (and my previous suspicions) I think that flashing Magisk v20 altered something in the system that is not reversible by uninstalling Magisk or flashing an older version.

That's why this was only fixable by factory resetting the device and avoid installing Magisk v20, unless you are on Android 10, that is. Well, @lee0525 and @gumball3000ro I'm assuming you guys were on Pie too?

**Comment by ElTifo** [comment] 2019-10-15 10:32
Xiaomi Mi A3 (laurel_sprout) doesn't allow fastboot boot. To install TWRP (for instance) we need to flash recovery.img into boot partition (on inactive slot) and then flash the TWRP installer zip (on the active slot).

With Magisk 19.3, the installer runs and the system gets booted ok. Reboot to recovery (TWRP or stock) is ok.

With Magisk 20.0 the installer runs and the system gets booted ok but it forces boot into bootloader if we try to access recovery (either TWRP or stock Recovery). Even if we install 19.3 zip and then update through Magisk Manager to 20.0, this happens if we try to access recovery.

As stated by others....something is wrong with 20.0 version.

Mi A3 is an A/B device and runs Android One (currently Pie).

**Comment by lee0525** [comment] 2019-10-15 10:34
> Based on that (and my previous suspicions) I think that flashing Magisk v20 altered something in the system that is not reversible by uninstalling Magisk or flashing an older version.
> 
> That's why this was only fixable by factory resetting the device and avoid installing Magisk v20, unless you are on Android 10, that is. Well, @lee0525 and @gumball3000ro I'm assuming you guys were on Pie too?
> 
> Maybe if @topjohnwu could pitch in here and find out exactly what could possible have changed between 19.4 and 20 that could alter this behavior, maybe we could revert it and fix the problem without factory resetting.

Yup. I'm on Pie too and gonna try the factory reset to check if this works for me

**Comment by osm0sis** [comment] 2019-10-15 12:03
Weird, working fine on my fajita (OP6T)

**Comment by Ae3NerdGod** [comment] 2019-10-15 12:14
Same here op7 pro, didn't try 19.4, but flashing stock boot.img and then magisk 19.3 reverts issue

**Comment by Ae3NerdGod** [comment] 2019-10-15 12:20
Something that might be worth noting: we have two different twrp images (at least the unofficial twrp does) one to `fastboot boot` while in pie, one for Q. Q twrp IMG will not boot from fastboot if active slot's bootloader is from the pie ROM, and if you try to install the recovery ramdisk for Q using the option in twrp (not the installer zip) causes the same behavior as magisk 20 does; rebooting to recovery fails and drops to bootloader/fastboot instead.

**Comment by rfgamaral** [comment] 2019-10-15 13:30
@Ae3NerdGod I've always used the Pie version of the unofficial TWRP, since I'm on Pie yet. But you found a way to revert the issue and I'd like to do the same, I guess the trick is on flashing stock `boot.img` and then flash TWRP installer again, followed by Magisk (v19.4 for me since I had that working before all of this).

Can you please let me know where can I get the stock `boot.img` from the latest official Pie and what is the exact command to flash that? I just want to be sure before messing my device 😆

**Comment by Ae3NerdGod** [comment] 2019-10-15 13:43
@rfgamaral 
op7 pro (guacamole) GM21AA 9.5.13 stock international boot image:
https://drive.google.com/open?id=1fon2XspyWSyEXe3aMi7RP-j7bQ_5JoCC
slow mirror: http://bowtie-ent.com/GM21AA_OOS_9.5.13_boot.img
guacamole fastboot packages: 
https://forum.xda-developers.com/oneplus-7-pro/how-to/rom-stock-fastboot-roms-oneplus-7-pro-t3931424

**Comment by jkooper32** [comment] 2019-10-15 14:48
@Ae3NerdGod I'm in the same situation as @rfgamaral. 

I had a few questions: 

1) will flashing the stock boot image erase my data or my settings ? 

2) Do I need to flash the stock image in bot slots or should i just use this command: fastboot flash boot GM21AA_OOS_9.5.13_boot.img ?

3) Do I need to disable all magisk/xposed modules to flash stock image? Will flashing stock image delete my modules? 

Thanks for all the help

**Comment by rfgamaral** [comment] 2019-10-15 15:56
@Ae3NerdGod Thank you very much for that.

@jkooper32 

1) it will not
2) if you don't use both slots separately and always use the one active (whatever that is), just flash to both, or just flash to the current broken one, it doesn't matter much I guess
3) no need, but just make sure to flash twrp installer followed by magisk to make sure your system boots succesfully

@Ae3NerdGod Please correct me if I'm wrong anywhere...

**Comment by jkooper32** [comment] 2019-10-15 15:59
Also, my phone is encrypted. Encryption has to be disabled in order to flash the stock image? Am I right?

**Comment by rfgamaral** [comment] 2019-10-15 17:25
> 
> 
> Also, my phone is encrypted. Encryption has to be disabled in order to flash the stock image? Am I right?

To flash `boot.img`? I never heard that one before, but I'm not sure, so wait for an answer from somebody that knows before doing anything.

**Comment by salustre** [comment] 2019-10-15 17:42
You can flash boot.img - this partition isn't encrypted, no worries.

Just make sure You have correct image.

Fot my OP7 I will use this one

https://www.oneplus7tips.com/download-kernel-oxygenos-9-5-8-op7/

**Comment by jkooper32** [comment] 2019-10-15 18:25
thank you very much gentlemen. I will fix my recovery once I get home. @rfgamaral what magisk did you end up using ? 19.4 or 19.3 ?

**Comment by rfgamaral** [comment] 2019-10-15 18:40
I haven't done it yet, no time to mess with my phone at the moment but I had v19.4 working before. Only v20 borked my TWRP.

**Comment by salustre** [comment] 2019-10-15 21:13
I can confirm that the following procedure was successful for me:

1) from bootloader mode execute
`fastboot flash boot boot.img`
2) boot twrp image (I user .70 unified)
`fastboot boot twrp.img`
3) flash twrp-installer.zip
4) flash magisk.zip (I flashed 19.4)

**Comment by jkooper32** [comment] 2019-10-15 21:36
@salustre I was reading the article you posted and this line kinda scared me: 

"If you have made other modifications (actual changes to the system, not apps that just need root access), then you’ll want to undo those changes before restoring the OxygenOS 9.5.8 kernel boot.img to the OnePlus 7". 

I don't think I've flashed anything through TWRP to modify the system, but I can't remember for sure.  In case I have tough, what would happen if I fastboot the stock recovery?

**Comment by Ae3NerdGod** [comment] 2019-10-15 21:45
@jkooper32 
As long as you flash twrp then magisk you should have no problem booting

PS: the article is saying if you personally modified the system partition, as in remounted it RW or flashed a zip that directly modified /system 

Worst case scenario you'd have to back to twrp and disable dm-verity with the universal dm-verity disabler here https://forum.xda-developers.com/android/software/universal-dm-verity-forceencrypt-t3817389

**Comment by Ae3NerdGod** [comment] 2019-10-15 21:47
PPS: to can also just flash system.img from your OOS version's fastboot package to undo any changes

**Comment by lee0525** [comment] 2019-10-16 01:02
> I can confirm that the following procedure was successful for me:
> 
> 1. from bootloader mode execute
>    `fastboot flash boot boot.img`
> 2. boot twrp image (I used .70 unified)
>    `fastboot boot twrp.img`
> 3. flash twrp-installer.zip
> 4. flash magisk.zip (I flashed 19.4)
> 
> So don't worry and go ahead with fixing Your twrp :)

do I need to uninstall the magisk module and do a backup first before doing so?

**Comment by Ae3NerdGod** [comment] 2019-10-16 02:25
1) for me all my modules seem to work normally. 

2) yes. Always just assume you need a backup. If whatever you're backing up is important enough to worry about and ask if you need to back it up, then the answer is yes. Anything and everything can go wrong at any time.

**Comment by lee0525** [comment] 2019-10-16 03:53
> I can confirm that the following procedure was successful for me:
> 
> 1. from bootloader mode execute
>    `fastboot flash boot boot.img`
> 2. boot twrp image (I used .70 unified)
>    `fastboot boot twrp.img`
> 3. flash twrp-installer.zip
> 4. flash magisk.zip (I flashed 19.4)
> 
> So don't worry and go ahead with fixing Your twrp :)

Just flash twrp using the above steps. Work like a charm. Thank you very much!

**Comment by HagenTronje** [comment] 2019-10-19 16:39
Does everybody reverting to Magisk19.4 mean Magisk20.0 is not supposed to work with Android 9 on OnePlus7 (9.5.8.GM57BA)?

**Comment by MrHappy** [comment] 2019-10-21 12:19
Is this going to be resolved?
You linked my issue (1958) to this, but I'm on Q.
Also OnePlus seems to have changed some thing which causes Magisk to break sensors, screen rotating, symlinks etc.
And as there is no working twrp for 1+6T on Q I can't flash any previous Magisk versions (unless the app lets me flash any previous version. In that case I don't know how to do this...)

**Comment by Ae3NerdGod** [comment] 2019-10-21 14:25
@MrHappy
On 1+7p, the sensors issue has nothing to do with magisk.
Are you on custom ROM? Or OOS
also, this might make an ass out of us, but I'd assume if the maker of magisk closes a topic, he's either working on it or can't fix it, either of which the only option is to wait. 

Do you have the q bootloader and baseband? 
On my 7pro nothing works right on Q custom ROMs unless I fastboot flash OOS Q first. 

In any case, go back to pie, head down to the Winchester, have a pint, and wait for this to all blow over.

**Comment by Ae3NerdGod** [comment] 2019-10-21 14:29
Also, you can manually install the twrp ramdisk from adb inside the ROM if you're savvy enough, you don't have to `fastboot boot`

**Comment by MrHappy** [comment] 2019-10-21 15:42
@Ae3NerdGod 
I'm on OOS 10.
Sensors (rotating of screen) works fine, untill I flash magisk_patched boot.img.
It seems O+ made some changes (added extra img or something like that - reserve.img if I recall correctly) and that doesn't help....

I don't like assumptions... It would also help other, I guess, if it was mentioned if he is on it / or it can be fixed.
(Prevents people opening similar issues ;) ).

adb ramdisk... WIll try that. Maybe an older version (19.4) works....

**Comment by Ae3NerdGod** [comment] 2019-10-21 15:53
Sensors work fine on the op7pro oos10 just to be clear, so maybe a separate sensors issue for the 6t

**Comment by MrHappy** [comment] 2019-10-21 15:59
@Ae3NerdGod 
It wouldn't surprise me....
I thought I was pretty clever googling stuff, but installing twrp with only adb I cannot find.... Only 'fastboot flash' or 'fastboot boot'....

Thanks for the heads-up... I'll keep away from persist.. ;)

**Comment by osm0sis** [comment] 2019-10-21 16:16
@rfgamaral why did you close this issue? You should reopen it if it's ongoing, since I don't think it's been fixed in the source yet.

**Comment by mauronofrio** [comment] 2019-10-21 16:20
Got the same problem on the OnePlus 6...

**Comment by Ae3NerdGod** [comment] 2019-10-21 17:21
for all those that are in **rooted** oos 10 on 6t and need TWRP @MrHappy 
try this
https://pastebin.com/7f7Z0kwE
get back to me if it didnt work, somethings weird about your twrp installer compared to the oneplus7pro

**Comment by MrHappy** [comment] 2019-10-21 17:57
@Ae3NerdGod 
I don't specifically need TWRP, but I have narrowed down my 'rotating screen' issue to riru-edxposed.
After disabling this module screen rotating works again, so it is not (specifically?) Magisk-related...

**Comment by mauronofrio** [comment] 2019-10-21 20:21
So after a really good clean up ( i use msmtool to come back to oreo, then update to pie and then updated to android Q), flashed TWRP installer, flashed magisk 19.4 beta and the device is rooted with a working twrp. Before this i tried to format data, but it didn't worked. After flashed magisk 20 i was unable to fix the problem also flashing Magisk 19.4.

**Comment by remewer** [comment] 2019-10-23 02:19
Is there a workaround on the version that gets installed using "Install to Inactive Slot" method? I'm currently on Magisk 19.4, but whel I use I nstall to Inactive Slot, it will force the latest version of Magisk.

**Comment by HagenTronje** [comment] 2019-10-23 15:26
Last weekend i update my OnePlus7 to Android 10.

I stored those files on my device:

OnePlus7Oxygen_14.E.21_OTA_021_all_1910071445_7c62a298c0e74bf4.zip
(from https://www.oneplus.com/de/support/softwareupgrade/details?code=10)

twrp-3.3.1-70-guacamole-unified-installer-mauronofrio.zip
(from https://forum.xda-developers.com/oneplus-7/development/recovery-unofficial-twrp-recovery-t3932943)

Magisk-uninstaller-20191011.zip
Magisk-v20.0.zip
(from https://github.com/topjohnwu/Magisk/releases/)

Then i restarted my device in bootloader-mode, connected it to my PC via USB-cable and did

fastboot boot twrp-3.3.1-70-guacamole-unified-Q-mauronofrio.img

From within TWRP i installed

OnePlus7Oxygen_14.E.21_OTA_021_all_1910071445_7c62a298c0e74bf4.zip
twrp-3.3.1-70-guacamole-unified-installer-mauronofrio.zip
Magisk-v20.0.zip

and rebooted my device.

The OnePlus7 works fine since then and TWRP is available on the device.

**Comment by mauronofrio** [comment] 2019-10-23 15:28
@HagenTronje the problem on oneplus 7 is on android Pie

**Closed** 2019-10-26 21:14 UTC

**Comment by roshantiwari434** [comment] 2020-10-05 03:53
Yesterday I installed the latest version of magisk manager v8.0.0 which is working here's the attachment of the [latest version of magisk manager](https://twrpupdate.com/download-latest-version-magisk-zip-magisk-manager/).
