### ISSUE TITLE
error 1 unknown/unsupported boot image format(issue still not resolved

### ISSUE THREAD

**Issue by kuttekalund** [topjohnwu/Magisk#1637] opened 2019-06-26 02:22 UTC
![Screenshot_2019-06-25-09-35-48](https://user-images.githubusercontent.com/52216580/60146265-99cafc80-97e6-11e9-9280-e2977b59853f.png)

my custom rom had supersu,substratum preinstalled 
i flashed unSU.zip to remove it 
done superuser removed 
root checker says "root access not properly setup"
i install magisk manager 
patch the boot.img file of current custom OS
100% completed 
boot into twrp
flash new patched boot.img done
flash magisk 19.3.zip
error 1 
please helpp
do I need to change magisk to any previous version 

what do I do please help

**Comment by osm0sis** [comment] 2019-06-26 03:02
Close this issue, it's pretty clearly a duplicate of #1526

You can patch your boot.img in Magisk Manager then flash it manually to root.

**Closed** 2019-06-26 03:53 UTC

**Comment by kuttekalund** [comment] 2019-06-26 09:31
@osm0sis I have patched it already 
but then device gets stuck in boot look @topjohnwu
