### ISSUE TITLE
/system could not be mounted when flashing 13.x

### ISSUE THREAD

**Issue by byronaltice** [topjohnwu/Magisk#295] opened 2017-07-18 19:20 UTC
### Issue
I have tried flashing 13.1, 13.2, and 13.3, but all fail with the message

```
- Mounting /system, /vendor, /cache, /data
! /system could not be mounted!
Updater process ended with ERROR: 1
Error installing zip file '/sdcard/Download/Magisk-v13.3.zip'
Updating partition details...
...done
```

When trying to flash the uninstaller, same error message.

Other zips are able to be flashed, such as elementalp, and twrp, and even Magisk 12.0.

### Stats
Hardware: Pixel XL
OS Version: Marlin-n2g47o-factory-7150cd63 (just reinstalled)

### Process

Flashed zips in this order:

1. ElementalX: ElementalX-P-1.11
2. Magisk: Magisk 13.x
3. TWRP: twrp-pixel-installer-marlin-3.1.0-0RC2
4. Boot Signer: VerifiedBootSigner-v7

**Comment by TheComputerGuy96** [comment] 2017-07-18 19:23
Duplicate of https://github.com/topjohnwu/Magisk/issues/47

**Closed** 2017-09-13 16:04 UTC
