### ISSUE TITLE
Magisk 11.5 breaks fingerprint sensor on FRD-L04C567B162

### ISSUE THREAD

**Issue by Gondost** [topjohnwu/Magisk#120] opened 2017-03-20 04:44 UTC
11.1 works, 11.5 completely broke the fingerprint sensor on my Huawei Honor 8. Stock rooted device. After uninstalling Magisk, functionality was restored.

**Comment by zhrmiah** [comment] 2017-03-22 05:55
I can confirm that it breaks the fingerprint sensor on my Huawei Honor 8 and locks my phone with pin code. I can't unlock my phone and I have to do hard reset.

**Comment by Gondost** [comment] 2017-03-22 14:34
> zhrmiah: I can confirm that it breaks the fingerprint sensor on my Huawei Honor 8 and locks my phone with pin code. I can't unlock my phone and I have to do hard reset.
Was this 11.5 or 11.6? On 11.5 I was able to flash the uninstall zip and everything went back to normal. I haven't tried 11.6 yet.

**Comment by zhrmiah** [comment] 2017-03-22 23:17
I flashed 11.1 then updated to 11.5 from Magisk manager. Restarted my phone and found that I cannot unlock my phone.

**Comment by topjohnwu** [comment] 2017-03-29 20:44
Huawei seems to have special parts in kernel, would take more time to investigate

**Comment by zhrmiah** [comment] 2017-03-31 03:37
@topjohnwu Thanks alot for managing time. I can't get new version. Stuck on 11.1.

**Comment by Gondost** [comment] 2017-03-31 20:00
@topjohnwu 12 also does the same thing -- flashing uninstaller zip fixes it and I can go back to 11.1.

Is there something that we can do to help make this easier? Stock boot image? Kernel source? Etc?

**Comment by Gondost** [comment] 2017-04-04 00:46
@topjohnwu 

Here is the unpacked boot image for both the Honor 8 Nougat boot.img. On the MM boot image, Magisk 11.1 is working but nothing later. On the N image Magisk isn't working at all, due to Huawei's messed up loop support.

[FRD-L04C567B162_MM-boot.zip](https://github.com/topjohnwu/Magisk/files/891815/FRD-L04C567B162_MM-boot.zip)
[FRD-L04C567B360_N-boot.zip](https://github.com/topjohnwu/Magisk/files/891817/FRD-L04C567B360_BOOT.zip)

**Comment by Gondost** [comment] 2017-05-14 18:59
Issue still present in v12 on Nougat (now that Huawei released an updated kernel with proper loop support), the fingerprint sensor stops working. The menus around Fingerprint ID are also different. Flashing 11.1 restores functionality.

I understand there were significant changes from 11.1 to 11.5(.6) onward, what could we do do help facilitate the debugging?

**Comment by zhrmiah** [comment] 2017-06-13 00:01
@Gondost I guess We have to wait until the issue is fixed by @topjohnwu

**Closed** 2017-09-13 15:41 UTC
