### ISSUE TITLE
magisktmp gone during boot

### ISSUE THREAD

**Issue by Live-Block** [topjohnwu/Magisk#7780] opened 2024-02-09 01:43 UTC
Device:Realme V3(RMX2200)
Android version:Android13
Magisk version name:b04e139
Magisk version code:27001

#### Before 26.2 version, I flash boot by magisk patching and my device work successfully (At least 26.1).
After 26.1 version, I can flash boot by magisk patching too, but when I boot my device, magisk manager show N/A.

I really need help, thanks.
Hope you have a nice day!

**Comment by canyie** [comment] 2024-02-09 04:05
You mean 26.1 is the latest working version, and starting from 26.2 it doesn't work anymore? Please provide a logcat captured on boot.

**Comment by Live-Block** [comment] 2024-02-09 05:05
This is log
[Logcat.log](https://github.com/topjohnwu/Magisk/files/14217492/Logcat.log)

**Comment by yujincheng08** [comment] 2024-02-09 05:26
`Cannot find '/debug_ramdisk/magisk': No such file or directory`

**Comment by yujincheng08** [comment] 2024-02-09 05:27
send magisk's log

**Comment by Live-Block** [comment] 2024-02-09 05:54
### Magisk log
[Uploading magisk_log_2024-02-09T13.52.30.log…]()

**Comment by canyie** [comment] 2024-02-09 12:30
麻烦抓取一份 Android bugreport 发上来：https://developer.android.com/studio/debug/bug-report
另外我注意到你的 log 里 magisk app 的版本是 26.2 稳定版，你的 boot 是稳定版修补的吗，如果是的话用 27001 debug 版修补刷进去再抓 bugreport

**Comment by Live-Block** [comment] 2024-02-09 13:58
这与带不带su没有关系，我在不带su的系统上也是这样
[
[bugreport-treble_arm64_bgS-TSV1.220628.053-2024-02-09-21-53-58.zip](https://github.com/topjohnwu/Magisk/files/14222555/bugreport-treble_arm64_bgS-TSV1.220628.053-2024-02-09-21-53-58.zip)
](url)

**Comment by ECM-xiaokong** [comment] 2024-02-09 14:04
一样的问题，我设备小米10S,更新到magisk27.0后直接不工作，倒退回magisk26.4才会工作

**Comment by Live-Block** [comment] 2024-02-09 14:05
我是26.2开始就没用了，能够修补，但是刷入了还是无法获取

**Comment by ECM-xiaokong** [comment] 2024-02-09 14:08
新年限定新版bug

**Comment by kooritea** [comment] 2024-02-09 18:09
一样的问题，从26.3使用直接刷入的方式更新到27.0后，app无法识别已安装的magisk。这个时候再通过app退回26.3依然不行，只能通过重新从rom中提取boot.img再进行修补刷入后可以解决。

我怀疑是使用旧的已修补的boot重新修补就会触发这个问题。

**Comment by yujincheng08** [comment] 2024-02-10 04:03
bugreport 太晚了。需要一个重启之后马上抓的。

**Comment by Live-Block** [comment] 2024-02-10 10:07
这个应该行，第一屏就在waiting device了
[bugreport-treble_arm64_bgS-TSV1.220628.053-2024-02-10-18-02-43.zip](https://github.com/topjohnwu/Magisk/files/14228834/bugreport-treble_arm64_bgS-TSV1.220628.053-2024-02-10-18-02-43.zip)

**Comment by yujincheng08** [comment] 2024-02-10 17:39
caused by this commit: it tries to umount `/debug_ramdisk` twice, which unmounts magisk tmp. wont fix.

**Closed by yujincheng08** 2024-02-10 17:39 UTC

**Comment by phhusson** [comment] 2024-02-11 02:39
/debug_ramdisk is used to store adb_debug.prop and userdebug_plat_sepolicy.cil, as per https://android.googlesource.com/platform/system/core/+/refs/heads/main/init/first_stage_init.cpp#481

The log mentions "/debug_ramdisk/magisk". I can happily fix GSI to properly handle adb_debug.prop and userdebug_plat_sepolicy.cil to conform to AOSP, but that won't fix Magisk, will it?
