### ISSUE TITLE
Hid Manager w/o Icon

### ISSUE THREAD

**Issue by Stillhard** [topjohnwu/Magisk#3778] opened 2021-01-27 15:45 UTC
Just to inform @topjohnwu, latest build canary debug https://github.com/topjohnwu/Magisk/commit/6fb20b3ee547271cc11870f8a876f4529e723f65 lost the launcher icon's after the packagename's renamed (hid)

Tested on OS 6 and OS 7

**Comment by Didgeridoohan** [comment] 2021-01-27 17:38
That's by design... It's even covered in the faq (except now it should read Android 5.0+):
https://topjohnwu.github.io/Magisk/faq.html#q-after-i-hidden-magisk-manager-the-app-icon-is-broken

You can close this now.

**Comment by Stillhard** [comment] 2021-01-27 17:55
> That's by design... It's even covered in the faq (except now it should read Android 5.0+):
> https://topjohnwu.github.io/Magisk/faq.html#q-after-i-hidden-magisk-manager-the-app-icon-is-broken
> 
> You can close this now.

It's all good then if it's so, closed

**Comment by topjohnwu** [comment] 2021-01-29 13:58
Currently the feature is blocked on API 26, this is a bug

**Closed** 2021-01-30 07:16 UTC
Labels: confirmed

**Comment by Stillhard** [comment] 2021-01-30 08:08
Apparently it's not fixed yet, I'm so sorry @topjohnwu

**Comment by Didgeridoohan** [comment] 2021-01-30 08:12
There's not been any new release since the fix, so unless you built the new Magisk app yourself you wouldn't be able to tell yet if it works or not...

**Comment by Stillhard** [comment] 2021-01-30 09:00
> There's not been any new release since the fix, so unless you built the new Magisk app yourself you wouldn't be able to tell yet if it works or not...

Oc i'm aware of it, using artifact from [here ](https://github.com/topjohnwu/Magisk/runs/1796541520)helped me get thru

**Comment by Stillhard** [comment] 2021-02-23 14:56
Bump this if it's alright

**Comment by Didgeridoohan** [comment] 2021-02-23 15:51
"Bumping" by simply posting a new message does nothing. If there's still an issue on the current (Canary) release you need to either open this issue again or make a new one with all the required information and details.
