### ISSUE TITLE
Moto G5 mount /dev/block/loop0->/dev/source failed with 13: permission denied

### ISSUE THREAD

**Issue by Theitfixer85** [topjohnwu/Magisk#333] opened 2017-08-08 18:59 UTC
From the magisk log on moto g5 with v13.3 installed (flashed v11.6 than used app to update to v13.3)

mount /dev/block/loop0->/dev/source failed with 13: permission denied

see my other issue for moto g5 for the boot.img

**Comment by sameer** [comment] 2017-08-10 18:02
Seems to be an f2fs issue, occurs on Z Play and other devices too

**Comment by ldrolez** [comment] 2017-08-16 14:33
duplicate of #312  ?

**Comment by Theitfixer85** [comment] 2017-08-27 16:33
The problem is we don't have any other kernels and until someone with the knowledge knows how to update the f2fs in the kernel it will never work

**Comment by fOmey** [comment] 2017-09-10 12:26
Running magisk on a doogee mix, same error..

```
--------- beginning of main
I(  305:  305) Magisk v14.0(1400) daemon started
I(  305:  307) ** post-fs mode running
--------- beginning of system
I(  305:  450) ** post-fs-data mode running
I(  305:  450) * Mounting mirrors
I(  305:  450) mount: /dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/system -> /dev/magisk/mirror/system
I(  305:  450) link: /dev/magisk/mirror/system/vendor -> /dev/magisk/mirror/vendor
I(  305:  450) bind_mount: /dev/magisk/mirror/bin
E(  305:  450) mount /dev/block/loop0->/dev/source failed with 13: Permission denied
I(  305:  582) ** late_start service mode running
I(  305:  582) * Running service.d scripts
I(  305:  582) * Running module service scripts
E( 5080: 5080) mount /dev/block/loop1->/dev/magisk_merge failed with 13: Permission denied
```

**Closed** 2017-09-13 16:08 UTC
