### ISSUE TITLE
Unable to hide magisk manager by renaming package ID! 

### ISSUE THREAD

**Issue by RamuSriram** [topjohnwu/Magisk#6485] opened 2022-12-28 07:10 UTC
Please help me, unable to rename the package of magisk. After hiding magisk the renamed app gets crashed when tried to open but after uninstalling it, the main magisk app still works. What's the reason behind the crash of renamed package ID app?  How can it be fixed now? Attached screenshot of error while opening after renaming. I am using OnePlus 9RT device with Android 13. Build number of my device is MT2111_11_F.13 Also attached the magisk log

![Screenshot_2022-12-28-09-08-45-91_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/71754546/209771575-623c13e0-7628-49b3-a955-088848a10171.jpg)

Device: OnePlus 9RT
Android version: Android 13
Magisk version name: 831a398b (25206) (D)
Magisk version code: 831a398b (25206) (D)
[magisk_log_2022-12-28T12.35.13.log](https://github.com/topjohnwu/Magisk/files/10312734/magisk_log_2022-12-28T12.35.13.log)

**Comment by vvb2060** [comment] 2022-12-28 09:51
upload crash log

**Comment by yujincheng08** [comment] 2022-12-28 09:52
I don't see any relative content from your log and I suspect if you are really using the debug version. Please reproduce the problem and provide full logcat. Otherwise, this issue will be closed again.

**Comment by RamuSriram** [comment] 2022-12-28 10:34
Ok, wait. I will send ADB logcat in a while. Meanwhile, watch the attached video where I'm reproducing the problem.

Uploading Record_2022-12-28-16-01-51.mp4…

**Comment by yujincheng08** [comment] 2022-12-28 11:15
your magisk app is debug version but the installed magisk is not

**Comment by RamuSriram** [comment] 2022-12-28 11:27
Okay, I have installed magisk debug now, still facing the same error. Attaching new log. 
[magisk_log_2022-12-28T16.56.53.log](https://github.com/topjohnwu/Magisk/files/10313966/magisk_log_2022-12-28T16.56.53.log)
![Screenshot_2022-12-28-16-57-24-20_785cfb1f0fb0c9a2030c9b38a1c3479a](https://user-images.githubusercontent.com/71754546/209805315-3d65714e-8f0b-4b00-b14a-416d9ad1fd42.jpg)

**Comment by yujincheng08** [comment] 2022-12-28 11:28
I think I said we need full adb logcat.

**Comment by RamuSriram** [comment] 2022-12-28 11:29
> I think I said we need full adb logcat.

Yes, please wait. I will send it after few hours. I am currently away from my PC.

**Comment by RamuSriram** [comment] 2022-12-28 11:35
> you can use logcat reader or so to get one.

Okay, trying.

**Comment by RamuSriram** [comment] 2022-12-28 11:39
> you can use logcat reader or so to get one.

Here is the log from Logcat Reader
[logcat_12-28-2022_17-08-01.txt](https://github.com/topjohnwu/Magisk/files/10314000/logcat_12-28-2022_17-08-01.txt)

**Comment by vvb2060** [comment] 2022-12-28 16:09
```
Unable to instantiate appComponentFactory
java.lang.ClassNotFoundException: Didn't find class "y.B" on path: DexPathList[[zip file "/data/app/~~CCXhtw6Pdcg2iY2I8Xki7A==/lk.ke-cZTuuq0nfFyzrnfrrAgXhw==/base.apk"],nativeLibraryDirectories=[/data/app/~~CCXhtw6Pdcg2iY2I8Xki7A==/lk.ke-cZTuuq0nfFyzrnfrrAgXhw==/lib/arm64, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.LoadedApk.createAppFactory(LoadedApk.java:283)
	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1059)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1149)
	at android.app.LoadedApk.getResources(LoadedApk.java:1404)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3128)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3120)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7049)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)

```

**Comment by vvb2060** [comment] 2022-12-28 16:12
upload repacked apk  (/data/app/~~CCXhtw6Pdcg2iY2I8Xki7A==/lk.ke-cZTuuq0nfFyzrnfrrAgXhw==/base.apk)

**Comment by RamuSriram** [comment] 2022-12-28 16:14
> upload repacked apk (/data/app/~~CCXhtw6Pdcg2iY2I8Xki7A==/lk.ke-cZTuuq0nfFyzrnfrrAgXhw==/base.apk)

Okay, Please wait.

**Comment by RamuSriram** [comment] 2022-12-28 16:46
> upload repacked apk (/data/app/~~CCXhtw6Pdcg2iY2I8Xki7A==/lk.ke-cZTuuq0nfFyzrnfrrAgXhw==/base.apk)

This. https://anonfiles.com/u7M6V7O6y8/base_apk

**Comment by vvb2060** [comment] 2022-12-28 17:01
#6475 fixed

wait next canary release

**Comment by RamuSriram** [comment] 2022-12-28 17:03
> #6475 fixed
> 
> wait next canary release

Okay. Waiting. Thanks :)

**Comment by vvb2060** [comment] 2022-12-28 17:06
you can use ci build now https://github.com/topjohnwu/Magisk/actions/runs/3784407872

**Comment by RamuSriram** [comment] 2022-12-28 17:12
> if you can't wait, you can use ci build https://github.com/topjohnwu/Magisk/actions/runs/3784407872

Pro brother, It Worked 😳 Thanks a lot for the quick response & solution :)

**Comment by RamuSriram** [comment] 2022-12-28 17:28
> if you can't wait, you can use ci build https://github.com/topjohnwu/Magisk/actions/runs/3784407872

Btw can I know was it because of main app downloading issue through Stub APK? Server side issue? Or app bug?

**Comment by RamuSriram** [comment] 2022-12-28 17:32
> > if you can't wait, you can use ci build https://github.com/topjohnwu/Magisk/actions/runs/3784407872
> 
> Btw can I know was it because of main app downloading issue through Stub APK? Server side issue? Any android 13 restriction? Or app bug?

**Comment by vvb2060** [comment] 2022-12-28 17:34
I think topjohnwu may have a little problem when compiling, the compiled apk is broken.

**Comment by RamuSriram** [comment] 2022-12-28 17:35
> I think topjohnwu may have a little problem when compiling, the compiled apk is broken.

Okay 👍

**Comment by vvb2060** [comment] 2022-12-28 17:40
https://github.com/topjohnwu/Magisk/actions/runs/3780156739

Because this ci build is fine. anyway, #6475 can prevent this from happening again in the future.

**Comment by RamuSriram** [comment] 2022-12-28 18:30
> https://github.com/topjohnwu/Magisk/actions/runs/3780156739
> 
> Because this ci build is fine. anyway, #6475 can prevent this from happening again in the future.

Yeah, it's working fine too 👍

**Comment by admin-elvistrujanovic** [comment] 2023-01-02 12:04
I'm using debug build, not canary build but I'm still have the same problem - how can this be fixed

**Comment by admin-elvistrujanovic** [comment] 2023-01-02 12:43
I'm using debug build, not canary build but I'm still have the same problem - how can this be fixed

~~Nevermind - I found a fix. After flashing the Magisk debug build via Recovery mode (migrating from stable to debug build), and installing Magisk debug apk I also need to install stub-debug.apk as the magisk update and after that install debug.apk and now the problem is fixed.~~ (this fix doesn't work for me after I updated Magisk debug build to the latest debug build from Magisk app)

**Comment by TaurineRepo** [comment] 2023-01-03 20:56
Not fixed in the future updates yet. Only in the 78f1b499 (25206) actually have the fix - for the new canary/debug build version it needs to be fixed manually.

> > https://github.com/topjohnwu/Magisk/actions/runs/3780156739
> > Because this ci build is fine. anyway, #6475 can prevent this from happening again in the future.
> 
> Yeah, it's working fine too 👍

**Comment by TaurineRepo** [comment] 2023-01-04 00:04
Unhide "off-topic" comment to get ability to see the comment that is not off-topic but I think that dev thinks that it's off-topic.

**Comment by RamuSriram** [comment] 2023-01-14 07:17
> https://github.com/topjohnwu/Magisk/actions/runs/3780156739
> 
> Because this ci build is fine. anyway, #6475 can prevent this from happening again in the future.

Hello, how to make it work in WorkSpace profile? Same magisk package name can't be present in both main & work profiles?

**Closed** 2023-02-28 07:45 UTC
Labels: confirmed
