### ISSUE TITLE
/sys/fs/pstore is empty after kernel crash

### ISSUE THREAD

**Issue by powellnorma** [topjohnwu/Magisk#7342] opened 2023-09-13 14:04 UTC
When I trigger a kernel crash via `echo c > /proc/sysrq-trigger`, normally  `/sys/fs/pstore` gets filled with 3 files:
```
sunfish:/ # ls /sys/fs/pstore/                                                                                                                                                                
console-ramoops-0  dmesg-ramoops-0  pmsg-ramoops-0
```

But when Magisk is installed, this folder stays empty.

What I noticed is that normally only after pin unlock pstore gets mounted:
```
pstore on /sys/fs/pstore type pstore (rw,seclabel,relatime)
```

But with magisk, something pstore related is already mounted before that stage:
```
pstore on /debug_ramdisk/.magisk/mirror/sys/fs/pstore type pstore (rw,seclabel,nosuid,nodev,noexec,relatime)
```

And after unlock:
```
pstore on /debug_ramdisk/.magisk/mirror/sys/fs/pstore type pstore (rw,seclabel,nosuid,nodev,noexec,relatime)
pstore on /sys/fs/pstore type pstore (rw,seclabel,relatime)
```

[magisk.log](https://github.com/topjohnwu/Magisk/files/12598446/magisk.log)
[dmesg.log](https://github.com/topjohnwu/Magisk/files/12598553/dmesg.log)

Device: Pixel4a
Android version: 13
Magisk version name: 26.3
Magisk version code: 26301

**Comment by kaiyu92** [comment] 2023-09-15 07:06
Same issue here with Pixel 4a device. `/sys/fs/pstore` seems to always be empty even after a kernel crash.

Device: Pixel 4a
Android Version: 10
Magisk version: 26.1

**Comment by vvb2060** [comment] 2023-09-16 15:25
I don't think it has anything to do with magisk.

**Comment by powellnorma** [comment] 2023-09-16 19:23
> I don't think it has anything to do with magisk.

I tested several times: When not using magisk `/sys/fs/pstore` gets filled, when using it `/sys/fs/pstore` stays empty.

**Comment by vvb2060** [comment] 2023-09-16 19:25
How to panic the kernel without root?

**Comment by powellnorma** [comment] 2023-09-16 19:28
In a debug build, one can use `adb root`

**Comment by vvb2060** [comment] 2023-09-16 19:29
After you install magisk, is adb root still available?

**Comment by powellnorma** [comment] 2023-09-16 19:32
I think so, since afaik `adb root` has nothing to do with magisk. Why are you asking though?

**Comment by vvb2060** [comment] 2023-09-16 19:35
Have you tried it?  If you have some magisk modules, adb root will not be available, kmsg may be for similar reasons.

**Comment by powellnorma** [comment] 2023-09-16 19:45
>  If you have some magisk modules, adb root will not be available

Yes, it works - I have just double checked

**Comment by powellnorma** [comment] 2023-09-23 12:52
I have found a solution that works for my device:

Add `umount("/sys/fs/pstore");` before the "mirror mounting" logic:

https://github.com/topjohnwu/Magisk/blob/15e13a8d8bb61ed896df94881d63903cbfcc516b/native/src/core/bootstages.cpp#L97-L98

My guess is that the system clears up the pstore of "two mounts before" it. Because I also tried to mount it again after the mirror logic (via `mount("pstore", "/sys/fs/pstore", "pstore", 0, "");`), and then pstore again stays empty.

I think the best solution would be to not use `MS_REC`, and instead always use the fallback logic, and then skip the mirror mount if `info.type == "pstore"`.

**Comment by yujincheng08** [comment] 2023-09-24 02:37
Not using `MS_REC` is not a good solution. Maybe you should try to move `pstore` into somewhere unbindable, then mount mirror `MS_REC` and move `pstore` back.

**Comment by vvb2060** [comment] 2023-09-25 19:27
After investigation, I found that if umount pstore in boot_complete and then mount pstore after unlock screen, files will exist. It should be caused by other reasons, not bind mount mirror

**Comment by Ristovski** [comment] 2023-10-20 18:25
Can confirm that same thing happens on Xiaomi Mi 11 Lite 5G NE (`lisa`). What exactly is the cause here?

**Comment by yujincheng08** [comment] 2023-10-24 15:05
https://android.googlesource.com/kernel/msm/+/b71d012395a42ae6b58f36f5eaf460a9ff29e31a%5E%21/

**Comment by yujincheng08** [comment] 2024-01-03 07:50
fixed by deedb462a09890f7cfb63880203be962ca4a0fd9

**Comment by yujincheng08** [comment] 2024-01-04 17:15
Try #7685

**Comment by vvb2060** [comment] 2024-01-07 05:11
The pstore is decrypted when the user first unlocks device, at which point no pstore instance can exist. Decryption will fail if [a pstore bind mount exists](https://github.com/topjohnwu/Magisk/pull/7685), or if [a unshared process retains a pstore instance](https://github.com/LSPosed/LSPosed/pull/2913).

**Closed** 2024-03-20 06:21 UTC
Labels: confirmed, core
