### ISSUE TITLE
Some customized kernels are incompatible with Magisk 24303+ that no longer strips verification flags of early mount partitions

### ISSUE THREAD

**Issue by Jon8RFC** [topjohnwu/Magisk#5777] opened 2022-04-30 13:12 UTC
Device: Pixel 6 Pro
Android version: 12.1 (SP2A.220405.004)
Magisk version name: 63a89d9
Magisk version code: 24306

I had this issue with 24305 as well, but no longer have that boot.img.  I never tested with 24304, 24303, 24302.
This is with a custom kernel, but not everyone using a Pixel 6/Pro and this custom kernel has this issue.  Some do, however.

The phone quickly crashes, and does not get to the point where an adb log can be taken.  It repeatedly will crash and reboot, but I was informed that it was not actually a bootloop I was experiencing because I cannot get to the point where adb access is possible.  It crashes in about 1 second once the "Google" splash screen is displayed and the phone flickers off, not getting anywhere close to the "G" animated loading screen, during which adb would be available.

I managed to get a console-ramoops-0 with @freak07's assistance.

The issue is reliably resolved with 100% boot success rate by flashing only a boot.img patched with magisk 24300.  I tested with a newer kernel as well, and disabled all modules, including not using the module for the custom kernel.  The phone cannot boot to a point where any troubleshooting can be done if using the custom kernel patched with magisk 24305 or 24306.

It is reliably reproducible, with a 0% boot success rate with a 24306 patched boot.img
For the sake of argument, I sent Freak07 my 24306 patched boot.img and they were able to successfully boot with it.  They sent me their own 24306 patched boot.img which worked for them, and it caused the same crash for me.

Supplemental info, if it's helpful:

- I believe I used to disable verity in the beginning, but once magisk was updated to no longer require it, I no longer did that, but I may be confusing my Pixel 5 with my Pixel 6 Pro.
- I have dirty flashed, without issue, every factory image as it's released, since December 2021, including the now-pulled December 2021 factory image.
- When using the flashable zip for this custom kernel, flashing via EXKM with Magisk 24305, it resulted in the EIO splash screen error, but the phone locked up and was unresponsive on the "Google" screen; the EIO issue does not occur when manually flashing a 24305/24306 boot.img via fastboot, but the crash occurs.  There is no issue whatsoever flashing via EXKM with Magisk 24300.

Necessary files:
https://drive.google.com/file/d/1XWTjcOqb_bdMsZQtx2vzEYlReOsRTfTT/view?usp=sharing

**Comment by canyie** [comment] 2022-05-01 05:41
```
[    1.248267][    T1] device-mapper: table: 254:10: verity: Hash device is too small
[    1.248269][    T1] device-mapper: ioctl: error adding target to table
[    1.248275][    T1] init: DM_TABLE_LOAD failed: Argument list too long
[    1.248392][    T1] init: [libfs_avb]Couldn't create verity device!
[    1.248396][    T1] init: Failed to setup verity for '/vendor_dlkm': Argument list too long
[    1.248400][    T1] init: Failed to mount /vendor_dlkm: Argument list too long
[    1.248450][    T1] init: Failed to mount required partitions early ...
[    1.248468][    T1] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
```
I think it's likely caused by init patch. @yujincheng08 Could you take a look for this?

**Comment by canyie** [comment] 2022-05-01 06:42
Does this build boot?
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8598403/app-debug.zip)

**Comment by Jon8RFC** [comment] 2022-05-01 08:46
Unfortunately, no.  It crashes as well.
[console-ramoops-0_2022-05-01.0337.txt](https://github.com/topjohnwu/Magisk/files/8598550/console-ramoops-0_2022-05-01.0337.txt)

**Comment by canyie** [comment] 2022-05-01 09:07
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8598572/app-debug.zip)
Hmmm... Try this?

**Comment by Jon8RFC** [comment] 2022-05-01 10:00
It would not boot.  It crashed.
[console-ramoops-0_2022-05-01.0458.txt](https://github.com/topjohnwu/Magisk/files/8598663/console-ramoops-0_2022-05-01.0458.txt)

**Comment by Jon8RFC** [comment] 2022-05-03 13:39
I've updated to 12.1.0 (SP2A.220505.002, May 2022) and Magisk 24307.
It crashes with 24307, but now it also crashes with 24300 so I am unable to get a console-ramoops-0 anymore by flashing a working patched kernel after the crash, and reflashing the rest of the files to be able to boot results in the ramoops being overwritten as I understand it.  I've attached it anyway, but it may be from me rebooting and reflashing the other files rather than the crashing.
[console-ramoops-0_24307_possibly.txt](https://github.com/topjohnwu/Magisk/files/8610787/console-ramoops-0_24307_possibly.txt)

**Comment by capntrips** [comment] 2022-05-03 14:34
Device: Pixel 6
Android version: 12.1 (SP2A.220405.004)
Magisk version name: cc79a96f
Magisk version code: 24307

I hadn't upgraded yet, so I was able to grab the `ramoops` from Kirisakura 2.3.0 on `SP2A.220405.004` and 24307:

[console-ramoops--2022-05-03--09-05.log](https://github.com/topjohnwu/Magisk/files/8611143/console-ramoops--2022-05-03--09-05.log)

I'm installing the May update now. I'll add that `ramoops`, if I'm able to grab it, as well

**Comment by canyie** [comment] 2022-05-03 16:37
Does it work with stock kernel?

**Comment by capntrips** [comment] 2022-05-03 16:38
it does

**Comment by capntrips** [comment] 2022-05-03 16:56
Device: Pixel 6
Android version: 12.1 (`SP2A.220505.002`)
Magisk version name: cc79a96
Magisk version code: 24307

24.3 works fine for me on `SP2A.220505.002`, so I was able to grab `ramoops` from Kirisakura 2.4.0 and 24307:

[console-ramoops--2022-05-03--11-52.log](https://github.com/topjohnwu/Magisk/files/8612234/console-ramoops--2022-05-03--11-52.log)

**Comment by Jon8RFC** [comment] 2022-05-03 17:15
> Does it work with stock kernel?

Yes.

**Comment by canyie** [comment] 2022-05-04 09:11
So this may be a kernel issue I think 🤔 Maybe Magisk triggered some bugs in the custom kernel. Anyway, I don't think Magisk should do anything for this

**Comment by freak07** [comment] 2022-05-04 12:38
@canyie I don´t think so. 

my kernel isn´t the only one that´s affected by this on the Pixel 6/Pro forums. 
check the post here for example:
https://forum.xda-developers.com/t/kernel-blu_spark-r60-a12l.4370811/post-86629989

While my kernel has linux-stable upstream I just checked the dm-verity drivers and they appear to be exactly the same as stock kernel.


Those issues started with canary 24303 after magisk removed the need to pass the vbmeta disable verity/verification flag and users actually run their devices like that. 

While updating my device I kept the vbmeta flags disabled for development purposes so I can flash images without relying on magisk patching anything and I never ran into this issue. Same as eng.stk in the post I quoted.

Some users with vbmeta flags enabled can flash the kernel.zip just fine via the kernel managers, while some others can´t and run into bootloops. 

Some get a device corrupted message, which can be solved by booting/flashing a boot.img from an outdated firmware once and flashing the correct boot.img afterwards.

**Comment by yujincheng08** [comment] 2022-05-05 06:04
I think there's nothing to do with Magisk.
If the stock kernel works, why don't the customized ones? If some syscalls are misused by Magisk, yes, Magisk should fix it. But the things seem like customized kernels rely on some undocumented internal behaviors of Magisk.

I would make it as won't fix at least someone else raise something Magisk does wrong.

**Closed by yujincheng08** 2022-05-05 06:04 UTC
Labels: regression, wontfix

**Comment by Jon8RFC** [comment] 2022-05-05 07:09
Based on the updated title, is it directly related to the fact that my phone was initially being used with the `--disable-verity --disable-verification ` flags, but I no longer use them and never did a device wipe after stopping using them? Because this issue doesn't happen to all users with a custom kernel, only a small subset, and I'm wondering if that's why.

**Comment by capntrips** [comment] 2022-05-06 17:01
I have wiped mine several times since I last used the disable flags on `vbmeta`, but I'm still affected by this, so I don't think that's the issue.

**Comment by yujincheng08** [comment] 2022-05-06 17:07
If you have done `--disable-verity --disable-verification`, the init will log like `Top-level vbmeta is disabled, skip Hashtree setup for ...`.

See:
https://cs.android.com/android/platform/superproject/+/master:system/core/init/first_stage_mount.cpp;drc=6951984bbefb96423970b82005ae381065e36704;l=742

**Comment by Jon8RFC** [comment] 2022-05-06 17:44
As best I can infer, at minimum, the bootloader is getting more picky as of the May 2022 update.

Flashing my Kirisakura boot.img patched with 24300 via fastboot, which worked on the April update, no longer works on the May update.
Flashing via EXKM instead, with Magisk 24300, now works, for some reason...just like on April.  I've been flashing a good 75+ times the last couple of days, just trying to learn something new...maybe I did something by accident?

Backing up that working custom-kernel boot.img from EXKM and then flashing it via fastboot works.  Its contents are drastically different compared to manually magisk-patching & flashing the kirisakura boot.img, based on skimming with a hex editor.  I let Freak07 know about what I saw.

I've seemingly confirmed that the May-based bootloader is being more picky about the boot.img contents in addition to the above.
Using a stock, AOSP-compiled boot.img, dtbo.img, vendor_boot.img, vendor_dlkm.img which Freak07 made for me, with Magisk 24300:
AOSP unpatched=crash
AOSP magisk-patched=crash
stock 3+AOSP patched boot.img=crash
AOSP 3+stock patched boot.img=boot

Some of whatever April used to allow or not require in a boot.img file, May no longer allows or does require.
Or it could be a bug corrected in the bootloader, and that trickled down to third-party compiled boot.img files.
What this means for 24303+ and custom kernels, if anything, I don't know.  It's some new info to me at least.

I'm worried that rooted days are numbered, however.

**Comment by freak07** [comment] 2022-05-06 20:12
>AOSP unpatched=crash
>AOSP patched=crash
>stock 3+AOSP patched boot.img=crash
>AOSP 3+stock patched boot.img=boot


First is expected to crash if you don't have verity/verification disabled.

But it seems the boot.img produced by the kernel environment doesn't play nice with magisk canary when verity/verification is enabled.

**Comment by freak07** [comment] 2022-05-09 20:20
@yujincheng08

@Jon8RFC and me continued testing. 

As far as I can see there are two issues. 

Compiled boot.img, dtbo.img, vendor_boot.img and vendor_dlkm.img from the aosp kernel build environment for May without any further changes to the source. 

@Jon8RFC patched the compiled aosp may boot.img via magisk stable, flashed the other images and the device crashed during boot.

I repacked the boot.img extracted from the May factory image with the kernel image compiled by the aosp environment (the kernel images to previous mentioned boot.img contained) and the device was able to boot the repacked boot.img when patched via magisk stable. 

The same repacked boot.img patched with latest canary did not boot on @Jon8RFC 's on a device with vbmeta flags intact. 

Since on pixel 6 devices, parts of the kernel build sit in all of those 4 images, it would be unfortunate if magisk didn't allow to use these, now that most users disabled the vbmeta flags. 

The compilation is just the stock may kernel without any modifications, so it's also not a kernel issue. 

@yujincheng08 please re-open the issue.

**Comment by yujincheng08** [comment] 2022-05-10 01:27
I dont care if Magisk stable is working or not. I will re-open this issue if:
1. device boots with the customized kenel without being patched by Magisk;
2. device does not boot with the patched customized kernel by Magisk canary;
3. both logs of the previous situation are provided.

**Comment by freak07** [comment] 2022-05-10 04:15
> I dont care if Magisk stable is working or not. I will re-open this issue if:

Isn't canary channel for testing regressions? 



> 1. device boots with the customized kenel without being patched by Magisk;

It will only boot if verity/verification is disabled if it's not the kernel that came with the stock May firmware. I don't understand the reason for this. Compile timestamp will be different and with vbmeta flags intact it will fail booting. But i can get you a log from my device with verity/verification disabled.

> 2. device does not boot with the patched customized kernel by Magisk canary;
@Jon8RFC can provide a kernel log/ramoops for that.

**Comment by yujincheng08** [comment] 2022-05-10 04:33
So customized kernels may not boot even if Magisk does not patch them?

**Comment by yujincheng08** [comment] 2022-05-10 05:08
Let me clarify the things.
Magisk was used to modify the fstab to inject Magisk components, and in the meantime, Magisk stipped `avb_key` and `avb` flags for all partitions. So, that 24300 works is just a side effect and has no insurance.
Now Magisk changed its way of injecting Magisk components, and it will no longer modify the fstab, and the side effect was thus gone together with the refactorization. Some configurations that rely on the fact that Magisk will strip those verification flags will no longer work, and that's expected. Users should disable the verification themselves since they are expected to have unlocked bootloaders.

**Comment by Jon8RFC** [comment] 2022-05-10 13:17
Here's a dmesg of Freak07's repacked AOSP boot.img which I patched with Magisk 24300
[dmesg_2022-05-10T08.11.txt](https://github.com/topjohnwu/Magisk/files/8661836/dmesg_2022-05-10T08.11.txt)

And also a ramoops of Freak07's repacked AOSP boot.img which I patched with Magisk 24308
[console-ramoops-0_2022-05-10T08.13.txt](https://github.com/topjohnwu/Magisk/files/8661835/console-ramoops-0_2022-05-10T08.13.txt)

**Comment by capntrips** [comment] 2022-05-11 02:21
I don't have immediate access to the untouched AOSP kernel, so I tried with blu_spark_r65, since it doesn't require a Magisk module, and while the unpatched version's `ramoops` is much less verbose, it does appear that the exact same issue (Hash device is too small) causes the kernel panic in both the unpatched and 24308 patched versions.

Here are the `ramoops`, if that is useful, at all:

[unpatched](https://github.com/topjohnwu/Magisk/files/8666193/console-ramoops--unpatched--2022-05-10--21-05.log)
[24308 patched](https://github.com/topjohnwu/Magisk/files/8666194/console-ramoops--24308-patched--2022-05-10--21-09.log)

**Comment by freak07** [comment] 2022-05-11 14:16
> Let me clarify the things. Magisk was used to modify the fstab to inject Magisk components, and in the meantime, Magisk stipped `avb_key` and `avb` flags for all partitions. So, that 24300 works is just a side effect and has no insurance. Now Magisk changed its way of injecting Magisk components, and it will no longer modify the fstab, and the side effect was thus gone together with the refactorization. Some configurations that rely on the fact that Magisk will strip those verification flags will no longer work, and that's expected. Users should disable the verification themselves since they are expected to have unlocked bootloaders.

Is it possible to restore the previous state? I don't know the implications for magisk, but going forward it might no longer be possible to change the GKI kernels into a zImage for custom kernels that only sits in the boot.img and not vendor_boot and vendor_dlkm too. (At the moment that's the case for pixel 6 and pixel 6 pro, but I'm sure QCOM based devices (those with snapdragons SOCs might follow soon) 

Disabling verity/verification requires a full wipe just like unlocking the bootloader. Every month updating the phone will re-enable verity/verification if users don't explicitly disable it! If a user boots, the user is forced to wipe. 

Since magisk started to modify the fstab (which is the case on magisk 24300 stable at the moment) all guides and therefore the users adjusted to no longer patch vbmeta so verity/verification is enabled for most. 

If those changes end up in the next magisk stable all those users are forced to disable verity/verification to flash a custom kernel on those newer devices. And every month if a user forgets to disable before booting, the user is forced to wipe again. 

At this moment it might only affect pixel 6 and pixel 6 pro, but I'm sure this will change sooner rather than later for non pixels too. 

@topjohnwu @yujincheng08 this change might have serious implications for a whole big bunch of users on pixel 6/pixel 6 pro. (My kernel alone has a download count of up to 500 for a single month (mirrors not counted), and there are a few other kernel projects in the forums as well)

**Comment by neekless** [comment] 2022-05-11 14:42
> Disabling verity/verification requires a full wipe just like unlocking the bootloader. Every month updating the phone will re-enable verity/verification if users don't explicitly disable it! If a user boots, the user is forced to wipe.

From my experience, a full wipe only occurs the first time verification is disabled. For subsequent updates, disabling verification would not cause a wipe.

I disabled verification the first time I rooted my p6pro, before magisk stripped the flags. When magisk started stripping flags I stopped disabling verification. Then I had this exact issue and was stuck using 24301 for a long time, every later version crashes during boot. I then decided to update to 24308 after reading this issue. Disabled verification and flashed the 4 GKI images and everything in my phone is still intact and I booted with magisk 24308.

**Comment by freak07** [comment] 2022-05-11 14:46
> > Disabling verity/verification requires a full wipe just like unlocking the bootloader. Every month updating the phone will re-enable verity/verification if users don't explicitly disable it! If a user boots, the user is forced to wipe.
> 
> From my experience, a full wipe only occurs the first time verification is disabled. For subsequent updates, disabling verification would not cause a wipe.
> 
> I disabled verification the first time I rooted my p6pro, before magisk stripped the flags. When magisk started stripping flags I stopped disabling verification. Then I had this exact issue and was stuck using 24301 for a long time, every later version crashes during boot. I then decided to update to 24308 after reading this issue. Disabled verification and flashed the 4 GKI images and everything in my phone is still intact and I booted with magisk 24308.

Interesting, thanks for chiming in. I was under the impression it would wipe if disabled again. 

If that's indeed the case it would lessen the implications for users, but I'm sure there are a lot of users that never disabled verity/verification and started only by unlocking bl, flashing stable 24300 and eventually decided to use a custom kernel.

**Comment by neekless** [comment] 2022-05-11 14:51
> Interesting, thanks for chiming in. I was under the impression it would wipe if disabled again.
> 
> If that's indeed the case it would lessen the implications for users, but I'm sure there are a lot of users that never disabled verity/verification and started only by unlocking bl, flashing stable 24300 and eventually decided to use a custom kernel.

This is my experience so it would be great if someone else can corroborate on this (in case my phone magically remained intact after disabling verification).

It's unfortunate that users have to wipe again in the future but they will just have to bite the bullet. I highly doubt magisk will go back to modifying fstab again.

I would like magisk to provide strong warnings to users about this once it reaches stable though.

**Comment by capntrips** [comment] 2022-05-11 15:35
> This is my experience so it would be great if someone else can corroborate on this (in case my phone magically remained intact after disabling verification).

I installed `SP2A.220405.004` with `-w --disable-verity --disable-verification`, booted into the system, and skipped through all of the installation steps. Then I upgraded to `SP2A.220505.002` without `-w` or the disable flags, and booted into the system. I rebooted into `fastboot`, flashed `vbmeta` with `--disable-verity --disable-verification`, and tried to boot into the system, but it bootlooped at the Google logo twice and ended up at the "Your data may be corrupt" screen with the option to try again or factory reset.

**Comment by freak07** [comment] 2022-05-11 16:01
> > This is my experience so it would be great if someone else can corroborate on this (in case my phone magically remained intact after disabling verification).
> 
> I installed `SP2A.220405.004` with `-w --disable-verity --disable-verification`, booted into the system, and skipped through all of the installation steps. Then I upgraded to `SP2A.220505.002` without `-w` or the disable flags, and booted into the system. I rebooted into `fastboot`, flashed `vbmeta` with `--disable-verity --disable-verification`, and tried to boot into the system, but it bootlooped at the Google logo twice and ended up at the "Your data may be corrupt" screen with the option to try again or factory reset.

That was my understanding and what I saw on the forums too.

**Comment by freak07** [comment] 2022-05-11 16:03
> > Is it possible to restore the previous state?
> 
> Definitely a no.

Is there another way to get magisk to allow those who choose to flash a kernel on those newer devices, which involves flashing boot, dtbo, vendor_boot and vendor_dlkm to not run into the vbmeta trap?

**Comment by capntrips** [comment] 2022-05-14 11:02
I managed to get Kirisakura 2.4.0  to boot on `SP2A.220405.004` with verity enabled using Magisk 24310. I had to append

**Comment by parvezyaser** [comment] 2022-05-25 15:41
#5777
