### ISSUE TITLE
magisk did not work 

### ISSUE THREAD

**Issue by tyjavajar** [topjohnwu/Magisk#6993] opened 2023-05-13 17:40 UTC
Device: jiayu s3s 
Android version: 8.1
Magisk version name: Debug
Magisk version code: https://github.com/topjohnwu/Magisk/commit/d0c9384233412c91d3538336e26fb419dd40c850 (26101) (D)

ROM URL:[https://forum.xda-developers.com/t/rom-8-0-0-8-1-0-official-mados-jiayu-s3-mt6752.3706919/](url)

The Magisk app is patched in, but the device is not rooted. 
[logcat.txt](https://github.com/topjohnwu/Magisk/files/11470204/logcat.txt)

[boot.zip](https://github.com/topjohnwu/Magisk/files/11470189/boot.zip)
[magisk_log_2023-05-14T00.40.11.log](https://github.com/topjohnwu/Magisk/files/11470194/magisk_log_2023-05-14T00.40.11.log)
![Screenshot_20230514-003928](https://github.com/topjohnwu/Magisk/assets/38398992/cd2d5566-0a0f-4feb-a5b8-a2aac430e066)
![Screenshot_20230514-004046](https://github.com/topjohnwu/Magisk/assets/38398992/bccaa953-957e-4a7b-9415-bf64243a20a3)

**Comment by yujincheng08** [comment] 2023-05-14 16:55
we need [bugreport](https://developer.android.com/studio/debug/bug-report)

**Comment by yujincheng08** [comment] 2023-05-14 16:59
likely duplicate of #6914

**Closed by yujincheng08** 2023-05-14 16:59 UTC
