### ISSUE TITLE
Magisk 24.1 Showing Installed N/A - Root Functions Intact

### ISSUE THREAD

**Issue by AlecPuran** [topjohnwu/Magisk#5339] opened 2022-01-30 16:34 UTC
Installation of Magisk 24.1 APK shows that Magisk installed is N/A. However, when using the v23.0 I still retain root functions, but cannot adjust root permissions or add new modules within the Magisk app, only previously allowed applications retain their root functions. Attempting to install Magisk 24.1 gives the following:

Target image: /dev/block/
Device platform: arm64-v8a
Installing: 24.1 (24100)
Unable to check signature
Installation failed

This issue also happened when installing Magisk 24.0, I have no reported issues with Magisk 23.0, other than that attempting to hide the Magisk app will not work unless I uninstall the unhidden Magisk app and clear all app data from the hidden app. This however installs Magisk 24.1 which has the issues described above.

Device: SM-G930W8
Android version: Android 8.0 Oreo
Magisk version name: 32fc34f9
Magisk version code: 24101

**Comment by cuteexe** [comment] 2022-01-30 18:41
#4174 will be fixed in the next release i guess

**Comment by pndwal** [comment] 2022-02-04 12:11
@OsmOsis
Are you sure this is a duplicate issue? Seems quite different: #4171 affects Android 6, 7 on armeabi-v7a and post 22.0 Magisk.

This user with Samsung S7 SM-G930W8 has Android 8.0, arm64-v8a, and 23.0 works, but not current 24.1

Others seem to have same symptoms, eg:

Samsung S7 Flat SM-GF930F , Android 8.0, 23.0 works, but not later Alpha (I assume 24.0, 24.1 haven't worked either but he hasn't reported) here:
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-86203051

And now, Samsung Note 8, 23.0 works, but not current 24.1 here:
https://forum.xda-developers.com/t/discussion-magisk-the-age-of-zygisk.4393877/post-86359701

Hope this can be properly addressed. Kind regards.

**Comment by pndwal** [comment] 2022-02-04 15:10
> ... I have no reported issues with Magisk 23.0, other than that attempting to hide the Magisk app will not work unless I uninstall the unhidden Magisk app and clear all app data from the hidden app. This however installs Magisk 24.1 ...

FYI, Others are also reporting this anomaly, ie. Magisk seems to be fetching stub for latest version when hiding the app, not current version, and process fails. This apparently occurred w/ 22.x also, after update to following versions were available.

This only occurs when users don't take available updates or install older versions, then hide the app. Workarounds include putting a JSON in custom channel and turning off data / network access.

**Comment by pndwal** [comment] 2022-02-04 22:15
Thanks @osm0sis. 👍

**Comment by canyie** [comment] 2022-02-05 04:52
Maybe already fixed by #5334, please try the latest ci build: https://github.com/topjohnwu/Magisk/actions/runs/1789246307

**Comment by capt-watson** [comment] 2022-02-05 11:54
Device name: Samsung Galaxy Note 8 (SM-N950F).

Android Version: 9 (Pie)

Rooted with TWRP and Magisk 23.0

Worked flawlessly. Hide features worked as expected.

Few days ago, fell for auto update to 24.1. Update failed due to unable to check signature error though the Magisk app got upgraded from 23 to 24.1.

Now the upgraded Magisk had no option to do anything except upgrade root to Magisk 24.1 via direct install method.

Tried once again, install failed again due to unable to check signature error.

Left with Magisk 24.1 app which gave me no option to unhide the previous Magisk i.e.23.0, uninstalled the Magisk 24.1 app in order to install Magisk 23.0 to get the original functionality back.

Most of the functionality of root restored except the ability to hide the Magisk app itself. This led to all banking and some financial apps stopping to work.

Decided to uninstall root altogether via TWRP and with Magisk 23 app renamed as uninstall.zip. TWRP flashed the uninstall zip file with no issues.

Reinstalled the Magisk 23.0 (TWRP & ODIN method. Device reported success with root checker app.

Reinstalled the Magisk 23.0 app but situation remained as it was before ,(i.e. not able to hide Magisk app).

Thinking that this problem could be due to previously hidden Magisk app 23.0, decided to wipe everything on the device including OS and TWRP using TWRP.

Finally left with no OS and any type of data on this device, reinstalled the stock firmware using ODIN.

This time rooted the device to 24.1 following the steps mentioned by Topjohnwu (Magisk patched AP file & ODIN). Regained root as confirmed by the root checker but still no Zygisk or any other option available in Magisk app. Also couldn't hide the Magisk app itself.

Uninstalled the Magisk app 24.1 and reinstalled the Magisk app 23. This app showed that device has Magisk root 24.1 but couldn't passed the safety check and not able to hide anything.

But it gave me the option to uninstall root which version 24.1 didn't give.

Uninstalled the root yesterday, reinstalled the Magisk app 24.1, patched boot.img file with Magisk 24.1.

Once again rooted with Magisk 24.1 following topjohnwu advised steps. Confirmed device rooted to Magisk 24.1 as shown by the Magisk 23.0 app but the Magisk 24.1 app continues to show N/A.

Would be glad for any advice. 

(https://forum.xda-developers.com/t/discussion-magisk-the-age-of-zygisk.4393877/post-86375205)

**Comment by pndwal** [comment] 2022-02-05 12:38
@capt-watson
Suggest you try Canyie's test build linked (extract from artifacts archive at end of page)...

**Comment by capt-watson** [comment] 2022-02-05 13:04
T

> @capt-watson
> 
> Suggest you try Canyie's test build linked (extract from artifacts archive at end of page).
> 
> * It's elementary my dear Watson... 

Thanks @pndwal for your suggestions. Will try out  Canyie's test build tomorrow.

**Comment by runcodedamnit** [comment] 2022-02-06 08:11
Same issue for me with Samsung S8. When back to v23 it works, V24 does not detect magisk,
The latest CI build does not get past the Magisk splash screen.

**Comment by yujincheng08** [comment] 2022-02-06 19:30
try canary 24102

**Comment by jeancarlosna** [comment] 2022-02-06 19:43
Canary 24102 recognize magisk core for me, it doesnt recognize in stable 24.1 for example or previous canary and alpha.
Still, in no version that has Zygisk, I can use it. It doesn't matter how many times I turn it on and restart. Still a 'No' at the magisk home. Does anyone have any ideas?

**Comment by yujincheng08** [comment] 2022-02-06 19:46
@jeancarlosna show your bootlog (not magisk log)

**Comment by jeancarlosna** [comment] 2022-02-06 20:01
@yujincheng08 can you explain how to get my bootlog, please? I never done it and I'm searching right now how to, but if you can explain it will be faster.

**Comment by yujincheng08** [comment] 2022-02-06 20:04
@jeancarlosna 
https://t.me/hzrtools/12 or https://t.me/hzrtools/10

**Comment by jeancarlosna** [comment] 2022-02-06 20:09
@yujincheng08 thanks!
[boot-2022-02-06-17-07-35.log](https://github.com/topjohnwu/Magisk/files/8011136/boot-2022-02-06-17-07-35.log)

**Comment by canyie** [comment] 2022-02-07 01:42
```
D Magisk  : zygisk: setup files for pid=[3221]
D Magisk  : zygisk: setup files for pid=[3222]
E linker  : "/system/bin/app_process64": ignoring DT_PREINIT_ARRAY in shared library!
D Magisk  : zygisk64: inject 1st stage
D Magisk  : found map /system/bin/app_process64 with start = 78c5300000, end = 78c5338000
E linker  : "/system/bin/app_process64": ignoring DT_PREINIT_ARRAY in shared library!
D Magisk  : zygisk64: inject 2nd stage
F appproc : Error changing dalvik-cache ownership : Operation not permitted
F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 3221 (4)
```

**Comment by canyie** [comment] 2022-02-07 02:18
@jeancarlosna What's your kernel version?

**Comment by jeancarlosna** [comment] 2022-02-07 02:22
@canyie Kernel architecture: aarch64
Kernel Version: 3.18.91-13895453-QB29822865(G930FXXS8ETCM)

**Comment by canyie** [comment] 2022-02-07 03:03
@jeancarlosna This issue is already addressed by #5372 but only for kernel version >= 3.19... We need to find a workaround for older kernels...

**Comment by yujincheng08** [comment] 2022-02-07 05:43
@jeancarlosna that would be a wontfix. its your kernel's restriction and the workaround is not working because your kernel is too old (at least 3.19). we do not want to take too much effort

**Comment by yujincheng08** [comment] 2022-02-07 08:22
This issue should be fixed. And @jeancarlosna is redirected to #5395

**Closed by yujincheng08** 2022-02-07 08:22 UTC

**Comment by mohammedrqa** [comment] 2022-02-22 13:55
sung Galaxy A6 sprint sm-a600p System 10
I tried it but there is a small problem
See the rooted image, but there is a problem, I tried to flash it via the modified recovery, the root zip file Tried searching for a modified website, but I couldn't find it

**Comment by osm0sis** [comment] 2023-05-25 19:06
Open a new issue if you have an issue, since this one is fixed.
