### ISSUE TITLE
Magisk v24.2 fails during additional setup

### ISSUE THREAD

**Issue by monde-green7** [topjohnwu/Magisk#5555] opened 2022-03-06 11:48 UTC
Device: Xiaomi Redmi Note 9 Pro
Android version: 11
Magisk version name: 7cfce9ff
Magisk version code: 24201

After patching the boot image and flashing it via fastboot, Magisk Manager asks to perform some additional setup when opened which fails. It is reported that Magisk is installed however in the application. Enabling Zygisk or rebooting from the Manager does not work and the logs are empty.

I have however captured the logcat of opening Magisk Manager and allowing it to try to perform the additional setup. The part of the logcat after `opjohnwu.magis: Accessing hidden method` corresponds to trying to reboot from the application as well.
[logcat.txt](https://github.com/topjohnwu/Magisk/files/8192452/logcat.txt)

Root access doesn't appear to work via adb to try to see if `/cache` gets cleared on boot (in case that is the reason for the empty logs), but the logs are actually present in app when trying version 24.1 - they are the same as in the logcat however. For the OS, I am using [lineage-18.1-20220304-nightly-miatoll-signed.zip](https://mirrorbits.lineageos.org/full/miatoll/20220304/lineage-18.1-20220304-nightly-miatoll-signed.zip) with the associated LineageOS recovery [lineage-18.1-20220304-recovery-miatoll.img](https://mirrorbits.lineageos.org/recovery/miatoll/20220304/lineage-18.1-20220304-recovery-miatoll.img).  The device has boot ramdisk and a separate vbmeta partition. Please let me know if any other logs would be helpful, provided that I am able to obtain them.

**Comment by trollogyadherent** [comment] 2022-03-06 14:44
oops you were faster. Here is my issue with details: #5557
I will reattach logs
[magisk_log_2022-03-06T152823.log](https://github.com/topjohnwu/Magisk/files/8192812/magisk_log_2022-03-06T152823.log)
[logcat.txt](https://github.com/topjohnwu/Magisk/files/8192813/logcat.txt)

**Comment by yujincheng08** [comment] 2022-03-19 17:17
Try #5620. It may have fixed this issue.

**Comment by yujincheng08** [comment] 2022-03-19 18:26
Duplicate of #5530

**Closed by yujincheng08** 2022-03-19 18:26 UTC
