### ISSUE TITLE
Samsung Galaxy Tab (SM-P205) vbmeta Hash Mismatch

### ISSUE THREAD

**Issue by joselampiao** [topjohnwu/Magisk#3482] opened 2020-11-13 23:41 UTC
I tried the steps for Samsung provided in the Wiki, and I ended with an error that the vbmeta hash was mismatch. Googling about this, I found some steps to use a blank vbmeta, which I tried using dd from /dev/zero to match the same size of the vbmeta.img and repacked magisk_pached. But after this, the Odin got stuck into writing vbmeta forever. 

I tried patching with Magisk 20.4, the only option that I have while patching is about recovery boot, which I didn't switch off yet, as I assume it isn't related. I tried the patching in the last firmware of the device, which matched the last updated using OTA.

Magisk detects the following: 
Ramdisk NO 
A/B NO
SAR YES
Crypto File

So, what can I do to solve this? Thanks

**Comment by variainfantry155** [comment] 2020-11-14 04:07
` _

**Comment by otavioarj** [comment] 2020-11-16 16:08
Similar issue [#3295](https://github.com/topjohnwu/Magisk/issues/3295). Try this fist

**Comment by osm0sis** [comment] 2021-03-07 14:02
Closing as duplicate of the newer issue linked above, which has more useful troubleshooting info for John.

**Closed by osm0sis** 2021-03-07 14:02 UTC
Labels: duplicate

**Comment by arynyklas** [comment] 2023-04-17 04:09
> Closing as duplicate of the newer issue linked above, which has more useful troubleshooting info for John. 👍

Why you closed all of this issues?
I receive error HASH_MISMATCH and I didn't find answer anywhere

**Comment by osm0sis** [comment] 2023-04-17 09:46
Then open a new one since it's a new/recurrent issue.

**Comment by bphd** [comment] 2024-04-04 11:07
> Then open a new one since it's a new/regression issue, not necessarily for the same reason as this 2 years old one.

Maybe yes if he hasn't touched the phone since lol
