### ISSUE TITLE
Android 11 MIUI devices need enabled verification in boot.img AVBv2 signature

### ISSUE THREAD

**Issue by qianmo-xw** [topjohnwu/Magisk#4447] opened 2021-06-22 12:13 UTC
The Xiaomi device using MT6893 cannot start. After patching the boot, it shows infinite restart. I have disabled the vbmeta test. The models are RedmiNote10Pro and RedmiK40Gaming.  I have used magiskboot extra cpio to prompt me that it failed. When I use Android_image_kitchen, the window flashes and nothing is unpacked. I think his boot has been specially encrypted. If you need it, I will upload the boot file for  the study...
Device: RedmiNote10Pro
Android version:11
Magisk version name: V23
Magisk version code: 23001

**Comment by qianmo-xw** [comment] 2021-06-22 12:26
this say my file is too big....

**Comment by osm0sis** [comment] 2021-06-23 01:49
So find another way to upload it or you're not providing anything useful and we'll have to close this issue.

**Comment by qianmo-xw** [comment] 2021-06-24 07:40
> So find another way to upload it or you're not providing anything useful and we'll have to close this issue...

This is link
https://drive.google.com/file/d/1AefUeYQcBviQ7XSFFCnWfkkDZqx8ceSy/view?usp=drivesdk

**Comment by osm0sis** [comment] 2021-06-24 11:40
> > So find another way to upload it or you're not providing anything useful and we'll have to close this issue...
> 
> This is link
> https://drive.google.com/file/d/1AefUeYQcBviQ7XSFFCnWfkkDZqx8ceSy/view?usp=drivesdk

It's asking me to request access. Can you set better permissions on it so I can just download directly?

**Comment by qianmo-xw** [comment] 2021-06-24 11:54
> > > So find another way to upload it or you're not providing anything useful and we'll have to close this issue...
> > 
> > 
> > This is link
> > https://drive.google.com/file/d/1AefUeYQcBviQ7XSFFCnWfkkDZqx8ceSy/view?usp=drivesdk
> 
> It's asking me to request access. Can you set better permissions on it so I can just download directly?

Sorry,That is I first use google drive,I don't know how to change set permissions,I think this link will be OK 
,try it,Thank you
https://mega.nz/file/U94XnYbB#iAhwO8En4LitpbePmNNCTNvylBRtJh3lZB5aD4n66yM

**Comment by qianmo-xw** [comment] 2021-06-24 11:56
> > > So find another way to upload it or you're not providing anything useful and we'll have to close this issue...
> > 
> > 
> > This is link
> > https://drive.google.com/file/d/1AefUeYQcBviQ7XSFFCnWfkkDZqx8ceSy/view?usp=drivesdk
> 
> It's asking me to request access. Can you set better permissions on it so I can just download directly?

Now , google drive also can download.

**Comment by osm0sis** [comment] 2021-06-25 04:53
It's a pretty normal looking boot hdr_v2 image:
```

Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: boot.img

Setting up work folders...

Image type: AOSP

Signature with "AVBv2" type detected.

Splitting image to "split_img/"...
ANDROID! magic found at: 0
BOARD_KERNEL_CMDLINE bootopt=64S3,32N2,64N2
BOARD_KERNEL_BASE 0x40078000
BOARD_NAME 
BOARD_PAGE_SIZE 2048
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x11088000
BOARD_SECOND_OFFSET 0xbff88000
BOARD_TAGS_OFFSET 0x07c08000
BOARD_OS_VERSION 11.0.0
BOARD_OS_PATCH_LEVEL 2021-05
BOARD_HEADER_VERSION 2
BOARD_HEADER_SIZE 1660
BOARD_DTB_SIZE 200079
BOARD_DTB_OFFSET 0x07c08000

Unpacking ramdisk to "ramdisk/"...

Compression used: gzip
75114 blocks

Done!
```

Ramdisk looks like boot-as-recovery 2SI SAR.

**Comment by qianmo-xw** [comment] 2021-06-25 05:00
> It's a pretty normal looking boot hdr_v2 image:
> 
> ```
> 
> Android Image Kitchen - UnpackImg Script
> by osm0sis @ xda-developers
> 
> Supplied image: boot.img
> 
> Setting up work folders...
> 
> Image type: AOSP
> 
> Signature with "AVBv2" type detected.
> 
> Splitting image to "split_img/"...
> ANDROID! magic found at: 0
> BOARD_KERNEL_CMDLINE bootopt=64S3,32N2,64N2
> BOARD_KERNEL_BASE 0x40078000
> BOARD_NAME 
> BOARD_PAGE_SIZE 2048
> BOARD_HASH_TYPE sha1
> BOARD_KERNEL_OFFSET 0x00008000
> BOARD_RAMDISK_OFFSET 0x11088000
> BOARD_SECOND_OFFSET 0xbff88000
> BOARD_TAGS_OFFSET 0x07c08000
> BOARD_OS_VERSION 11.0.0
> BOARD_OS_PATCH_LEVEL 2021-05
> BOARD_HEADER_VERSION 2
> BOARD_HEADER_SIZE 1660
> BOARD_DTB_SIZE 200079
> BOARD_DTB_OFFSET 0x07c08000
> 
> Unpacking ramdisk to "ramdisk/"...
> 
> Compression used: gzip
> 75114 blocks
> 
> Done!
> ```
> 
> Ramdisk looks like boot-as-recovery 2SI SAR.

So should I try patch recovery.img？

**Comment by pndwal** [comment] 2021-06-25 11:04
Doubt it, especially for Xiaomi.

Boot-as-recovery 2SI SAR just means a Hybrid ramdisk still in boot partition boots with USES_RECOVERY_AS_BOOT method.

Are you actually offered Recovery mode check box when patching? You'e trying with it unchecked, right?

**Comment by qianmo-xw** [comment] 2021-06-25 11:13
> Doubt it, especially for Xiaomi.
> 
> Boot-as-recovery 2SI SAR just means a Hybrid ramdisk still in boot partition boots with USES_RECOVERY_AS_BOOT method.
> 
> Are you actually offered Recovery mode check box when patching? You'e trying with it unchecked, right?

I tried patch boot and found that the machine was in a boot loop. Then I tried unpack boot, use magiskboot extract, they, and he displayed wirte file failed. When I used the windows version of android_kitchen_image, it did not extract any files. I think it might be that the boot is encrypted.  , But you can unzip it. I think the version of windows tool is a bit low. I just tried unpack boot to check because the machine is in the boot loop. You mean I can try patch recovery.img to get magisk?

**Comment by osm0sis** [comment] 2021-06-25 14:55
I already unpacked it in AIK and showed it's a hdr_v2 image, so it's clearly not "encrypted" or anything. You don't have a recovery.img on your device, recovery is inside the boot.img.

**Comment by pndwal** [comment] 2021-06-25 15:06
No. I don't know of any Xiaomi that need Magisk in recovery, and these should only include type III (ramdisk= no) devices (But Xiaomi is an exception).
https://topjohnwu.github.io/Magisk/boot.html
Yours is type IV. As long as ramdisk = yes in Magisk App you shouldn't even see Recovery mode check box. If you do, ensure its unchecked when patching boot.img. PW

**Comment by Gong-Mi** [comment] 2021-06-27 16:17
Is it related to vendor-boot.img

**Comment by Gong-Mi** [comment] 2021-06-27 17:28
Is it related to vendor-boot.img

**Comment by osm0sis** [comment] 2021-06-27 21:36
No. This device is hdr_v2 so does not have a vendor_boot.

**Comment by Gong-Mi** [comment] 2021-06-28 03:08
[magisk_install_log_2021-06-28T10_52_02Z (1).log](https://github.com/topjohnwu/Magisk/files/6723027/magisk_install_log_2021-06-28T10_52_02Z.1.log)
[magisk_install_log_2021-06-28T10_57_54Z.log](https://github.com/topjohnwu/Magisk/files/6723028/magisk_install_log_2021-06-28T10_57_54Z.log)

**Comment by Gong-Mi** [comment] 2021-06-28 03:16
https://drive.google.com/file/d/1GeFyCfawejQMRR9nVLGDO88UFLsfrMWh/view?usp=sharing

**Comment by qianmo-xw** [comment] 2021-06-29 08:48
> It's a pretty normal looking boot hdr_v2 image:
> 
> ```
> 
> Android Image Kitchen - UnpackImg Script
> by osm0sis @ xda-developers
> 
> Supplied image: boot.img
> 
> Setting up work folders...
> 
> Image type: AOSP
> 
> Signature with "AVBv2" type detected.
> 
> Splitting image to "split_img/"...
> ANDROID! magic found at: 0
> BOARD_KERNEL_CMDLINE bootopt=64S3,32N2,64N2
> BOARD_KERNEL_BASE 0x40078000
> BOARD_NAME 
> BOARD_PAGE_SIZE 2048
> BOARD_HASH_TYPE sha1
> BOARD_KERNEL_OFFSET 0x00008000
> BOARD_RAMDISK_OFFSET 0x11088000
> BOARD_SECOND_OFFSET 0xbff88000
> BOARD_TAGS_OFFSET 0x07c08000
> BOARD_OS_VERSION 11.0.0
> BOARD_OS_PATCH_LEVEL 2021-05
> BOARD_HEADER_VERSION 2
> BOARD_HEADER_SIZE 1660
> BOARD_DTB_SIZE 200079
> BOARD_DTB_OFFSET 0x07c08000
> 
> Unpacking ramdisk to "ramdisk/"...
> 
> Compression used: gzip
> 75114 blocks
> 
> Done!
> ```
> 
> Ramdisk looks like boot-as-recovery 2SI SAR.

can you send me your Android Image Kitchen,I can not unpack boot

**Comment by Gong-Mi** [comment] 2021-06-29 08:53
https://bigota.d.miui.com/21.6.23/miui_ARES_21.6.23_18dac870a1_11.0.zip




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月29日(星期二) 下午4:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [topjohnwu/Magisk] Xiaomi device using MT6893 cannot start (#4447)





  
It's a pretty normal looking boot hdr_v2 image:
  Android Image Kitchen - UnpackImg Script by osm0sis @ xda-developers Supplied image: boot.img Setting up work folders... Image type: AOSP Signature with "AVBv2" type detected. Splitting image to "split_img/"... ANDROID! magic found at: 0 BOARD_KERNEL_CMDLINE bootopt=64S3,32N2,64N2 BOARD_KERNEL_BASE 0x40078000 BOARD_NAME  BOARD_PAGE_SIZE 2048 BOARD_HASH_TYPE sha1 BOARD_KERNEL_OFFSET 0x00008000 BOARD_RAMDISK_OFFSET 0x11088000 BOARD_SECOND_OFFSET 0xbff88000 BOARD_TAGS_OFFSET 0x07c08000 BOARD_OS_VERSION 11.0.0 BOARD_OS_PATCH_LEVEL 2021-05 BOARD_HEADER_VERSION 2 BOARD_HEADER_SIZE 1660 BOARD_DTB_SIZE 200079 BOARD_DTB_OFFSET 0x07c08000 Unpacking ramdisk to "ramdisk/"... Compression used: gzip 75114 blocks Done!  
Ramdisk looks like boot-as-recovery 2SI SAR.
  
can you send me your Android Image Kitchen,I can not unpack boot
 
&mdash;

**Comment by qianmo-xw** [comment] 2021-06-29 09:01
![image](https://user-images.githubusercontent.com/83547396/123768394-df04f600-d8fa-11eb-9b6c-a9834b2bf86b.png)
This is firmware partition, no vendor_boot no recovery image
download url:https://bigota.d.miui.com/V12.5.3.0.RKPCNXM/chopin_images_V12.5.3.0.RKPCNXM_20210527.0000.00_11.0_cn_90be99bee5.tgz
When I unpack boot
![image](https://user-images.githubusercontent.com/83547396/123769095-8124de00-d8fb-11eb-8213-7a446090d136.png)
This is boot.img:https://mega.nz/file/UxYgRToA#gClY-dySdRMCfkeNbSNsUWUKWurpemacIE8vG2Et1XA

**Comment by qianmo-xw** [comment] 2021-06-29 09:35
> No. This device is hdr_v2 so does not have a vendor_boot.

Oh,I found AIK3.8 in your twitter and xda, thank you.

**Comment by qianmo-xw** [comment] 2021-06-29 10:30
> No. This device is hdr_v2 so does not have a vendor_boot.
![image](https://user-images.githubusercontent.com/83547396/123782356-d5ce5600-d907-11eb-81c6-071da0dc0cb4.png)
I think MIUI not use default fstab file.So when patched boot device partition not mount?

**Comment by osm0sis** [comment] 2021-06-29 10:32
That's the recovery fstab, but yes that might still be the case.

**Comment by qianmo-xw** [comment] 2021-06-29 10:53
> No. This device is hdr_v2 so does not have a vendor_boot.
![image](https://user-images.githubusercontent.com/83547396/123782869-55f4bb80-d908-11eb-89d9-e5e5de06a37e.png)

I think MIUI not use default fstab file.So when patched boot device partition not mount?
And this device can use offical dev MIUI version to get offical Root,
Although use offical Root,He will also prompt that there is a problem inside your device, please contact your device manufacturer for details, but this does not matter, the device can still be used normally after pressing OK.
![image](https://user-images.githubusercontent.com/83547396/123783668-3316d700-d909-11eb-9bca-dc1cdafaaf2a.png)
When I tried to use offical root ls /dev/block/bootdevice/by-name/, I found the vendor_boot_b partition, and then I pulled it to my computer and tried to unpack but failed. Of course, I also backed up the original boot file. I found that the patch boot is in a boot loop. I tried to restore the original boot file. The device is still in the boot loop. If it follows the normal logic, the device should boot normally. Incredible
This is vendor_boot partition file:https://mega.nz/file/0gB3hYaS#ZXMl73mWSKqw0JjkpfBdKjpX02JKF0yKxqFizTY1Io8

**Comment by Gong-Mi** [comment] 2021-07-02 13:34
[miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip](https://github.com/topjohnwu/Magisk/files/6754875/miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip)
miui k40g  root  ota
https://183-2-128-134.ksyungslb.com/bigota.d.miui.com/21.6.30/miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip

**Comment by pndwal** [comment] 2021-07-03 02:04
RedmiNote10Pro Device model caused me some confusion here!

"Redmi Note10 Pro" has Qualcomm SM7150 chipset!

Is this actually "Redmi Note10 Pro (China)" model variant?

Perhaps this affects only MTK SOC systems?

**Comment by pndwal** [comment] 2021-07-03 03:11
Perhaps this is the same issue:
https://github.com/topjohnwu/Magisk/issues/4421
If so, this solution could work for you:
https://forum.xda-developers.com/t/root-gained.4290689/

**Comment by qianmo-xw** [comment] 2021-07-03 05:32
> Perhaps this is the same issue:
> #4421
> If so, this solution could work for you:
> https://forum.xda-developers.com/t/root-gained.4290689/

Yes, in China, this device is mtk soc，and I think this problem is all a-vb Mtk soc can't use magisk.
this is first xiaomi MTK device use v-ab

**Comment by Gong-Mi** [comment] 2021-07-03 18:10
I think it's the problem of MediaTek 1100
Redmi Note10（mt 700） can be written with vbmeta and turned on.

Redm inote10 （mt700）is a-vb mtk soc

**Comment by hairiece** [comment] 2021-07-05 07:37
> [miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip](https://github.com/topjohnwu/Magisk/files/6754875/miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip)
> miui k40g root ota
> https://183-2-128-134.ksyungslb.com/bigota.d.miui.com/21.6.30/miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip

Where did you get this root repair ota package? Can you give me the page address? My device is Redmi K40 gaming, and the processor is Dimensity 1200. After using magisk to generate boot.img and flashing into my device, it will also get stuck in the mi logo loop and cannot start normally.

**Comment by hairiece** [comment] 2021-07-05 07:38
> [miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip](https://github.com/topjohnwu/Magisk/files/6754875/miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip)
> miui k40g root ota
> https://183-2-128-134.ksyungslb.com/bigota.d.miui.com/21.6.30/miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip
Where did you get this root repair ota package? Can you give me the page address? 
My device is Redmi K40 gaming, and the processor is Dimensity 1200(MTK6893). After using magisk to generate boot.img and flashing into my device, it will also get stuck in the mi logo loop and cannot start normally.

**Comment by hairiece** [comment] 2021-07-05 07:38
> [miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip](https://github.com/topjohnwu/Magisk/files/6754875/miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip)
> miui k40g root ota
> https://183-2-128-134.ksyungslb.com/bigota.d.miui.com/21.6.30/miui-blockota-ares-21.6.30-21.6.30.root-b0232e993b-11.0.zip

Where did you get this root repair ota package? Can you give me the page address? 
My device is Redmi K40 gaming, and the processor is Dimensity 1200(MTK6893). After using magisk to generate boot.img and flashing into my device, it will also get stuck in the mi logo loop and cannot start normally.

**Comment by Gong-Mi** [comment] 2021-07-05 07:45
下载文件里面，知道名字叫可以下载。

https://bigota.d.miui.com/日期/包名

**Comment by Gong-Mi** [comment] 2021-07-05 07:47
官方root的ota包，不过我解密不了。

**Comment by hairiece** [comment] 2021-07-05 09:57
> 官方root的ota包，不过我解密不了。

官方的啊，我还以为是其它什么地方提供的。我也试过那个包从中提取里面的内容，也是提取不出来。

**Comment by Gong-Mi** [comment] 2021-07-14 04:16
https://drive.google.com/file/d/1QzhXw4SA81jpQwZCplDz8oeksKJA0Awn/view?usp=sharing
k40g-root-12.5.6-boot.img

**Comment by Gong-Mi** [comment] 2021-07-14 14:13
https://drive.google.com/file/d/1BlpItb-Ht76AhK5QPyP6Vxzxq6gItJzg/view?usp=sharing
k40g-root-12.5.6-not_OTG-boot.img

**Comment by Gong-Mi** [comment] 2021-07-14 16:17
https://drive.google.com/file/d/1fHuycmWO6H1QtTHjGfwnZmFqWaBbC8xg/view?usp=sharing
Comparison tool

**Comment by carey036** [comment] 2021-07-20 06:34
A boot which could be used well (like offical boot) will be disabled after executed` 
./magiskboot unpack -n boot.img
./magiskboot repack -n boot.img`
if you unpack new-boot.img, executing `./magiskboot cpio ramdisk.cpio 'extract'` would need the access of root while it's not needed by origin boot's ramdisk.cpio.

so, may the problem is caused by magisk's repack tool?

**Comment by osm0sis** [comment] 2021-08-21 10:03
This appears to have devolved into off topic and potentially unrelated devices. Any leads here from anybody?

**Comment by osm0sis** [comment] 2021-08-22 02:29
Did anyone try with the latest testing fork alpha? https://github.com/vvb2060/magisk_files/blob/master/app-release.apk

I think there were some mtk fixes.

**Comment by pndwal** [comment] 2021-08-22 09:13
> @qianmo-xw Can you try with the latest testing fork alpha? https://github.com/vvb2060/magisk_files/blob/master/app-release.apk
> 
> I think there were some mtk fixes.

I think @vvb2060 master branch = Lite version! - see associated json.
[Likely of interest only to those wanting basic superuser privileges and a way to hide root from bank apps that detect isolated processes at this stage, or wanting to test this.

Also Magisk Lite uses whitelist mode; all applications are hidden by default, and only the applications ticked in Hide can obtain super user permissions.
adb shell automatically has super user privileges. Module function is not available.]

This is latest Alpha:
https://github.com/vvb2060/magisk_files/blob/alpha/app-release.apk

Not sure if it includes MTK fixes are included. Here are all changes since last Canary (Chinese translated):
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-85472445 PW

**Comment by pndwal** [comment] 2021-08-22 09:15
> @qianmo-xw Can you try with the latest testing fork alpha? https://github.com/vvb2060/magisk_files/blob/master/app-release.apk
> 
> I think there were some mtk fixes.

I think @vvb2060 master branch = Lite version! - see associated json.
[Likely of interest only to those wanting basic superuser privileges and a way to hide root from bank apps that detect isolated processes at this stage, or wanting to test this.

Also Magisk Lite uses whitelist mode; all applications are hidden by default, and only the applications ticked in Hide can obtain super user permissions.
adb shell automatically has super user privileges. Module function is not available.]

This is latest Alpha:
https://github.com/vvb2060/magisk_files/blob/alpha/app-release.apk

Not sure if it includes MTK fixes are included. Here are all changes since last Canary (Chinese translated):
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-85472445 PW

**Comment by osm0sis** [comment] 2021-08-22 09:23
Thanks! You can also just read the commit logs: https://github.com/vvb2060/Magisk/commits/alpha

**Comment by pndwal** [comment] 2021-08-22 09:40
Sure! ... Are any fixes for MTK in particular?

**Comment by osm0sis** [comment] 2021-08-22 09:47
Some Meizu devices are MTK SoC, and the zygote check fix might also help since deleting zygote.rc files was a fix mentioned in some issues for MTK devices.

**Comment by pndwal** [comment] 2021-08-22 10:41
Could be worth trying after next release also in that case, as further Meizu compatibility fixes have been merged in branch since 1eb83ad8-alpha-31 release.

**Comment by AndyCGYan** [comment] 2021-08-22 14:12
Perhaps I can add to this discussion. I extracted and compared a self-patched boot image from 21.6.30, and a known-working image of the same build patched privately by someone, and the only difference is in ramdisk CPIO (the private CPIO is larger, but ramdisk content is identical). Could it be that it needs some special parameter in CPIO repacking?

**Comment by carey036** [comment] 2021-08-25 02:19
> @qianmo-xw Can you try with the latest testing fork alpha? https://github.com/vvb2060/magisk_files/blob/alpha/app-release.apk
> 
> I think there were some mtk fixes.
> 
> Edit: Corrected link to alpha.

didn't work, Infinite restart after flashing boot.

AIK v3.8 works well after repacking boot packed by magisk, is there any difference between AIK and magiskboot

**Comment by osm0sis** [comment] 2021-08-25 12:32
If you AIK repack --original, the only difference would be that AIK strips the AVBv2 signing.

**Comment by carey036** [comment] 2021-08-28 09:53
> If you AIK repack --original, the only difference would be that AIK strips the AVBv2 signing.

i opened magisk patched boot.img in hexadecimal, I found "00 00 00 **03** 00 00 00 00 61 76 62 74 6F 6F 6C 20" in this file, the file is not available, but if change it to "00 00 00 **00** 00 00 00 00 61 76 62 74 6F 6F 6C 20", it will be available. any solution?
if any attachment is needed, please let me know

**Comment by carey036** [comment] 2021-08-28 12:50
> Perhaps I can add to this discussion. I extracted and compared a self-patched boot image from 21.6.30, and a known-working image of the same build patched privately by someone, and the only difference is in ramdisk CPIO (the private CPIO is larger, but ramdisk content is identical). Could it be that it needs some special parameter in CPIO repacking?

run command
```
magiskboot hexpatch new-boot.img \
0000000300000000617662746F6F6C20 \
0000000000000000617662746F6F6C20
```
could solve this problem

**Comment by muddpunk** [comment] 2021-09-02 10:23
I figured I'd post here rather than make a duplicate issue. I'm having the same issue with my Xiaomi Redmi Note 8 Pro. I've tried patching both boot.img and recovery.img from the miui 12.5 ROM and consistently getting a bootloop. I've also tried flashing vbmeta with the command `fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img` before flashing both patched boot.img and recovery.img. 

This is my SoC model: MediaTek Helio G90T (MT6785T)

A little bit of extra information, I flashed the new android 11 ROM on top of my android 10 and kept all data. So not a fresh install or anything. I did do the whole safe mode thing to disable any modules from my previous setup too, but still had the same outcome.

Unfortunately I'm camping with my family at the minute, so I'm unable to help any further. However, as soon as we're back home I can help check files and or try the Canary build. If there's any more information I can grab from my phone without being near a PC let me know.

**Comment by pndwal** [comment] 2021-09-02 13:59
Can I take it you have Ramdisk=no? Nb. Xiaomi is an exception to norms for type III devices, having boot ramdisk compatible bootloaders, and all Xiaomi devices I know of need Magisk in boot despite ramdisk=no.

Yours may be an MTK related issue of course, but as it seems possible you had / have incompatible modules since you moved to Android 11, please check this issue:
https://github.com/topjohnwu/Magisk/issues/4624

It may be that modules were not disabled due to this despite booting to Safe Mode and are the issue. (Check you used the working timing.) Nb, both my devices are Qualcomm however. Nb.2. this won't work if you're now using un-patched boot image this won't work as booting to Safe Mode w/ Magisk is required as Magisk actually detects the Safe Mode key combo. To try different timing, flash new Magisk-patched image again.

**Comment by muddpunk** [comment] 2021-09-02 14:45
![Screenshot_2021-09-02-15-19-09-318_com topjohnwu magisk](https://user-images.githubusercontent.com/48693062/131862762-3412b655-471c-4d62-a355-21c321f8257f.jpg)

Apparently I do have Ramdisk=Yes.

Before reading your comment I had already taken a quick look at your post about timing with safe mode. It makes more sense to me that the modules weren't disabled, but how would i ever know if they were or not? 😅 
(Which upon re reading, it coincides with your comment  "Nb.2. this won't work if you're now using un-patched boot image as booting to Safe Mode w/ Magisk is required because Magisk actually detects the Safe Mode key combo.")

I'm going to try the patched boot.img shortly and persist on getting in to safe mode. This seems like progress for me considering the headache I've had the last couple of days, so i appreciate your advice 😄

**Comment by muddpunk** [comment] 2021-09-02 15:05
I literally can't get in to safe mode. I just keep getting thrown in to fastboot no matter what timings i try 😅

**Comment by muddpunk** [comment] 2021-09-02 15:56
Is it possible I can't reach safe mode because it doesn't get to the MIUI animation?

**Comment by pndwal** [comment] 2021-09-02 17:56
Could be different on MTK. I got black screen / restart if held pwr button too long, and did also end up in Fastboot somehow.

What worked for me was not to wait for animation as Imentioned. Static MI or Redmi logo lasts about 15 seconds, then I get MIUI or LineageOS animation. I release pwr and immediately hold vol- at about 4 seconds in, well before boot animation, and continue holding till safe mode is booted. This consistently lands me in Magisk detected Safe Mode confirmed by disabled MagiskHide on next system boot. Hope it helps.

**Comment by muddpunk** [comment] 2021-09-02 18:05
Yeah see I tried that too, but it's never made it to any boot animation at all. Unfortunately I can't test anything else today, but I have grabbed the alpha release that was mentioned above and I'll try again tomorrow. If not, I might have to revert back to android 10, install twrp with an older magisk again and disable the modules like that 🤷

**Comment by muddpunk** [comment] 2021-09-03 13:59
Just realised I can't go back on firmware without completely wiping and doing it fresh. So I've backed everything up and I'm going to clean install A11 and try magisk again. If it works this time round, I guess most issues probably stem from previous modules.

**Comment by carey036** [comment] 2021-09-03 14:11
> Just realised I can't go back on firmware without completely wiping and doing it fresh. So I've backed everything up and I'm going to clean install A11 and try magisk again. If it works this time round, I guess most issues probably stem from previous modules.

have ever try to replace "0000000300000000617662746F6F6C20" to "0000000000000000617662746F6F6C20" in hexadecimal

**Comment by muddpunk** [comment] 2021-09-03 15:41
> have ever try to replace "0000000300000000617662746F6F6C20" to "0000000000000000617662746F6F6C20" in hexadecimal

No. However, a fresh clean install of the same rom has allowed magisk to finally work. Had to of been the modules for sure right?

**Comment by pndwal** [comment] 2021-09-03 23:25
>Had to of been the modules for sure right?

Well, data/adb/magisk.db could have been corrupted, but less likely.

**Comment by osm0sis** [comment] 2021-09-24 02:59
Did @qianmo-xw ever even confirm that hexpatching workaround resolved his issue?

**Comment by carey036** [comment] 2021-09-25 08:58
> Did @qianmo-xw ever even confirm that hexpatching workaround resolved the issue on their device?

i built modified magisk in this repo, and shared the apk in coolapk, there were hundred of times download and tested well.

i also have a k40g and it is ok with this magisk.

**Comment by aviraxp** [comment] 2021-10-04 12:16
It turns out that this hexpatch is exactly to revert the magiskboot change that disables these 2 AVB flags which is done in https://github.com/topjohnwu/Magisk/blob/439d497a13c73a9ffa5f5a9a2575d1ecc7501858/native/jni/magiskboot/bootimg.cpp#L740:

`/* Flags for the vbmeta image.
 *
 * AVB_VBMETA_IMAGE_FLAGS_HASHTREE_DISABLED: If this flag is set,
 * hashtree image verification will be disabled.
 *
 * AVB_VBMETA_IMAGE_FLAGS_VERIFICATION_DISABLED: If this flag is set,
 * verification will be disabled and descriptors will not be parsed.
 */
typedef enum {
  AVB_VBMETA_IMAGE_FLAGS_HASHTREE_DISABLED = (1 << 0),
  AVB_VBMETA_IMAGE_FLAGS_VERIFICATION_DISABLED = (1 << 1)
} AvbVBMetaImageFlags;`

The issue is, why do we have to undo this patch?

**Comment by osm0sis** [comment] 2021-10-04 16:16
bootloader doesn't like it I guess. One thing of concern is that it's not only MTK devices, as @DarthJabba9 has confirmed the issue on his Xiaomi and POCO devices too, running both stock MIUI and custom ROMs.

**Comment by osm0sis** [comment] 2021-10-15 13:04
Leave it open. There is an issue with the AVBv2 signature patching that magiskboot does.

**Comment by osm0sis** [comment] 2021-11-08 02:22
This should fix it once merged, try the apk-debug.apk in the Artifacts zip: https://github.com/topjohnwu/Magisk/actions/runs/1432894612

**Comment by Gong-Mi** [comment] 2021-11-08 02:35
> This should fix it once merged, try the apk-debug.apk in the Artifacts zip: https://github.com/topjohnwu/Magisk/actions/runs/1432894612

可以ota 升级系统吗
我没有第3方rec

Can you update it with the ota method 。  
I don't like rec

**Comment by Gong-Mi** [comment] 2021-11-08 02:50
> This should fix it once merged, try the apk-debug.apk in the Artifacts zip: https://github.com/topjohnwu/Magisk/actions/runs/1432894612

可以添加虚拟还原原厂boot吗
联发科貌似不喜欢系统里面替换。

Can you help me add a simulated uninstall boot ？ 
MediaTek does not seem to like the boot used by the system replacement 。

**Comment by Gong-Mi** [comment] 2021-11-08 04:08
> This should fix it once merged, try the apk-debug.apk in the Artifacts zip: https://github.com/topjohnwu/Magisk/actions/runs/1432894612


使用了
![Screenshot_2021-11-08-12-05-43-108_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/62661921/140682896-beec3f08-dd73-4d51-bece-7d9f92b3aeba.jpg)

**Comment by osm0sis** [comment] 2021-11-13 06:44
Try this one as well to test @Fox2Code's theory please: https://github.com/topjohnwu/Magisk/actions/runs/1435283509

**Comment by Gong-Mi** [comment] 2021-11-13 07:24
> Try this one as well to test @Fox2Code's theory in #4906 please: https://github.com/topjohnwu/Magisk/actions/runs/1435283509

Well, after all, it didn't merge into the mainstream

**Comment by osm0sis** [comment] 2021-11-13 15:44
Neither did the last one you tried, but this solution may be more universal.

> This is still POC as we have not many information about the issue, I theorized that MIUI on Android11 crashed due to the lack of avb flags due to the `0x2` flag being set. The `0x1` disable most checks already, and should be enough for most devices.
> 
> Note: please restore stock image before trying this build, the fix target MIUI Android 11 users, but any other device owner are welcome to test the changes included in this PR to check for any regressions.

**Comment by Gong-Mi** [comment] 2021-11-13 15:53
> Neither did the last one you tried, but this solution may be more universal.
> 
> > This is still POC as we have not many information about the issue, I theorized that MIUI on Android11 crashed due to the lack of avb flags due to the `0x2` flag being set. The `0x1` disable most checks already, and should be enough for most devices.
> > 
> > Note: please restore stock image before trying this build, the fix target MIUI Android 11 users, but any other device owner are welcome to test the changes included in this PR to check for any regressions.

I think

Problem: there is a problem with the official Android 12 internal test

I can only test and modify boot

**Comment by Gong-Mi** [comment] 2021-11-18 08:57
> Neither did the last one you tried, but this solution may be more universal.
> 
> > This is still POC as we have not many information about the issue, I theorized that MIUI on Android11 crashed due to the lack of avb flags due to the `0x2` flag being set. The `0x1` disable most checks already, and should be enough for most devices.
> > 
> > Note: please restore stock image before trying this build, the fix target MIUI Android 11 users, but any other device owner are welcome to test the changes included in this PR to check for any regressions.

大失败  0100000000617662746F6F6C20
不行  
9b5185bb不能通过开机


fail
0100000000617662746F6F6C20
No boot. For mtk1200,

9b5185bb failed the acceptance.

**Comment by Gong-Mi** [comment] 2021-11-18 08:58
> Neither did the last one you tried, but this solution may be more universal.
> 
> > This is still POC as we have not many information about the issue, I theorized that MIUI on Android11 crashed due to the lack of avb flags due to the `0x2` flag being set. The `0x1` disable most checks already, and should be enough for most devices.
> > 
> > Note: please restore stock image before trying this build, the fix target MIUI Android 11 users, but any other device owner are welcome to test the changes included in this PR to check for any regressions.

Test version official stable version system-Android 11

**Comment by osm0sis** [comment] 2021-11-24 10:34
I think this needs to remain open until there's a way to toggle KEEPVBMETAFLAG in the app 🤔

**Comment by Gong-Mi** [comment] 2021-11-24 10:40
> I think this needs to remain open until there's a way to toggle KEEPVBMETAFLAG in the app 🤔

Thank you

I want to know if it's finished.

**Comment by Gong-Mi** [comment] 2021-11-24 20:27
> I think this needs to remain open until there's a way to toggle KEEPVBMETAFLAG in the app 🤔

https://github.com/topjohnwu/Magisk/pull/4975#pullrequestreview-815341698


![Screenshot_2021-11-25-04-13-49-818_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/62661921/143308470-6726a72e-6f8c-4378-afff-938c8f2932bd.jpg)

All that's missing is an introduction to the new features.
Other than that, perfect.

**Comment by Gong-Mi** [comment] 2021-12-07 12:43
the latest

https://github.com/topjohnwu/Magisk/pull/5028

**Comment by osm0sis** [comment] 2021-12-08 08:10
Shit, now OnePlus 9 Pro needs it set to 00 as well, now that OPPO has merged OOS into ColorOS. 😢😒

**Comment by yujincheng08** [comment] 2022-01-13 07:26
ui is done. could be closed

**Closed** 2022-01-13 11:19 UTC
Labels: regression
