### ISSUE TITLE
Unable to establish socket connection with daemon

### ISSUE THREAD

**Issue by vdbhb59** [topjohnwu/Magisk#2944] opened 2020-07-04 18:12 UTC
If you see the below image, this overlay root access request is like this since the last 3-4 releases of canary. Full clean flash, update, be it whatever, this BUG is there. Since Auto Grant is ON, this bug does not bother me much, but this needs looking into please.
The thing is, the overlay does not give an option of clicking, or selecting anything other than Deny button. Everything else on that overlay is a dead button ideally.
Does not allow snapshot when this overlay is there, so took snap from another mobile.

![Magisk Overlay BUG](https://user-images.githubusercontent.com/60728004/86518494-c4b34c00-be4f-11ea-94e5-f8b0fc34e293.png)

**Comment by Andre088** [comment] 2020-07-04 19:48
Samsung Galaxy s20 Plus twrp

**Comment by vdbhb59** [comment] 2020-07-04 20:06
> Samsung Galaxy s20 Plus twrp
What? Is your comment making any sense?

**Comment by nabraas60000** [comment] 2020-07-04 20:08
Hi

**Comment by nabraas60000** [comment] 2020-07-04 20:09
Hi

**Comment by X1nto** [comment] 2020-07-05 07:45
I have a similar problem, but instead of it prompt actually showing up, it pops up for 1 second and then disappears, setting default prompt answer to "grant" doesn't work either

**Comment by vdbhb59** [comment] 2020-07-05 08:01
For me, it does not go away, unless I remove MagiskManager from recent and or I switch to other app..

**Comment by osm0sis** [comment] 2020-07-05 13:18
Logs? Settings? Last working Canary Manager?

**Comment by vdbhb59** [comment] 2020-07-05 13:28
Logs: None available, as clicking on Magisk Logs icon, closes Magisk Manager.
Settings: Squished, Auto Grant, 30 seconds time out, toast, and nothing else.
Device: Any device, OnePlus, Samsung, Xiaomi.
OS: Any, Oreo, Pie, Q, all..
Last working Canary: Do not recall exactly, but I recall, this issue started from 4-5 releases ago.

**Comment by osm0sis** [comment] 2020-07-05 13:35
Please find out the last working Canary: https://github.com/topjohnwu/magisk_files/commits/canary

**Comment by X1nto** [comment] 2020-07-05 13:37
Just found out that both manager and magisk received update today, after updating everything works fine.

**Comment by vdbhb59** [comment] 2020-07-05 13:44
> Please find out the last working Canary by downloading app-debug.apk from the corresponding commits here: https://github.com/topjohnwu/magisk_files/commits/canary

https://github.com/topjohnwu/magisk_files/commit/7a388abedd902a773ac803984166ecd58d5edb80

**Comment by vdbhb59** [comment] 2020-07-05 13:46
> Just found out that both manager and magisk received update today, after updating everything works fine.

For me, it does not. I am on latest canary (289)(20418), and cannot uninstall Magisk, as Galaxy device (the one where I am replying from now).
My other phones are not with me right now.

**Comment by osm0sis** [comment] 2020-07-05 13:47
> [topjohnwu/magisk_files@7a388ab](https://github.com/topjohnwu/magisk_files/commit/7a388abedd902a773ac803984166ecd58d5edb80)

There's no Manager app-debug.apk in that commit, are you saying it didn't start with a Manager update but with a Magisk update instead?

**Comment by vdbhb59** [comment] 2020-07-05 13:51
> > [topjohnwu/magisk_files@7a388ab](https://github.com/topjohnwu/magisk_files/commit/7a388abedd902a773ac803984166ecd58d5edb80)
> 
> There's no Manager app-debug.apk in that commit, are you saying it didn't start with a Manager update but with a Magisk update instead?

Yes, as this one is from where I started getting issue.

**Comment by osm0sis** [comment] 2020-07-05 13:57
Okay, cool. So it works with 20415/284 and breaks with 20416/285. :+1:

**Comment by vdbhb59** [comment] 2020-07-05 14:01
> Okay, cool. So it works with 20415/284 and breaks with 20416/285. +1

Right. I would have given more details, but by clicking log option on manager, closes it out (not crash or force close), but just close it out, and the system wide logs are disabled via shell script, so no logs available.

**Comment by famaTV** [comment] 2020-07-05 15:31
Hello and many thanks guys for your great and continuous support!

I have two problems:
1. Same as above (when you have the root option in Magisk of Automatic Response to Grant), I got stuck with an overlay window that there is no way to press on the Grant button (see attached)

2. I can't get Magisk Manager to hide itself using the "Hide Magisk Manager" (renaming / repackaging the app), I get an error message of "Hide Magisk Manager failed" (see attached). 

Even after trying the latest manager apk (published today), I see the same problems. By the way, the zip file says last update 6 days ago (not sure if only the apk was updated today. You may notice under "Latest" (version of Magisk/Manager) it just says "Loading..." no status nor a button to install/update.

I don't remember when that started to happen but everything was working with Canary version a couple of months back (I haven't updated till yesterday). If I download older managers apk and try to rename/hide it, it gets stuck/failed.

I am including a screenshot of my Magisk manager version and my HW info (see attached). There is no log produced though.

Thank you in advance

![Magisk Problem 03](https://user-images.githubusercontent.com/6208778/86536054-5624cb80-beed-11ea-9145-9f50c5fcd356.jpeg)
![Magisk Problem 02](https://user-images.githubusercontent.com/6208778/86536057-5755f880-beed-11ea-9931-b9369bc7e026.jpeg)
![Magisk Problem 01](https://user-images.githubusercontent.com/6208778/86536058-5755f880-beed-11ea-82f7-ef32c2f44de4.jpeg)

**Comment by vdbhb59** [comment] 2020-07-05 16:05
Also @osm0sis, I am getting a lot of random reboots with Magisk. Attaching the Magisk Log. Gives full log of the last crash.

`--------- beginning of main
--------- beginning of system
06-16 15:45:46.638   693   693 I Magisk  : Magisk a0b47f3c(20418) daemon started
06-16 15:45:46.639   693   693 I Magisk  : * Device API level: 29
06-16 15:45:46.647   693   694 D Magisk  : resetprop: getprop [ro.crypto.state]: [encrypted]
06-16 15:45:46.647   693   694 D Magisk  : resetprop: getprop [init.svc.vold]: [running]
06-16 15:45:46.671   693   694 I Magisk  : ** post-fs-data mode running
06-16 15:45:46.675   693   694 I Magisk  : * Initializing Magisk environment
06-16 15:45:46.719   693   694 I Magisk  : * Mounting mirrors
06-16 15:45:46.719   693   694 I Magisk  : mount: /sbin/.magisk/mirror/vendor
06-16 15:45:46.719   693   694 I Magisk  : mount: /sbin/.magisk/mirror/data
06-16 15:45:46.720   693   694 I Magisk  : link: /sbin/.magisk/mirror/system
06-16 15:45:46.720   693   694 I Magisk  : link: /sbin/.magisk/mirror/product
06-16 15:45:46.720   693   694 I Magisk  : * Setting up internal busybox
06-16 15:45:46.740   693   694 D Magisk  : resetprop: decode with protobuf [/data/property/persistent_properties]
06-16 15:45:46.743   693   694 D Magisk  : resetprop: prop [persist.sys.safemode] does not exist
06-16 15:45:46.938   693   694 I Magisk  : * Running post-fs-data.d scripts
06-16 15:45:46.940   693   694 D Magisk  : magiskdb: query magiskhide=[1]
06-16 15:45:46.940   693   694 I Magisk  : * Starting MagiskHide
06-16 15:45:46.940   693   694 D Magisk  : hide_list: initialize
06-16 15:45:46.960   693   694 I Magisk  : hide_list init: [com.google.android.gms/com.google.android.gms.unstable]
06-16 15:45:46.965   693   694 I Magisk  : hide_list init: [org.microg.gms.droidguard/com.google.android.gms.unstable]
06-16 15:45:46.972   693   694 I Magisk  : hide_policy: Hiding sensitive props
06-16 15:45:46.972   693   694 D Magisk  : resetprop: prop [ro.boot.vbmeta.device_state] does not exist
06-16 15:45:46.972   693   694 D Magisk  : resetprop: getprop [ro.boot.verifiedbootstate]: [green]
06-16 15:45:46.972   693   694 D Magisk  : resetprop: getprop [ro.boot.flash.locked]: [1]
06-16 15:45:46.972   693   694 D Magisk  : resetprop: getprop [ro.boot.veritymode]: [enforcing]
06-16 15:45:46.972   693   694 D Magisk  : resetprop: prop [ro.boot.warranty_bit] does not exist
06-16 15:45:46.972   693   694 D Magisk  : resetprop: prop [ro.warranty_bit] does not exist
06-16 15:45:46.972   693   694 D Magisk  : resetprop: getprop [ro.debuggable]: [1]
06-16 15:45:46.972   693   694 D Magisk  : resetprop: update prop [ro.debuggable]: [0] by modifying prop data structure
06-16 15:45:46.972   693   694 D Magisk  : resetprop: getprop [ro.secure]: [1]
06-16 15:45:46.972   693   694 D Magisk  : resetprop: getprop [ro.build.type]: [userdebug]
06-16 15:45:46.972   693   694 D Magisk  : resetprop: update prop [ro.build.type]: [user] by modifying prop data structure
06-16 15:45:46.972   693   694 D Magisk  : resetprop: getprop [ro.build.tags]: [test-keys]
06-16 15:45:46.972   693   694 D Magisk  : resetprop: update prop [ro.build.tags]: [release-keys] by modifying prop data structure
06-16 15:45:46.972   693   694 D Magisk  : resetprop: prop [ro.vendor.boot.warranty_bit] does not exist
06-16 15:45:46.972   693   694 D Magisk  : resetprop: prop [ro.vendor.warranty_bit] does not exist
06-16 15:45:46.972   693   694 D Magisk  : resetprop: prop [vendor.boot.vbmeta.device_state] does not exist
06-16 15:45:46.972   693   694 D Magisk  : resetprop: getprop [ro.bootmode]: [normal]
06-16 15:45:46.972   693   694 D Magisk  : resetprop: getprop [ro.boot.mode]: [normal]
06-16 15:45:46.972   693   694 D Magisk  : resetprop: prop [vendor.boot.mode] does not exist
06-16 15:45:46.972   693   694 D Magisk  : resetprop: prop [ro.boot.hwc] does not exist
06-16 15:45:46.972   693   694 D Magisk  : resetprop: prop [ro.boot.hwcountry] does not exist
06-16 15:45:46.972   693   694 D Magisk  : resetprop: getprop [ro.build.selinux]: [1]
06-16 15:45:46.972   693   694 D Magisk  : resetprop: delete prop [ro.build.selinux]
06-16 15:45:46.981   693   694 D Magisk  : bind_mnt: /sbin/.magisk/modules <- /sbin/.magisk/mirror/data/adb/modules
06-16 15:45:46.982   693   701 D Magisk  : proc_monitor: nothing to monitor, wait for signal
06-16 15:45:47.067   693   694 I Magisk  : * Running module post-fs-data scripts
06-16 15:45:47.067   693   694 I Magisk  : * Loading modules
06-16 15:45:47.067   693   694 I Magisk  : busybox-ndk: loading mount files
06-16 15:45:47.071   693   694 D Magisk  : mnt_tmp : /system/xbin <- tmpfs
06-16 15:45:47.072   693   694 D Magisk  : bind_mnt: /system/xbin/7z <- /sbin/.magisk/mirror/system/xbin/7z
06-16 15:45:47.072   693   694 D Magisk  : cp_link : /system/xbin/[ <- /sbin/.magisk/modules/busybox-ndk/system/xbin/[
06-16 15:45:47.072   693   694 D Magisk  : cp_link : /system/xbin/[[ <- /sbin/.magisk/modules/busybox-ndk/system/xbin/[[`

............

`06-16 15:45:47.093   693   694 D Magisk  : bind_mnt: /system/xbin/zip <- /sbin/.magisk/mirror/system/xbin/zip
07-05 21:26:37.238   693   701 D Magisk  : proc_monitor: nothing to monitor, wait for signal
07-05 21:26:37.257   693   701 D Magisk  : proc_monitor: nothing to monitor, wait for signal
07-05 21:26:38.501   693  1116 I Magisk  : ** late_start service mode running
07-05 21:26:38.501   693  1116 I Magisk  : * Running service.d scripts
07-05 21:26:38.502   693  1116 I Magisk  : * Running module service scripts
07-05 21:26:40.071   693   701 D Magisk  : proc_monitor: ptrace zygote PID=[722]
07-05 21:26:40.072   693   701 D Magisk  : proc_monitor: ptrace zygote PID=[723]
07-05 21:26:51.218   693  3331 I Magisk  : ** boot_complete triggered
07-05 21:26:51.218   693  3331 I Magisk  : hide_policy: Hiding sensitive props (late)
07-05 21:26:51.218   693  3331 D Magisk  : resetprop: prop [vendor.boot.verifiedbootstate] does not exist
07-05 21:27:01.586   693  4278 D Magisk  : su: request from pid=[4275], client=[7]
07-05 21:27:01.587   693  4278 D Magisk  : su: request from uid=[10160]
07-05 21:27:01.587   693  4278 D Magisk  : magiskdb: query su_biometric=[0]
07-05 21:27:01.587   693  4278 D Magisk  : magiskdb: query magiskhide=[1]
07-05 21:27:01.588   693  4278 D Magisk  : su: waiting child pid=[4279]
07-05 21:27:01.588  4279  4279 D Magisk  : su: fork handler
07-05 21:27:01.588  4279  4279 D Magisk  : su: use global namespace
07-05 21:27:24.304   693  5539 D Magisk  : su: request from pid=[5536], client=[11]
07-05 21:27:24.304   693  5539 D Magisk  : su: request from uid=[10166]
07-05 21:27:24.304   693  5539 D Magisk  : magiskdb: query su_biometric=[0]
07-05 21:27:24.304   693  5539 D Magisk  : magiskdb: query magiskhide=[1]
07-05 21:27:24.712   693  5539 D Magisk  : su: waiting child pid=[5566]
07-05 21:27:24.712  5566  5566 D Magisk  : su: fork handler
07-05 21:27:24.713  5566  5566 D Magisk  : su: use namespace of pid=[5536]
--------- beginning of crash
07-05 21:28:19.210   693   701 D Magisk  : proc_monitor: nothing to monitor, wait for signal
07-05 21:28:19.325   693  4278 D Magisk  : su: return code=[0]
07-05 21:28:19.395   693   701 D Magisk  : proc_monitor: nothing to monitor, wait for signal
07-05 21:28:19.487   693  5539 D Magisk  : su: return code=[0]
07-05 21:28:20.578   693   701 D Magisk  : proc_monitor: ptrace zygote PID=[5961]
07-05 21:28:20.578   693   701 D Magisk  : proc_monitor: ptrace zygote PID=[5962]
07-05 21:28:34.619   693  7154 I Magisk  : ** boot_complete triggered
07-05 21:28:34.619   693  7154 I Magisk  : hide_policy: Hiding sensitive props (late)
07-05 21:28:34.619   693  7154 D Magisk  : resetprop: prop [vendor.boot.verifiedbootstate] does not exist
07-05 21:28:41.683   693  8217 D Magisk  : su: request from pid=[8214], client=[7]
07-05 21:28:41.683   693  8217 D Magisk  : su: request from uid=[10160]
07-05 21:28:41.683   693  8217 D Magisk  : magiskdb: query su_biometric=[0]
07-05 21:28:41.683   693  8217 D Magisk  : magiskdb: query magiskhide=[1]
07-05 21:28:41.684   693  8217 D Magisk  : su: waiting child pid=[8218]
07-05 21:28:41.685  8218  8218 D Magisk  : su: fork handler
07-05 21:28:41.686  8218  8218 D Magisk  : su: use global namespace`

Hope this helps..

**Comment by Andre088** [comment] 2020-07-06 08:29
Kannst du mir vielleicht helfen erstens sagt magnisk app soll nach neue magnisk hide schauen, 2 ich brauche für mein Samsung Galaxy s20 Plus twrp zum patchen mit magnisk um supersu für lucky patcher Kannst du mir vielleicht weiterhelfen?Email flashandre87@gmail.com vielen Dank

**Comment by X1nto** [comment] 2020-07-06 08:30
> Kannst du mir vielleicht helfen erstens sagt magnisk app soll nach neue magnisk hide schauen, 2 ich brauche für mein Samsung Galaxy s20 Plus twrp zum patchen mit magnisk um supersu für lucky patcher Kannst du mir vielleicht weiterhelfen?Email flashandre87@gmail.com vielen Dank 

Please use English only

**Comment by Andre088** [comment] 2020-07-09 21:13
Samsung Galaxy s20 Plus

**Comment by Andre088** [comment] 2020-07-09 22:02
Samsung Galaxy s20 Plus twrp in recovery

**Comment by Andre088** [comment] 2020-07-09 22:04
Ja Samsung Galaxy s20 twrp in recovery

**Comment by Bengel088x** [comment] 2020-07-12 16:31
Kann mir jemand helfen brauche Samsung Galaxy s20 Plus twrp in recovery, flashandre87@gmail.com

**Comment by vdbhb59** [comment] 2020-07-20 19:56
When I click Bug icon, I face manager app crashing with this error:

FATAL EXCEPTION: main
Process: com.topjohnwu.magisk, PID: 8557
java.lang.IllegalArgumentException: PrecomputedText's Parameters don't match the parameters of this TextView.Consider using setTextMetricsParams(precomputedText.getParams()) to override the settings of this TextView: PrecomputedText: {textSize=15.0, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[en_GB,en_US,en_IN,gu_IN,hi_IN,es_ES,de_DE], typeface=android.graphics.Typeface@fbd82b74, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@3190d5a, breakStrategy=1, hyphenationFrequency=0}TextView: {textSize=15.0, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[en_GB,en_US,en_IN,gu_IN,hi_IN,es_ES,de_DE], typeface=android.graphics.Typeface@fbd82b74, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@3190d5a, breakStrategy=1, hyphenationFrequency=0}
	at android.widget.TextView.setText(TextView.java:6731)
	at android.widget.TextView.setText(TextView.java:6649)
	at android.widget.TextView.setText(TextView.java:6601)
	at androidx.core.widget.TextViewCompat.setPrecomputedText(TextViewCompat.java:887)
	at com.topjohnwu.magisk.databinding.AdaptersGenericKt$setPrecomputedText$1$1.run(AdaptersGeneric.kt:41)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7807)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by Andrew-afk** [comment] 2020-08-01 16:07
They closed my thread, showed me this, and still open, what a horrible staff
Anyways, Canary also not working

**Comment by vdbhb59** [comment] 2020-08-01 17:08
> They closed my thread, showed me this, and still open, what a horrible staff
> Anyways, Canary also not working, same issue

Closed as that was a duplicate of what has been raised in this one. Not horrible, but trying to keep the issue log clean and clear.

**Comment by vdbhb59** [comment] 2020-08-01 17:09
> Kann mir jemand helfen brauche Samsung Galaxy s20 Plus twrp in recovery

Do you think, this is TWRP repo? Where do you people land from here?

**Comment by Andrew-afk** [comment] 2020-08-04 17:40
> > They closed my thread, showed me this, and still open, what a horrible staff
> > Anyways, Canary also not working, same issue
> 
> Closed as that was a duplicate of what has been raised in this one. Not horrible, but trying to keep the issue log clean and clear.

My issue still open, you closed it without a solution. You better keep it open so your reference can lead to this issue faster, because my issue is recent.

Also, i asked if there was a command for give root privileges to apps. Give me an answer.

**Comment by unixandria-xda** [comment] 2020-08-04 17:46
> My issue still open, you closed it without a solution. You better keep it open so your reference can lead to this issue faster, because my issue is recent.
> 
> Also, i asked if there was a command for give root privileges to apps. Give me an answer.

I would advise against giving repo mods orders. Might not end well

**Comment by benathan** [comment] 2020-08-08 14:05
@osm0sis Device that works flawlessly: Le 2 with the latest LOS 16
Devices that have the same problem: Samsung A9000 Stock 6.0.1, Samsung C9000 Stock 8.0.0
Both devices shows the same logs as belows
Logs:
>08-08 21:45:34.397   386  4060 D Magisk  : su: request from pid=[4058], client=[10]
08-08 21:45:34.397   386  4060 D Magisk  : su: request from uid=[10161]
08-08 21:45:34.397   386  4060 D Magisk  : magiskdb: query magiskhide=[1]
08-08 21:45:35.237   386  3540 D Magisk  : su: return code=[0]
08-08 21:45:35.237   386  4060 E Magisk  : read (4 != -1) failed with 104: Connection reset by peer
08-08 21:45:35.247   386  4060 W Magisk  : su: request rejected (10161)
08-08 21:45:35.317   386  4091 D Magisk  : su: request from pid=[4090], client=[12]
08-08 21:45:35.317   386  4091 D Magisk  : su: request from uid=[10161]
08-08 21:45:35.337   386  4091 W Magisk  : su: request rejected (10161)
08-08 21:48:00.077   386  4303 D Magisk  : su: request from pid=[4301], client=[10]
08-08 21:48:00.077   386  4303 D Magisk  : su: request from uid=[10030]
08-08 21:48:00.077   386  4303 D Magisk  : magiskdb: query magiskhide=[1]
08-08 21:48:00.087   386  4303 D Magisk  : su: waiting child pid=[4304]
08-08 21:48:00.087  4304  4304 D Magisk  : su: fork handler
08-08 21:48:00.087  4304  4304 D Magisk  : su: use global namespace

btw, Changing the "Automatic Response" from Prompt to Grant didn't resolve the problem.
All the above devices are running with the Latest Magisk (20419/291)

**Comment by vdbhb59** [comment] 2020-08-08 15:17
> command for give root privileges to apps

Read: https://android.stackexchange.com/questions/203850/is-there-a-way-to-give-root-privileges-to-an-app-through-the-adb

**Comment by f-666** [comment] 2020-08-12 11:35
I had the same problem on my Nexus 6P with LineageOS 15.1. With the latest Magisk Manager canary version the problem is gone. I get the overlay again with 6c8fe465 (292).

**Comment by vdbhb59** [comment] 2020-08-12 13:01
> I had the same problem on my Nexus 6P with LineageOS 15.1. With the latest Magisk Manager canary version the problem is gone. I get the overlay again with [6c8fe46](https://github.com/topjohnwu/Magisk/commit/6c8fe4659061ac4424ff0a0d65e0ea23be327ca2) (292).

You are lucky, but I still have the issue on the current one too.

**Comment by osm0sis** [comment] 2020-08-14 12:16
@vdbhb59, how about 293?

**Comment by vdbhb59** [comment] 2020-08-14 16:31
> @vdbhb59, how about 293?

Just checked, still the same. Give me a couple of days time, probably by Sunday eod. I will do a clean flash of my ROM with latest 293 in the Magisk zip to check. Though 20.4 stable is working, only canary giving error.

**Comment by vdbhb59** [comment] 2020-08-24 16:41
Fresh Logs: https://github.com/topjohnwu/Magisk/files/5119126/magisk_log_20200824_214412.log

**Comment by osm0sis** [comment] 2020-08-24 18:12
@diareuse, any ideas? This was another thing that broke after the recent Kotlin rewrites.

**Comment by topjohnwu** [comment] 2020-08-24 20:34
@osm0sis the issue is not in Magisk Manager, or at least not only. The title is misleading (I'll update it)
The real issue lies in the socket connection unable to establish with the daemon.
It is just that the way @diareuse setup activities made it impossible to *NOT* show an UI after activity start, and since no information is sent over the wire, the UI cannot do anything and it looks like it is frozen.

**Comment by topjohnwu** [comment] 2020-09-05 02:53
@vdbhb59 any luck with the latest canaries?

**Comment by vdbhb59** [comment] 2020-09-05 07:47
> @vdbhb59 any luck with the latest canaries?

Hi Mate. Nope still the same. Attached the image. Sorry for not reverting earlier.
![20200905_131102](https://user-images.githubusercontent.com/60728004/92300603-b666d680-ef4b-11ea-9b33-35f77e8405ae.jpg)
![Screenshot_20200905-131604](https://user-images.githubusercontent.com/60728004/92300639-fd54cc00-ef4b-11ea-8db4-de7b5b91cac5.png)

**Comment by palmbeach05** [comment] 2020-09-06 02:02
Agree with above, issue still exists. I'm on moto g7 power (a/b device) and what he sees is exactly the same as what i see

**Comment by topjohnwu** [comment] 2020-09-07 18:41
@vdbhb59 I need full logcat, not Magisk logs to debug this issue. Start logcat record and request for su so I can see exactly what had happened.

**Comment by topjohnwu** [comment] 2020-09-09 22:56
@Andrew-afk please STOP spamming Github issues, either you provide more info on this issue, or I will block you on Github.

**Comment by topjohnwu** [comment] 2020-09-10 04:18
Closing this as nobody is providing any relevant info, duping to #3159 as it is the same issue and it provides logcat for debugging

**Closed by topjohnwu** 2020-09-10 04:18 UTC
Labels: bug

**Comment by palmbeach05** [comment] 2020-09-10 20:59
@topjohnwu logs as requested. Its taken from matlog rather than the adb method, but this should help. Magisk 20425 and magisk manager (298) which were released earlier today. I have it set to auto accept when permission is requested. Pop up screen does show up, then disappears. When i tap on magisk manager, popup shows up, and only way out is to hit the back button.

[logs-2020-09-10-16-51-55.zip](https://github.com/topjohnwu/Magisk/files/5204616/logs-2020-09-10-16-51-55.zip)

**Comment by osm0sis** [comment] 2020-09-10 21:34
@palmbeach05 maybe start a new issue with that, since this one is long and getting convoluted now
