### ISSUE TITLE
MagiskInit Incompatible with MTK devices

### ISSUE THREAD

**Issue by mrmazakblu** [topjohnwu/Magisk#3042] opened 2020-08-03 11:18 UTC
Continued from 
https://github.com/topjohnwu/Magisk/issues/3040

Magisk patches boot.img. Log shows complete. But magisk.init is not run on boot.

same result with 20.4 and latest canary. Previous similar issue with devices on android 11 and boot.img has no 'apex' dir.

This problem is on android 10 and the boot.img does have 'apex' dir,

can confirm patched image is flashed by spflash readback. It is same image as was flashed. 

[magisk_canary-boot-logcat.txt](https://github.com/topjohnwu/Magisk/files/5015599/magisk_canary-boot-logcat.txt)
[magisk_install_log_2020-08-03T065156Z.log](https://github.com/topjohnwu/Magisk/files/5015600/magisk_install_log_2020-08-03T065156Z.log)

[magisk_patched.zip](https://github.com/topjohnwu/Magisk/files/5015606/magisk_patched.zip)

**Comment by mrmazakblu** [comment] 2020-08-04 11:15
Do not know how to tell if it's a pactching issue or boot order issue. 
The logcat does not seem any different from stock or patched boot.img. at least to me. 

Is there a way to manually patch the boot.img to try?

**Comment by mrmazakblu** [comment] 2020-08-07 11:58
Just putting out this question. Could the separate dtbo image be effecting the ability of magisk_patched boot having working root?

**Comment by mrmazakblu** [comment] 2020-08-18 00:57
seems similar to this issue.

https://github.com/topjohnwu/Magisk/issues/3021

but i have been unable to download the referenced canary build to verify.

**Comment by mrmazakblu** [comment] 2020-08-18 01:12
beta canary 20420 does same. 
it patches boot.img Log looks normal. 
fastboot flash boot magisk_patched.img 
completes, no error. Reboot to android, magisk is not installed.

**Comment by topjohnwu** [comment] 2020-08-18 18:20
Duplicate #2994

**Comment by mrmazakblu** [comment] 2020-08-18 18:50
Thanks for the attention.  But is this issue a dip of the one you
referenced?
The devices commenting on that issue are on Android 11, and there bootmimg
does not have an apex folder in ramdisk. Neither are true on my device.

**Comment by mrmazakblu** [comment] 2020-08-19 23:11
@topjohnwu  @osm0sis  has said 2 times now, that this problem is not same as the issue in duplicate tag.

Because this is not on an Android 11 , and the ramdisk does have the apex dir

Are there any logs that I would help identify what is happening during the boot up?

I have a very limited twrp working. But I should be able to get lask kmsg with it if it may help

**Comment by topjohnwu** [comment] 2020-08-20 02:04
The cause is the same, that's why it's duped...

**Comment by mrmazakblu** [comment] 2020-09-03 21:38
Just tried new canary. I know this issue is not listed on change log. but I tried anyway.

magisk patched boot.img with canary 20421, phone still boots, and magisk init has not ran.

**Comment by osm0sis** [comment] 2020-09-04 03:26
Any change with 20422?

**Comment by mrmazakblu** [comment] 2020-09-04 10:14
20422 Still not seeing any sign of modified init or magisk. Still normal boot process and no magisk. 

only entry in logcat for magisk , is reference to the manager app.

https://del.dog/abihutogry

**Comment by topjohnwu** [comment] 2020-09-04 13:04
Please let me know the device info from Magisk Manager.
A/B? SAR? Ramdisk?

**Comment by mrmazakblu** [comment] 2020-09-04 13:30
Ab noabe, thehhh.  ™™
Sar yes wayddedtsag


I have tried recovery mode (not on latest yet)

When try to boot recovery when patched, neither recovery nor rooted system
would boot.

**Comment by mrmazakblu** [comment] 2020-09-05 14:19
Just tried recovery mode with 20424. Recovery will not boot. Just pauses few moments, then reboots to system (unrooted).

Noticed when I updated the canary manager app, the option for recovery mode has gone.

**Comment by lss4** [comment] 2020-09-06 04:50
Try installing [Magisk 20407](https://github.com/topjohnwu/magisk_files/tree/50ded4e34088a1675811f2b5dce5502e7bc4801f). If that works for you then we're having a similar issue. Magisk on my Pixel C broke since 20408.

On Android 10, Pixel C is in a similar state as yours:
A/B - no
SAR - yes
Ramdisk - yes

**Comment by osm0sis** [comment] 2020-09-06 12:44
You said you tried recovery mode, try regular on 424 also

**Comment by mrmazakblu** [comment] 2020-09-06 15:17
I needed to be more specific, yes I did try both ways with 20422 and 424

Have not gone back to 20407 as suggested above yet though.

**Comment by lss4** [comment] 2020-09-07 01:24
I think I might take a look at what happened between 20407 (2aede977) and 20408 (87de0e7a) and look for a possible cause...

**Comment by mrmazakblu** [comment] 2020-09-07 15:45
I am not able to try the older build ( i read a comment that old builds are not supported any way)

I allways get an error downloading the files when I try.

**Comment by lss4** [comment] 2020-09-07 18:28
Older canary build in the magisk_files repo is always available. The link/commit I pointed previously is the one containing the 20407 builds.

Older canary builds are not supported because certain issues might have been fixed in latest builds (as such, the bug reports would be invalid). However, they'll still be helpful in finding regressions, in case an older build worked for you, but the latest build doesn't.

**Comment by mrmazakblu** [comment] 2020-09-07 20:07
UPDATE on device root. Not really on the magisk issue though. Unless this information tells magisk dev anything

I have factory rom leak or release, not sure which) the firmware spflash files included "boot-debug.img" when this is flashed to boot from fastboot, adb root is allowed and root shell is available. At this time i do not kow if this can be used to elevate apps to root access though.

**Comment by lss4** [comment] 2020-09-08 02:51
> UPDATE on device root. Not really on the magisk issue though. Unless this information tells magisk dev anything
> 
> I have factory rom (leak or release, not sure which) the firmware spflash files included "boot-debug.img" when this is flashed to boot from fastboot, adb root is allowed and root shell is available. At this time i do not kow if this can be used to elevate apps to root access though.
> 
> magisk patching this boot-debug.img did not allow magisk to run. still shows "Status N/A"

That takes back memories. You're using a Mediatek device, right... I remembered that my old Mediatek devices also had the `boot-debug.img` variant in the factory image, which contained an "insecure" adbd that'll give you a root shell from adb. From what I remember, the "insecure" adbd was useful for some tools to inject a custom recovery for the device so you can flash other stuffs from there.

Unfortunately my experience with Mediatek devices was only around JB/KitKat, and it was before I get to know Magisk. Back then CWM's Superuser was my favorite tool for root.

Well, back to the topic... I don't think using a boot-debug.img should have any issue with Magisk. It should be the same, just without certain "protections" set in place on normal boot images.

**Comment by mrmazakblu** [comment] 2020-09-08 11:45
Well I was thinking more along the lines using the debug-boot feature of Android 10 as the main root entry point. 

As described on this Google developers white page, root is simply given when you set debug prop, and add your own plat_sepolicy.cil


https://source.android.com/compatibility/vts/vts-on-gsi

**Comment by lss4** [comment] 2020-09-09 02:42
Have you tried 20407 canary? Does it work for you?

Currently I need to know whether we're having the same issue to further assess the impact of the regression. I've already found which specific commit broke mine (see my issue).

**Comment by mrmazakblu** [comment] 2020-09-09 10:17
I have not been able to download that version.

I can open the commit for it, I can see the files. 
But when I add the address to that commit (from the .jason file) to magisk manager custom update chanel, the version 20407 shows, but when I try to patch, it always gives me download error. 

I have tried each release from 17 upwards. And they all fail to give root.
I can only assume we have different issue

**Comment by osm0sis** [comment] 2020-09-09 11:51
You can't use it as an update channel since it's always the same address in the .json, you need to download the APK yourself and then use the "Install from storage" feature in the Modules page.

**Comment by mrmazakblu** [comment] 2020-09-11 12:00
I was following along with issue #3021 

I checked my /proc/cmdline

My phone does have androidboot.hardware=mt6765

But I also see , what I thought strange. Maybe it's normal

Root=/dev/ram



Also , might not matter, but in stock boot ramdisk there are 2 fstab files.

**Comment by osm0sis** [comment] 2020-10-04 15:30
Probably same as this: #3228

If so, might follow along there since this issue thread has become pretty convoluted.

**Comment by mrmazakblu** [comment] 2020-10-04 20:23
Confirmed still same , MAGISK init not running with majisk 21 and manager 8
ON two of my phones now. 
the one i stated with BLU G90
now ULEFONE Note 9P

**Comment by Crescendo-BLYAT** [comment] 2020-10-26 16:53
Guys, Magisk 20.3 is working perfectly on my MTK Redmi Note 8 Pro - MIUI 12 Global - Android 10.

Any version greater than that will cause random SIM unrecognized problem on simple reboot + bluetooth MAC to be defaulted to 00:00:46:00:00:01 (the BT_Addr file in nvdata folder is corrupted, needs TWRP restore to fix).

6 out of 10 reboot will throw the device with no SIM problem (airplane mode doesn't help) + bluetooth MAC become 00:00:46:00:00:01.

**Comment by p3yot3** [comment] 2020-10-26 17:02
Just a FYI, I've also been unable to get Magisk working on my MTK device - it's a Ulefone Armor 9. The previous release of Magisk worked fine on my older Armor 3 & I was able to update to the latest Magisk version after flashing, but I'm unable to do that with my Armor 9 for some reason.

**Comment by Crescendo-BLYAT** [comment] 2020-11-18 05:18
> I think I might take a look at what happened between 20407 ([2aede97](https://github.com/topjohnwu/Magisk/commit/2aede97754fec67d393bde0c7725ed84d8c3c112)) and 20408 ([87de0e7](https://github.com/topjohnwu/Magisk/commit/87de0e7a0e13bcbbc2491b158149c8dea3f77937)) and look for a possible cause...
> 
> Is there a guide for testing specific commits? I'm still new to `git bisect`...
> 
> ~EDIT: It seems I need some more details regarding build environment. Attempted `./build.py all` at a commit in between ([8ab0453](https://github.com/topjohnwu/Magisk/commit/8ab045331bf0055ef92a8ca4e26c66bf2108724f)), set by `git bisect`, failed with these errors...~
> 
> ~This is on latest Manjaro Linux, currently using GCC10. I have latest Android Studio installed from AUR, pointed the terminal environment to use bundled JRE, and have successfully run `./build.py ndk`.~
> 
> ~I don't know if this commit compiles, but I need to make sure my build environment is correct first. By the way, I'm not sure if I should use `--recurse-submodules` when cloning the repo for bisecting...~
> 
> EDIT 2: Guess I need to use `git submodule update`. After doing that, `./build.py all` finished without issues.

CONFIRMED that the last bootable on my Redmi Note 8 Pro - Android 10 is 20407 ([2aede97](https://github.com/topjohnwu/Magisk/commit/2aede97754fec67d393bde0c7725ed84d8c3c112)).

**Comment by vvb2060** [comment] 2020-11-18 07:23
try
https://raw.githubusercontent.com/vvb2060/magisk_files/master/mtk.json

**Comment by kidonng** [comment] 2020-11-18 08:25
@vvb2060 Didn't work on Redmi Note 8 Pro.

**Comment by vvb2060** [comment] 2020-11-18 08:39
@kidonng https://raw.githubusercontent.com/vvb2060/magisk_files/7098b4acd0978d79e283ea2ccb1510593418acea/mtk.json

**Comment by lss4** [comment] 2020-11-18 09:22
> > I think I might take a look at what happened between 20407 ([2aede97](https://github.com/topjohnwu/Magisk/commit/2aede97754fec67d393bde0c7725ed84d8c3c112)) and 20408 ([87de0e7](https://github.com/topjohnwu/Magisk/commit/87de0e7a0e13bcbbc2491b158149c8dea3f77937)) and look for a possible cause...
> > Is there a guide for testing specific commits? I'm still new to `git bisect`...
> 
> CONFIRMED that the last working on my Redmi Note 8 Pro - Android 10 is 20407 ([2aede97](https://github.com/topjohnwu/Magisk/commit/2aede97754fec67d393bde0c7725ed84d8c3c112)).
> 
> Higher than that will fail to load Magisk. Magisk isn't loaded at all.

If that's the case (up to 20407 worked) you probably have the same issue as I did (#3021), although mine was not a MTK device.

Try doing a `cat /proc/cmdline` and see if your device's boot parameter has `androidboot.hardware=<device>` in it. From 20408 and onwards that boot parameter is mandatory for a proper Magisk installation, assuming your device's `fstab`, wherever it is, has a correct name format that would be `fstab.<device>`.

**Comment by kidonng** [comment] 2020-11-18 12:40
> @kidonng https://raw.githubusercontent.com/vvb2060/magisk_files/7098b4acd0978d79e283ea2ccb1510593418acea/mtk.json

It works! But one of my apps (FooView) reports the following error:

 > Root testing failed, please upgrade your SU or change SELinux to permissive mode

Anyway thanks for the effort.

**Comment by Crescendo-BLYAT** [comment] 2020-11-19 02:55
> If that's the case (up to 20407 worked for you) you probably have the same issue as I did (#3021), although mine was not a MTK device.
> 
> Try doing a `cat /proc/cmdline` and see if your device's boot parameter has `androidboot.hardware=<device>` in it. From 20408 and onwards that boot parameter is mandatory for a proper Magisk installation, assuming your device's `fstab`, wherever it is, has a correct name format that would be `fstab.<device>`.

Yes, same issue as #3021 except the latest Magisk Manager working normally sans the superuser prompt like your problem.

Also there's no `androidboot.hardware=<device>`. 
But the SIM missing & bluetooth MAC problems I encountered with 20400 is gone in this release 20407.
I'll try older than 20407 & see about the prompt.

Anyway to manually add the `androidboot.hardware=<device>` in cmdline?

**Comment by lss4** [comment] 2020-11-19 03:07
> > If that's the case (up to 20407 worked for you) you probably have the same issue as I did (#3021), although mine was not a MTK device.
> > Try doing a `cat /proc/cmdline` and see if your device's boot parameter has `androidboot.hardware=<device>` in it. From 20408 and onwards that boot parameter is mandatory for a proper Magisk installation, assuming your device's `fstab`, wherever it is, has a correct name format that would be `fstab.<device>`.
> 
> Yes, same issue as #3021 except the latest Magisk Manager working normally sans the superuser prompt like your problem.
> 
> Also there's no `androidboot.hardware=<device>`.
> But the SIM missing & bluetooth MAC problems I encountered with 20400 is gone in this release 20407.
> I'll try older than 20407 & see about the prompt.
> 
> Anyway to manually add the `androidboot.hardware=<device>` in cmdline?

Sadly I don't know of a good way without rebuilding the kernel... my issue was fixed after the developer built a new kernel with the parameter included.

**Comment by Crescendo-BLYAT** [comment] 2020-11-19 03:34
Magisk 20402 til 20406 can't be flashed with error: Unsupported/Unknown image format.
However 20401 & 20407 is OK with superuser prompt broken.

**Comment by Crescendo-BLYAT** [comment] 2020-11-22 05:52
> @kidonng https://raw.githubusercontent.com/vvb2060/magisk_files/7098b4acd0978d79e283ea2ccb1510593418acea/mtk.json

WORKING PERFECTLY on Redmi Note 8 Pro - MIUI 12.0.2.0 - Android 10.
Thanks a lot!!!

What did you do? Maybe you can initiate PR to main repo? @topjohnwu

**Comment by Crescendo-BLYAT** [comment] 2020-11-22 06:00
Oops celebrate too soon... 
Although it's working, I can't access internal storage whatsoever.
/storage/emulated is not present, only /storage/self is present.

Apart from that, it's working. Su is working as well.

**Comment by Crescendo-BLYAT** [comment] 2020-11-28 14:46
@vvb2060 https://github.com/vvb2060/magisk_files/commit/0c59f81390b0967e8b42a37add369bf73fd5db69 BOOT & WORKING!
Internal Storage also available. 
I will test it further but initial test is ALL OK!
KUDOS TO YOU!

Do you still need the Magisk log?

**Comment by Crescendo-BLYAT** [comment] 2020-11-29 03:41
Confirmed: ALL OK!
Only some modules need a reinstall like: ACC & EdXposed.
The rest is ALL OK!

THANK YOU SO MUCH! @vvb2060

**Comment by Crescendo-BLYAT** [comment] 2020-12-01 07:52
One failed boot but nothing's changed...
It just boot to recovery out of blue then I reboot it to system & it boot just OK.
Here's the log: https://pastebin.com/YhCfMCiK

**Comment by londbell** [comment] 2020-12-04 07:35
> try
> https://raw.githubusercontent.com/vvb2060/magisk_files/master/mtk.json

It works.Thank you.

**Comment by ivisible** [comment] 2020-12-08 18:17
> try
> https://raw.githubusercontent.com/vvb2060/magisk_files/master/mtk.json

it work for blu g90 mt6762
g0310ww
android 10
Ab no
Sar yes
Ramdisk yes

![Screenshot_20201208-112602](https://user-images.githubusercontent.com/75693404/101524193-9fbf8980-3957-11eb-83f5-ed04aeb6400a.png)

**Comment by mrmazakblu** [comment] 2020-12-08 21:56
> > try
> > https://raw.githubusercontent.com/vvb2060/magisk_files/master/mtk.json
> 
> it work for blu g90 mt6762
> g0310ww
> android 10
> Ab no
> Sar yes
> Ramdisk yes

That is same device I have, and the one I opened this original issue with
 Need to confirm on my device too. Thanks for mentioning it

**Comment by mrmazakblu** [comment] 2020-12-09 22:59
@topjohnwu do you have some way to see what changes @vvb2060  made to his released magisk that allows it to work.

Yes I am confirming that I now see root permission on my mtk device, but using custom update chanel that @vvb2060  shared in this issue thread.

**Comment by mrmazakblu** [comment] 2020-12-11 23:33
Using the update channel from @vvb2060  , I cannot get pass safety-net. 
Gives "asertattion failed", with and without hide-props


![IMG_20201211_175405_662](https://user-images.githubusercontent.com/23422338/101964403-3e115080-3bdf-11eb-90e2-86926bb71dfb.jpg)
![IMG_20201211_183019_338](https://user-images.githubusercontent.com/23422338/101964415-46698b80-3bdf-11eb-99ce-e8ff0024b446.jpg)

**Comment by Crescendo-BLYAT** [comment] 2020-12-12 11:00
for now, having updated Magisk run fine in this MTK is Godsend, so let's focus on the usability first than SafetyNet issue...

**Comment by Crescendo-BLYAT** [comment] 2020-12-12 11:02
@vvb2060 could you please update your Magisk with this patch https://github.com/topjohnwu/Magisk/commit/0064b01ae03b2f0dfff9f858e91df0c24a468dcd ?
It helps with the latest EdXposed & Riru sepolicy problem.

**Comment by Crescendo-BLYAT** [comment] 2020-12-12 12:46
> @topjohnwu do you have some way to see what changes @vvb2060 made to his released magisk that allows it to work.
> 
> Yes I am confirming that I now see root permission on my mtk device, by using custom update chanel that @vvb2060 shared in this issue thread.
> 
> During install , magisk manager showed magisk version 21.1.
> The official 21.1 did not work though.

I think this one, correct me if I'm wrong...
https://github.com/vvb2060/Magisk/commit/1e0f96d0fdd7ada50859de743eabb9779cc7b29c

**Comment by mrmazakblu** [comment] 2020-12-13 11:40
More confused information.

I had the aabe2696(21101) version of magisk installed, and phone is rooted with it
 
I changed update chanel back to beta, I stead of vvn2060's chanel. Allowed a live update from manager. 
The log showed successful flashing to the detected magisk patched boot
 Did a reboot and only to find that manager still shows the old version as installed.

**Comment by Crescendo-BLYAT** [comment] 2020-12-14 01:49
@mrmazakblu then there's this commit: https://github.com/vvb2060/magisk_files/commit/38abb9eda106ea4207bea564107e7188cd602748
which is way more updated than MTK version, in the same repo by @vvb2060.

I'm confused of the purpose of those lite version.

**Comment by Crescendo-BLYAT** [comment] 2020-12-17 16:51
OK latest alpha branch from @vvb2060 fixed everything...

**Closed** 2020-12-31 14:30 UTC
Labels: needs investigation

**Comment by vvb2060** [comment] 2020-12-31 14:33
Fixed
