### ISSUE TITLE
Android Device Monitor只顯示設備名，不顯示進程。

### ISSUE THREAD

**Issue by xmhwws** [topjohnwu/Magisk#1748] opened 2019-08-06 09:01 UTC
開啟官方root後，檢測發現ro.debuggable=1。

（monitor.bat是Android Device Monitor，簡稱DDMS）
此時，打開monitor.bat調試apk，monitor.bat既顯示設備名，也顯示進程。
![1](https://user-images.githubusercontent.com/42903751/62526029-0405a100-b86b-11e9-8a6a-5554900c948f.png)

但在我安裝了magisk後，monitor.bat只顯示設備名，不顯示進程。
![2](https://user-images.githubusercontent.com/42903751/62526068-1aabf800-b86b-11e9-8382-a80e1a560cc0.png)

我卸載magisk後，monitor.bat又開始既顯示設備名，也顯示進程。
測試了紅米Note5和谷歌nexus5這兩個手機，情況是壹樣的。
這應該是壹個bug？請問，有解決方法嗎？

**Comment by Didgeridoohan** [comment] 2019-08-06 12:01
This is not a bug, and nothing that needs it's own issue opened. You can close it...

Your problem is likely that MagiskHide, by design, changes ro.debuggsble to 0.

**Comment by xmhwws** [comment] 2019-08-06 16:16
I'm sorry, but I'm not quite sure what you mean.
Please help me check the setting of apk. Did I make any mistake?
![4](https://user-images.githubusercontent.com/42903751/62556946-8eb8c100-b8a8-11e9-9aa2-e0d7b59046ae.png)
![3](https://user-images.githubusercontent.com/42903751/62556948-90828480-b8a8-11e9-8d47-52c7a1bdda16.png)
![5](https://user-images.githubusercontent.com/42903751/62556663-f3bfe700-b8a7-11e9-8fb4-db9970da0749.png)

**Comment by xmhwws** [comment] 2019-08-06 16:31
I'm sorry, you're right.
I forgot to change the Settings for magisk. It doesn't take effect until the phone is restarted.
![6](https://user-images.githubusercontent.com/42903751/62557819-4ef2d900-b8aa-11e9-9c8f-3fa33a5b51a9.png)
Is there any way to make the ro.debuggable value equal to 1 without turning off magisk hide?

**Comment by topjohnwu** [comment] 2019-08-06 16:35
MagiskHide 就是為了避免偵測才會隱藏那些 prop
想要那些 prop 的話，就只能把 magiskhide 關掉
魚與熊掌不可兼得

**Closed by topjohnwu** 2019-08-06 16:35 UTC
