### ISSUE TITLE
[Samsung Galaxy A50] Random reboots when using phone in Magisk Recovery Mode.

### ISSUE THREAD

**Issue by Thiago4532** [topjohnwu/Magisk#2640] opened 2020-04-01 10:30 UTC
I rooted my cellphone using only Magisk (Samsung Galaxy A50 SM-A505GT) but everytime I reboot the cellphone in Magisk mode the cellphone randomly reboots. Maybe it's related with [this](https://forum.xda-developers.com/galaxy-s10/how-to/random-reboot-fix-snapdragon-sm-g9750-t3953300) but I don't know  how I can fix this. Which logs I need to send to you? I am using Android Pie.

**Comment by osm0sis** [comment] 2020-04-02 01:49
A last_kmsg or console-ramoops directly after booting up following one of these reboots.

magisk.log.bak (i.e. the one from the previous boot) might be useful too.

**Comment by osm0sis** [comment] 2020-04-06 03:00
@Thiago4532 if you don't offer anything further we'll be forced to close this issue from a lack of information. :slightly_frowning_face:

**Comment by Thiago4532** [comment] 2020-04-06 03:51
Sorry I forgot. Apparently it was the same problem as the Galaxy S10, when I was trying to run this command:   
`su  
dd   if=/data/media/0/AP_G9750ZHU1ASF1_CL16082828_QB24224470_REV00_user_low_ship_MULTI_CERT_meta_OS9.tar.md5 of=/dev/shm
cat /proc/*/smaps_rollup`
the smartphone crashes. This problem only exists in the lasts Magisk versions. I am unable to send logs 'cause I solved the issue downgrading Magisk from v20.4 to  v19.3, everything is working fine now and I'm going to wait Android 10 to update Magisk again.

**Comment by Thiago4532** [comment] 2020-04-06 03:53
Sorry I forgot. Apparently it was the same problem as the Galaxy S10, when I was trying to run this command:
`su dd if=/dev/random of=/dev/shm`  
`cat /proc/*/smaps_rollup`
the smartphone crashes. This problem only exists in the lasts Magisk versions. I am unable to send logs 'cause I solved the issue downgrading Magisk from v20.4 to v19.3, everything is working fine now and I'm going to wait Android 10 to update Magisk again.

**Comment by Thiago4532** [comment] 2020-04-06 06:36
Ok. I updated to Android 10 and updated Magisk to v20.4 and the crash returns. I am going to post the log.

**Comment by Thiago4532** [comment] 2020-04-06 06:47
[last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/4436225/last_kmsg.txt)
[console-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/4436226/console-ramoops-0.txt)

Samsung Galaxy A50 - Android 10 - Magisk v20.4
I get these logs after forcing a crash running the above cat command.
Running the cat command with Magisk v19.3 and Android 9 didn't crash the phone.

**Comment by Thiago4532** [comment] 2020-04-11 07:01
It's possible to use Magisk v19.3 in Android 10?

**Comment by osm0sis** [comment] 2020-04-11 09:09
Not recommended. Is 19.3 the last version that works for you?

**Comment by Nitorac** [comment] 2020-04-12 14:06
@Thiago4532 I just tried but Magisk v19.3 with Android 10 results in a bootloop :(

**Comment by osm0sis** [comment] 2020-04-12 14:22
@Nitorac, do you have the same device as Thiago? If not, this is not your issue, so please do not hijack it.

**Comment by Nitorac** [comment] 2020-04-12 14:44
@osm0sis Sorry, I didn't explained my case :
I own a A50 too (SM-A505FN) and I was also on Magisk v19.3 with Android 9 and all was working fine. 
I can report that this issue occurs from at least Magisk v20.0 (at each stable release from Magisk v20.0 included, I tried to see if the issue was resolved but it wasn't, it always ended up in bootloops caused by a kernel panic and no logcats).

So i answered to Thiago because he was asking if it was possible to use Magisk v19.3 on Android 10. I just tried but I was stuck in a bootloop).

**Comment by osm0sis** [comment] 2020-04-12 15:20
Can you try with the latest Canary just so we're certain?

**Comment by Nitorac** [comment] 2020-04-12 15:48
I can confirm that the issue happen on Magisk Canary (Debug) version (ef9d077c (20401)).
Here are the logs
[console-ramoops-0.log](https://github.com/topjohnwu/Magisk/files/4466597/console-ramoops-0.log)
[last_kmsg.log](https://github.com/topjohnwu/Magisk/files/4466599/last_kmsg.log).

It crashes with a kernel panic when executing the command `cat /proc/*/smaps_rollup` after filled up only ~100 KB in /dev/shm with : `dd if=/dev/random of=/dev/shm`

**Comment by johnjutsu** [comment] 2020-04-17 15:38
I have also seen this issue.  Have had stability with v19.3, but not the newer versions.  I recently rebuilt the A50 kernel with the patch for the S10 problem @Thiago4532 mentioned, and now the newer Magisk version is stable as well (2 days now).  So seems to definitely be related to that issue.

Link to kernel bug: https://bugzilla.kernel.org/show_bug.cgi?id=201377

Hope that helps.

**Comment by Thiago4532** [comment] 2020-04-17 16:15
Where did you find the S10 patch?

**Comment by johnjutsu** [comment] 2020-04-17 16:45
@Thiago4532 From this thread: https://forum.xda-developers.com/galaxy-s10/help/s10-random-reboot-kernel-panic-t3952078
It is a kernel source patch, not a binary patch.

**Comment by Thiago4532** [comment] 2020-04-17 17:08
@johnjutsu I need to rebuild the kernel with the new source code?

**Comment by johnjutsu** [comment] 2020-04-17 17:27
Just to be clear, I did not test this on Android 10, just Pie.  So, if you want to follow the process for Android 10, I can't say it'll work for sure.

I grabbed the kernel source from Samsung Open Source web site and built from there, then re-built the boot.img and recovery.img to be patched by Magisk.

**Comment by Nitorac** [comment] 2020-04-17 17:29
I'm trying to rebuild the kernel from the latest Open Source Samsung, and I will see if it works on the Android 10 ROM

**Comment by johnjutsu** [comment] 2020-04-17 17:50
@Nitorac You can try A505FDDU4BTC4.  There's a good chance the kernel is the same between the two.  You could download both ROMs to compare if you wanted.

**Comment by Nitorac** [comment] 2020-04-18 09:52
It doesn't seems to work with A505FDDU4BTC4 on the A505FN :( (or I made a mistake x) )

**Comment by topjohnwu** [comment] 2020-04-23 11:35
Sounds like an Samsung kernel bug, not related to Magisk

**Closed by topjohnwu** 2020-04-23 11:35 UTC
Labels: bug

**Comment by Thiago4532** [comment] 2020-04-29 21:19
> Sounds like an Samsung kernel bug, not related to Magisk

But why Magisk v19.3 works perfectly?

**Comment by pvtai** [comment] 2021-03-17 16:09
> > Sounds like an Samsung kernel bug, not related to Magisk
> 
> But why Magisk v19.3 works perfectly?

Hi @Thiago4532 
Are you still using the A50? How much magisk version are you using and is it stable?
Thank you,
