### ISSUE TITLE
Magisk app freezes when rooted on OOS10+OOS11 devices after commit 3938322

### ISSUE THREAD

**Issue by humbleoxygen12** [topjohnwu/Magisk#7214] opened 2023-08-07 14:58 UTC
Device: OnePlus 8T
Android version: 11
Magisk version name: canary
Magisk version code: 26105

Magisk Manager freezes at mask interface after upgrading to 26105. Everything works fine in 26104. Tried both masked and unmasked 26105 version, the problem still exists.

[Logcat](https://github.com/topjohnwu/Magisk/files/12281459/1.txt)

Dev Edit: The regression starts with commit https://github.com/topjohnwu/Magisk/commit/39383229d1f6f860a125ad72264528bd4e1a9835

**Comment by dobi3** [comment] 2023-08-08 09:43
Same here.. 26104 is fine
Oneplus 7 Pro Android 11

**Comment by SEAL300** [comment] 2023-08-08 13:08
Same here OnePlus 6 android 11

**Comment by MT-ZJ** [comment] 2023-08-10 16:00
same here in oneplus8pro android11

**Comment by digiw** [comment] 2023-08-11 08:15
Same here OnePlus 5t android 10

**Comment by digiw** [comment] 2023-08-11 16:29
> Hide the Magisk app
For example, I, yes, used the Hide the Magisk app to convert magisk to a different package name before upgrading to the new version

**Comment by humbleoxygen12** [comment] 2023-08-11 16:46
> By "mask interface" do you mean "Hide the Magisk app" dialog (as suggested by you saying "masked and unmasked" version), or just the Magisk mask logo splash screen?
I means the Magisk mask logo splash screen

**Comment by osm0sis** [comment] 2023-08-11 16:54
> > By "mask interface" do you mean "Hide the Magisk app" dialog (as suggested by you saying "masked and unmasked" version), or just the Magisk mask logo splash screen?
> 
> I mean the Magisk mask logo splash screen. I'm using stock Oxygen OS 11.

A little confused here, you're using OOS11 when more up-to-date options like OOS13.1 and LOS20 are available for your device?

**Comment by humbleoxygen12** [comment] 2023-08-11 16:59
> A little confused here, you're using OOS11 when more up-to-date options like OOS13.1 and LOS20 are available for your device?

New OOS switched to OOS13, while non stock rom have issues about auto brightness, 🤷

**Comment by osm0sis** [comment] 2023-08-11 18:08
I downgraded my OP5T to last OOS (Android 10) and can confirm the 26105 hang at the Magisk app splash screen, where 26104 works, and that it occurs when updating from both hidden and unhidden app.

**Comment by hazart29** [comment] 2023-08-14 09:20
I got issue, my mbanking app detected root, i hv been hide the magisk delta app

**Comment by nguyenhoangphuc121** [comment] 2023-08-15 14:11
canary version has bug tho

**Comment by pndwal** [comment] 2023-08-20 12:43
I'm don't know if testers here have tried with or without Universal SafetyNet Fix module builds installed, but it looks like this issue may be related:

**Comment by humbleoxygen12** [comment] 2023-08-20 12:58
> I'm don't know if testers here have tried with or without Universal SafetyNet Fix module builds installed, but it looks like this issue may be related:
> https://github.com/Displax/safetynet-fix/issues/29
> 
> User says stability is restored after disabling module.

Thanks for your comment, but the issue here only related to Magisk Manager itself

**Comment by osm0sis** [comment] 2023-08-20 12:59
Yeah, my test setup was literally only the ROM and Magisk.

**Comment by athanatos1** [comment] 2023-08-20 13:25
I also confirm the magisk manager apk app freezes on a fresh rom install oneplus pro 9, oos a11.

**Comment by pndwal** [comment] 2023-08-20 13:37
> Yeah, my 5T test setup was literally only the OOS ROM and Magisk.

Thanks for confirming... Seems the USNF issue may be related to this one then, rather than vice versa... Or not... 🤪

**Comment by osm0sis** [comment] 2023-08-20 14:19
> I also confirm the magisk manager apk app freezes on a fresh rom install oneplus pro 9, oos a11. If you don't flash the boot.img, the apk opens. If you flash 26105, the apk freezes and will not open.

Ah that's useful info I bet, the app only freezes if rooted.

**Comment by DyeHardZ** [comment] 2023-08-25 05:59
same here oneplus 7T android 11

**Comment by osm0sis** [comment] 2023-08-25 11:52
No need to chime in with further devices, the common denominator is clearly OOS10 and OOS11. 👍

**Comment by athanatos1** [comment] 2023-08-28 21:04
Latest version 26.2 also results in a frozen magisk.apk manager. Oneplus pro9, A11.

**Comment by athanatos1** [comment] 2023-08-28 21:45
[debug.log](https://github.com/topjohnwu/Magisk/files/12458433/debug.log)
I attached a debug log from the official debug version of magisk for the freezing problem. There is a lot of OS information here on my one plus device, hopefully something can be fixed. 

Please tell me guys whats the problem logcat command to log magisk related activity only or other helpful logcat commands, thanks!

**Comment by xerta555** [comment] 2023-08-29 12:40
Latest beta (26.2) freeze on app logo for me too on my OnePlus Nord N10 5G (A10).
I test it last night (app freeze), i just downgrade the app to 26.1

Today i did the test again, i recorded the logcat:
[Log_2023-08-29_14-33-52.txt](https://github.com/topjohnwu/Magisk/files/12464544/Log_2023-08-29_14-33-52.txt)

**Comment by xerta555** [comment] 2023-08-29 12:53
> Try magisk build from this CI: [topjohnwu/Magisk/actions/runs/5617639740](https://github.com/topjohnwu/Magisk/actions/runs/5617639740)
> 
> I think it is related to libsu 5.2.0 update.

Where is the zip/apk file ?

**Comment by osm0sis** [comment] 2023-08-29 15:29
> > Try magisk build from this CI: [topjohnwu/Magisk/actions/runs/5617639740](https://github.com/topjohnwu/Magisk/actions/runs/5617639740)
> > I think it is related to libsu 5.2.0 update.
> 
> Where is the zip/apk file ?

In the artifacts .zip, extract and try the debug.apk

**Comment by xerta555** [comment] 2023-08-29 15:34
> > > Try magisk build from this CI: [topjohnwu/Magisk/actions/runs/5617639740](https://github.com/topjohnwu/Magisk/actions/runs/5617639740)
> > > I think it is related to libsu 5.2.0 update.
> > 
> > 
> > Where is the zip/apk file ?
> 
> In the artifacts .zip, extract and try the debug.apk

I just install the debug.apk file and i can't even open itself, i don't have the Magisk logo.
Logfile: [Log_2023-08-29_17-32-47.txt](https://github.com/topjohnwu/Magisk/files/12466375/Log_2023-08-29_17-32-47.txt)

**Comment by osm0sis** [comment] 2023-08-29 15:40
I'll try too when I get home, but that's the commit directly after 26104 was released, so pretty definitely the problem.

**Comment by osm0sis** [comment] 2023-08-30 00:43
Can confirm that https://github.com/topjohnwu/Magisk/commit/39383229d1f6f860a125ad72264528bd4e1a9835 is the breaking commit.

**Comment by canyie** [comment] 2023-08-31 17:09
Try this build? https://github.com/canyie/Magisk/actions/runs/6040156771

**Comment by kiaroa** [comment] 2023-08-31 17:27
> Try this build? https://github.com/canyie/Magisk/actions/runs/6040156771

Flashed stock unpatched boot.
Installed the debug APK, patched the boot file, flashed patched boot file. 
On restart the stub MM is present, but the download doesn't complete. Installing the debug apk manually gives the same hang on the mask splash as before.

Oneplus 7 Pro , Android 11.

**Comment by canyie** [comment] 2023-08-31 17:29
Attach a logcat when it hangs?

**Comment by xerta555** [comment] 2023-08-31 17:42
> Try this build? [canyie/Magisk/actions/runs/6040156771](https://github.com/canyie/Magisk/actions/runs/6040156771)

Hang on Magisk logo
Logcat: [Log_2023-08-31_19-41-18.txt](https://github.com/topjohnwu/Magisk/files/12488865/Log_2023-08-31_19-41-18.txt)

**Comment by canyie** [comment] 2023-09-01 00:44
Thanks for help, I located the problem. A fix is coming soon

**Comment by macerg** [comment] 2023-09-02 06:59
Same here on OnePlus 6 Android 11. App freezes on start.

**Comment by xerta555** [comment] 2023-09-02 15:39
The Manager freeze again with the new `26203` canary
Logcat: [Log_2023-9-02_17-37-19.txt](https://github.com/topjohnwu/Magisk/files/12504255/Log_2023-9-02_17-37-19.txt)

**Comment by osm0sis** [comment] 2023-09-02 20:28
Yep, no fixes to close this have been merged yet.

**Comment by xerta555** [comment] 2023-09-02 20:31
> Yep, no fixes to close this have been merged yet.

Oh, you're right to tell me, I thought the opposite 👍🏻

**Comment by canyie** [comment] 2023-09-04 07:12
Should be fixed by https://github.com/topjohnwu/libsu/commit/69652a9f7b2b0d53f5af592123040cef198831e6 and 1e034e3.
Please try Magisk v26.3.

**Closed by canyie** 2023-09-04 07:12 UTC
Labels: regression, confirmed, APP

**Comment by kiaroa** [comment] 2023-09-04 09:44
Fixed, confirmed.

**Comment by digiw** [comment] 2023-09-04 09:56
> Should be fixed by [topjohnwu/libsu@69652a9](https://github.com/topjohnwu/libsu/commit/69652a9f7b2b0d53f5af592123040cef198831e6) and [1e034e3](https://github.com/topjohnwu/Magisk/commit/1e034e3e0e4aaf8716d77746faf5781e5af8e12e). Please try Magisk v26.3.

Thanks！！

**Comment by xerta555** [comment] 2023-09-04 11:18
I confirm: the last canary works successfull now.

**Comment by athanatos1** [comment] 2023-09-04 14:43
Thank you, working great on oneplus devices again!

**Comment by xerta555** [comment] 2023-10-12 21:48
Hi, it's just me or a similar bug occurs from any version >26.1 ?
I just test all stable/beta/canary/debug version >26.1, and after seconds during device start, my homescreen appear, and arround 4-5 seconds after, my device just reboot in recovery mode.

I have to flash again Magisk v26.1 as zip file to be able to boot again propeply, install again v26.1 apk and flash again the v26.1 version with direct install method.

Anyone have the same issue ? Is it related to the first issue of this thread ?

I know I don't have a logcat to publish here, i don't currently have a workstation on which to connect my device in adb to retrieve a log file.

Thanks.

**Comment by xerta555** [comment] 2023-10-14 15:48
> After the above mentioned issue was fixed Magisk v26.3 works good for me on the latest OOS11. You didn't specify what OOS version you're using. Mybe one of the magisk modules results in this benaviour in your case?

I'm running stock OOS10.
There have been no new modules whatsoever on my device since the initial bug mentioned in this thread.

**Comment by pndwal** [comment] 2023-10-15 01:44
> > Hi, it's just me or a similar bug occurs from any version >26.1 ?
> > Since the publication of the second canary version following the publication of version v26.3, i have had the following problem
> > I just test all stable/beta/canary/debug version >26.1, and after seconds during device start, my homescreen appear, and arround 4-5 seconds after, my device just reboot in recovery mode...

Please say device... Is it A only, legacy SAR? (Ie. launched with Android 9, A only)...

**Comment by xerta555** [comment] 2023-10-15 11:45
> Please say if you erroneously see Recovery Mode option in Magisk Install menu on your device...

What do you want to say ? I'm afraid I don't understand

**Comment by pndwal** [comment] 2023-10-15 13:34
> > Please say if you erroneously see Recovery Mode option in Magisk Install menu on your device...
> 
> What do you want to say ? I'm afraid I don't understand

Probably doesn't apply (as launch version was A10.and probably an A/B device)... Some devices were being misidentified as L-SAR A only (Ramdisk=No) devices and users would see Recovery Mode (checked) in Magisk Install menu... If left checked /recovery partition would be patched with direct updates, also reboot would boot to recovery... Fix was applied so latest 26.3 at least should no show that option for your device...

**Comment by xerta555** [comment] 2023-10-15 14:09
> > > Please say if you erroneously see Recovery Mode option in Magisk Install menu on your device...
> > 
> > 
> > What do you want to say ? I'm afraid I don't understand
> 
> Probably doesn't apply (as launch version was A10.and probably an A/B device)... Some devices were being misidentified as L-SAR A only (Ramdisk=No) devices and users would see Recovery Mode (checked) in Magisk Install menu... If left checked /recovery partition would be patched with direct updates, also reboot would boot to recovery... Fix was applied so latest 26.3 at least should no show that option for your device...

I was talking about recovery mode, because something crashed everything on my device until it restarted in recovery mode.
Once in recovery mode, it says that there is no system installed.

But I'm pretty sure the problem is with Magisk, but I don't know what

**Comment by pndwal** [comment] 2023-10-16 07:47
mmm.

> I was talking about recovery mode, because something crashed everything on my device until it restarted in recovery mode. Once in recovery mode, it says that there is no system installed.

Just FYI, Recovery mode Magisk I referred to is not simply booting to recovery mode... It's Magisk installed in /recovery partition instead of/boot... Until 1st gen SAR ('Legacy SAR' boot type) A only devices (circa 2018, 2019) Boot mode Magisk always worked fine, but now we had devices without ramdisk in /boot (Ramdisk=No) or bootloader support for the same... Only way to have Magisk was to add Recovery mode option and patch /recovery partition which always includes a generic ramdisk to accommodate magiskinit. (Nb. /boot is not patched at all, and one must boot via recovery using special key combo to arrive at system with Magisk instead of recovery OS.)... All modern devices (like original 'Legacy ramdisk' boot type) launched with Android 10+ are '2SI ramdisk SAR' boot type and once again always support ramdisk/initramfs in /boot partition, ie. Boot mode Magisk...

That's why you shouldn't/don't see Recovery mode option for your device... (The device misidentification regression is also fixed in 26.3.)

> But I'm pretty sure the problem is with Magisk, but I don't know what
> 
> EDIT: I had opened a new thread earlier but it was closed without explanation #7425

Well looks like LoveSy has explained why it was closed... She cited line 27 of issue template for you:
>  **DO NOT** report issues if you have any modules installed

> EDIT: Problem fixed, was due to a specific Magisk module.

Great!... But that's exactly why that rule exists... The first this users should do is try after disabling/uninstalling modules... Others hours or developer hours would be wasted... 😜

Tip: Only supply logs using Debug Magisk and uninstall all modules, otherwise devs will see release build/modules in logs and just close issue.. Often the won't bother to explain why but did for you.

**Comment by xerta555** [comment] 2023-10-16 10:37
> Just FYI, Recovery mode Magisk I referred to is not simply booting to recovery mode... It's Magisk installed in /recovery partition instead of/boot... Until 1st gen SAR ('Legacy SAR' boot type) A only devices (circa 2018, 2019) Boot mode Magisk always worked fine, but now we had devices without ramdisk in /boot (Ramdisk=No) or bootloader support for the same... Only way to have Magisk was to add Recovery mode option and patch /recovery partition which always includes a generic ramdisk to accommodate magiskinit. (Nb. /boot is not patched at all, and one must boot via recovery using special key combo to arrive at system with Magisk instead of recovery OS.)... All modern devices (like original 'Legacy ramdisk' boot type) launched with Android 10+ are '2SI ramdisk SAR' boot type and once again always support ramdisk/initramfs in /boot partition, ie. Boot mode Magisk...

Ah ok thx for infos.

> Great!... But that's exactly why that rule exists... The first this users should do is try after disabling/uninstalling modules... Others hours or developer hours would be wasted... 😜
> Tip: Only supply logs using Debug Magisk and uninstall all modules, otherwise devs will see release build/modules in logs and just close issue.. Often the won't bother to explain why but did for you.

I do have a tendency to be a bit flaky at times :P
