### ISSUE TITLE
Magisk Hide not working with Google Pay

### ISSUE THREAD

**Issue by keyute** [topjohnwu/Magisk#1177] opened 2019-03-07 11:45 UTC
Running canary version build 18112 on Pixel 3 XL Stock ROM

Draglia Lost is working with Magisk Hide
Google pay isnt

Edit: It appears to be causing my settings to read 0B for both storage and cache. Reverted back to 18.1 and all is fine but Dragalia Lost stops working

Edit 2: Added device name

**Comment by DenyDarko** [comment] 2019-03-07 15:09
#1152

**Comment by Didgeridoohan** [comment] 2019-03-07 15:35
And, it's usually a good idea to take a look at previous issues, both open and closed, before opening a new one... There's been several like this in the past few days.

**Comment by keyute** [comment] 2019-03-07 15:37
> And, it's usually a good idea to take a look at previous issues, both open and closed, before opening a new one... There's been several like this in the past few days.

i'm reporting a new issue. I cannot clear data and cache as my settings read 0B on both. reverted back to magisk 18.1 and the issue is gone. weird. running march security update patch

**Comment by Didgeridoohan** [comment] 2019-03-07 15:49
The issue is about MagiskHide and Google Pay (something that, if you've read the link provided @DenyDarko, will be ignored)... You've added another issue as an edit. Better not to mix different reports in one issue.

I suggest you close this one (to save @topjohnwu the trouble) and open a new one with a proper bug report for the other issue you're experiencing. Take a look in the [Magisk repo readme](https://github.com/topjohnwu/Magisk/blob/master/README.MD) for info on how to provide that...

**Closed** 2019-03-07 15:50 UTC
