### ISSUE TITLE
Updating to 20.4 imposible 

### ISSUE THREAD

**Issue by Anthony270268** [topjohnwu/Magisk#2704] opened 2020-04-19 09:57 UTC
Hi, I'm trying to update as usually6to 20.since 2 weeks but the process stop with an error.
Here is the log
- Target image: /dev/block/mmcblk0p17
- Device platform: armeabi-v7a
2034+0 records in
2034+0 records out
2082816 bytes (2.0MB) copied, 0.039897 seconds, 49.8MB/s
1410+1 records in
1410+1 records out
1443916 bytes (1.4MB) copied, 0.051171 seconds, 26.9MB/s
boot_patch.sh: line 61: chmod: Permission denied
boot_patch.sh: line 64: ./magiskinit: Permission denied
- Unpacking boot image
boot_patch.sh: line 73: ./magiskboot: Permission denied
- Checking ramdisk status
- Stock boot image detected
boot_patch.sh: line 104: cat: Permission denied
- Patching ramdisk
boot_patch.sh: line 136: ./magiskboot: Permission denied
boot_patch.sh: line 148: rm: Permission denied
- Repacking boot image
boot_patch.sh: line 181: ./magiskboot: Permission denied
! Unable to repack boot image!
boot_patch.sh: line 51: rm: Permission denied
boot_patch.sh: line 52: rm: Permission denied
! Installation failed

**Comment by Didgeridoohan** [comment] 2020-04-19 10:08
Duplicate of https://github.com/topjohnwu/Magisk/issues/2609

Please close

**Closed** 2020-04-19 13:07 UTC
Labels: duplicate

**Comment by Anthony270268** [comment] 2020-04-19 13:34
Okay, now that I spent time opening n account here while I soulhd have been allowed to report the issue from the app I can now well see that others have the same problem...

**Comment by osm0sis** [comment] 2020-04-19 13:45
Report from the app? You think this the Play Store? 🙄

It's simple: Search before you post.
