### ISSUE TITLE
Cannot update to latest Canary version

### ISSUE THREAD

**Issue by sn-o-w** [topjohnwu/Magisk#8161] opened 2024-06-28 23:05 UTC
Device: Nexus 5 (hammerhead)
Android version: 10
Magisk version name: Canary
Magisk version code: 27001

---

Hi,

I cannot update to the latest Canary, I get this error:

<img src="https://github.com/topjohnwu/Magisk/assets/2406819/f91cb662-1a0a-462e-85df-eac5c3c5b652" width="300">

This is the device's kernel:
[boot-17.1-2023-02-17.zip](https://github.com/user-attachments/files/16037446/boot-17.1-2023-02-17.zip)

**Comment by lssong99** [comment] 2024-06-29 00:08
On my A15b3 P8P, the error becomes: unable to unpack boot image.

This happens right after install the apk, same after reboot. The downloaded APK file exists in Download folder.

![Uploading Screenshot_20240629-090701.png…]()

**Comment by yujincheng08** [comment] 2024-06-29 02:39
Duplicate of #8083

**Closed by yujincheng08** 2024-06-29 02:39 UTC
