### ISSUE TITLE
Installed Magisk Manager 7.5.0 and Magisk v20.2, bricked phone V20 US996

### ISSUE THREAD

**Issue by jjcf89** [topjohnwu/Magisk#2212] opened 2020-01-04 23:26 UTC
V20 US996
Running Alpha Omega Oreo: https://forum.xda-developers.com/v20/development/alpha-omega-rom-oreo-vs995-h910-ls997-t3847510/

* Installed latest Magisk Manager 7.5.0
* Installed Magisk v20.2 using direct install
* Clicked Reboot button in app
* Phone booted directly into fastboot and I can't get past it.

I will try to figure out how to reprogram the boot image.

**Comment by jjcf89** [comment] 2020-01-04 23:28
Looks like this has been posted about here: https://forum.xda-developers.com/v20/how-to/warning-dont-upgrade-version-magisk-20-2-t4028577

**Comment by chaveiro** [comment] 2020-01-05 12:05
Same hpened to my LG G5 H850 runing H85030f_00_OPEN_EU_OP_1122.
Recovered by flashing original boot image and flashing Magick v20.1 from TWRP..
I noticed that during the updage to Magisk v20.2 it showed on the console log that it had detected a stock boot image as oposed to the already patched version i was using (v20.1). Maybe that is the origin of the problem.
Advice you to quickly remove the 20.1 live update fromas many people will get stuck...

**Comment by osm0sis** [comment] 2020-01-05 18:13
Can you upload the boot.img for your ROMs that aren't working?

**Comment by chaveiro** [comment] 2020-01-05 19:15
[boot.emmc H85030f_00_OPEN_EU_OP_1122 patched by Magisk20.1.zip](https://github.com/topjohnwu/Magisk/files/4023818/boot.emmc.H85030f_00_OPEN_EU_OP_1122.patched.by.Magisk20.1.zip)
This file is my working boot image. It's patched by Magisk 20.1. If i let it upgrade to 20.2 it corrupts and phone enters fastboot everytime.

**Comment by osm0sis** [comment] 2020-01-05 20:32
Perfect. lz4_legacy packed kernel binary in the boot.img was failing to unpack since Canary 20107, so this is almost definitely a duplicate of #2203. :good:

**Comment by osm0sis** [comment] 2020-01-06 00:39
This should be closed by https://github.com/topjohnwu/Magisk/commit/2262af728e0c6fc4e3ac420bafc28e453c84f1eb

**Comment by jjcf89** [comment] 2020-01-06 04:30
In case someone stumbles across this issue, here's a direct link to the steps I took to restore my phone. https://forum.xda-developers.com/showpost.php?p=81390999&postcount=39

**Comment by osm0sis** [comment] 2020-01-06 06:00
@jjcf89 can you upload the working boot.img from your ROM still? It might be a different case from the G5 above.

**Comment by topjohnwu** [comment] 2020-01-06 10:18
@jjcf89 please try out the latest canary build and report if it fixes your issue

**Comment by jjcf89** [comment] 2020-01-07 14:38
[boot_20200103_magisk20.1.img.gz](https://github.com/topjohnwu/Magisk/files/4031053/boot_20200103_magisk20.1.img.gz)



> @jjcf89 please try out the latest canary build and report if it fixes your issue

Can I install a canary build using the manager?

**Comment by osm0sis** [comment] 2020-01-07 16:41
> [boot_20200103_magisk20.1.img.gz](https://github.com/topjohnwu/Magisk/files/4031053/boot_20200103_magisk20.1.img.gz)
> 
> > @jjcf89 please try out the latest canary build and report if it fixes your issue
> 
> Can I install a canary build using the manager?

You can, just switch to the Canary channel in Settings by putting https://bit.ly/2oIlk3A in the Custom channel dialog.

Looks like the latest Canary should work for you, since that .img you uploaded also had lz4_legacy for the kernel binary compression format. :+1:

**Closed** 2020-01-08 14:40 UTC

**Comment by jjcf89** [comment] 2020-01-08 14:43
Confirmed.  Installed Canary build and phone still works.
