### ISSUE TITLE
In app Updater, not working, no error message on Samsung Fold 4

### ISSUE THREAD

**Issue by Conan179** [topjohnwu/Magisk#8447] opened 2024-10-10 17:41 UTC
Hello, I have a problem updating the app, the Canary version, it ran without errors, but the version hasn't changed.

https://github.com/user-attachments/assets/aab1a2ea-56d6-401e-813a-9cad7cbfdeb1

As requested, I switched to Debug and the update works now.

Device: Samsung Fold 4
Android version: 14
Magisk version name: Magisk v28.0 (canary and debug)
Magisk version code: 28001

**Comment by macerg** [comment] 2024-10-11 00:12
Same here on my OnePlus 6 android 11.

**Comment by kyrenlee** [comment] 2024-10-11 00:56
install v28.0 apps,then patch boot.img to magisk-28000-xxx.img. last, reflash boot the magisk-28000-xx.img to phone.

**Comment by macerg** [comment] 2024-10-11 01:01
> install v28.0 apps,then patch boot.img to magisk-28000-xxx.img. last, reflash boot the magisk-28000-xx.img to phone.

You may have misunderstood the issue here.

**Comment by aviraxp** [comment] 2024-10-11 01:35
duplicated https://github.com/topjohnwu/Magisk/issues/8448

**Comment by macerg** [comment] 2024-10-11 04:37
> duplicated #8448

I think this is a different issue.

**Comment by Conan179** [comment] 2024-10-11 09:39
@aviraxp No its not a duplicated from 8448.
On my screencap, you can see, the download are finish without error.
My problem is the install process.

**Comment by aviraxp** [comment] 2024-10-12 16:29
I tried myself and it works without issues. Please provide log if the issue is reproducible.

**Comment by macerg** [comment] 2024-10-13 00:48
https://github.com/user-attachments/assets/724c4401-fbbf-40b7-a2b9-68f55ed1341c
Video showing 'error downloading file''.

**Comment by aviraxp** [comment] 2024-10-13 02:39
Your issue is duplicated https://github.com/topjohnwu/Magisk/issues/8448

> https://github.com/user-attachments/assets/724c4401-fbbf-40b7-a2b9-68f55ed1341c Video showing 'error downloading file''.

**Comment by Conan179** [comment] 2024-10-14 09:11
No is it NOT.
If you look closely at my screen capture above, you can see that the download was SUCCESSFUL and the installation process has started. It even says "Magisk Updated" at the top. Google Protect has even checked the downloaded apk file.

**Comment by aviraxp** [comment] 2024-10-14 09:29
> No is it NOT.
> If you look closely at my screen capture above, you can see that the download was SUCCESSFUL and the installation process has started. It even says "Magisk Updated" at the top. Google Protect has even checked the downloaded apk file.

I am repsonding to @macerg 's comment, noy yours. Also if you respond thmub up with the comment that ask you to provide logs, i think i have no way but close the issue, as i can never reproduce it.

**Comment by macerg** [comment] 2024-10-14 10:30
> > No is it NOT.
> > If you look closely at my screen capture above, you can see that the download was SUCCESSFUL and the installation process has started. It even says "Magisk Updated" at the top. Google Protect has even checked the downloaded apk file.
> 
> I am repsonding to @macerg 's comment, not yours. Also if you respond thmub up with the comment that ask you to provide logs, i think i have no way but close the issue, as i can never reproduce it.

Well , I can reproduce it consistently. Two different scenarios. By trying the update from the magisk manager app, the download fails, as shown in my screen recording, if download from GitHub, download succeeds but install goes ahead but does absolutely nothing. I remain at 27.

**Comment by towe96** [comment] 2024-10-14 18:52
Same issue as macerg. The in-app updater fails, installing the .apk from Github runs but it remains at version 27.

Xiaomi 14 with PIF, Shamiko and LSPosed (Zygisk).

**Comment by njtony11** [comment] 2024-10-15 14:52
After installing v28 from GitHub, stable still shows v27
![123](https://github.com/user-attachments/assets/a71f90a9-dd18-4637-a56b-b954e5d2e2db)

**Comment by macerg** [comment] 2024-10-16 01:17
> After installing v28 from GitHub, stable still shows v27 ![123](https://private-user-images.githubusercontent.com/60228975/376668221-a71f90a9-dd18-4637-a56b-b954e5d2e2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDE3MDYsIm5iZiI6MTcyOTA0MTQwNiwicGF0aCI6Ii82MDIyODk3NS8zNzY2NjgyMjEtYTcxZjkwYTktZGQxOC00NjM3LWE1NmItYjk1NGU1ZDJlMmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAxMTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YzUxZWFiYTI2Mjk3MWZiZjZiZGFkMjFiYzJhNGJlNDliYzZjY2I1MWQ1OTA4MzVmODk2YjdjN2M3Y2EzMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GY9r2JX7ZfSamPG02Gn-PVCRKeqpfahos2s17s4hX6Y)

Same here

**Comment by stetorIT** [comment] 2024-10-18 17:48
> After installing v28 from GitHub, stable still shows v27

same here on Xiaomi MI13 Pro with HyperOS 1.0.2
also it does not install from recovery with zip nor by patching and flashing boot.img and init_boot.img from the app and from fastboot
the 27000 work well at least with the fastboot mode
![photo_5807628462842824316_y](https://github.com/user-attachments/assets/532a831d-49ec-4f81-a6b5-14475c2e7b39)

**Comment by macerg** [comment] 2024-10-19 12:21
Appears to have been fixed. Installed ok now for me.  Form in app updater.
Thanks for fixing, in my case, at least.

**Comment by tajnymag** [comment] 2024-10-19 12:28
> Appears to have been fixed. Installed ok now for me. From in app updater. Thanks for fixing, in my case, at least.

I'm afraid you just somehow got lucky. Nothing has changed at least on my end. What's more, thefe doesn't even seem to be a new release, so you were installing the same apk which has been failing for us

**Comment by macerg** [comment] 2024-10-19 12:42
> > Appears to have been fixed. Installed ok now for me. From in app updater. Thanks for fixing, in my case, at least.
> 
> I'm afraid you just somehow got lucky. Nothing has changed at least on my end. What's more, thefe doesn't even seem to be a new release, so you were installing the same apk which has been failing for us

How peculiar! 🤨

**Comment by macerg** [comment] 2024-10-20 05:01
Sorry for the non standard approach but I know no other method. Since upgrading to 28.0 (28000) many of my apps {eg, Nationwide) are failing security checks. I need to revert to 27000 urgently because I am dependant on these apps.
Can I just install the 27000 app over 28000 and repatch from the 27000 once installed or do I need to reflash from twrp? Please assist, desperate!
OnePlus 6 on Android 11.
Thanks 🙏 in anticipation.

**Comment by tajnymag** [comment] 2024-10-20 06:27
> Sorry for the non standard approach but I know no other method. Since upgrading to 28.0 (28000) many of my apps {eg, Nationwide) are failing security checks. I need to revert to 27000 urgently because I am dependant on these apps. Can I just install the 27000 app over 28000 and repatch from the 27000 once installed or do I need to reflash from twrp? Please assist, desperate! OnePlus 6 on Android 11. Original install was done via twrp. Thanks 🙏 in anticipation.

That's a different issue

**Comment by macerg** [comment] 2024-10-20 06:47
> > Sorry for the non standard approach but I know no other method. Since upgrading to 28.0 (28000) many of my apps {eg, Nationwide) are failing security checks. I need to revert to 27000 urgently because I am dependant on these apps. Can I just install the 27000 app over 28000 and repatch from the 27000 once installed or do I need to reflash from twrp? Please assist, desperate! OnePlus 6 on Android 11. Original install was done via twrp. Thanks 🙏 in anticipation.
> 
> That's a different issue
I know "it's a different issue"  what is the correct method to try and get help please as it's obviously not a 'bug'. Just desperate for a solution.

**Comment by Bryantdl7** [comment] 2024-10-22 22:18
Same issue here, unable to finish magisk installation, thus unable to open the magisk app at all now

**Comment by Conan179** [comment] 2024-12-01 23:35
Now the error also occurs for me with the debug version when I try to update the app from 28001 to 28002, no error message, exactly the same behavior as in my video above.

**Comment by Conan179** [comment] 2024-12-04 09:48
https://www.dropbox.com/scl/fi/9y81lhukhy13pp604bpet/2024-12-04-10.45.23.mp4?rlkey=npr1fy05b4b6wj82dzaam57k4&dl=0

**Closed** 2024-12-19 01:55 UTC
