### ISSUE TITLE
(25.0) LG V50 Stock Android 12 - Zygisk stays deactivated

### ISSUE THREAD

**Issue by menotuu** [topjohnwu/Magisk#5997] opened 2022-06-18 12:30 UTC
Device: LG V50 ThinQ (V500N)
Android version: Android 12 40b
Magisk version name: cacf8736
Magisk version code: 25001

Zygisk stays deactivated, I restarted the phone many times. 
I patched the boot_b.img file with hooked on 'preserve force encryption' in magisk.
I don't know what could be the problem, and I'm not a pro user.

[boot_b.img](https://www.sendspace.com/file/9uesjy)

[magisk.log](https://github.com/topjohnwu/Magisk/files/8933532/magisk_log_2022-06-18T14.27.16.log)
[boot.log](https://github.com/topjohnwu/Magisk/files/8933533/boot-2022-06-18-14-25-14.log)

![1](https://user-images.githubusercontent.com/38182429/174438043-a93c33b2-20cc-4252-9447-6b3a63680a51.png)
![2](https://user-images.githubusercontent.com/38182429/174438045-cc15b200-f857-4c70-9a8e-729bceaefeca.png)
![3](https://user-images.githubusercontent.com/38182429/174438047-1a777265-0ff5-463d-b8c2-2b4a81943f77.png)
![4](https://user-images.githubusercontent.com/38182429/174438048-968fb30f-cf72-4b5c-9501-8094137ff34b.png)

**Comment by vvb2060** [comment] 2022-06-18 13:43
Duplicate of #5955
It looks like this file is missing from other devices besides MTK.

**Closed by vvb2060** 2022-06-18 13:43 UTC

**Comment by vvb2060** [comment] 2022-06-18 13:54
https://github.com/topjohnwu/Magisk/actions/workflows/build.yml?query=event%3Apush

you can try install ci build

**Comment by menotuu** [comment] 2022-06-18 14:02
ci build does mean what?

**Comment by vvb2060** [comment] 2022-06-18 14:04
https://github.com/topjohnwu/Magisk/suites/6983264550/artifacts/273232681

**Comment by menotuu** [comment] 2022-06-18 14:23
I uninstalled magisk manager and installed app-release.apk from your posted artifacs package.

still same. I think magisk log line 1534, right?
mount /dev/6Kgmfpb/.magisk/zygisk/magisk64->/system/bin/bootanimation failed with 2: No such file or directory

[magisk.log](https://github.com/topjohnwu/Magisk/files/8933762/magisk.log)
[boot.log](https://github.com/topjohnwu/Magisk/files/8933763/boot.log)

**Comment by vvb2060** [comment] 2022-06-18 14:58
If you don't know how, wait for the next canary release

**Comment by menotuu** [comment] 2022-06-18 15:03
but should it not fixed already in your posted artifacs package app-release.apk?
