### ISSUE TITLE
I lose root privileges after updating

### ISSUE THREAD

**Issue by uvzen** [topjohnwu/Magisk#4297] opened 2021-04-30 20:05 UTC
Device: Huawei P10 VTR-L09
Android version: 8.0.0.386(C432)
Magisk version name: 20.4-22.1
Magisk version code: 22104

Log file: 
[magisk_install_log_2021-04-30T213909Z.log](https://github.com/topjohnwu/Magisk/files/6407771/magisk_install_log_2021-04-30T213909Z.log)
Boot image:
[RECOVERY_RAMDIS.zip](https://github.com/topjohnwu/Magisk/files/6407773/RECOVERY_RAMDIS.zip)

When I update magisk to the latest version (22.1) I lose root privileges as if magisk has not installed.
Installed: N/A
A/B: No,
Ramdisk: Yes

I tried to install magisk via TWRP and via the patched_boot.img file, but to no avail. The last working version of magisk for my device is magisk_20.4

![screenshot](https://user-images.githubusercontent.com/80232276/116748684-12f99300-aa00-11eb-856a-0fb208be6342.png)

**Comment by Didgeridoohan** [comment] 2021-05-01 05:06
Apart from this likely being a duplicate, it's kind of crappy to just change the version code in the issue text to match the reporting requirements, but not actually provide any testing/log/etc information from that Magisk version... Seeing the same here and there, but in this report it was just so obvious.

If the reporting user is that lazy, how do you expect the developer to take your report seriously?

**Comment by cawidtu** [comment] 2021-05-04 07:49
I do not think this is a duplicate of issue https://github.com/topjohnwu/Magisk/issues/4174 since the latter still allows su access, so Magisk seems active in some way. In the present issue, Magisk does not seem to start up at all. I see strong links to issue https://github.com/topjohnwu/Magisk/issues/4306 I opened yesterday, though. Both are dealing with Huawei EMUI 8 devices and report Magisk 20.4 as latest working version.

**Comment by osm0sis** [comment] 2021-05-09 14:31
#4319

**Closed** 2021-05-09 14:31 UTC
Labels: duplicate
