### ISSUE TITLE
WiFi not working due to new sepolicy flag

### ISSUE THREAD

**Issue by a6680** [topjohnwu/Magisk#7764] opened 2024-02-05 16:13 UTC
After trying to update to Magisk 27.0 (27001) on Android 10, WiFi still says "IP configuration failed" and WiFi doesn't work. However, with Magisk 26.4 (26400), the WiFi works fine.
Device: Wayne (Xiaomi 6x)
Android version: 10 (CarbonROM)
Magisk version name: 27.0
Magisk version code: 27001

[wifi_log.txt](https://github.com/topjohnwu/Magisk/files/14168252/wifi_log.txt)

**Comment by a6680** [comment] 2024-02-05 16:14
WiFi log provided

**Comment by yujincheng08** [comment] 2024-02-05 18:43
also need magisk log

**Comment by yujincheng08** [comment] 2024-02-05 18:48
I think this is your ROM's issue. It does not correctly set `POLICYDB_CONFIG_ANDROID_NETLINK_ROUTE`.

**Comment by yujincheng08** [comment] 2024-02-05 19:07
Oh after further investigation I know what is going on now. It's a regression on Android 10- with high kernel version.

**Comment by aviraxp** [comment] 2024-02-06 01:03
Ask your kernel devs to revert commit https://review.lineageos.org/#/c/301314.

**Comment by UniverseCodex01** [comment] 2024-02-06 02:42
> After trying to update to Magisk 27.0 (27001) on Android 10, WiFi still says "IP configuration failed" and WiFi doesn't work. However, with Magisk 26.4 (26400), the WiFi works fine.
> Device: Wayne (Xiaomi 6x)
> Android version: 10 (CarbonROM)
> Magisk version name: 27.0
> Magisk version code: 27001
> 
> [wifi_log.txt](https://github.com/topjohnwu/Magisk/files/14168252/wifi_log.txt)
> 
> 

Same issue on miui 12.5.3 android 10. For the moment I'm returning to 26.4

**Comment by vvb2060** [comment] 2024-02-06 03:04
If you know what this is doing, you can try it, we don't offer any support for this.
```
allow netdomain netdomain netlink_route_socket { bind nlmsg_readpriv nlmsg_getneigh }
```

**Comment by UnMarshmallow** [comment] 2024-02-06 09:53
> After trying to update to Magisk 27.0 (27001) on Android 10, WiFi still says "IP configuration failed" and WiFi doesn't work. However, with Magisk 26.4 (26400), the WiFi works fine. Device: Wayne (Xiaomi 6x) Android version: 10 (CarbonROM) Magisk version name: 27.0 Magisk version code: 27001
> 
> [wifi_log.txt](https://github.com/topjohnwu/Magisk/files/14168252/wifi_log.txt)

I also have this problem but after switching the kernel to permissive the wifi works again, for the moment it only has this solution.

**Comment by UniverseCodex01** [comment] 2024-02-06 13:32
> > After trying to update to Magisk 27.0 (27001) on Android 10, WiFi still says "IP configuration failed" and WiFi doesn't work. However, with Magisk 26.4 (26400), the WiFi works fine. Device: Wayne (Xiaomi 6x) Android version: 10 (CarbonROM) Magisk version name: 27.0 Magisk version code: 27001
> > 
> > [wifi_log.txt](https://github.com/topjohnwu/Magisk/files/14168252/wifi_log.txt)
> 
> I also have this problem but after switching the SELinux to permissive the wifi works again, for the moment he only has this solution for me.

Can you return to enforce selinux and try this module? It's supposed to fix WiFi on android 10 with magisk v27

![wifi_fix_1.0.zip](https://github.com/topjohnwu/Magisk/files/14180558/wifi_fix_1.0.zip)

**Comment by UnMarshmallow** [comment] 2024-02-06 14:09
> > > After trying to update to Magisk 27.0 (27001) on Android 10, WiFi still says "IP configuration failed" and WiFi doesn't work. However, with Magisk 26.4 (26400), the WiFi works fine. Device: Wayne (Xiaomi 6x) Android version: 10 (CarbonROM) Magisk version name: 27.0 Magisk version code: 27001
> > > [wifi_log.txt](https://github.com/topjohnwu/Magisk/files/14168252/wifi_log.txt)
> > 
> > 
> > I also have this problem but after switching the SELinux to permissive the wifi works again, for the moment he only has this solution for me.
> 
> Can you return to enforce selinux and try this module? It's supposed to fix WiFi on android 10 with magisk v27
> 
> ![wifi_fix_1.0.zip](https://github.com/topjohnwu/Magisk/files/14180558/wifi_fix_1.0.zip)

Well... According to my test, this does not solve the problem regarding WiFi.

**Comment by UniverseCodex01** [comment] 2024-02-06 14:49
> > > > After trying to update to Magisk 27.0 (27001) on Android 10, WiFi still says "IP configuration failed" and WiFi doesn't work. However, with Magisk 26.4 (26400), the WiFi works fine. Device: Wayne (Xiaomi 6x) Android version: 10 (CarbonROM) Magisk version name: 27.0 Magisk version code: 27001
> > > > [wifi_log.txt](https://github.com/topjohnwu/Magisk/files/14168252/wifi_log.txt)
> > > 
> > > 
> > > I also have this problem but after switching the SELinux to permissive the wifi works again, for the moment he only has this solution for me.
> > 
> > Can you return to enforce selinux and try this module? It's supposed to fix WiFi on android 10 with magisk v27
> > 
> > ![wifi_fix_1.0.zip](https://github.com/topjohnwu/Magisk/files/14180558/wifi_fix_1.0.zip)
> 
> Well... According to my test, this does not solve the problem regarding WiFi. Always the error "IP configuration failed"

Well I tried xf thanks for your test 👍

**Comment by Djkusuma182** [comment] 2024-02-06 15:43
> After trying to update to Magisk 27.0 (27001) on Android 10, WiFi still says "IP configuration failed" and WiFi doesn't work. However, with Magisk 26.4 (26400), the WiFi works fine. Device: Wayne (Xiaomi 6x) Android version: 10 (CarbonROM) Magisk version name: 27.0 Magisk version code: 27001
> 
> [wifi_log.txt](https://github.com/topjohnwu/Magisk/files/14168252/wifi_log.txt)

same. me to.



> > > After trying to update to Magisk 27.0 (27001) on Android 10, WiFi still says "IP configuration failed" and WiFi doesn't work. However, with Magisk 26.4 (26400), the WiFi works fine. Device: Wayne (Xiaomi 6x) Android version: 10 (CarbonROM) Magisk version name: 27.0 Magisk version code: 27001
> > > [wifi_log.txt](https://github.com/topjohnwu/Magisk/files/14168252/wifi_log.txt)
> > 
> > 
> > I also have this problem but after switching the SELinux to permissive the wifi works again, for the moment he only has this solution for me.
> 
> Can you return to enforce selinux and try this module? It's supposed to fix WiFi on android 10 with magisk v27
> 
> ![wifi_fix_1.0.zip](https://github.com/topjohnwu/Magisk/files/14180558/wifi_fix_1.0.zip)

not working for me.

**Comment by andrewcharnley** [comment] 2024-02-09 20:19
I don't know why this was closed.

The issue exists on 26.4 if zygisk is enabled (or maybe zygisk + enforcing).

Going back to 26.3 and all is working again, so the change  was introduced in 26.4.

**Comment by UniverseCodex01** [comment] 2024-02-09 20:30
> I don't know why this was closed.
> 
> The issue exists on 26.4 if zygisk is enabled (or maybe zygisk + enforcing).
> 
> Going back to 26.3 and all is working again, so the change  was introduced in 26.4.

Kernel issue, search for an update kernel to your device. It's sad but it's true magisk team can't solve it

**Comment by andrewcharnley** [comment] 2024-02-09 20:32
Perhaps but the issue doesn't exist on 26.3 so maybe we need a choice?

**Comment by UniverseCodex01** [comment] 2024-02-09 20:38
> Perhaps but the issue doesn't exist on 26.3 so maybe we need a choice?

Probably magisk change their code and something it's conflicting with a sepolicy of the kernel. On the top a magisk team person says that it's related to WiFi permission sepolicy. Kernels are using a new sepolicy that was introduced on a11

**Comment by UniverseCodex01** [comment] 2024-02-09 20:38
> > Perhaps but the issue doesn't exist on 26.3 so maybe we need a choice?
> 
> Probably magisk change their code and something it's conflicting with a sepolicy of the kernel. On the top a magisk team person says that it's related to WiFi permission sepolicy. Kernels are using a new sepolicy that was introduced on a11

My usage kernel release a new version with fix for WiFi on magisk v27

**Comment by vvb2060** [comment] 2024-02-11 14:57
We should keep the sepolicy flag unchanged

**Comment by andrewcharnley** [comment] 2024-02-11 14:58
FYI the following didn't fix it for me either, on 26.4 or 27. The module someone posted above is doing the same thing.

allow netdomain netdomain netlink_route_socket { bind nlmsg_readpriv nlmsg_getneigh }

**Comment by vvb2060** [comment] 2024-02-11 15:18
Updated the title, if it still doesn't work after allowing the rule then it's not the same issue, please open a new issue. 
This issue is only for regressions introduced by #7636.

**Comment by ilya-bystrov** [comment] 2024-03-14 22:20
I am not an experienced user and it took me some time to figure out how to downgrade Magisk. It might be helpful for others. 

I tried to downgrade Magisk through the Magisk App, and after rebooting, the phone was stuck at the boot logo. 
I launched TWRP, uninstalled Magisk by renaming Magisk to 'uninstall.zip', rebooted, and then installed a new version from TWRP, which fixed the issue.

https://twrp.me/
https://magiskmanager.com/

**Comment by zinhuofc** [comment] 2024-03-16 15:44
here 26.4 works, the problem is only in versions 27, I tried with an updated kernel and not working

**Comment by aviraxp** [comment] 2024-03-17 05:54
Please test if https://github.com/aviraxp/Magisk/actions/runs/8313167486/artifacts/1332721246 works for you.

**Comment by Flamefire** [comment] 2024-03-17 11:40
> #7636
> 
> If you know what this is doing, you can try it, we don't offer any support for this.
> 
> ```
> allow netdomain netdomain netlink_route_socket { bind nlmsg_readpriv nlmsg_getneigh }
> ```

FWIW: `audit2allow` mentions:

**Comment by senposage** [comment] 2024-03-18 17:51
thx for this was just going to pull my v40 out of retirement to give to the the folks for a music player and encoutered this issue

**Comment by topjohnwu** [comment] 2024-03-19 09:54
Fixed with d20b30c

**Closed by topjohnwu** 2024-03-19 09:54 UTC
Labels: regression, confirmed, core

**Comment by ManKetnas** [comment] 2024-04-11 06:42
just updated magisk to v27.0 and got same issues.  Where can I get the fixed application, dont like to downgrade, thx ?

**Comment by JumboMite** [comment] 2024-05-05 01:20
I was experiencing the same problem with Android 9 on Magisk 27.  I couldn't make a WiFi connection unless I set selinux to permissive. 

I tried the latest Canary build (downloaded May 3rd), no change. 

Downgraded to Magisk 26.3 as @andrewcharnley suggested and WiFi connections are possible again with Selinux enforcing.

**Comment by ManKetnas** [comment] 2024-05-05 10:07
> I was experiencing the same problem with Android 9

I personally dont care anymore, I did a backup of my data and swaped to crdroid after +5years. 
Now I'm using KernelSu and I'm happy so far, I hope that I never have to use Magisk again. You always have to be frightened about every small change of a setting or uodate, its a nightmare.
