### ISSUE TITLE
bootloop after flashing patched boot image

### ISSUE THREAD

**Issue by flyingduck234** [topjohnwu/Magisk#3089] opened 2020-08-18 21:42 UTC
running Stock firmware and stock recovery
Android 10

[magisk_patched.zip](https://github.com/topjohnwu/Magisk/files/5092999/magisk_patched.zip)
[original_boot.zip](https://github.com/topjohnwu/Magisk/files/5093001/original_boot.zip)

**Comment by osm0sis** [comment] 2020-08-19 01:14
Try the latest Canary? Did your device's stock ROM update to Android 10?

**Comment by flyingduck234** [comment] 2020-08-19 02:15
its updated to android 10.

how can i change to canary.

also i opened init file ramdisk and i can't open it in notepad++ or the encoding is strange

**Comment by osm0sis** [comment] 2020-08-19 02:23
Get the latest Canary Manager, link in the README, then use it to patch your boot.img. If it doesn't work then this is a duplicate of #2695.

**Closed by osm0sis** 2020-08-19 02:23 UTC
