### ISSUE TITLE
Boot stuck at Sony Logo with LOS 17.1 on XZ1c

### ISSUE THREAD

**Issue by Flamefire** [topjohnwu/Magisk#4365] opened 2021-05-16 19:12 UTC
After flashing the patched boot.img via `fastboot flash boot magisk...` the device won't get past the SONY logo anymore.
Reflashing the original boot.img resolves this but can't get it to work with magisk.

I also can't get an adb connection (I guess it hangs to early) so no logs unfortunately.

/proc/mounts is
```
/dev/block/platform/soc/1da4000.ufshc/by-name/system / ext4 ro,seclabel,relatime,discard 0 0
tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,size=1889304k,nr_inodes=472326,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
proc /proc proc rw,relatime,gid=3009,hidepid=2 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
tmpfs /mnt tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1889304k,nr_inodes=472326,mode=755,gid=1000 0 0
tmpfs /apex tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1889304k,nr_inodes=472326,mode=755 0 0
/dev/block/platform/soc/1da4000.ufshc/by-name/oem /ocm ext4 ro,seclabel,relatime,data=ordered 0 0
/dev/block/platform/soc/1da4000.ufshc/by-name/vendor /vendor ext4 ro,seclabel,relatime,discard 0 0
none /dev/cg2_bpf cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
none /dev/cpuctl cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0
none /acct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
none /dev/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent 0 0
none /dev/memcg cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
none /dev/stune cgroup rw,nosuid,nodev,noexec,relatime,schedtune 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
none /config configfs rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,seclabel,relatime 0 0
/dev/block/bootdevice/by-name/userdata /data ext4 rw,seclabel,nosuid,nodev,noatime,noauto_da_alloc,errors=panic,data=ordered 0 0
/dev/block/bootdevice/by-name/cache /cache ext4 rw,seclabel,nosuid,nodev,noatime,noauto_da_alloc,errors=panic,data=ordered 0 0
/dev/block/bootdevice/by-name/modem /vendor/firmware_mnt vfat ro,context=u:object_r:firmware_file:s0,relatime,uid=1000,gid=1000,fmask=0337,dmask=0227,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro 0 0
/dev/block/bootdevice/by-name/bluetooth /vendor/bt_firmware vfat ro,context=u:object_r:bt_firmware_file:s0,relatime,uid=1002,gid=3002,fmask=0337,dmask=0227,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro 0 0
/dev/block/bootdevice/by-name/dsp /vendor/dsp ext4 ro,seclabel,nosuid,nodev,relatime,data=ordered 0 0
/dev/block/bootdevice/by-name/persist /mnt/vendor/persist ext4 rw,seclabel,nosuid,nodev,noatime,data=ordered 0 0
/dev/block/bootdevice/by-name/Qnovo /mnt/qns ext4 rw,seclabel,nosuid,nodev,noexec,noatime,discard,data=ordered 0 0
tmpfs /storage tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1889304k,nr_inodes=472326,mode=755,gid=1000 0 0
/dev/block/loop2 /apex/com.android.conscrypt@299900000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop2 /apex/com.android.conscrypt ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop3 /apex/com.android.media.swcodec@290000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop3 /apex/com.android.media.swcodec ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop4 /apex/com.android.apex.cts.shim@1 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop4 /apex/com.android.apex.cts.shim ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop5 /apex/com.android.resolv@290000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop5 /apex/com.android.resolv ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop6 /apex/com.android.tzdata@290000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop6 /apex/com.android.tzdata ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop7 /apex/com.android.runtime@1 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop7 /apex/com.android.runtime ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop8 /apex/com.android.media@290000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop8 /apex/com.android.media ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/bootdevice/by-name/appslog /mnt/rca ext4 rw,seclabel,nosuid,nodev,noexec,noatime,discard,data=ordered 0 0
/dev/block/bootdevice/by-name/diag /mnt/idd ext4 rw,seclabel,nosuid,nodev,noexec,noatime,discard,data=ordered 0 0
adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
/data/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /storage/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/full/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/dev/block/vold/public:179,1 /mnt/media_rw/CD28-EB81 exfat rw,dirsync,nosuid,nodev,noexec,noatime,fs=exfat,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=cp437,iocharset=utf8,namecase=0,symlink=0,bps=512,errors=remount-ro 0 0
/mnt/media_rw/CD28-EB81 /mnt/runtime/default/CD28-EB81 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6 0 0
/mnt/media_rw/CD28-EB81 /storage/CD28-EB81 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6 0 0
/mnt/media_rw/CD28-EB81 /mnt/runtime/read/CD28-EB81 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18 0 0
/mnt/media_rw/CD28-EB81 /mnt/runtime/write/CD28-EB81 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18 0 0
/mnt/media_rw/CD28-EB81 /mnt/runtime/full/CD28-EB81 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=7 0 0
```

[boot.img.tar.gz](https://github.com/topjohnwu/Magisk/files/6489803/boot.img.tar.gz)

Device: Sony Xperia XZ1 compact
Android version: 10 (LOS 17.1)
Magisk version name:  f822ca5b
Magisk version code: 23001

I have a flashed TWRP on this device (i.e. `fastboot flash recovery twrp.img`) and haven't found a stock recovery img otherwise I'd have tried that.

Checked https://github.com/topjohnwu/Magisk/issues/3752 for related issues but the unpacked magisk ramdisk doesn't have a fstab file

**Comment by osm0sis** [comment] 2021-05-16 21:15
Standard "v0" hdr with os_version:
```

Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: boot.img

Setting up work folders...

Image type: AOSP

Splitting image to "split_img/"...
ANDROID! magic found at: 0
BOARD_KERNEL_CMDLINE user_debug=31 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 sched_enable_hmp=1 sched_enable_power_aware=1 service_locator.enable=1 swiotlb=2048 androidboot.configfs=true androidboot.usbcontroller=a800000.dwc3 loop.max_part=7 zram.backend=z3fold androidboot.hardware=lilac buildvariant=userdebug
BOARD_KERNEL_BASE 0x00000000
BOARD_NAME 
BOARD_PAGE_SIZE 4096
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x01000000
BOARD_SECOND_OFFSET 0x00f00000
BOARD_TAGS_OFFSET 0x00000100
BOARD_OS_VERSION 10.0.0
BOARD_OS_PATCH_LEVEL 2021-04
BOARD_HEADER_VERSION 0

Unpacking ramdisk to "ramdisk/"...

Compression used: gzip
3633 blocks

Done!
```

Old style 2SI with only init and empty directories in the ramdisk.

**Comment by EmTeeAge** [comment] 2021-05-26 23:01
I have a Sony Xperia XA2 and I'm facing a similar problem - after updating Lineage OS I lost root and wanted to flash Magisk again, however never got past the Sony logo after flashing the boot image. Now that I've completely reinstalled the OS, I still didn't manage to get past the Sony logo with the newest patched boot image. Is there any way I can get some logs from somewhere to be a bit more helpful?

**Comment by osm0sis** [comment] 2021-05-27 00:14
@Flamefire, does 22.1 work for you?

**Comment by nonyonah** [comment] 2021-05-27 19:01
I use a Nokia 3.2 and tried installing magisk through the patched boot image. It booted up but into a black screen and it kept rebooting, sometimes with a slow animation. I had to remove the root by long pressing and restarting the device, hope it gets fixed though

**Comment by Flamefire** [comment] 2021-05-29 09:00
@osm0sis Yes using 22.1 works for me.

**Comment by osm0sis** [comment] 2021-11-07 09:48
Any luck on 23013?

**Comment by kgursu** [comment] 2021-11-10 20:33
Tried to switch to Lineage OS official 18.1, but it also didn't help me. That time, I tried the latest Magisk, which was 23.012, I suppose. Lastly, I switched to an unofficial version of Magisk, which includes modified 23 version especially for Xperia Z2. I may give you that file, if you would like to look.
Another possible interference could be the GApps I installed, which was BitGApps and still is, which includes an ARM compatible one, because the latest BitGApps requires reflashing its zip after OTA updates.

**Comment by osm0sis** [comment] 2021-11-23 15:25
Latest is 23014 @kgursu, so you need to try that.

**Comment by kgursu** [comment] 2021-11-23 18:02
Ok, but without 32 bit OS support, is this still worth trying?

Chris Renshaw ***@***.***>, 23 Kas 2021 Sal, 18:25 tarihinde
şunu yazdı:

**Comment by osm0sis** [comment] 2021-11-23 19:13
Not sure what you're talking about, Magisk supports arm and x86.

**Comment by osm0sis** [comment] 2021-12-04 04:15
Well, since no update from @Flamefire, I'll close this as likely fixed with all the regressions. 👍

**Closed by osm0sis** 2021-12-04 04:15 UTC
Labels: regression

**Comment by amo13** [comment] 2022-08-29 17:15
Unfortunately, I am having this very issue on my Sony Xperia XA2 (pioneer) with the current magisk version v25.2. I am running LineageOS for Microg 18.1-20220406.
Extracted boot.img with the [LineageOS update-payload-extractor](https://github.com/LineageOS/scripts/tree/master/update-payload-extractor), copied to the device, used said magisk version to patch the boot.img and flashed it in fastboot.
I also can't get past the Sony logo on boot.

**Comment by amo13** [comment] 2022-08-29 19:58
I'm sorry, I mixed up versions of the rom zip and boot.img. It does work fine.
