### ISSUE TITLE
[Magisk] add Rescue scenario

### ISSUE THREAD

**Issue by Sekkei** [topjohnwu/Magisk#5358] opened 2022-02-01 14:40 UTC
Repost 4. time because your magisk-bot is a dictator.
you have three clones of this in your closed section.

I know that magisk has two ways to help remove broken installs or module:
Safe Mode - very ominous never seen a device capable of this , but it might exit
ADB - well, only usefull if you have a custom reovery , but than you would not need it , fasboot ist not adb , while booting is no adb , so where/when should this be used ?

I propose a new feature that can help people stuck.
If a device is in bootloop or stuck on boot , you can mostly fix it with flashing the stock boot.img and/or vbmeta.img. (fastboot)
Reboot. Than allow the Magisk app to disable itself or all/some modules (atm the tab is greyed out). On the next reboot first search for this case and disable accordingly.
Reflash patched partitions / reinstall magisk and manualy remove or modify broken modules.

Additional thoughts; or use a special file in root of internal storage to detect on boot. some phones can have sdcards.

Things not possible: expect adb/debugging , root acces , flashing healthy data partition

Device: Samsung Galaxy S8 (SM-G950F)
Android version: 11
Magisk version name: 32fc34f
Magisk version code: 24101

**Comment by Sekkei** [comment] 2022-02-03 01:58
> You open new issue without knowledge. 

True.

>Flash stock boot image will make superuser access unavailable (no way to get root access) and magisk app cannot disable itself without superuser access

It should only be used to trigger the next boot behavior of magisk , e.g. user flashes stock boot/vbmeta , open magisk app to disable apps (or better activate a root_but_no_modules / safe mode) , for example create a simple shared_pref value , that will be read and executed before the first magisk script is used. So instead of loading the mirrored/linked folders check if magisk shared_pref exist (or file inside internal storage / sdcard)
Or in short: activate magisk own safe/core mode from app

Did I miss there something ? I hope/think there should no superuser be needed

**Comment by Jon8RFC** [comment] 2022-02-04 12:08
In the interim, there's this:
https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver

**Comment by Sekkei** [comment] 2022-02-04 20:50
> In the interim, there's this: https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver

Nice , This will probably work on most bootloops but not if the system rom will not boot or if it crashes before module scripts are executed. (Crashes or more likely vendor verify checks)

Also I think a rescue situation should come from the project that is the actually reason for this , even if third-party addons are to blame)

**Comment by vvb2060** [comment] 2022-02-06 08:57
Duplicate of #4624

**Closed by vvb2060** 2022-02-06 08:57 UTC

**Comment by Sekkei** [comment] 2022-02-07 01:19
> Duplicate of #4624

No it's not ? I proposed to add a new/different way to disable modules , with or without safe mode , not that I don't find the safe mode. Pls read not assume..

**Comment by m00nwtchr** [comment] 2022-05-16 17:42
This is a really needed feature, i can't find any working way to get into Safe Mode on a bootlooping Samsung Galaxy S20 FE.
