### ISSUE TITLE
very strange problem when installing nethunter lite via magisk

### ISSUE THREAD

**Issue by maoruiQa** [topjohnwu/Magisk#8623] opened 2024-12-10 12:44 UTC
Device: oneplus 6t
Android version: 13
Magisk version name: 28.1
Magisk version code: 28101

nethunter lite:[https://kali.download/nethunter-images/kali-2024.2/nethunter-2024.2-generic-arm64-kalifs-full.zip](url)
the log:
```
 Copying zip to temp directory
- Installing nh.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
mkdir: can't create directory '/modules_update/': Read-only file system
unzip: can't change directory to '/modules_update/Kali-NetHunter': No such file or directory
```

**Comment by Killer74-hub** [comment] 2024-12-11 18:49
Same issue. "! Installation failed"

**Comment by maoruiQa** [comment] 2024-12-13 03:31
Mein says "installation complete" at the top of the screem, but actually nothing installed. I found out that it even didn't start to run the preinstall.sh in nethunter, as I add 'echo "test"' at the beginning of the script and no "test" appeared on the script.

**Comment by yujincheng08** [comment] 2024-12-30 05:19
Caused by https://github.com/topjohnwu/Magisk/commit/d33b077a13b34691a7f1fd3643336e09383ced78

This module uses the deprecated `NVBASE`: https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-installer/-/blob/2024.2/update/META-INF/com/google/android/update-binary#L67

Fixed by nethunter in https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-installer/-/commit/bae97632478a8ea8c55def6d22e0fe3a18dea8bd

**Closed by yujincheng08** 2024-12-30 05:19 UTC
