### ISSUE TITLE
Device doesn't boot / doesn't mount hw_product partition

### ISSUE THREAD

**Issue by user456789** [topjohnwu/Magisk#5616] opened 2022-03-19 01:37 UTC
Device: Huawei Mate 10 Pro (BLA-L29)
Android version: 10 (EMUI 10.0.0.202(C432E9R1P3))
Magisk version name: Canary
Magisk version code: 24303

I've got the same problem as described in here: #4772 

With current stable version 24300 the device boots and Magisk itself is working fine but the hw_product partition is not mounted.

When I tried Canary version 24303, which should include a fix as I understand it for #4772, the device reboots directly back to fastboot.

[RAMDISK.zip](https://github.com/topjohnwu/Magisk/files/8308369/RAMDISK.zip)
[magisk_install_log_2022-03-19T01:30:51_24303.log](https://github.com/topjohnwu/Magisk/files/8308370/magisk_install_log_2022-03-19T01.30.51_24303.log)
[magisk_install_log_2022-03-19T01:33:45_24300.log](https://github.com/topjohnwu/Magisk/files/8308371/magisk_install_log_2022-03-19T01.33.45_24300.log)
[magisk_log_2022-03-19T01:30:57_24303_unpatched.log](https://github.com/topjohnwu/Magisk/files/8308372/magisk_log_2022-03-19T01.30.57_24303_unpatched.log)
[magisk_log_2022-03-19T01:33:50_24300_unpatched.log](https://github.com/topjohnwu/Magisk/files/8308373/magisk_log_2022-03-19T01.33.50_24300_unpatched.log)
[magisk_log_2022-03-19T02:13:13_24300_patched.log](https://github.com/topjohnwu/Magisk/files/8308374/magisk_log_2022-03-19T02.13.13_24300_patched.log)
[magisk_patched-24300_IOYqj.zip](https://github.com/topjohnwu/Magisk/files/8308375/magisk_patched-24300_IOYqj.zip)
[magisk_patched-24303_zFdZU.zip](https://github.com/topjohnwu/Magisk/files/8308376/magisk_patched-24303_zFdZU.zip)
[partitions_bla-l29_emui10.txt](https://github.com/topjohnwu/Magisk/files/8308377/partitions_bla-l29_emui10.txt)

**Comment by yujincheng08** [comment] 2022-03-19 02:05
We need dmesg if the device wont boot.

**Comment by user456789** [comment] 2022-03-19 02:25
I flashed the ramdisk with 24303 again, let it crash to fastboot, flashed 24300 again and took the log. I hope that was the way.

[dmesg.log](https://github.com/topjohnwu/Magisk/files/8308442/dmesg.log)

**Comment by yujincheng08** [comment] 2022-03-19 02:33
No. That's not the way. As long as you flash 24300, dmesg is for 24300. You should find last_kmsg or ramoops

**Comment by user456789** [comment] 2022-03-19 02:49
I found this one. Sorry Android is still a jungle for me.

[console-ramoops-0.txt](https://github.com/topjohnwu/Magisk/files/8308479/console-ramoops-0.txt)

**Comment by yujincheng08** [comment] 2022-03-19 04:20
Duplicate of #5607

**Comment by yujincheng08** [comment] 2022-03-19 04:20
I will follow this in the duplicated issue.

**Closed by yujincheng08** 2022-03-19 04:20 UTC

**Comment by qianmo-xw** [comment] 2022-06-05 12:46
> Device: Huawei Mate 10 Pro (BLA-L29) Android version: 10 (EMUI 10.0.0.202(C432E9R1P3)) Magisk version name: Canary Magisk version code: 24303
> 
> I've got the same problem as described in here: #4772
> 
> With current stable version 24300 the device boots and Magisk itself is working fine but the hw_product partition is not mounted.
> 
> When I tried Canary version 24303, which should include a fix as I understand it for #4772, the device reboots directly back to fastboot.
> 
> [RAMDISK.zip](https://github.com/topjohnwu/Magisk/files/8308369/RAMDISK.zip) [magisk_install_log_2022-03-19T01:30:51_24303.log](https://github.com/topjohnwu/Magisk/files/8308370/magisk_install_log_2022-03-19T01.30.51_24303.log) [magisk_install_log_2022-03-19T01:33:45_24300.log](https://github.com/topjohnwu/Magisk/files/8308371/magisk_install_log_2022-03-19T01.33.45_24300.log) [magisk_log_2022-03-19T01:30:57_24303_unpatched.log](https://github.com/topjohnwu/Magisk/files/8308372/magisk_log_2022-03-19T01.30.57_24303_unpatched.log) [magisk_log_2022-03-19T01:33:50_24300_unpatched.log](https://github.com/topjohnwu/Magisk/files/8308373/magisk_log_2022-03-19T01.33.50_24300_unpatched.log) [magisk_log_2022-03-19T02:13:13_24300_patched.log](https://github.com/topjohnwu/Magisk/files/8308374/magisk_log_2022-03-19T02.13.13_24300_patched.log) [magisk_patched-24300_IOYqj.zip](https://github.com/topjohnwu/Magisk/files/8308375/magisk_patched-24300_IOYqj.zip) [magisk_patched-24303_zFdZU.zip](https://github.com/topjohnwu/Magisk/files/8308376/magisk_patched-24303_zFdZU.zip) [partitions_bla-l29_emui10.txt](https://github.com/topjohnwu/Magisk/files/8308377/partitions_bla-l29_emui10.txt)

hey,bro,how can you unlock bootloader on emui10？any method？
