### ISSUE TITLE
25207 completely breaks

### ISSUE THREAD

**Issue by Originalimoc** [topjohnwu/Magisk#6645] opened 2023-02-27 13:36 UTC
Device: Redmi K30 Pro
Android version: 12
Magisk version name: 7dbfba7
Magisk version code: 25207

issue 6637 related maybe

MIUI 13/14
Android 12
Not obfs manager package name
fresh img flash or recovery install
can't launch manager
even freeze system

**Comment by Originalimoc** [comment] 2023-02-27 13:38
su (toast) and mounting still working though

**Comment by canyie** [comment] 2023-02-27 13:55
Duplicate of #6637

**Closed** 2023-02-27 13:55 UTC
Labels: duplicate
