### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by lollilol** [topjohnwu/Magisk#5039] opened 2021-12-11 12:02 UTC
Device: Sony Xperia 1 III (XQ-BC52)
Android version: 11
Magisk version name: 5d6d2417
Magisk version code: 23015

After successfully installing a module and pressing the system "back" button or the back button on the top right, magisk does to the home page instead of staying on the modules page. This is very annoying since when i'm installing 5-10 modules from zips i always have to switch to the modules page again. In Magisk 23000 Stable this wasn't the case.

**Comment by akano12** [comment] 2021-12-11 12:35
> Device: Sony Xperia 1 III (XQ-BC52) Android version: 11 Magisk version name: [5d6d241](https://github.com/topjohnwu/Magisk/commit/5d6d241791ed096c51440b0ae410d1b23aa25101) Magisk version code: 23015
> 
> After successfully installing a module and pressing the system "back" button or the back button on the top right, magisk does to the home page instead of staying on the modules page. This is very annoying since when i'm installing 5-10 modules from zips i always have to switch to the modules page again. In Magisk 23000 Stable this wasn't the case.

duplicate of https://github.com/topjohnwu/Magisk/issues/4333

**Closed** 2021-12-11 14:03 UTC
