### ISSUE TITLE
Flashing from V19.4 to v24.1 Gives Bootloop & V19.3 working but gives only "magisk su" permissions not modules support

### ISSUE THREAD

**Issue by jnelson89** [topjohnwu/Magisk#5466] opened 2022-02-16 02:35 UTC
Device: Vivo V5
Android: 6.0
Magisk version name: magisk canary 25
Magisk version code: 24102

I flashed all latest versions via patch boot.img from v19.4 to v24.1 all giving bootloop (Maybe bcoz of overlay.d)
. So, I tried flashing v19.3 and it flashed successfully without any bootloop but the problem is that it wont installed magisk fully, I have access to only "magisk su", I mean root access only, not modules or even magisk hide which was present in v19.3!! I even read about this issue in the old issues but everyone got fixed when they updated to new version but here I'm facing a whole new issues which is I'm unable to flash new version of magisk and old are not fully working!!
**P.S: I can't flash magisk via recovery bcoz my device doesn't have custom recovery. So, flashing only via fastboot with unlocked bootloader.**
![Screenshot_20220216_074551](https://user-images.githubusercontent.com/86909284/154185414-7a696488-c02f-412c-bfb8-89b952dca22a.png)

**Comment by jnelson89** [comment] 2022-02-16 02:47
@canyie Looking for your help btw!

**Comment by TsXor** [comment] 2022-02-17 13:06
Note that the latest magisk manager cannot recognize early versions of magisk. So if you need to test whether v19.3 is working or not, you should install Magisk Manager v8.0.7 (can be found in releases)
*I do not recommend to compile the manager app yourself because it is hard to do it now due to the sunset of bintray.

**Comment by jnelson89** [comment] 2022-02-17 17:08
> Note that the latest magisk manager cannot recognize early versions of magisk. So if you need to test whether v19.3 is working or not, you should install Magisk Manager v8.0.7 (can be found in releases) *I do not recommend to compile the manager app yourself because it is hard to do now due to the sunset of bintray.

I used version 8.0.7 but no magisk detection but su only working!!

**Comment by TsXor** [comment] 2022-02-17 17:53
Ohh... You can check if magisk daemon is running&nbsp;
by executing `magisk -v`.

---Original---
From: ***@***.***&gt;
Date: Fri, Feb 18, 2022 01:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [topjohnwu/Magisk] Flashing from V19.4 to v24.1 Gives Bootloop &amp; V19.3 working but gives only "magisk su" permissions not modules support (Issue #5466)




  
Note that the latest magisk manager cannot recognize early versions of magisk. So if you need to test whether v19.3 is working or not, you should install Magisk Manager v8.0.7 (can be found in releases) *I do not recommend to compile the manager app yourself because it is hard to do now due to the sunset of bintray.
  
I used version 8.0.7 but no magisk detection but su only working!!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jnelson89** [comment] 2022-02-17 23:34
**Maybe... Checkout this**
![Screenshot_20220218_050207](https://user-images.githubusercontent.com/86909284/154589353-9025933a-bcc3-4301-a127-c0d0a0b3d522.png)

**Comment by jnelson89** [comment] 2022-02-17 23:36
> Ohh... You can check if magisk daemon is running&nbsp; by executing `magisk -v`.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Feb 18, 2022 01:08 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [topjohnwu/Magisk] Flashing from V19.4 to v24.1 Gives Bootloop &amp; V19.3 working but gives only "magisk su" permissions not modules support (Issue #5466) Note that the latest magisk manager cannot recognize early versions of magisk. So if you need to test whether v19.3 is working or not, you should install Magisk Manager v8.0.7 (can be found in releases) *I do not recommend to compile the manager app yourself because it is hard to do now due to the sunset of bintray. I used version 8.0.7 but no magisk detection but su only working!! — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

**Maybe... checkout this**
![Screenshot_20220218_050207](https://user-images.githubusercontent.com/86909284/154589528-fe114ece-62a4-403b-9ec3-7a8893f4ed1a.png)

**Comment by yujincheng08** [comment] 2022-02-18 00:35
Seems to be a duplicate of #5148

**Comment by jnelson89** [comment] 2022-02-18 05:15
> Seems to be a duplicate of #5148

**Really, Is there a fix for this yet?**

**Closed** 2022-02-18 17:51 UTC
