### ISSUE TITLE
Systemless hosts module doesn't work after magisk UPDATE!

### ISSUE THREAD

**Issue by RamuSriram** [topjohnwu/Magisk#6735] opened 2023-03-12 10:58 UTC
The Systemless Hosts module appears to be broken in the latest Magisk debug (981ccabb (25210)). Despite tapping on the 'Systemless Hosts' option, the module fails to add. Although a toast notification indicating 'Added systemless hosts' appears, the module does not appear in the modules list. Please refer to the attached screenshots for more information. Restarting the system was attempted, but the module remained absent. Additionally, there is no record of the module in the Magisk logs. Please also see the attached logcat file for further information.
![IMG_20230312_162325](https://user-images.githubusercontent.com/71754546/224539995-530179ad-f812-4f3f-aeeb-f7708f9a2e47.jpg)

Device: OnePlus 9RT
Android version: Android 13
Magisk version name: 981ccabb (25210) (D)
Magisk version code: 981ccabb (25210) (D)
[magisk_log_2023-03-12T16.26.36.log](https://github.com/topjohnwu/Magisk/files/10950629/magisk_log_2023-03-12T16.26.36.log)
[logcat_03-12-2023_15-58-36.txt](https://github.com/topjohnwu/Magisk/files/10950630/logcat_03-12-2023_15-58-36.txt)

**Comment by yujincheng08** [comment] 2023-03-12 13:45
Duplicate of #6688

**Closed by yujincheng08** 2023-03-12 13:45 UTC

**Comment by RamuSriram** [comment] 2023-03-12 15:45
> It is module bug and it has been solved, but not release yet. You can use CI build or downgrade to previous version and wait for 25211

Alright, thanks for letting me know.

**Comment by stanleylhs** [comment] 2023-03-21 20:49
@HuskyDG Pardon me, where can I find the CI build?
