### ISSUE TITLE
Magisk framework does no longer start up on Treble device since commit 0c99c4d93f638d5cde9a232321af791c54be278b

### ISSUE THREAD

**Issue by cawidtu** [topjohnwu/Magisk#4306] opened 2021-05-03 14:10 UTC
Device: Huawei P10 Plus, Vendor EMUI 8.0.0.386
Android version: 9 (OpenKirin LineageOs 16.0 Build 6, https://openkirin.net/download/)
Magisk version name: fb8000b5
Magisk version code: 22104

The latest Canary does not start the Magisk framework on my Treble device. Device is booting, but Magisk app displays Magisk as N/A and no su rights are available. The latest working stable version is 20.4, where Magisk starts and su access works. Already Magisk 21.0 fails to start up.

I did a binary search on the Magisk commit history. The problem seems to exist since commit 0c99c4d93f638d5cde9a232321af791c54be278b.  
Commit 8ab045331bf0055ef92a8ca4e26c66bf2108724f is the last one where Magisk starts. Note that this commit has the comment "Some custom treble use different names, so use what we read" in native/jni/init/mount.cpp; however, in the next commit this comment is gone.

Here is a list of the block devices on the phone. Thank you.

`
:/dev/block/platform/ff3b0000.ufs/by-name # ls -la
total 0
drwxr-xr-x 2 root root 1200 1970-04-06 11:20 .

drwxr-xr-x 4 root root 1320 1970-04-06 11:20 ..

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 bootfail_info -> /dev/block/sdd15

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 cache -> /dev/block/sdd13

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 cust_a -> /dev/block/sdd52

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 dfx -> /dev/block/sdd20

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 dto_a -> /dev/block/sdd40

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 dts_a -> /dev/block/sdd39

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 erecovery_kernel_a -> /dev/block/sdd31

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 erecovery_ramdisk_a -> /dev/block/sdd32

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 erecovery_vbmeta_a -> /dev/block/sdd45

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 erecovery_vendor_a -> /dev/block/sdd33

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 fastboot_a -> /dev/block/sdd25

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 frp -> /dev/block/sdc1

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 fw_hifi_a -> /dev/block/sdd29

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 fw_lpm3_a -> /dev/block/sdd22

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 hisee_fs -> /dev/block/sdd19

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 hisee_img_a -> /dev/block/sdd24

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 isp_boot_a -> /dev/block/sdd27

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 isp_firmware_a -> /dev/block/sdd28

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 kernel_a -> /dev/block/sdd35

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 misc -> /dev/block/sdd16

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 modem_fw_a -> /dev/block/sdd42

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 modem_om -> /dev/block/sdd7

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 modem_secure -> /dev/block/sdd3

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 modemnvm_backup -> /dev/block/sdd9

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 modemnvm_factory -> /dev/block/sdd8

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 modemnvm_img -> /dev/block/sdd10

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 modemnvm_system -> /dev/block/sdd11

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 modemnvm_update_a -> /dev/block/sdd47

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 nvme -> /dev/block/sdd4

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 odm_a -> /dev/block/sdd14

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 oeminfo -> /dev/block/sdd5

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 patch_a -> /dev/block/sdd48

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 persist -> /dev/block/sdc2

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 product_a -> /dev/block/sdd51

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 ramdisk_a -> /dev/block/sdd36

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 recovery_ramdisk_a -> /dev/block/sdd37

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 recovery_vbmeta_a -> /dev/block/sdd44

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 recovery_vendor_a -> /dev/block/sdd38

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 reserved1 -> /dev/block/sdc3

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 reserved10 -> /dev/block/sdd18

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 reserved2 -> /dev/block/sdd17

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 reserved3_a -> /dev/block/sdd23

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 reserved4_a -> /dev/block/sdd43

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 reserved5 -> /dev/block/sdd54

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 rrecord -> /dev/block/sdd21

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 secure_storage -> /dev/block/sdd6

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 sensorhub_a -> /dev/block/sdd34

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 splash2 -> /dev/block/sdd12

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 system_a -> /dev/block/sdd53

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 teeos_a -> /dev/block/sdd30

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 trustfirmware_a -> /dev/block/sdd41

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 userdata -> /dev/block/sdd55

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 vbmeta_a -> /dev/block/sdd46

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 vector_a -> /dev/block/sdd26

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 vendor_a -> /dev/block/sdd50

lrwxrwxrwx 1 root root   16 1970-04-06 11:20 version_a -> /dev/block/sdd49

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 vrl -> /dev/block/sdd1

lrwxrwxrwx 1 root root   15 1970-04-06 11:20 vrl_backup -> /dev/block/sdd2
`

**Comment by lss4** [comment] 2021-05-05 03:49
Back then my Google Pixel C was broken at dbf8c412091c9abb6449d7fadb6ef7e6ca456563, which was 3 commits later than yours. (see #3021)

The cause at that time was the absence of `androidboot.hardware=<device>` in the kernel cmdline. The issue was eventually resolved on the kernel side, by actually adding that entry in the kernel cmdline so Magisk can correctly find the fstab.

I don't have a Huawei phone myself, but if you can get the `# cat /proc/cmdline` then it would be possible to know whether the issue is a duplicate of mine or not.

Still, as with #4297, I can't know whether Magisk has always been broken on OpenKirin since then, or it's only being broken recently. After all, the commits in question were about one year old.

**Comment by cawidtu** [comment] 2021-05-05 05:31
Thank you. I saw your issue 3021 before, but unfortunately it is not the same problem since the androidboot.hardware variable is set on my device:

`loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolat
e1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=e
nforcing buildvariant=user androidboot.swtype=normal fastboot_version=Chipset-ch
icago8.0.0.6(081T)_FASTBOOT setup_logctl=0 fastbootdmd=0 enter_recovery=0 androi
dboot.mode=normal pmu_nv_addr=0x20b20014 low_volt_flag=0 boardid=0x00001549 norm
al_reset_type=coldboot  TP_COLOR=225  COLOR_TMP=0 LCD_DENSITY=0  DDIC_INFO= ddr_
die=3072M@0M ddr_die=3072M@4096M  productid=0x3a032814 efuse_status=0 androidboo
t.serialno=QYJ7N17411002456 himntn=0111111111111010001011000000000000000010 boot
_slice=0x00059052 reboot_reason=coldboot last_bootup_keypoint=250 recovery_updat
e=0 userlock=unlocked androidboot.oemmode=user bootlock=unlocked hw_bfm_enable=1
 ddr_density=3 swiotlb=2 mdmreglogbase=0x00000000 mdmreglogsize=0x00000000 modem
_socp_enable=0 androidboot.hardware=hi3660 androidboot.veritymode=enforcing andr
oidboot.verifiedbootstate=ORANGE ufs_product_name=THGBF7T0L8LBATAC  format_data=
1 cpu_buck_reg=0x;;  LCD_ID=1 androidboot.ddrsize=6 oba_version=20190228180706_O
BA_VERSION kce_status=1   androidboot.vercnt1=2 bl1_time=2371 bl2_time=11172 log
o_time=3569 androidboot.slot_suffix=_a dsm_notify=1  console=ttyS0`

**Comment by lss4** [comment] 2021-05-05 06:06
> Thank you. I saw your issue 3021 before, but unfortunately it is not the same problem since the androidboot.hardware variable is set on my device:
> 
> `loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolat e1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=e nforcing buildvariant=user androidboot.swtype=normal fastboot_version=Chipset-ch icago8.0.0.6(081T)_FASTBOOT setup_logctl=0 fastbootdmd=0 enter_recovery=0 androi dboot.mode=normal pmu_nv_addr=0x20b20014 low_volt_flag=0 boardid=0x00001549 norm al_reset_type=coldboot TP_COLOR=225 COLOR_TMP=0 LCD_DENSITY=0 DDIC_INFO= ddr_ die=3072M@0M ddr_die=3072M@4096M productid=0x3a032814 efuse_status=0 androidboo t.serialno=QYJ7N17411002456 himntn=0111111111111010001011000000000000000010 boot _slice=0x00059052 reboot_reason=coldboot last_bootup_keypoint=250 recovery_updat e=0 userlock=unlocked androidboot.oemmode=user bootlock=unlocked hw_bfm_enable=1 ddr_density=3 swiotlb=2 mdmreglogbase=0x00000000 mdmreglogsize=0x00000000 modem _socp_enable=0 androidboot.hardware=hi3660 androidboot.veritymode=enforcing andr oidboot.verifiedbootstate=ORANGE ufs_product_name=THGBF7T0L8LBATAC format_data= 1 cpu_buck_reg=0x;; LCD_ID=1 androidboot.ddrsize=6 oba_version=20190228180706_O BA_VERSION kce_status=1 androidboot.vercnt1=2 bl1_time=2371 bl2_time=11172 log o_time=3569 androidboot.slot_suffix=_a dsm_notify=1 console=ttyS0`

Since you have that entry (`androidboot.hardware=hi3660`) in the cmdline, do you have a valid fstab file named `fstab.hi3660` anywhere on the device that Magisk could then pick it up?

**Comment by cawidtu** [comment] 2021-05-05 06:16
I found the following two occurrences

`/vendor/etc/fstab.hi3660
.sbin/.magisk/mirror/vendor/etc/fstab.hi3660`

The second one is probably made by Magisk (running in version 20.4 on my device)

The content of /vendor/etc/fstab.hi3660 is as follows:

`# Android fstab file.
#<src>                                                  <mnt_point>         <type>    <mnt_flags and options>                       <fs_mgr_flags>
# The filesystem that contains the filesystem checker binary (typically /system) cannot
# specify MF_CHECK, and must come before any filesystems that do specify MF_CHECK
/dev/block/bootdevice/by-name/system    /system    ext4     ro,barrier=1    wait,avb
/dev/block/bootdevice/by-name/splash2    /splash2   ext4     rw,nosuid,nodev,noatime,data=ordered,context=u:object_r:splash2_data_file:s0 wait,check
/dev/block/bootdevice/by-name/vendor    /vendor    ext4     ro,barrier=1    wait,avb
/dev/block/bootdevice/by-name/product   /product   ext4    ro    wait
/dev/block/bootdevice/by-name/version   /version   ext4    ro    wait
/dev/block/bootdevice/by-name/cust    /cust    ext4    ro    wait
/dev/block/bootdevice/by-name/odm    /odm    ext4    ro    wait
/dev/block/bootdevice/by-name/patch         /patch_hw                ext4      ro wait,verify
/devices/hi_mci.1/mmc_host/mmc1/*                       auto                auto      defaults                                      voldmanaged=sdcard:auto,noemulatedsd
/devices/platform/hi_mci.1/mmc_host/mmc1/*                       auto                auto      defaults                                      voldmanaged=sdcard:auto,noemulatedsd
/devices/ff200000.hisi_usb/ff100000.dwc3/*              auto                auto      defaults                                      voldmanaged=usbotg:auto
/devices/platform/ff200000.hisi_usb/ff100000.dwc3/*     auto                auto      defaults                                      voldmanaged=usbotg:auto
/dev/block/bootdevice/by-name/userdata         /data                f2fs      nosuid,nodev,noatime,discard,inline_data,inline_xattr wait,check,fileencryption=aes-256-xts:aes-256-cts
/dev/block/bootdevice/by-name/cache         /cache                ext4      rw,nosuid,nodev,noatime,data=ordered wait,check
/dev/block/bootdevice/by-name/misc       /misc       emmc      defaults        defaults
/dev/block/zram0             none         swap    defaults     zramsize=536870912
/dev/block/bootdevice/by-name/hisee_fs      /hisee_fs                ext4      ro,barrier=1,context=u:object_r:hisee_data_file:s0    wait,check
/dev/block/bootdevice/by-name/modem_secure      /modem_secure   ext4    rw,noauto_da_alloc,nosuid,nodev,noatime,data=ordered,barrier=1,context=u:object_r:modem_secure_file:s0  wait,check
`

**Comment by lss4** [comment] 2021-05-05 06:35
> I found the following two occurrences
> 
> `/vendor/etc/fstab.hi3660 .sbin/.magisk/mirror/vendor/etc/fstab.hi3660`
> 
> The second one is probably made by Magisk (running in version 20.4 on my device)
> 
> The content of /vendor/etc/fstab.hi3660 is as follows (sorry for the poor formatting, but the code tags do not work as expected with this content):

If you need to create a multi-line code block you need 3 backticks.

Guess the issue you're having is not really the same as the one I had. On the other hand, I think there are some Kirin-related stuffs going on as when processing `androidboot.hardware`, as your device is a `hi3660`, it set a flag named `kirin` to true.

**Closed** 2021-05-13 11:13 UTC
Labels: regression

**Comment by cawidtu** [comment] 2021-05-13 12:23
The issue is closed; however, even with the latest Canary (23001) I cannot see that the problem has been solved. Magisk does not start up, no traces of Magisk in the log etc. Version 20.4 works fine. It seems that the commit mentioned in the title ("More complete support for fstab in dt") introduced the problem; however, I am unable to figure out myself what exactly happened.

So is this a "won't fix" because Huawei devices are no longer fully supported?
