### ISSUE TITLE
Lastest Magisk Debug Issue

### ISSUE THREAD

**Issue by Master3lwa** [topjohnwu/Magisk#5908] opened 2022-06-03 20:01 UTC
Device: infinix x603 (Zero5) 
Android version:7.0
Magisk version name:2106751e
Magisk version code:24315 (30)D

I got an issue after upgrading to the latest version of magisk debug.. 
1- zygisk not working. 
2-superuser and module menu has been disabled. 
3- after restart the phone its not boot and open directly after a while. 
4- there's no root access on whole applications that needs root.
![Screenshot_20220603-213638](https://user-images.githubusercontent.com/48556367/171941585-199832e2-7288-4be1-8845-abd1fb9221e7.jpg)

Here's logs:
[Magisk.log](https://github.com/Master3lwa/MillYaro/blob/main/magisk_log_2022-06-03T21.36.48.log)

**Comment by yujincheng08** [comment] 2022-06-03 22:24
submit bugreport instead.

**Comment by pndwal** [comment] 2022-06-04 00:29
Just in case, is a previous 'hidden' Magisk app still set up? (Check in device settings, apps, for 'Settings' or whatever custom name you chose).

Nb. Hide the Magisk app function is also broken in latest Canary/Debug for many (all?) in this build...

**Comment by digiw** [comment] 2022-06-04 03:46
Me too, hide magicsk fuction was broken in last ver.2106751e

**Comment by macerg** [comment] 2022-06-04 06:22
Duplicate of  #5905

**Comment by vvb2060** [comment] 2022-06-04 15:16
no bugreport, close. repack issue should goto 5905

**Closed by vvb2060** 2022-06-04 15:16 UTC
