### ISSUE TITLE
Manager crash trying to access Modules list with specific numbers of directories

### ISSUE THREAD

**Issue by QuinTeknoLife** [topjohnwu/Magisk#2631] opened 2020-03-31 02:09 UTC
The title of this report should suffice, but if it doesn't I have screen capped what is happening and dumped it [here. ](https://photos.app.goo.gl/8bQ36G6oQj1yd3dr7)

The magisk-logs you can find [here. ](https://drive.google.com/file/d/19s28bQfLOgJj50YUzIaRsgqSjJ6Z5gMp/view?usp=drivesdk) 

I am using a Samsung Galaxy S6 G920F with LineageOS 17.1 (android 10), both magisk and manager are on the latest canary builds.

If i have missed something or if you require more information/logs/corona lemme know 😊

**Comment by osm0sis** [comment] 2020-03-31 02:29
A logcat of the crash would be helpful. Only a small number of devices seem to have this issue.

**Comment by HTAEDFOLEGNA** [comment] 2020-03-31 10:07
[magisk_log_20200331_120627.log](https://github.com/topjohnwu/Magisk/files/4408278/magisk_log_20200331_120627.log)
Here is a log and I have the same issue

**Comment by diareuse** [comment] 2020-03-31 10:21
We need a [logcat](https://play.google.com/store/search?q=logcat) not a magisk log as it doesn't contain all the necessary information for this particular crash. Make sure to note the exact time when the crash occurred and paste both it here. Thanks.

**Comment by kevin01523** [comment] 2020-03-31 10:36
![Screenshot_20200331-183219](https://user-images.githubusercontent.com/8380242/78017162-75580e00-737e-11ea-8bd3-b8f7b773346c.jpg)
Redmi note 6 pro 
Havoc os 3.3
Android 10

**Comment by Charaktor** [comment] 2020-03-31 10:55
I got the same problem. Pixel 4, March patch, latest canary.
[logcat_03-31-2020_12-54-19.txt](https://github.com/topjohnwu/Magisk/files/4408521/logcat_03-31-2020_12-54-19.txt)

**Comment by datsoy** [comment] 2020-03-31 13:54
here's mine. Oneplus6t Android Q 10.3.2
[logcat_03-31-2020_21-49-24.txt](https://github.com/topjohnwu/Magisk/files/4409450/logcat_03-31-2020_21-49-24.txt)

**Comment by xdMatthewbx** [comment] 2020-03-31 22:14
[logcat.txt](https://github.com/topjohnwu/Magisk/files/4411801/logcat.txt)
same here
latest canary manager 5537b083 (282) & magisk ef9d077c (20401), oneplus 7 pro, latest official havoc os 3.3 march 29 build

**Comment by kevin01523** [comment] 2020-03-31 23:39
Doesn't crash when on safety mode.i managed to find out that some modules may be the cause of crashes for me. It does crash if  i got app systemizer module and riru storage isolation module installed.it does still crash even if data or wifi is off for me

**Comment by osm0sis** [comment] 2020-03-31 23:54
Thanks all. We're good for logs now. I can reproduce it on both my Galaxy Nexus (Lineage Marshmallow) and OnePlus 5 (Pixel Experience Pie). :+1:

It's definitely that java.lang.ArrayIndexOutOfBoundsException error.

**Comment by QuinTeknoLife** [comment] 2020-04-01 00:20
I do not know if 5537b083(282)(9) is supposed to address this or whether it's unrelated but the problem is still there, just saying 🤓

**Comment by osm0sis** [comment] 2020-04-01 01:20
If one hour ago I'm saying I reproduced the issue, then you know 282 is still effected.

**Comment by QuinTeknoLife** [comment] 2020-04-01 03:54
> If one hour ago I'm saying I reproduced the issue, then you know 282 is still effected.

Touché lol

**Comment by HTAEDFOLEGNA** [comment] 2020-04-01 19:35
Is it fixed yet or do you need a logcat from s10 plus too

**Comment by QuinTeknoLife** [comment] 2020-04-01 19:38
> Thanks all. We're good for logs now. I can also reproduce it on both my Galaxy Nexus (Lineage Marshmallow) and OnePlus 5 (Pixel Experience Pie). 
> 
> It's definitely that java.lang.ArrayIndexOutOfBoundsException error.

@HTAEDFOLEGNA When it's fixed someone on the dev team will close this issue

**Comment by HTAEDFOLEGNA** [comment] 2020-04-01 20:32
[magisk_logcat_04-01-2020_22-25-06.txt](https://github.com/topjohnwu/Magisk/files/4417457/magisk_logcat_04-01-2020_22-25-06.txt)
LOGCAT from s10plus using...
![Screenshot_20200401-223020](https://user-images.githubusercontent.com/43749122/78183608-7b2a1e00-7468-11ea-80eb-2e6b119f4430.jpg)
Don't mean to keep bugging but I have bluetooth issues too so if you fix this problem maybe I can actually modules to fix my Bluetooth problem...so I hope this logcat helps is all I saying

**Comment by 1tuanhasan** [comment] 2020-04-01 20:37
😂

**Comment by QuinTeknoLife** [comment] 2020-04-05 00:13
decided to do some more testing, removed all installed modules using mm while in TWRP, and suddenly the crashing doesn't occur anymore. I shall now one by one add the modules back and report back what I might find.

**Comment by QuinTeknoLife** [comment] 2020-04-05 00:38
BINGO!! I have found the scoundrel that causes this issue (for me)! 

It ended up being MagiskHidePropsConf which was making manager crash.

**Comment by xdMatthewbx** [comment] 2020-04-05 00:50
i used mm in twrp and it just sort of fixed itself, didnt install or uninstall anything other than mm

**Comment by QuinTeknoLife** [comment] 2020-04-05 00:53
> i used mm in twrp and it just sort of fixed itself, didnt install or uninstall anything other than mm

mm does nothing (besides letting me do what it should) like that for me lol, I love mm (anything CLI in general), has been a livesaver for bootlooping modules so many times

**Comment by osm0sis** [comment] 2020-04-05 01:26
I have one device with a bunch of modules crashing and one with none crashing, so I don't think it's directly related to that.

**Comment by Aduser345** [comment] 2020-04-07 05:54
I noticed something that you can access the modules tab if you quickly press the button after the opening Magisk manager

**Comment by osm0sis** [comment] 2020-04-08 00:58
> I noticed something that you can access the modules tab if you quickly press the button after opening Magisk manager

Weird, can confirm that on my OP5!

@diareuse, any chance that helps narrow down the cause of the java.lang.ArrayIndexOutOfBoundsException error?

**Comment by Aduser345** [comment] 2020-04-08 05:00
Yeah it is weird but fif one switches to other tab and then back it crashes 😅😅

**Comment by diareuse** [comment] 2020-04-08 08:34
That unfortunately doesn't help at all. I know where the issue is, what it causes, but I don't know how to fix it yet.

**Comment by WrichikBasu** [comment] 2020-04-08 15:17
On my Samsung Galaxy On7 running API 23, I faced the same issue. It was working fine until I uninstalled the Energized module. After reboot, when I go to the Modules tab, the app instantly crashes.

Here is a logcat obtained using Android Studio. The crash was triggered at around 20:26:44 where you can see the `ArrayIndexOutOfBoundsException`.

[manager_canary_logcat.txt](https://github.com/topjohnwu/Magisk/files/4451284/manager_canary_logcat.txt)

The following is the logcat that has been filtered using "com.topjohnwu.magisk". However, it is at a different time. Note that this one does not show the above exception, but shows that the app has died.

[magisk_canary_manager_filtered_log.txt](https://github.com/topjohnwu/Magisk/files/4451298/magisk_canary_manager_filtered_log.txt)

**Comment by osm0sis** [comment] 2020-04-09 00:01
I was able to stop the crash on my Galaxy Nexus by going from 8 modules down to 7. 🤔

**Comment by osm0sis** [comment] 2020-04-09 01:40
@topjohnwu @diareuse 

The conditions to trigger the crash are having exactly 8 or 9 modules. Less than 8, or greater than 9 and it works fine. This shouldn't be too hard to fix, knowing this.

**Comment by h4rl0ck48** [comment] 2020-04-09 01:58
> @topjohnwu @diareuse 
> 
> The conditions to trigger the crash are having exactly 8 or 9 modules. Less than 8, or greater than 9 and it works fine. This shouldn't be too hard to fix, knowing this.

Really helpful, modules are working again¡😁

**Comment by QBANIN** [comment] 2020-04-09 10:02
> @topjohnwu @diareuse
> 
> The conditions to trigger the crash are having exactly 8 or 9 modules. Any device I've tried. Less than 8, or greater than 9 and it works fine. This shouldn't be too hard to fix, knowing this.

Well, not in my case. I have 16 modules active + 2 disabled but Manager v282 keeps crashing then trying to access module list.

**Comment by osm0sis** [comment] 2020-04-09 14:05
Ah, there might be other "magic" numbers..

**Comment by osm0sis** [comment] 2020-04-09 15:39
Turns out this is an old bug, originally introduced with the redesign in 270, reported in #2300, and fixed in 272.

It remained fixed as recently as 279, but has been mysteriously broken again starting with 280.

**Comment by Aduser345** [comment] 2020-04-09 17:51
I don't have any crashes when I switched to custom rom and reinstalled all modules that I was using before when it was crashing on stock rom. Does this help?

**Comment by gudenau** [comment] 2020-04-10 02:08
For me the crashes don't have any pattern at all. Before I'd have to go into the module tab dozens of times before it wouldn't crash. Different amounts of time waiting on the main screen didn't change my chances of crashing.

**Comment by osm0sis** [comment] 2020-04-11 15:48
@diareuse tracked down the underlying bug and will be pushing a fix branch/PR soon. Next Manager Canary after that should work! :+1:

**Comment by WrichikBasu** [comment] 2020-04-11 16:18
> @diareuse tracked down the underlying bug and will be pushing a fix branch/PR soon. Next Manager Canary after that should work! 👍

Just out of curiosity, where was the bug?

**Comment by diareuse** [comment] 2020-04-11 16:19
The thorough explanation will be posted in the commit message. Please be patient.

**Closed** 2020-04-12 12:40 UTC
Labels: bug

**Comment by osm0sis** [comment] 2020-04-19 13:09
Canary with the fix is now out! 👏
