### ISSUE TITLE
Magisk Manager freezes

### ISSUE THREAD

**Issue by anonymix007** [topjohnwu/Magisk#7164] opened 2023-07-16 00:37 UTC
Device: Red Magic 8 Pro
Android version: 13
Magisk version name: Debug
Magisk version code: 26103 

Seems to be the same as #6515, but it was closed as stale. 
[logcat.zip](https://github.com/topjohnwu/Magisk/files/12063057/logcat.zip)
[anr.zip](https://github.com/topjohnwu/Magisk/files/12063058/anr.zip)

**Comment by yujincheng08** [comment] 2023-08-04 16:56
@anonymix007 @badnng 
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/12262897/app-debug.zip)
Please use this ver to grab logcat (rename .zip -> .apk)

**Comment by anonymix007** [comment] 2023-08-04 19:49
[logcat.zip](https://github.com/topjohnwu/Magisk/files/12264165/logcat.zip)

**Comment by badnng** [comment] 2023-08-06 10:24
> @anonymix007 @badnng [app-debug.zip](https://github.com/topjohnwu/Magisk/files/12262897/app-debug.zip) Please use this ver to grab logcat (rename .zip -> .apk)

But he's back to normal. Thank you~
I'm using the stable version,is done and not freeze
:)

**Comment by yujincheng08** [comment] 2023-08-06 16:41
```
08-04 22:35:37.558  1662  1662 D Zygote  : Forked child process 15984
08-04 22:35:37.559  2883  2933 I ActivityManager: Start proc 15984:com.topjohnwu.magisk/u0a234 for activityPre com.topjohnwu.magisk

08-04 22:35:37.858 16061 16061 D AndroidRuntime: Calling main entry com.topjohnwu.superuser.internal.RootServerMain
...
08-04 22:35:47.998 16061 16061 W IPC     : Shutting down...
08-04 22:35:47.998 16061 16061 W IPC     : java.lang.RuntimeException
08-04 22:35:47.998 16061 16061 W IPC     : 	at com.topjohnwu.superuser.internal.d.start(Unknown Source:7)
08-04 22:35:47.998 16061 16061 W IPC     : 	at java.lang.Runtime.exit(Runtime.java:153)
08-04 22:35:47.998 16061 16061 W IPC     : 	at java.lang.System.exit(System.java:1488)
08-04 22:35:47.998 16061 16061 W IPC     : 	at com.topjohnwu.superuser.internal.RootServiceServer.exit(RootServiceServer.java:300)
08-04 22:35:47.998 16061 16061 W IPC     : 	at com.topjohnwu.superuser.internal.RootServiceServer.run(RootServiceServer.java:124)
08-04 22:35:47.998 16061 16061 W IPC     : 	at android.os.Handler.handleCallback(Handler.java:942)
08-04 22:35:47.998 16061 16061 W IPC     : 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-04 22:35:47.998 16061 16061 W IPC     : 	at android.os.Looper.loopOnce(Looper.java:242)
08-04 22:35:47.998 16061 16061 W IPC     : 	at android.os.Looper.loop(Looper.java:374)
08-04 22:35:47.998 16061 16061 W IPC     : 	at com.topjohnwu.superuser.internal.RootServerMain.main(Unknown Source:50)
08-04 22:35:47.998 16061 16061 W IPC     : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-04 22:35:47.998 16061 16061 W IPC     : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:478)
08-04 22:35:47.998 16061 16061 I com.topjohnwu.magisk:root:0: System.exit called, status: 0
08-04 22:35:47.998 16061 16061 I AndroidRuntime: VM exiting with result code 0.
...
08-04 22:45:53.385  2883  2920 I ActivityManager: Killing 15984:com.topjohnwu.magisk/u0a234 (adj 900): remove task
```

**Comment by yujincheng08** [comment] 2023-08-06 17:50
https://github.com/topjohnwu/libsu/blob/4032a4d6bc23840bbb3a0cc8234fdcbeab278895/service/src/main/java/com/topjohnwu/superuser/internal/RootServiceServer.java#L117

**Comment by anonymix007** [comment] 2023-08-06 22:06
@yujincheng08 I think (but not totally sure) that this is caused by some sort of task killer. I remember that I've seen "Phone has been accelerated" message and there was a long delay between Manager being opened second time.

 It seems that I can get the same `com.topjohnwu.superuser.internal.d.start` line in logs if I do the following (in termux as root, works almost every time):
1. Open Manager to make sure if work fine now and minimize it
2. Run `kill $(pidof com.topjohnwu.magisk)`
3. Manager no longer works
Repeating step 2 fixes the manager almost every time (sometimes it needs to be repeated few times)

While it's not reasonable to expect `kill` to work (and why would someone do it), it seems that OS did it and it needs to be handled somehow.

**Comment by yujincheng08** [comment] 2023-08-07 05:29
look at my quoted log https://github.com/topjohnwu/Magisk/issues/7164#issuecomment-1666915533

Magisk was killed after 10min. So it's not what u said.

The most likely reason is that the broadcast was delayed. But I cannot see any log about it.

**Comment by yujincheng08** [comment] 2023-09-03 03:16
duplicate of #7214

**Closed by yujincheng08** 2023-09-03 03:16 UTC
Labels: needs investigation

**Comment by Mdmahim20** [comment] 2023-09-03 03:23
Hi

**Comment by anonymix007** [comment] 2023-09-07 11:01
@yujincheng08 should this be fixed in 26301?
If so then please reopen. It still happens after night:
[magisk.log.zip](https://github.com/topjohnwu/Magisk/files/12547811/magisk.log.zip)
Seems that killing both `com.topjohnwu.magisk:root:0` and its parent also does the same:
[magisk.log.zip](https://github.com/topjohnwu/Magisk/files/12547875/magisk.log.zip)
