### ISSUE TITLE
Redmi note 7 pro miui 11 version 11.0.8 went into boot loop.

### ISSUE THREAD

**Issue by san325** [topjohnwu/Magisk#3299] opened 2020-10-08 12:59 UTC
sir, 
Redmi note 7 pro miui 11 version 11.0.8 went into
after flashing magisk zip 21.0 beta update. 
I request you to fix the problem. i update from 20.4 to 21.0. and then i downgrade to 20.4 to fix.

**Comment by Didgeridoohan** [comment] 2020-10-08 13:07
I'm curious how you expect possible problems to be fixed without providing any kind of useful information (logs)?

And may I suggest that you need to be careful with how you express yourself. Saying that you "request" John to fix the problem is very rude and demanding. A but more humility might be in order...

**Closed** 2020-10-08 18:48 UTC
