### ISSUE TITLE
Magisk canary 26103 cannot patch Android 14 Beta 4 on P6P

### ISSUE THREAD

**Issue by lssong99** [topjohnwu/Magisk#7157] opened 2023-07-12 10:13 UTC
Device: Pixel 6 Pro
Android version: Android 14 Beta 4
Magisk version name: a8c4a33e
Magisk version code: 26103

It seems Magisk canary 26103 is not able to patch the boot.img of Android 14 Beta 4 of Pixel 6 Pro. However, other user reports canary 26102 or stable 2100 could. 

The log from failed 26103 installation as follow

```- Device platform: arm64-v8a
- Installing: a8c4a33e (26103)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/[data/user_de/0/f.kmi.nf/install/boot.img](http://data/user_de/0/f.kmi.nf/install/boot.img)]
HEADER_VER      [4]
KERNEL_SZ       [25056616]
RAMDISK_SZ      [0]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [lz4_legacy]
VBMETA
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
resetprop: get prop [ro.crypto.state]: [encrypted]
�preinit device: metadata
- Pre-init storage partition: metadata
�Add file [init] (100750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add file [overlay.d/sbin/magisk32.xz] (100644)
Add file [overlay.d/sbin/magisk64.xz] (100644)
Add file [overlay.d/sbin/stub.xz] (100644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Failed to process cpio: No such file or directory (os error 2)
! Unable to patch ramdisk
! Installation failed```

**Comment by yujincheng08** [comment] 2023-07-12 12:25
Duplicate of https://github.com/topjohnwu/Magisk/issues/7109

**Closed by yujincheng08** 2023-07-12 12:25 UTC
