### ISSUE TITLE
Canary force closes on open

### ISSUE THREAD

**Issue by jacbrooks** [topjohnwu/Magisk#6649] opened 2023-02-28 02:48 UTC
Device: Pixel 7 Pro
Android version: 13 QPR 2.3
Magisk version name: Debug
Magisk version code: 25207

Canary, Beta & Stable force close but Debug does not. ``
[Log_2023-02-27_21-14-39.txt](https://github.com/topjohnwu/Magisk/files/10846100/Log_2023-02-27_21-14-39.txt)

**Comment by canyie** [comment] 2023-02-28 03:11
Duplicate of #6637

**Closed by canyie** 2023-02-28 03:11 UTC
