### ISSUE TITLE
[nougat] Magisk loses root since 26 on nougat by simply switching tabs in MM

### ISSUE THREAD

**Issue by Ph0rk0z** [topjohnwu/Magisk#8573] opened 2024-11-22 16:41 UTC
Device: vs995 (LGV20)
Android version: 7.0 Nougat
Magisk version name: 28001
Magisk version code: 28001

Am stuck running rom based on carrier for volte support. It is odexed and doesn't boot when I deodex it or even any of the framework. Need xposed of some sort to sign microg. Using magisk 23.0 root is fine. Newer magisk all lose root when wifi is connected/enabled or simply when I go to magisk manager and switch between superuser and logs button a few times. After that log is empty and no apps have superuser.

I have tried from 26-28 all without success. Cannot see any error in logcat. If I never open MM root seems fine for a while. Thought it was related to zygisk but it's not. Have heard rumor that it's related to MK2000 kernel but don't see how since it works from boot if untouched. How can I troubleshoot this further, I'd really like to be able to use newer magisk and modules, don't care about detectability, just root management.

**Comment by canyie** [comment] 2024-11-23 03:49
Hello, yeah, it's me again...
This looks like a duplicate of #6914 ?

**Comment by Ph0rk0z** [comment] 2024-11-23 13:29
That does sound like the likely reason. Kernel isn't AOSP though. I guess it's not fixable.

**Closed** 2024-12-28 01:46 UTC
