### ISSUE TITLE
Bootloop with patched boot.img image on Samsung Galaxy S9+ (Android 10)

### ISSUE THREAD

**Issue by mengjie0718** [topjohnwu/Magisk#5656] opened 2022-03-29 04:21 UTC
Device: Samsung Galaxy S9+/SM-G9650 (Snapdragon)
Android version:10
Magisk version name: canary
Magisk version code: 24304
this device bootloops with the latest canary version  and  no way to collect kernel log without root.
boot.img :
[boot.img.zip](https://github.com/topjohnwu/Magisk/files/8368017/boot.img.zip)
`cat /proc/mounts`
[monts.txt](https://github.com/topjohnwu/Magisk/files/8368024/monts.txt)

**Comment by yujincheng08** [comment] 2022-03-29 06:46
Duplicate of #5624

**Closed by yujincheng08** 2022-03-29 06:46 UTC
