### ISSUE TITLE
[24201] failing to update Magisk

### ISSUE THREAD

**Issue by madduck** [topjohnwu/Magisk#5544] opened 2022-03-05 15:28 UTC
I just installed 24201 (Canary) in the hope of addressing/resolving https://github.com/topjohnwu/Magisk/issues/4174[](https://user-images.githubusercontent.com/195073/156877079-04268fd7-d1e7-4985-98cf-c69bd47b45a7.png). When launching, I am now shown that Magisk is installed, although the app itself still has a N/A next to the latest version:
![image](https://user-images.githubusercontent.com/195073/156889743-1692fa68-9edc-4d32-b913-ecd0529de29b.png)
I was asked at first launch whether to update. However, when I confirmed, as well as if I click that Update button now, select to patch vbmeta in boot.img (which I used to have to do), and then choose the Direct Installation method, the install fails:

! Installation failed
! Unable to detect target image

The problem persists if I try without "vbmeta in boot".

The patch method does seem to work, however.

Device: Oneplus 5T
Android version: 11
Magisk version name: canary
Magisk version code: 24201

**Comment by rootk1t** [comment] 2022-03-07 10:45
I faced the same issue with Magisk v24.2

Magisk App updated without issues to v24.2.

1. When i click update as in screenshot above, it stopps with error
! Installation failed
! Unable to detect target image
2. I entered TWRP 3.6.0, tried installing Magisk-v24.2.apk (with and without renaming to .zip).
It says:

Magisk 24.2 Installer
! Cannot mount /system
- Unmounting partitions

Update process ended with ERROR: 1
Error installing zip file "path/Magisk-v24.2.zip"

3. I tried to patch boot.img within Magisk App. It patches it without issues, but after flashing it via TWRP, Magisk Manager asks to perform some additional setup when opened, and reboot.
After reboot is asks the same again and again.

The same happens to the latest canary as well.

At the same time Magisk-v24.1.apk installs without issues within Android or TWRP.

Device: Sony Tablet Z
Android version: 9.0
Magisk version name: canary
Magisk version code: 24200

**Comment by canyie** [comment] 2022-03-07 12:19
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8197571/app-debug.zip)
How about this? Reverted #5524 .

**Comment by rootk1t** [comment] 2022-03-07 14:02
Thank you for your build.

Unfortunately it didn't work for me.

As official v24.2 it stopps with an error in Magisk Manager: 
"! Installation failed
! Unable to detect target image"

And from TWRP it shows

"! Cannot mount /system

 Unmounting partitions

Update process ended with ERROR: 1
Error installing zip file "path/app-debug.zip"

**Comment by BlueMax** [comment] 2022-03-13 17:45
> As official v24.2 it stopps with an error in Magisk Manager: "! Installation failed ! Unable to detect target image"

Are you sure you haven't accidentally pointed the `app-debug.zip` to it (instead of boot.img)? I once did and i think it was the same error.
 
> And from TWRP it shows
> Update process ended with ERROR: 1 Error installing zip file "path/app-debug.zip"

I get the same on TWRP 3.6.1 with Magisk 24.3 so something seems to be still wrong there.
I updated to v24.3 manager first, pre-patched the boot.img and flashed it with dd in TWRP. That worked for me (I9506, Linux 3.4, LOS18.1).

**Comment by canyie** [comment] 2022-03-17 04:35
Have you installed magisk alpha? Revert to official version and try again.

**Comment by yujincheng08** [comment] 2022-03-19 06:38
Duplicate of #5530

**Closed by yujincheng08** 2022-03-19 06:38 UTC
Labels: regression

**Comment by yujincheng08** [comment] 2022-03-19 17:18
Try #5620
