### ISSUE TITLE
 mount /data/adb/modules ->  failed

### ISSUE THREAD

**Issue by atimofeev86** [topjohnwu/Magisk#6729] opened 2023-03-11 10:57 UTC
Device: samsung S10+
Android version: 13
Magisk version name: 981ccabb
Magisk version code: 25210

magisk version 25210 don't mount modules:
03-11 12:52:48.013  6069  6071 E : mount /data/adb/modules -> /dev/Pkr/.magisk/modules failed with 2: No such file or directory
03-11 12:52:48.013  6069  6071 E : mount (null) -> /dev/Pkr/.magisk/modules failed with 2: No such file or directory
03-11 12:52:48.013  6069  6071 E : mount (null) -> /dev/Pkr/.magisk/modules failed with 2: No such file or directory
[magisk_log_2023-03-11T12.54.17.log](https://github.com/topjohnwu/Magisk/files/10948303/magisk_log_2023-03-11T12.54.17.log)

version 25206 works

**Comment by fatalcoder524** [comment] 2023-03-11 11:51
Duplicate of #6688

**Comment by yujincheng08** [comment] 2023-03-11 16:34
Duplicate of #6688

**Closed by yujincheng08** 2023-03-11 16:34 UTC
