### ISSUE TITLE
Bootloop on Redmi Note 8 after updating to v25.1

### ISSUE THREAD

**Issue by Ben-Break** [topjohnwu/Magisk#6014] opened 2022-06-21 12:05 UTC
Device: Redmi Note 8 (ginkgo)
Android version: 12
ROM: Pixel Experience Plus
Magisk version name: 25.1
Magisk version code: 25101

After I updated from version 25.0 to 25.1 from the magisk app using direct install (as I have done previously), my phone is now stuck in a bootloop. I later tried installing the beta build and even a fix to #6000 but nothing has worked. The [last_kmsg](https://github.com/topjohnwu/Magisk/files/8948186/last_kmsg.txt) file from after I installed the latest debug build is down below, however, I could not get the boot.img as I have had issues with decrypting my files. Also, note that I have had magisk and a custom rom installed for about a year so it is not a problem on first install or anything like that.
Please feel free to ask for any more information/files if it is required, and thanks in advance to anyone that reads this!

[last_kmsg](https://github.com/topjohnwu/Magisk/files/8948186/last_kmsg.txt)

**Comment by BratSinot** [comment] 2022-06-21 16:05
Same here, why I upgrade before I saw issues -_-

**Comment by BratSinot** [comment] 2022-06-21 16:12
Okey, for me this https://github.com/topjohnwu/Magisk/issues/6000#issuecomment-1159733754 worked =)

**Comment by yujincheng08** [comment] 2022-06-22 04:15
Duplicate of #6000

**Closed by yujincheng08** 2022-06-22 04:15 UTC

**Comment by yujincheng08** [comment] 2022-06-22 05:25
oh wait its not the same. can you post the magisk patched boot image?

**Comment by Ben-Break** [comment] 2022-06-22 09:04
> can you post the magisk patched boot image?

As I quickly said before, my phone's files appear to be encrypted (I can't see them inside orangefox) and I haven't been able to find a fix for this, meaning I unfortunately can't see/pull the boot.img. I will try my best to find a way to decrypt it but I can't guarantee I will be able to. If anyone knows how I could fix this I would really appreciate it if you could help 👍

**Comment by Ben-Break** [comment] 2022-06-23 07:13
> oh wait its not the same. 

Could somebody please re-open this issue since it's not a duplicate?
Thanks 👍

**Comment by BratSinot** [comment] 2022-07-22 14:46
@TheRealIndru @yujincheng08 
Any news about this issue?

I got a but on #issuecomment-1159733754 build and I can't post issue because Bot close that issue because of version (#6117) -_-"

**Comment by TheRealIndru** [comment] 2022-08-18 20:48
> @TheRealIndru @yujincheng08 Any news about this issue?
> 
> I got a bug on [#issuecomment-1159733754](https://github.com/topjohnwu/Magisk/issues/6000#issuecomment-1159733754) build and I can't post issue because Bot close that issue because of version (#6117) -_-"

I simply remained on 24.3 and don't plan to update anymore. My terminal is pretty old anyway, might be the best thing to do.

**Comment by BratSinot** [comment] 2022-08-19 07:21
> @TheRealIndru @yujincheng08 Any news about this issue?
> 
> I got a bug on [#issuecomment-1159733754](https://github.com/topjohnwu/Magisk/issues/6000#issuecomment-1159733754) build and I can't post issue because Bot close that issue because of version (#6117) -_-"

v25.2 is ok for me.
