### ISSUE TITLE
Xperia Issues

### ISSUE THREAD

**Issue by Otral** [topjohnwu/Magisk#1537] opened 2019-06-01 05:40 UTC
[console-ramoops-0.zip](https://github.com/topjohnwu/Magisk/files/3243430/console-ramoops-0.zip)
更新19.1及之后的版本无限重启 附带刷19203后从/sys/fs/tore中提取的log

**Comment by 8lexliu** [comment] 2019-06-12 23:50
@topjohnwu hi, is there anything we can do to help you to identify the cause?

**Comment by MartinX3** [comment] 2019-06-13 19:38
Here is a pstore from a guy which get bootloops installing 18.1 on SODP based OmniROM (I don't know what is different on his device, while I can use 18.1, but he did fullwipes and reinstall ROM).
[console-ramoops-0.log](https://github.com/topjohnwu/Magisk/files/3287812/console-ramoops-0.log)

And here is my part

> Until 18.1 / 19.0 the installation of the magisk on a clean stock rom was fine.
> Since then it results into a bootloop.
> 
> The XZ2, XZ2C, XZ2P and XZ3 having this problem, seems that the [Xperia 1](https://github.com/topjohnwu/Magisk/issues/1574) (Our direct hardware successor) has the same problem.
> So I assume a sony stock firmware compatibility problem.
> 
> Luckily I was able to extract the `/sys/fs/pstore` in TWRP.
> I attached it:
> 
> Default stock setting in fstab for userdata -> crashing at Sony Logo
> `encryptable=ice`
> [console-ramoops-0.log](https://github.com/topjohnwu/Magisk/files/3276795/console-ramoops-0.log)
> 
> Modified stock setting in fstab for userdata -> crashing at Powered by Android logo
> `encryptable=footer`
> [console-ramoops-0.log](https://github.com/topjohnwu/Magisk/files/3276877/console-ramoops-0.log)
> [dmesg-ramoops-0.log](https://github.com/topjohnwu/Magisk/files/3276878/dmesg-ramoops-0.log)

Btw.
Installing directly 19.1/19.2/19.3 on a SODP based custom rom results into a "corrupted device error".
Even TWRP won't work anymore and "fastboot boot twrp.img" gives weird mismatch errors from the bootloader until I flash a clean boot.img again.

**Comment by 8lexliu** [comment] 2019-06-17 02:11
Also after v19. 0 , Magisk cannot patch Sony's .sin format boot Image with an error message "no boot image found"

**Comment by LucasZhaoting** [comment] 2019-06-18 13:27
I have a xperia 10 too, also with magisk 18 can get root, after update cant. but i cant install modules, yes i can install, but after reboot dont appear i installed modules.

**Comment by MartinX3** [comment] 2019-06-18 13:29
@LucasZhaoting is that a "bootloop" problem you report in this "bootloop" issue?

**Comment by LucasZhaoting** [comment] 2019-06-18 13:41
Just telling, if i update magisk, it will get bootloop, only work with magisk 18, but cant install modules too

**Comment by 8lexliu** [comment] 2019-06-18 17:39
This issue *might* be related to https://github.com/topjohnwu/Magisk/issues/1418  and here's a response from John https://github.com/topjohnwu/Magisk/issues/1418#issuecomment-491463219

**Comment by Myself5** [comment] 2019-06-18 17:43
>Highly doubt it

That means I do **not** think it is...

**Comment by 8lexliu** [comment] 2019-06-18 17:46
> > Highly doubt it
> 
> That means I do **not** think it is...

Thanks for correcting 🤐

**Comment by 8lexliu** [comment] 2019-06-22 14:49
PSA: The bootloop issue still exists in the latest Canary build.

**Comment by 8lexliu** [comment] 2019-06-27 13:28
PSA: Bootloop issue has been fixed in the latest Canary build. https://github.com/topjohnwu/magisk_files/commit/f8a96a5cb278689cde6327d663a285a9d2ac88cd

**Comment by MartinX3** [comment] 2019-06-27 22:48
@8lexliu
What about module usage?
I heard this version forced the core mode on stock xperia?

**Comment by 8lexliu** [comment] 2019-06-28 07:57
@MartinX3 No issue, at least on Xperia 1 magisk works fine.

**Closed** 2019-08-02 08:30 UTC
Labels: Need Investigate
