### ISSUE TITLE
Vivo Y31, 25.101 magiskinit can't mount init.rc, no problem here with 24.3

### ISSUE THREAD

**Issue by romanovj** [topjohnwu/Magisk#6082] opened 2022-07-09 16:24 UTC
02-08 17:20:33.870 0 0 W magiskinit: Mount [.magisk/rootdir/system/etc/init/hw/init.rc] -> [/system/etc/init/hw/init.rc]
02-08 17:20:33.870 0 0 I do_mount pid: 1 comm:magiskinit mount .magisk/rootdir/system/etc/init/hw/init.rc at hw/init.rc, flags:4096
02-08 17:20:33.870 0 0 W magiskinit: mount .magisk/rootdir/system/etc/init/hw/init.rc->/system/etc/init/hw/init.rc failed with 1: Operation not permitted
02-08 17:20:37.082 0 0 I init : Parsing file /system/etc/init/hw/init.rc...

Device: Vivo Y31
Android version: A12.1
Magisk version name: 9183a0a6
Magisk version code: 25101

On Vivo Y31 24.3 magisk can't mount on /system or /vendor, so I wrote .rc scripts for overlayfs on /system (no problems with working with layers) and other stuff, but at least there were no problems with injecting code in init.rc and su daemon.
[log.txt](https://github.com/topjohnwu/Magisk/files/9077507/log.txt)

**Comment by canyie** [comment] 2022-07-09 16:31
#5148

**Comment by romanovj** [comment] 2022-07-09 17:18
> #5148

that's different issue...
I'm not developer so I could be mistaken. Looks like my problem in twostage.cpp file. 

"Use /data as tmpfs mount point in 2SI setup"
Previously, Magisk changes the mount point from /system to /system_root
by patching fstab to prevent the original init from changing root.
The reason why we want to prevent the original init from switching the
root directory is because it will then be read-only, making patching
and injecting magiskinit into the boot chain difficult.

There is some restrictions in kernel, so magisk can't mount /system, but old method for code injection in init.rc worked(24.3).

**Comment by yujincheng08** [comment] 2022-07-09 18:42
Duplicate of #6081

**Closed by yujincheng08** 2022-07-09 18:42 UTC
