### ISSUE TITLE
Help me when i am patching my boot.img through magisk manager it is saying unable to unpack /unknown image format please help me. I am providing you my boot.img please help me.

### ISSUE THREAD

**Issue by vishal12345678901234567890** [topjohnwu/Magisk#3646] opened 2021-01-05 23:45 UTC
Help me when i am patching my boot.img through magisk manager it is saying unable to unpack /unknown image format please help me. I am providing you my boot.img please help me.
I am providing in zip format because the website is not allowing me to send .img . So just extract it and see what is the problem.please help me . I am using oppo f15 (cph2001) and the boot image which iam sending is from the latest firmware of oppo f15 ( CPH2001PUEX_11_OTA_1470_all_GlioAPybO0Vk) software version - CPH2001EX_11_C.47
[boot.zip](https://github.com/topjohnwu/Magisk/files/5768229/boot.zip)
It is showing like this
[magisk_install_log_2021-01-06T05:26:57Z.log](https://github.com/topjohnwu/Magisk/files/5773192/magisk_install_log_2021-01-06T05.26.57Z.log)

**Comment by zgfg** [comment] 2021-01-06 14:32
Duplicate of #3647, pls close

**Comment by vishal12345678901234567890** [comment] 2021-01-07 03:23
Please help me zgfg

**Closed** 2021-01-07 03:23 UTC
