### ISSUE TITLE
MAGISK v28 Does not install after flashing in twrp.

### ISSUE THREAD

**Issue by Kiotaro-2009** [topjohnwu/Magisk#8445] opened 2024-10-10 11:15 UTC
After flashing the magisk 28 in twrp, and restarting the app appeared as usual but you touch it and it does not finish installing, it instantly exits the installation process. Please does anyone know how to solve the error?

-->

Device: Redmi note 11/spesn
Android version: 13
Magisk version name: Magisk v28.0
Magisk version code: 28001

**Comment by salvogiangri** [comment] 2024-10-17 15:39
Do not install via recovery.
https://github.com/topjohnwu/Magisk/blob/1b12f45f390d00a6b8149788eb8238507695c6d8/docs/install.md?plain=1#L146

**Comment by canyie** [comment] 2024-10-22 02:59
Duplicate of #8474

**Closed by canyie** 2024-10-22 02:59 UTC
