### ISSUE TITLE
Update from Magisk 20.3 to 20.4 cause bootloop in KitKat device

### ISSUE THREAD

**Issue by martobg10** [topjohnwu/Magisk#2621] opened 2020-03-30 06:36 UTC
### What is the issue I have:
* I currently have Magisk 20.3 installed. When I tried to update to Magisk 20.4(also tried canary) I got a bootloop. I can't give logcat because ADB is waiting for the device.

### Which versions of Magisk I tried:
`Stable Magisk 20.4`                        [Build date: March 28, 2020]
`Canary Magisk ef9d077c (20401)`  [Build date: March 28, 2020]

### Notes:
* Clean patching works, but not dirty patching.
* I'm patching the kernel manually, because of https://github.com/topjohnwu/Magisk/issues/2619.
* On my Pocophone F1 with Android 10, I don't have any issues with updating the Magisk.

**Comment by osm0sis** [comment] 2020-03-30 08:49
Can you upload a "clean" magisk_patched.img and a "dirty" magisk_patched.img for comparison?

**Comment by martobg10** [comment] 2020-03-30 10:32
@osm0sis,

magisk_patched_clean_20.4.img (bootable without issues)(no magisk to 20.4)
https://my.pcloud.com/publink/show?code=XZcKrMkZ9uqLvq9i8EXJ4jcRyiQSBhX0hPgk

magisk_patched_dirty_from_20.3_to_20.4.img (bootloop)(20.3 to 20.4)
https://my.pcloud.com/publink/show?code=XZVlrMkZhQ90gBzjFPkQE1sHE2yKDp08XUXk

File №1: I "clean" patched my **stock** kernel with Magisk 20.4
File №2: I "dirty" patched my **custom** kernel with Magisk 20.4. I don't know how to patch the stock kernel with an older version of Magisk. Difference between the stock and the custom kernel is some changes in init.rc, also added two files with kernel parameters tweaks in the ramdisk, you will see them. I don't think that will be a problem for the comparison you want.

**Comment by osm0sis** [comment] 2020-03-30 13:04
@topjohnwu, looks like for the dirty patched image the script incorrectly backed up the old magiskinit instead of keeping the original init.

**Comment by osm0sis** [comment] 2020-03-31 17:19
Can you upload the working 20.3 boot.img now? I want to see if I can reproduce the patching issue on my side.

**Comment by martobg10** [comment] 2020-03-31 18:15
Here you go 😃

https://my.pcloud.com/publink/show?code=XZa0HTkZJKcuCFHgOA4brrkegV7IWYWvSTfy

**Comment by osm0sis** [comment] 2020-03-31 20:07
@martobg10, how was the boot.img originally patched? Looks manual, since it isn't correctly done, so the /.backup/.magisk configuration file is missing, and that's why dirty patching doesn't detect Magisk in it and doesn't keep the backed up original init file.

Your magisk_patched_clean_20.4.img does dirty patch correctly, so you just need to use it going forward, and this issue can be closed as (technically) invalid. :+1:

**Closed by osm0sis** 2020-03-31 20:07 UTC
Labels: bug

**Comment by martobg10** [comment] 2020-03-31 20:51
@osm0sis, I just found the reason why my .backup is missing.
After patching the kernel with Magisk. I had made several changes to the ramdisk using Carliv Image Kitchen. I just found out that the .backup folder disappears when I repack the boot image. I tried the same with your Android Image Kitchen but didn't have this problem. The .magisk folder is not deleted, after repack.
