### ISSUE TITLE
unsupported image format

### ISSUE THREAD

**Issue by Qyrln** [topjohnwu/Magisk#3949] opened 2021-02-26 22:26 UTC
Hello , Dev
ROM : 7.1.2 AOSP based ROM 
When I update magisk to latest version (22.0) by direct install , it fails with "Unsupported/Unknown image format" 
The previous versions of magisk was working perfectly 
So that's a log report using the latest canary (79ee85c0(22001)) using inbuilt magisk log 

[MagiskLog.txt](https://github.com/topjohnwu/Magisk/files/6097470/MagiskLog.txt)

And

[boot_img.zip](https://github.com/topjohnwu/Magisk/files/6097471/boot_img.zip)

**Comment by dhruvkrishnavaid** [comment] 2021-02-27 08:37
The same happens with me every time I try to update Magisk to 22.0

Rom info =>
Android 5.1 Stock Rom
Magisk patched boot.img
No TWRP
Currently on Magisk 21.4

My device name: Micromax Canvas Nitro 3 E352

[Here's the install log.](https://gofile.io/d/p12fBP)
So, currently I use Magisk app v22.0 on Magisk Core 21.4 as a temporary fix.

**Comment by osm0sis** [comment] 2021-02-27 15:45
That's a totally normal boot.img with dt.

**Comment by dhruvkrishnavaid** [comment] 2021-02-27 16:13
> That's a totally normal boot.img with dt.

😅 If that's totally normal, then why can't it directly install the update?

**Comment by osm0sis** [comment] 2021-02-27 16:46
Exactly 😉

**Comment by Haus3master** [comment] 2021-02-27 16:51
Well, the new update might have requested a few binaries that aren't available for your specific device, this might be a possible reason....

**Comment by dhruvkrishnavaid** [comment] 2021-02-28 14:37
But that's not the issue because the Magisk app patches the boot image correctly if I use the select and patch a file.
I am now going to install Magisk through fastboot because no other way is left. 😭
I know I will loose my data, but I want to update Magism

**Comment by dhruvkrishnavaid** [comment] 2021-02-28 15:04
Wow! I lost root after flashing the Magisk 22.0 patched boot.img.
Here are some screenshots.
![Screenshot_2021-02-28-20-26-17](https://user-images.githubusercontent.com/69188774/109423026-f9d66500-7a03-11eb-878d-6c4edc3f294c.png)
![Screenshot (118)](https://user-images.githubusercontent.com/69188774/109423029-022ea000-7a04-11eb-9e63-9de653380c53.png)

I probably found why I lost root. It's, maybe, due to the 64-bit ELF type which makes it non-executable.

For now, I am flashing the old Magisk 21.4 boot.img

**Comment by KaMyKaSii** [comment] 2021-02-28 23:41
This happened to me once after upgrading to some of the latest Magisk Canary builds (maybe 22000, not sure). I installed the last Magisk Manager update and when I opened it again to install the Magisk update, The "Let's go" button on the direct installation did nothing, something I had never seen before. I clicked many times and nothing. I forced the Magisk Manager stop and tried to do the installation of Magisk again, now with the unsupported image error. I rebooted the phone normally and went straight into fastboot. I restarted on TWRP, backed up boot.img, restored stock boot.img and did a clean installation of Magisk. After restarting on Android, I looked at the boot.img backup with a hexadecimal editor and the image was completely zeros. So I believe that Magisk for some reason is cleaning the boot partition improperly before checking it

**Comment by dhruvkrishnavaid** [comment] 2021-03-01 03:21
Sorry, I forgot to upload the Magisk 22.0 patched boot.img
So, here it goes
https://gofile.io/d/bBMDOv

**Comment by Martina-Neumayer** [comment] 2021-03-04 12:40
Confirmed. V22 update is a disaster.

If you have "unsupported image.. bla bla bla" info, don't reboot your device! Otherways it will brick itself.

To fix this problem you will need an working, undamaged and unpatched "boot.img" file which can be pulled (extracted) from the system image (can be an OTA image or any other available), appropriate for your device and the system version you already have on it.

You don't need to know exact system version. But pay attention on the system variant.
For example..
The device was on stock android 8, so you need also a system package file for stock android 8, and the best idea is to take a most earlier version released.
That same rule is by custom roms.
Do not "mix" stock with custom!

Next, extract this image on your PC. Just search for and find some tools for that and read manuals from them.

Then take the extracted "boot.img" file (can also be, like in my case was, "boot.image" so rename it to "boot.img"), and put it on your SD card. If your device have sd card. If not you can use an USB-OTG cable with the pendrive.

Second thing you need is the Magisk installation file, this with the "apk" extension.
Make a copy of it and now..
First file rename to something easy, for example "magisk.zip" The name is irrelevant, but the extention must be a ZIP.
The second copy rename to "uninstall.zip".
Both of them put also on SD card or pendrive.

And now a bit tricky part..

It is very possible that your device after the reboot goes stright away to the fastboot mode.
But in lots of cases this fastboot mode will be unusable, because the device will be not recognizable by the PC or will be recognizable wrong/incorrectly.
In such cases you can't use PC to flash any files to the device and don't even try to do that.

But..
If you have TWRP on your phone or any other type of non-stock recovery, no worries.. you're almost at home ;)

Okay.. Try to go into the TWRP. It can be a bit hard but after a few tries you can do it.
In my case (LG V30) I needed to go to this faulty fastboot mode and from it I choosed "restart", then I hold "VOL-DOWN" button and I was pressing the power button very quickly.

In TWRP you can make a backup first. This is optional.
Next go to "install" menu and now you can try to uninstall this faulty/broken magisk, by flashing "uninstall.zip" file to the device.
Probably will not work but it doesn't hurt to try.
If works, ok. If not, you will see an info screen about it and you will be sure now what was the primary cause of the problem.

Next step..
Go again in the "install" menu and flash the "boot.img" file into the device.
Do it untill the flash process ends with the info like "flashing sucessfull".
Then go to the wipe menu and make a wipe "cache/dalvik". Only that, nothing other!

Now try to reboot the device.
The device may boot properly, but it will probably catch a boot-loop a few times and will goes again into the fastboot mode.

Okay.. it is normal and let's fix this one too..
Go again into the TWRP.
Go to the "install" menu and this time flash the "magisk.zip" file.
Wait a bit till you see "installation successfully" or similar message.
Go to wipe menu and again do a wipe "cache/dalvik" but this time do it two times, one stright after the another.

Now you can reboot your phone. At best power it off from the TWRP menu, and then power it on manually by power button.
The phone should now start normally into the android system like before the issue.

Magisk should be updated and working. Root should be intact, and so on. And most important all of your data should be allright.
Just make some checks to be sure that all is okay.

The one thing that you need to repeat is to install or reinstall your previously used magisk modules.
They may reset after this type of repair.
But this is now is a piece of cake, because Your device is working, so you can bring them also back to life.

That's all.
Happy fixing ;)

**Comment by Geremia** [comment] 2021-03-06 02:21
I this issue, too, when trying to patch [lineage-17.1-20210304-nightly-jfltexx-signed.zip](https://download.lineageos.org/jfltexx) with Magisk 22.0.

**Comment by osm0sis** [comment] 2021-03-07 13:43
Try 22003?

**Comment by Qyrln** [comment] 2021-03-07 16:09
> Try 22003?

Installed it , but when I try to update by direct install and tap "Let's Go " nothing happen , this bug exists in latest stable release but somehow I succeed to proceed to installation dialogue , but I can't do this now .
So I captured a catlog to this bug


[logcat_03-07-2021_17-37-24.txt](https://github.com/topjohnwu/Magisk/files/6097457/logcat_03-07-2021_17-37-24.txt)

**Comment by KaMyKaSii** [comment] 2021-03-07 17:00
> > Try 22003?
> 
> Installed it , but when I try to update by direct install and tap "Let's Go " nothing happen , this bug exists in latest stable release but somehow I succeed to proceed to installation dialogue , but I can't do this now .
> So I captured a catlog to this bug
> 
> [logcat_03-07-2021_17-37-24.txt](https://github.com/topjohnwu/Magisk/files/6097457/logcat_03-07-2021_17-37-24.txt)

The same for me, the "Let's Go" button does not lead to the installation screen. I also tried to install some modules but the installation screen also did not appear. But after rebooting the device, Magisk was up to date and the modules installed, which means that the process of updating/installing Magisk and modules was done, just does not appear on the screen.
Attached is a logcat from when I tried to perform the installation before rebooting
[fjdjjd.txt.zip](https://github.com/topjohnwu/Magisk/files/6097557/fjdjjd.txt.zip)

**Comment by osm0sis** [comment] 2021-03-07 17:29
So technically the "unsupported image" issue is resolved? 😛

**Comment by Qyrln** [comment] 2021-03-07 18:14
> So technically the "unsupported image" issue is resolved? 😛

As @KaMyKaSii said , after I rebooted phone , magisk was up-to-date , but I cant see installation dialogue when I install modules (that's after rebooting with latest canary )

**Comment by osm0sis** [comment] 2021-03-07 18:55
Perfect so honestly that's a separate issue. Can one of you guys spin that off? I'm going to close this one. 👍

**Closed by osm0sis** 2021-03-07 18:55 UTC
Labels: regression
