### ISSUE TITLE
Patching ramdisk.img on Huawei P60 will make it too big to be flashed

### ISSUE THREAD

**Issue by Alpa7000** [topjohnwu/Magisk#7478] opened 2023-11-04 05:49 UTC
Device:Huawei P60 (leona)
Android version: 12 (SKQ1.220804.001)
Magisk version name: debug
Magisk version code: 26302

**Comment by canyie** [comment] 2023-11-04 07:30
Duplicate of #7361

**Closed by canyie** 2023-11-04 07:30 UTC
