### ISSUE TITLE
 vbmeta verification failed

### ISSUE THREAD

**Issue by brsteej** [topjohnwu/Magisk#1939] opened 2019-10-15 14:59 UTC
Hello ..
I have Samsung Galaxy Tab s5e / Tab s6
I downloaded magisk manager and patched the AP file..
Copied the patched AP to the PC
Used the latest Odin (V13) (Flashed patched AP, BL, CP And CSC) ..
How ever when my phone reboots I get vbmeta verification failed ..
0_0_INDIVLDVMT_EDRHS

On Magisk 19.3 it was fine i did that steps one month ago with same firmware and same devices and it works fine

Until magisk update 20 i cant do it again

I tried to reflash only vbmeta.img from original firmware but no luck
is there any way to repatch firmware with magisk 19.3 without update to magisk 20 ?

**Comment by osm0sis** [comment] 2019-10-15 15:17
Duplicate of #1919, please close.

**Closed** 2019-10-15 17:23 UTC
