### ISSUE TITLE
DiLink3.0 not detecting Magisk, and `/sbin/su: inaccessible or not found `

### ISSUE THREAD

**Issue by mrupdate** [topjohnwu/Magisk#7238] opened 2023-08-15 09:08 UTC
Device: BYD DiLink3.0
Android version: 10
Magisk version name: 26.1
Magisk version code: 26105

MagiskManager not detecting Magisk, and su: inaccessible or not found

```
1|DiLink3.0:/ $ ls -la /sbin/
ls: /sbin//magiskinit: Permission denied
ls: /sbin//magisk32: Permission denied
ls: /sbin//magisk64: Permission denied
ls: /sbin//stub.apk: Permission denied
total 0
drwxr-xr-x  3 root root 220 2017-01-01 08:52 .
drwxrwxrwt 26 root root 940 2017-01-01 08:52 ..
drwxr-xr-x  8 root root 180 2017-01-01 08:52 .magisk
lrwxrwxrwx  1 root root  10 2017-01-01 08:52 magisk -> ./magisk64
lrwxrwxrwx  1 root root   8 2017-01-01 08:52 resetprop -> ./magisk
lrwxrwxrwx  1 root root   8 2017-01-01 08:52 su -> ./magisk
lrwxrwxrwx  1 root root  14 2017-01-01 08:52 supolicy -> ./magiskpolicy
1|DiLink3.0:/ $ su
/system/bin/sh: su: inaccessible or not found
DiLink3.0:/ $ ps -A | grep magisk
root            59     1   79008   5744 0                   0 S magiskd
u0_a79        4948    81 5487604 193408 0                   0 S com.topjohnwu.magisk
```
This is bugreport & boot.img:
https://drive.google.com/drive/folders/1UrHOkVFN6tIbTrxVZXM-UWB6qzB2xUXq?usp=drive_link

**Comment by yujincheng08** [comment] 2023-08-16 02:55
Duplicate of #6743

**Closed by yujincheng08** 2023-08-16 02:55 UTC
