### ISSUE TITLE
mount (null)

### ISSUE THREAD

**Issue by pashamcr** [topjohnwu/Magisk#6764] opened 2023-03-20 05:29 UTC
Device: lenovo
Android version: 9
Magisk version name: canary
Magisk version code: 981ccabb(25210)

```
mount /data/adb/modules -> /sbin/.magisk/modules failed with 2: No such file or directory
mount (null) -> /sbin/.magisk/modules failed with 2: No such file or directory
```

[magisk_log_2023-03-20T07.52.36.log](https://github.com/topjohnwu/Magisk/files/11014326/magisk_log_2023-03-20T07.52.36.log)

Magisk does not see (is not highlighted in the file manager) the busybox module, I have not tried other modules. The module was downloaded from here [https://forum.xda-developers.com/t/tools-zips-scripts-osm0sis-odds-and-ends-multiple -devices-platforms.2239421/](https://forum.xda-developers.com/t/tools-zips-scripts-osm0sis-odds-and-ends-multiple-devices-platforms.2239421/) . If you rename the archive of the module, Magisk sees it and installs it, but in the end the module does not work.
... On android 6 this problem is not present.

**Comment by vvb2060** [comment] 2023-03-20 05:34
Duplicate of #6688

**Closed by vvb2060** 2023-03-20 05:34 UTC
