### ISSUE TITLE
Request: Do something different with the "Flashing" overlay

### ISSUE THREAD

**Issue by ammmze** [topjohnwu/Magisk#3579] opened 2020-12-17 21:37 UTC
I think we need to do something different with that "Flashing" animation overlay thing that you get when installing a zip, patching the boot img, etc.

I ran into a scenario where I was installing a module that had a bit of an install process that was interactive (via volume keys), and it got to a part where it was warning about compatibility with some devices, however I couldn't read all of it because the flashing overlay covered it up.

Maybe a simple workaround would be if the user clicks it, then it becomes mostly transparent?

**Comment by unixandria-xda** [comment] 2020-12-17 23:16
My preferred resolution is it goes back to the header.

There's a bunch of wasted space up there now and that's really intrusive being in the middle of the screen

**Comment by qnorsten** [comment] 2021-01-04 10:34
Isn't this a duplicate of https://github.com/topjohnwu/Magisk/issues/3250 ?

**Comment by ammmze** [comment] 2021-01-04 19:55
👍🏻  yep...didn't see it when i opened this. So #3627 will resolve #3250 and #3579.

**Closed** 2021-01-16 05:29 UTC
