### ISSUE TITLE
Unable to launch on Android 15 device

### ISSUE THREAD

**Issue by wuyou-123** [topjohnwu/Magisk#8094] opened 2024-05-31 10:07 UTC
Device: Xiaomi Pad 6S Pro
Android version: 15
Magisk version name: 81658d45
Magisk version code: 27002

Waiting for a blue page during startup

logcat
```
2024-05-31 17:57:52.308  3173-3173  AndroidRuntime          pid-3173                             D  Shutting down VM
2024-05-31 17:57:52.308  3173-3173  AndroidRuntime          pid-3173                             E  FATAL EXCEPTION: main
                                                                                                    Process: com.topjohnwu.magisk, PID: 3173
                                                                                                    java.lang.RuntimeException: Unable to instantiate application com.topjohnwu.magisk.core.App package com.topjohnwu.magisk: java.lang.RuntimeException: Cannot read value from namespace systemui from DeviceConfig. It could be that the code using flag executed before SettingsProvider initialization. Please use fixed read-only flag by adding is_fixed_read_only: true in flag declaration.
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1503)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1428)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7713)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9008)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)
                                                                                                    Caused by: java.lang.RuntimeException: Cannot read value from namespace systemui from DeviceConfig. It could be that the code using flag executed before SettingsProvider initialization. Please use fixed read-only flag by adding is_fixed_read_only: true in flag declaration.
                                                                                                    	at android.app.FeatureFlagsImpl.load_overrides_systemui(FeatureFlagsImpl.java:158)
                                                                                                    	at android.app.FeatureFlagsImpl.notificationChannelVibrationEffectApi(FeatureFlagsImpl.java:324)
                                                                                                    	at android.app.Flags.notificationChannelVibrationEffectApi(Flags.java:127)
                                                                                                    	at android.app.NotificationChannel.writeToParcel(NotificationChannel.java:397)
                                                                                                    	at android.content.pm.ParceledListSlice.writeElement(ParceledListSlice.java:61)
                                                                                                    	at android.content.pm.ParceledListSlice.writeElement(ParceledListSlice.java:35)
                                                                                                    	at android.content.pm.BaseParceledListSlice.writeToParcel(BaseParceledListSlice.java:183)
                                                                                                    	at android.content.pm.ParceledListSlice.writeToParcel(ParceledListSlice.java:35)
                                                                                                    	at android.os.Parcel.writeTypedObject(Parcel.java:2345)
                                                                                                    	at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3713)
                                                                                                    	at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:1027)
                                                                                                    	at a.p.R(SourceFile:1)
                                                                                                    	at com.topjohnwu.magisk.core.App.attachBaseContext(SourceFile:307)
                                                                                                    	at android.app.Application.attach(Application.java:368)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1357)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1496)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1428) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7713) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9008) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887) 
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.app.Application.getContentResolver()' on a null object reference
                                                                                                    	at android.provider.Settings$Config.getContentResolver(Settings.java:20582)
                                                                                                    	at android.provider.Settings$Config.getStrings(Settings.java:20193)
                                                                                                    	at android.provider.SettingsConfigDataStore.getProperties(SettingsConfigDataStore.java:48)
                                                                                                    	at android.provider.DeviceConfig.getPropertiesWithoutOverrides(DeviceConfig.java:1125)
                                                                                                    	at android.provider.DeviceConfig.getProperties(DeviceConfig.java:1115)
                                                                                                    	at android.app.FeatureFlagsImpl.load_overrides_systemui(FeatureFlagsImpl.java:146)
                                                                                                    	at android.app.FeatureFlagsImpl.notificationChannelVibrationEffectApi(FeatureFlagsImpl.java:324) 
                                                                                                    	at android.app.Flags.notificationChannelVibrationEffectApi(Flags.java:127) 
                                                                                                    	at android.app.NotificationChannel.writeToParcel(NotificationChannel.java:397) 
                                                                                                    	at android.content.pm.ParceledListSlice.writeElement(ParceledListSlice.java:61) 
                                                                                                    	at android.content.pm.ParceledListSlice.writeElement(ParceledListSlice.java:35) 
                                                                                                    	at android.content.pm.BaseParceledListSlice.writeToParcel(BaseParceledListSlice.java:183) 
                                                                                                    	at android.content.pm.ParceledListSlice.writeToParcel(ParceledListSlice.java:35) 
                                                                                                    	at android.os.Parcel.writeTypedObject(Parcel.java:2345) 
                                                                                                    	at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3713) 
                                                                                                    	at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:1027) 
                                                                                                    	at a.p.R(SourceFile:1) 
                                                                                                    	at com.topjohnwu.magisk.core.App.attachBaseContext(SourceFile:307) 
                                                                                                    	at android.app.Application.attach(Application.java:368) 
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1357) 
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1496) 
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1428) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7713) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9008) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887) 
2024-05-31 17:57:52.308  3173-3173  Bx                      pid-3173                             E  java.lang.RuntimeException: Unable to instantiate application com.topjohnwu.magisk.core.App package com.topjohnwu.magisk: java.lang.RuntimeException: Cannot read value from namespace systemui from DeviceConfig. It could be that the code using flag executed before SettingsProvider initialization. Please use fixed read-only flag by adding is_fixed_read_only: true in flag declaration.
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1503)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1428)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7713)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9008)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)
                                                                                                    Caused by: java.lang.RuntimeException: Cannot read value from namespace systemui from DeviceConfig. It could be that the code using flag executed before SettingsProvider initialization. Please use fixed read-only flag by adding is_fixed_read_only: true in flag declaration.
                                                                                                    	at android.app.FeatureFlagsImpl.load_overrides_systemui(FeatureFlagsImpl.java:158)
                                                                                                    	at android.app.FeatureFlagsImpl.notificationChannelVibrationEffectApi(FeatureFlagsImpl.java:324)
                                                                                                    	at android.app.Flags.notificationChannelVibrationEffectApi(Flags.java:127)
                                                                                                    	at android.app.NotificationChannel.writeToParcel(NotificationChannel.java:397)
                                                                                                    	at android.content.pm.ParceledListSlice.writeElement(ParceledListSlice.java:61)
                                                                                                    	at android.content.pm.ParceledListSlice.writeElement(ParceledListSlice.java:35)
                                                                                                    	at android.content.pm.BaseParceledListSlice.writeToParcel(BaseParceledListSlice.java:183)
                                                                                                    	at android.content.pm.ParceledListSlice.writeToParcel(ParceledListSlice.java:35)
                                                                                                    	at android.os.Parcel.writeTypedObject(Parcel.java:2345)
                                                                                                    	at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3713)
                                                                                                    	at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:1027)
                                                                                                    	at a.p.R(SourceFile:1)
                                                                                                    	at com.topjohnwu.magisk.core.App.attachBaseContext(SourceFile:307)
                                                                                                    	at android.app.Application.attach(Application.java:368)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1357)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1496)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1428) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7713) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9008) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887) 
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.app.Application.getContentResolver()' on a null object reference
                                                                                                    	at android.provider.Settings$Config.getContentResolver(Settings.java:20582)
                                                                                                    	at android.provider.Settings$Config.getStrings(Settings.java:20193)
                                                                                                    	at android.provider.SettingsConfigDataStore.getProperties(SettingsConfigDataStore.java:48)
                                                                                                    	at android.provider.DeviceConfig.getPropertiesWithoutOverrides(DeviceConfig.java:1125)
                                                                                                    	at android.provider.DeviceConfig.getProperties(DeviceConfig.java:1115)
                                                                                                    	at android.app.FeatureFlagsImpl.load_overrides_systemui(FeatureFlagsImpl.java:146)
                                                                                                    	at android.app.FeatureFlagsImpl.notificationChannelVibrationEffectApi(FeatureFlagsImpl.java:324) 
                                                                                                    	at android.app.Flags.notificationChannelVibrationEffectApi(Flags.java:127) 
                                                                                                    	at android.app.NotificationChannel.writeToParcel(NotificationChannel.java:397) 
                                                                                                    	at android.content.pm.ParceledListSlice.writeElement(ParceledListSlice.java:61) 
                                                                                                    	at android.content.pm.ParceledListSlice.writeElement(ParceledListSlice.java:35) 
                                                                                                    	at android.content.pm.BaseParceledListSlice.writeToParcel(BaseParceledListSlice.java:183) 
                                                                                                    	at android.content.pm.ParceledListSlice.writeToParcel(ParceledListSlice.java:35) 
                                                                                                    	at android.os.Parcel.writeTypedObject(Parcel.java:2345) 
                                                                                                    	at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3713) 
                                                                                                    	at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:1027) 
                                                                                                    	at a.p.R(SourceFile:1) 
                                                                                                    	at com.topjohnwu.magisk.core.App.attachBaseContext(SourceFile:307) 
                                                                                                    	at android.app.Application.attach(Application.java:368) 
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1357) 
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1496) 
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1428) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7713) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9008) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887) 
2024-05-31 17:57:52.309  3173-3173  opjohnwu.magisk         pid-3173                             I  System.exit called, status: 1
2024-05-31 17:57:52.309  3173-3173  AndroidRuntime          pid-3173                             I  VM exiting with result code 1, cleanup skipped.
2024-05-31 17:57:52.321  2745-3486  ActivityManager         system_server                        I  Process com.topjohnwu.magisk (pid 3173) has died: fg  TOP 
2024-05-31 17:57:52.321  1870-1870  Zygote                  pid-1870                             I  Process 3173 exited cleanly (1)
2024-05-31 17:57:52.322  2745-3749  libprocessgroup         system_server                        I  Removed cgroup /sys/fs/cgroup/uid_10335/pid_3173
```

**Comment by yujincheng08** [comment] 2024-05-31 12:43
Duplicate of #8060

**Closed by yujincheng08** 2024-05-31 12:43 UTC
