### ISSUE TITLE
AndroidQ无法挂载system分区

### ISSUE THREAD

**Issue by scarlet-glass** [topjohnwu/Magisk#2264] opened 2020-01-15 10:58 UTC
adb su下，使用mount -o remount,rw /system挂载，提示mount: '/system' not in /proc/mounts
这个是什么情况，该问题在Android P上也是如此。

**Comment by scarlet-glass** [comment] 2020-01-15 11:00
@topjohnwu 希望大佬帮忙解答一下~

**Comment by Didgeridoohan** [comment] 2020-01-15 12:02
Take a look here: https://github.com/topjohnwu/magisk_files/blob/2d7ddefbe4946806de1875a18247b724f5e7d4a0/notes.md#new-system-as-root-implementation

And then you can close the issue, since it's not a bug.

**Comment by scarlet-glass** [comment] 2020-01-15 13:37
> Take a look here: https://github.com/topjohnwu/magisk_files/blob/2d7ddefbe4946806de1875a18247b724f5e7d4a0/notes.md#new-system-as-root-implementation
> 
> And then you can close the issue, since it's not a bug.

我有看到这个链接，但是没看太懂，是意思不能挂载了吗？

**Comment by scarlet-glass** [comment] 2020-01-15 13:44
> Take a look here: https://github.com/topjohnwu/magisk_files/blob/2d7ddefbe4946806de1875a18247b724f5e7d4a0/notes.md#new-system-as-root-implementation
> 
> And then you can close the issue, since it's not a bug.

直接挂载根目录？  mount -o remount,rw /    ？

**Comment by topjohnwu** [comment] 2020-01-15 15:53
Yes

**Closed by topjohnwu** 2020-01-15 15:53 UTC
