### ISSUE TITLE
Android 14 Beta 4 patching boot.img fails

### ISSUE THREAD

**Issue by K7Adam** [topjohnwu/Magisk#7155] opened 2023-07-11 20:38 UTC
Device: Pixel 6 Pro (raven)
Android version: Android 14 Beta 4
Magisk version name: 26103 debug
Magisk version code:  a8c4a33e (26103) (D)

Patching the boot.img of the factory images of the Android 14 beta 4 builds (UPB4.230623.005) fails.

**Here is what I get while patching:**
```
#Device platform: arm64-v8a
- Installing: a8c4a33e (26103) - Copying image to cache - Unpacking boot image
Checking ramdisk status - Stock boot image detected
- Patching ramdisk
- Pre-init storage partition : metadata Unable to patch ramdisk
! Installation failed

```
**Here is the full magisk_install_log:**
```
- Device platform: arm64-v8a
- Installing: a8c4a33e (26103)
- Copying image to cache
- Unpacking boot image
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [4]
KERNEL_SZ       [25056616]
RAMDISK_SZ      [0]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [lz4_legacy]
VBMETA
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
resetprop: get prop [ro.crypto.state]: [encrypted]
preinit device: metadata
- Pre-init storage partition: metadata
Add file [init] (100750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add file [overlay.d/sbin/magisk32.xz] (100644)
Add file [overlay.d/sbin/magisk64.xz] (100644)
Add file [overlay.d/sbin/stub.xz] (100644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Failed to process cpio: No such file or directory (os error 2)
! Unable to patch ramdisk
! Installation failed
```

**And here are some 'System.err's that I found in the magisk_log file:**
```
07-11 22:31:06.944 31258 31385 W System.err: java.lang.ArithmeticException: divide by zero
07-11 22:31:06.944 31258 31385 W System.err: 	at com.topjohnwu.magisk.signing.SignBoot.getSignableImageSize(SignBoot.java:200)
07-11 22:31:06.944 31258 31385 W System.err: 	at com.topjohnwu.magisk.signing.SignBoot.verifySignature(SignBoot.java:148)
07-11 22:31:06.944 31258 31385 W System.err: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchBoot(MagiskInstaller.kt:471)
07-11 22:31:06.944 31258 31385 W System.err: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.handleFile(MagiskInstaller.kt:426)
07-11 22:31:06.944 31258 31385 W System.err: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.patchFile(MagiskInstaller.kt:549)
07-11 22:31:06.944 31258 31385 W System.err: 	at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Patch.operations(MagiskInstaller.kt:597)
07-11 22:31:06.944 31258 31385 W System.err: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$result$1.invokeSuspend(MagiskInstaller.kt:566)
07-11 22:31:06.944 31258 31385 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-11 22:31:06.944 31258 31385 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-11 22:31:06.944 31258 31385 W System.err: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
07-11 22:31:06.944 31258 31385 W System.err: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
07-11 22:31:06.944 31258 31385 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
07-11 22:31:06.944 31258 31385 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-11 22:31:06.944 31258 31385 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
07-11 22:31:06.945 31258 31385 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
07-11 22:31:07.500  1385  1385 W magisk64: type=1400 audit(0.0:483): avc:  denied  { search } for  name="tests" dev="dm-48" ino=112 scontext=u:r:untrusted_app_32:s0:c116,c257,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=com.topjohnwu.magisk
07-11 22:31:07.500  1385  1385 W magisk64: type=1400 audit(0.0:484): avc:  denied  { search } for  name="tests" dev="dm-48" ino=112 scontext=u:r:untrusted_app_32:s0:c116,c257,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=com.topjohnwu.magisk
07-11 22:31:07.500  1385  1385 W magisk64: type=1400 audit(0.0:485): avc:  denied  { search } for  name="tests" dev="dm-48" ino=112 scontext=u:r:untrusted_app_32:s0:c116,c257,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=com.topjohnwu.magisk
07-11 22:31:07.500  1385  1385 W magisk64: type=1400 audit(0.0:486): avc:  denied  { search } for  name="tests" dev="dm-48" ino=112 scontext=u:r:untrusted_app_32:s0:c116,c257,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=com.topjohnwu.magisk
07-11 22:31:13.844 31258  1180 I okhttp.OkHttpClient: --> GET https://topjohnwu.github.io/magisk-files/canary.json
07-11 22:31:13.877 31258  1180 I okhttp.OkHttpClient: <-- 200 https://topjohnwu.github.io/magisk-files/canary.json (30ms, unknown-length body)
07-11 22:32:25.498 31258  2190 I okhttp.OkHttpClient: --> GET https://topjohnwu.github.io/magisk-files/canary.json
07-11 22:32:25.561 31258  2190 D TrafficStats: tagSocket(86) with statsTag=0xffffffff, statsUid=-1
07-11 22:32:25.580 31258  2190 W opjohnwu.magisk: Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (unsupported, reflection, allowed)
07-11 22:32:25.716 31258  2190 I okhttp.OkHttpClient: <-- 200 https://topjohnwu.github.io/magisk-files/canary.json (218ms, unknown-length body)
```

**Comment by HiFIi** [comment] 2023-07-11 23:36
Yep same

**Comment by HiFIi** [comment] 2023-07-11 23:39
Download the latest Magisk from GitHub actions and it solved my issue just now mate

**Comment by canyie** [comment] 2023-07-12 00:54
Duplicate of #7109

**Closed** 2023-07-12 00:55 UTC
