### ISSUE TITLE
Green screen at first opening

### ISSUE THREAD

**Issue by spectrum70** [topjohnwu/Magisk#6522] opened 2023-01-11 20:12 UTC
Device: avicii (Oneplus Nord)
Android version: 12 (GSI over 10)
Magisk version name: Canary
Magisk version code: 25206

After installing apk, first start get green screen, no logo. Hangs for some minutes then it crashes.
Same for 25.2 and 25.1, while 24.3 works.

Clearing app data and cache, it starts with logo, but it hangs there, same way.
[logcat.txt](https://github.com/topjohnwu/Magisk/files/10395673/logcat.txt)

**Comment by canyie** [comment] 2023-01-12 01:22
```
01-11 20:54:30.659  5141  5141 E AndroidRuntime: FATAL EXCEPTION: main
01-11 20:54:30.659  5141  5141 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 5141
01-11 20:54:30.659  5141  5141 E AndroidRuntime: android.view.InflateException: Binary XML file line #25 in com.topjohnwu.magisk:layout/activity_main_md2: Binary XML file line #25 in com.topjohnwu.magisk:layout/activity_main_md2: Error inflating class androidx.fragment.app.FragmentContainerView
01-11 20:54:30.659  5141  5141 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #25 in com.topjohnwu.magisk:layout/activity_main_md2: Error inflating class androidx.fragment.app.FragmentContainerView
01-11 20:54:30.659  5141  5141 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at a.ea.e(SourceFile:1)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at a.Qe.S(SourceFile:4)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at a.Qe.f(Unknown Source:1)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at androidx.navigation.fragment.NavHostFragment.t(SourceFile:2)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at androidx.fragment.app.h.f(SourceFile:15)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at androidx.fragment.app.h.h(SourceFile:9)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at a.ea.R(SourceFile:23)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at a.ea.oc(Unknown Source:91)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at a.ea.t(Unknown Source:31)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.<init>(SourceFile:11)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at a.YM.onCreateView(Unknown Source:16)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at a.i6.onCreateView(SourceFile:4)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at a.Ft.y(Unknown Source:23)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at androidx.appcompat.app.f.setContentView(Unknown Source:7)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at a.sK.k(SourceFile:1)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at com.topjohnwu.magisk.ui.MainActivity.c(Unknown Source:0)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at a.Hu.run(SourceFile:9)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-11 20:54:30.659  5141  5141 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by vvb2060** [comment] 2023-01-15 03:22
Duplicate of #5880

**Closed** 2023-01-15 03:26 UTC

**Comment by spectrum70** [comment] 2023-01-15 07:58
Hi,

so who is responsible for this issue ? GSI rom ?
