### ISSUE TITLE
Does not support Oppo device

### ISSUE THREAD

**Issue by tilsgee** [topjohnwu/Magisk#2543] opened 2020-03-14 14:16 UTC
![Screenshot_2020-03-14-21-16-32-26](https://user-images.githubusercontent.com/62179071/76683754-1cc40980-6639-11ea-8c64-182a45369f7c.png)

**Comment by osm0sis** [comment] 2020-03-14 17:20
You didn't upload the image or any useful info, but almost certainly this is a duplicate of #2510 since Oppo similarly encrypts their OTA images, and should be closed.

**Closed** 2020-03-14 18:06 UTC
