### ISSUE TITLE
Magisk Mount fail

### ISSUE THREAD

**Issue by fatalcoder524** [topjohnwu/Magisk#6713] opened 2023-03-08 16:41 UTC
Device: OnePlus 11
Android version: 13
Magisk version name: 981ccabb(25210)
Magisk version code: 25210

01-03 09:58:48.866  1494  1496 I : * Mounting mirrors
01-03 09:58:48.866  1494  1496 E : mount /data/adb/modules -> /dev/0UUxx/.magisk/modules failed with 2: No such file or directory
01-03 09:58:48.866  1494  1496 E : mount (null) -> /dev/0UUxx/.magisk/modules failed with 2: No such file or directory
01-03 09:58:48.866  1494  1496 E : mount (null) -> /dev/0UUxx/.magisk/modules failed with 2: No such file or directory

[magisk_log_2023-03-08T22.07.42.log](https://github.com/topjohnwu/Magisk/files/10922842/magisk_log_2023-03-08T22.07.42.log)

**Comment by vvb2060** [comment] 2023-03-08 16:59
Duplicate of #6688

**Closed by vvb2060** 2023-03-08 16:59 UTC
