### ISSUE TITLE
cant get root

### ISSUE THREAD

**Issue by boucymatt** [topjohnwu/Magisk#7835] opened 2024-02-20 17:33 UTC
i tried direct install and a fresh boot.img for rooting and still cant get root access

Device: lenovo tab m8

Android version: 13
Magisk version name: 27.0
Magisk version code: 27001

[bugreport-TB300FU_EEA-TP1A.220624.014-2024-02-20-17-20-53.zip](https://github.com/topjohnwu/Magisk/files/14349180/bugreport-TB300FU_EEA-TP1A.220624.014-2024-02-20-17-20-53.zip)

**Comment by yujincheng08** [comment] 2024-02-22 13:32
Duplicate of #7820

**Closed by yujincheng08** 2024-02-22 13:32 UTC
