### ISSUE TITLE
Magisk force-closes after update with Magisk-v22.0.apk on Samsung S7 (herolte)

### ISSUE THREAD

**Issue by 7wells** [topjohnwu/Magisk#3895] opened 2021-02-23 17:35 UTC
Hello!

I have been using Magisk 20.4 and Magisk Manager 8.0.7 on my Samsung S7 Exynos (herolte) without any issues.

Today, I updated with Magisk-v22.0.apk. Since then, when I try to open the Magisk Manager, I get the message that Magisk was force-closed, and Magisk Manager does not open. I do receive pop-ups, though, for apps asking for root permission. I run Magisk 20.4, knowing that meanwhile there is 21.4 available on GitHub, but 20.4 was working fine so far.

I deinstalled Magisk Manager (as I could not open it anymore), flashed the latest Magisk uninstaller from GitHub via TWRP and afterwards the hitherto working Magisk 20.4 (also from GitHub). After installing the Magisk Manager app version 8.0.7 (also from GitHub), it works again.

Do you guys have some hints for me what I should try to drill down the reason for my problem when trying to use 22.0 and how to eventually overcome this?

Please accept my humble apologies if I am overseeing the obvious. 😊 

Thank you so much for your help - and stay healthy. 👍

**Comment by placst80** [comment] 2021-02-23 17:50
Same happens to me, with a Xiaomi Mi A1 stock previously rooted

**Comment by Zenjir0** [comment] 2021-02-23 17:57
Also happens on my Oneplus 5T LineageOS 17.1 current nightly. Everything works fine on 8.0.7 but 22.0 just crashes.

**Comment by Didgeridoohan** [comment] 2021-02-23 18:36
Did anyone try to just clear data for the Magisk app?

**Comment by Martina-Neumayer** [comment] 2021-02-23 18:37
That same on lg v30. This whole "v22" update idea is a mega piece of sh**!
Seems that it bricked my device completely.
After the reboot I can only see such screen..

![LG-V30-Bootloader-Unlock](https://user-images.githubusercontent.com/13028529/108890825-530e5500-760e-11eb-896e-44001a3383a2.jpg)

And now what?!

**Comment by 7wells** [comment] 2021-02-23 19:40
Yes, I cleared the cache and data of Magisk Manager, but that did not help.

What helped was indeed reading the caveat to first unhide the Magisk Manager app before updating to the new Magisk app - and following that advice. It took me that extra round to do it right. :blush

**Comment by Didgeridoohan** [comment] 2021-02-23 20:14
So in other words this is not actually an issue and you can close this so that John or Chris doesn't have to.

**Comment by silveroxides** [comment] 2021-02-23 21:10
Had similar issue on Huawei honor 8 with build FRD-L09C432B418. Went back to previous setup and will await possible hot fix before attempting again.

**Comment by Didgeridoohan** [comment] 2021-02-23 21:21
> Had similar issue on Huawei honor 8 with build FRD-L09C432B418. Went back to previous setup and will await possible hot fix before attempting again.

If your Magisk app is force closing because you updated with the old app hidden there will be no hot fix... When updating to v22+ from an earlier release it is required to not have the app hidden (as the release notes states).

If you did not have the app hidden while updating you need to provide a lot more info for there to be any kind of fix.

**Comment by Aytackydln** [comment] 2021-02-23 21:32
Well that was stupid. I read the patch notes didn't see any warning. If it was such a big deal to unhide before updating it should have been forced by manager. Maybe with an intermediate patch. You can never expect your users to "read" anyway. Any such mistake is developer's fault

**Comment by Didgeridoohan** [comment] 2021-02-23 21:37
> I read the patch notes didn't see any warning.

What are you talking about? It's pretty big and right at the top:
https://topjohnwu.github.io/Magisk/releases/22000.html

**Comment by 0274dmv** [comment] 2021-02-24 00:12
I got same problem with 22.0 update. All my fault is didn't read release instructions first and update directly after got notification on the top of my Lenovo K4 Note A7010 --> without hidden mode changed. Rarely people use this model for open source rooting project. Its my challenge.
Please senior master, advise me to get my device back to normal >> without change or deleting data and storage <<
Thnxs !!

**Comment by nutrikazuma** [comment] 2021-02-24 01:36
I have the same problem os force close um my Huawei Nexus 6p. Already cleared the cache, cleared the data, removed extensions and reinstalled Magisk, but still force close.

**Comment by Aytackydln** [comment] 2021-02-24 08:25
I also updated from notification. Patch notes I saw there didn't have any warning. Still just putting a warning was a mistake

**Comment by silveroxides** [comment] 2021-02-24 08:33
I unhid it and it worked. But still the app was pushed through notification. I didn't give it much thought since it seemed to only be manager update. Take into consideration that i do NOT actively follow development and i was NOT presented clearly with patch notes before being able to install. So the oversight here is not including fail-safes such as pop up warning before entering install displaying "warning! Magisk must not be hidden or else the install will not succeed!" You see what i mean? So don't go blaming the user and same the other way around. Users don't be rude to developer. It is a fantastic piece of software they developed. Just communicate and give constructive feedback. Everyone have a great week.

**Comment by c3k** [comment] 2021-02-24 08:46
+1 updated from notification with Manager hidden (S10)

Tried to install new and previous apk, both can't detect magisk and can't do a direct reinstall (but root enabled app still working).

In my mind the hidden manager is still the "root enabler" app, but is stuck with the update request.
I try to restore a titanium backup with no luck.
Fear about rebooting.

Ideas?

**Comment by Martina-Neumayer** [comment] 2021-02-24 09:35
@nutrikazuma That same is with my device.
I've managed somehow (it is very hard now to get into) to reach TWRP, seems intact and working.

But looks like the problem occurs in the boot.img patching process, and then the app forced flashing such corrupted img into the device. That's why myphone jumps now directly into the fastboot mode after every reboot.

I think that flashing correct boot.img should fix the problem, but by doing this probably all data from the device may be wiped.
Probably because I am not sure about the data wiping. If someone knows, please correct me.

In my case is a bit crappy because I can't reach my phone from my linux PC. It shows itself very randomly and as some "external camera" bs.

Next problem is that that my LG v30 was oficially unlocked (bootloader unlocked by lg website those days) and I does not know where the magisk app stores backups of previously working boot images. I don't have this unlocked img provided by lg anymore.
Well.. I know where it can be saved but to access it (cloud drive) I need my 2FA codes from my authenticator app, but the app is on that bricked phone. Damn paradox!

So.. now the main question is:
Is the magisk manager app making a backups of the existing boot.img before patching and if yes, where are those backups saved/stored on the device?

And the second question..
Is there any way to flash such boot.img without wipping the datas from the phone?

**Comment by Martina-Neumayer** [comment] 2021-02-24 09:56
As for the "update from notification screen" problem..

Yeap.. a lot's of people did that and now they are stuck in troubles.

This way of updates are a veeeeeeeeryyyy bad idea! It should be not allowed!
Okay.. It should only display some infos about the new version of the app and by taping on it, redirect to some webpage with all details, warnings, howtos etc.
But never-ever allow the user to update such important app like magisk directly from notification bar.

In my case I just wanted to see entire info, and by tapping on the noti bar accidentally I started update process.
And in this moment my pfone was already messed up, because I can't read exactly all those infos only a part of it (hidpi amoled screeen, very small letters, no scrolling option in this nag-screen and I was also outside in the direct sun).
Yeap.. the app UI design does matter.

As I mentioned already before..
Such update way is a very, very, very bad idea.
As we all see here it can lead to lot's of problems.

**Comment by olivierberten** [comment] 2021-02-24 10:18
Not much to add... Your app sent me a notification requesting me to update... Since I trusted you knew what you were doing, I did what you(r app) asked me to do...

I guess I'll have to reconsider my trust...

Is there already a guide somewhere about how to recover from that failed update? Should I reboot or rather not as long as there's no solution?

**Comment by Michele64** [comment] 2021-02-24 10:20
Same here, Oneplus 5t ,update without warning...

**Comment by topjohnwu** [comment] 2021-02-24 10:29
I see no logs here, closing...

**Closed by topjohnwu** 2021-02-24 10:29 UTC

**Comment by 0274dmv** [comment] 2021-02-24 11:10
Log 🤔? I can't even open magisk manager at all. Please tell me how to?

**Comment by Martina-Neumayer** [comment] 2021-02-24 11:42
> I see no logs here, closing...

I am sorry, but it is a joke?!
If yes, than very pitty and sad one.
How the heck, people with the totally bricked devices can access and give you a logs?!

**Comment by Didgeridoohan** [comment] 2021-02-24 11:57
> I am sorry, but it is a joke?!
> If yes, than very pitty and sad one.
> How the heck, people with the totally bricked devices can access and give you a logs?!

I have seen no reports of any devices being totally bricked (and this issue is about the Magisk app force closing, so any other reports of devices not booting doesn't actually have anything to do in this particular issue ticket)... It should be perfectly possible to recover, in many cases with just a couple of steps and no data lost (simply restoring the boot image or dirty flashing your entire device and then starting over should work in the majority of cases).

The proper way to get logs then, would be to restore the device and recreate the issue while saving all the logs you can (Magisk install log, logcat, etc).

The proper logs for what this particular issue ticket is about would be a logcat from when the Manager is crashing, but so far it looks like it's caused by updating the app when it was already hidden. This won't work, as stated in the release notes... The big issue here seems so far to be two-fold:
Either users used the update notification to update the app (which doesn't show the release notes so it's then hard to know about the caveat of not updating on a hidden app) or users just didn't read the release notes.

**Comment by Martina-Neumayer** [comment] 2021-02-24 13:31
Mine was bricked by this crappy update and many people mentioned that same as well.

My Dear.. perhaps you have a spare time to play some "games" with the "recreating issues" etc., but I don't.
I need to do my business job and I can't. I can't even login to my work account because the 2FA app is on that bricked device.

As I mentioned earlier: my magisk was NOT hidden. I only tapped on the notification info to see what's new and the whole crap started. Then I only saw for a few seconds something telling about "faulty image file" and next my phone rebooted itself and that's all. I have now only unusable fastboot mode screen, no PC sees the device and no latest backups done.
I can barelly reach the TWRP but I don't know is it working fine or not? I am not sure.
In the simple words.. I am sitting ducks now.

My phone is now charging and I am searching where is my unlocked boot.img file.
And if I remember correctly (yeap, I am a bit old now), lg v30 does a factory reset after the bootloader flash.
So.. first of all I need to do my device backup, even in such broken state. Better so than nothing to have for data restoring.
Then I will try to bring it back to life.
I simply can't afford any user-data loss from this particullar device.

**Comment by gavtroy** [comment] 2021-02-24 21:13
@Martina-Neumayer your issue is presumably unrelated. The issue here is that the app force closes after update until reinstalled.

While there's nothing to fix considering the damage is already done, how can you say the app breaking itself is not an issue? That's never an acceptable user experience, regardless of what's written in the release notes that nobody is reading. It would be more helpful to pin an issue with a simple explanation and resolution, after in future don't break it on purpose.

**Comment by Martina-Neumayer** [comment] 2021-03-04 11:44
@gavtroy Sorry for the delay, but the commenting option was disabled.

I have already unbricked my device sucessfully without any data lose.
It is not that hard, but it need to be done correctly, step by step.

**Comment by agamez** [comment] 2022-02-01 09:04
> +1 updated from notification with Manager hidden (S10)
> 
> Tried to install new and previous apk, both can't detect magisk and can't do a direct reinstall (but root enabled app still working).
> 
> In my mind the hidden manager is still the "root enabler" app, but is stuck with the update request. I try to restore a titanium backup with no luck. Fear about rebooting.
> 
> Ideas?
> 
> EDIT: solved by unistall hidden manager, install 8.0.7 and redo the update process (credits to ineedroot69).

Hi @c3k

Could you explain how did you proceed exactly? Which way did you use to uninstall hidden manager?

Thanks!

**Comment by c3k** [comment] 2022-02-01 19:37
> > +1 updated from notification with Manager hidden (S10)
> > Tried to install new and previous apk, both can't detect magisk and can't do a direct reinstall (but root enabled app still working).
> > In my mind the hidden manager is still the "root enabler" app, but is stuck with the update request. I try to restore a titanium backup with no luck. Fear about rebooting.
> > Ideas?
> > EDIT: solved by unistall hidden manager, install 8.0.7 and redo the update process (credits to ineedroot69).
> 
> Hi @c3k
> 
> Could you explain how did you proceed exactly? Which way did you use to uninstall hidden manager?
> 
> Thanks!

you have to manually find it in "all apps" list
