### ISSUE TITLE
Magisk won't backup init_boot.img

### ISSUE THREAD

**Issue by shawnlinboy** [topjohnwu/Magisk#6378] opened 2022-11-08 09:17 UTC
Device: Pixel 7
Android version: 13
Magisk version name: cf9957ce
Magisk version code: 25205

I'm using the latest version of Magisk on my pixel 7 and everything works fine. However, there is a small problem on this platform.

As Google changed the name of their boot.image from `boot.img` to `init_boot.img`, I found Magisk won't backup the factory boot image after patching into a file, and this makes us impossible when we want to restore images.

A temporary solution is to manually rename init_boot.img to boot.img before selecting it, and everything just works after this, factory boot image can be backed up safe and sound, which also makes restore process success.

I suspect it's the Magisk strong match the filename boot.img that caused this problem? If so please add support to init_boot.img.

**Comment by pritster5** [comment] 2022-11-08 15:29
I'm having this issue as well. This is also the reason the "install to inactive slot" method  after OTA will soft brick a Pixel 7/Pro. Restoring stock boot images before install isn't actually doing anything even though the toast message says the stock boot image has been restored.

**Comment by laltroweb** [comment] 2022-12-05 12:33
Same here. Pixel 7 pro.
Magisk "install as ota" is a very good feature.
Hope can be fixed in next release (just a switch to patch boot.img or init_boot.img can be sufficient, or directly based on phone models).

**Comment by yujincheng08** [comment] 2022-12-15 08:18
Close because of no log. Feel free the recreate an issue with log.

**Comment by osm0sis** [comment] 2022-12-21 22:15
This kinda looks straightforward without a log.

**Comment by pritster5** [comment] 2022-12-21 22:27
Thank you for this. You don't need a log for everything lmao

**Comment by osm0sis** [comment] 2022-12-21 22:34
No, someone should have provided a log from installation, it would (still) help.

**Comment by pritster5** [comment] 2022-12-22 05:12
> No, someone should have provided a log from the failed installations, it would (still) help.

Kind of hard to do that given that it soft bricks the device to use this installation method.

**Comment by osm0sis** [comment] 2022-12-22 05:29
It's only a soft brick after you reboot...

**Comment by vvb2060** [comment] 2022-12-22 10:04
@osm0sis Have you found the cause of the problem?

**Comment by vvb2060** [comment] 2022-12-22 10:06
We couldn't find any problems with the script, so need a log, did you find it?

**Comment by yujincheng08** [comment] 2022-12-22 10:19
@osm0sis init_boot will still use the name boot (in find_boot function), thus the codes you quoted are right... Plz *do* reprocuce the problem or find problem code before adding "confirmed" label.

**Comment by osm0sis** [comment] 2022-12-22 11:19
I don't have a Pixel 7 but I'll run some further tests.

**Comment by yujincheng08** [comment] 2022-12-23 07:43
Tested on cuttlefish without any problem. So did on Pixel 7 pro.

```
vsoc_x86_64:/ # cat /sdcard/Download/magisk_install_log_2022-12-23T15.40.33.log
- Target slot: _b
- Target image: /dev/block/vda5
- Device platform: x86_64
- Installing: 62042e61 (25205)
Parsing boot image: [/dev/block/vda5]
HEADER_VER      [4]
KERNEL_SZ       [0]
RAMDISK_SZ      [2264790]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2022-08]
PAGESIZE        [4096]
CMDLINE         []
RAMDISK_FMT     [lz4_legacy]
VBMETA
Loading cpio: [ramdisk.cpio]
- Unpacking boot image
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
- Repacking boot image
Parsing boot image: [/dev/block/vda5]
HEADER_VER      [4]
KERNEL_SZ       [0]
RAMDISK_SZ      [2264790]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2022-08]
PAGESIZE        [4096]
CMDLINE         []
RAMDISK_FMT     [lz4_legacy]
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [4]
KERNEL_SZ       [0]
RAMDISK_SZ      [2800062]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2022-08]
PAGESIZE        [4096]
CMDLINE         []
- Flashing new boot image
RULESDIR=/metadata/magisk
***************************************
 Next reboot will boot to second slot!
***************************************
- All done!
vsoc_x86_64:/ # readlink /dev/block/by-name/init_boot_b
/dev/block/vda5
vsoc_x86_64:/ # ls /data/magisk_backup_a51a7805eecb9d1a164e3466d3c1f50f885d0369/
boot.img.gz
vsoc_x86_64:/ #
```

**Closed by yujincheng08** 2022-12-23 07:43 UTC

**Comment by vvb2060** [comment] 2022-12-23 07:54
Flashing patched_boot.img shared by others is not a supported installation method.

**Comment by osm0sis** [comment] 2022-12-23 08:01
Sounds good to me. Agreed. Apologies for the false reopen.

**Comment by karlicoss** [comment] 2023-09-05 22:07
For anyone who has a similar issue, this guide helped me to recreate the backup so it's restorable with Magisk https://gist.github.com/pexcn/71d7d242c5e805d9346d2dc9db17fb90
(sorry no logs since I installed magisk ages ago!)
