### ISSUE TITLE
Android 11 October Patch Pixel 3a XL bootloop with Magisk 21/Manager 8.0.1

### ISSUE THREAD

**Issue by Starforce9** [topjohnwu/Magisk#3292] opened 2020-10-08 00:11 UTC
With magisk_patched.img after patching the boot.img for the October 2020 update it consistently bootloops. No custom recovery installed or anything out of the ordinary.

**Comment by KyoukanGG** [comment] 2020-10-08 01:40
Same issue with a 4 XL. Have tried a few times, a couple with 20.4 and a couple with 21.

**Comment by TheSysWiz** [comment] 2020-10-08 02:53
Identical issue, except mine is a 2XL.  Multiple attempts have failed, forcing me to flash back the original boot image. On latest Canary.

**Comment by neetrath** [comment] 2020-10-08 09:09
Same issue with Pixel 2

**Comment by fancy-rabbit** [comment] 2020-10-08 16:58
same issue with Pixel 3

**Comment by MichaelSMVogel** [comment] 2020-10-08 19:05
have you disabled any modules before update? There is a known issue with systemless hosts triggering a boot loop
if you have adb enabled, run adb wait-for-device shell magisk --remove-modules
if not, flash original boot.img and boot without magisk, enable and authorize your computer for adb debugging
flash patched image and then restart with the adb remove command
this should get you to a rooted phone on october patch with latest magisk but without any modules

**Comment by KyoukanGG** [comment] 2020-10-08 22:10
> adb wait-for-device shell magisk --remove-modules

I've literally never had this command work, so I always just assumed it was for some use case I've never run into. I just tried again, and it dumped me back off to the bootloader.

It's also worth mentioning that when I get back into the bootloader (whether via command above, or from button combination), and attempt to start from there, it will fail with:

> Enter reason: no valid slot to boot

**Comment by MichaelSMVogel** [comment] 2020-10-08 22:14
It needs to run when magisk has started but before it loads the modules. So force restart the phone and execute the command right away. It will restart the phone after the modules were removed.
The boot slot thing is likely because the phone rebooted so many times that it wants to try the second partition. You can switch back to the other slot via fastboot and try again...

**Comment by KyoukanGG** [comment] 2020-10-08 22:19
I run the command before I even turn the phone on (that's what the adb wait-for-device part is...), so that it executes at the earliest possible time. Is there some finesse to waiting until the right time that I'm missing?

> The boot slot thing is likely because the phone rebooted so many times that it wants to try the second partition.

Maybe? But in this case it was the first reboot after flashing, so... seems unlikely? Does it remember failed reboots from before the last successful boot?

**Comment by MichaelSMVogel** [comment] 2020-10-08 22:24
No finesse in timing, you are doing it right. I have experienced the boot slot issue before and I flashed the whole firmware package without the -w option again to get it back to working. But I do use the --remove-modules command and it does work for me as intended.

There is some sort of counter in the phone for the second system partition. I do not know the details of that.

**Comment by KyoukanGG** [comment] 2020-10-08 22:25
Not sure the etiquette on posting updates, so I made a new post instead of editing the previous, just to keep it clear that they are distinct.

I went ahead and reflashed Magisk, ran the adb wait command before even rebooting, then rebooted the phone. Phone attempted to boot, restarted, then went back to bootloader with the "no valid slot" entry reason. I then set the active boot partition back to b (which is where I flashed Magisk), attempted to boot, and am bootlooped again.

**Comment by MichaelSMVogel** [comment] 2020-10-08 22:28
hm, maybe two different issues that have the same result? I am sorry but I don't know what else to suggest.

**Comment by itismo** [comment] 2020-10-09 06:25
Same issue on Pixel 2 XL, I have no Magisk modules installed at all and every time i flash the patched Magisk image I go into a bootloop that is solved only by flashing the stock boot image.

**Comment by itismo** [comment] 2020-10-09 08:34
Hello,

Managed to boot my phone with root by installing Magisk v21 Beta using TWRP, the stable version V20.4 does not also work even with TWRP.

**Comment by fancy-rabbit** [comment] 2020-10-09 13:03
run adb wait-for-device shell magisk --remove-modules just take me to the bootloader with 'no valid slot to boot'.
A11 Oct, Pixel 3

**Comment by TheSysWiz** [comment] 2020-10-09 20:21
Still bootloop city.   :(
1. I flashed the magisk-patched boot image.
2. I rebooted and ran "adb wait-for-device shell magisk --remove-modules".  It eventually ran and rebooted.  And rebooted...
3. Basically, it bootloops until I re-flash the stock boot.img

Any more ideas?  I'd really like my root back.  :)

**Comment by drakax1** [comment] 2020-10-10 08:52
Hi all,

Took me less than 30sec to get it on my Pixel 3a

1. adb devices _#be sure device is recognized_
2. adb reboot bootloader
3. fastboot getvar all _#to check which slot is active **a** or **b**_
[img]https://i.imgur.com/4RGzBLE.jpg[/img]
5. fastboot set_active _**a** or **b**_
6. fastboot flash boot magisk_patched.img
7. fastboot reboot

Hope it'll help.

**Comment by Didgeridoohan** [comment] 2020-10-10 09:35
Just a thought, but also make sure that your Platform Tools are up-to-date. All kinds of weird issues can arise if you don't have the latest versions of adb and fastboot...

**Comment by ziofat** [comment] 2020-10-10 10:46
Pixel 4 XL, previously installed Magisk on Android 10 but lost it when upgrade to Android 11.
I installed Magisk Manager 8.0.2 today and using the latest October image to patch the boot.img, then flash the patched boot.img. My phone then cannot boot anymore, it always go to fastboot mode. I cannot get into recovery mode or rescue mode.

I have to use flash_all without -w to restore the system image.

I am not sure is this a same problem, but no modules were installed.

**Comment by TheSysWiz** [comment] 2020-10-10 15:41
> Took me less than 30sec to get it on my Pixel 3a:
[snip]
> Hope it'll help.

Unfortunately, it did not do the trick.  I already had been flashing to the active slot.
It bootloops until the stock boot image gets flashed.  I do not have any modules installed (per advice above). 

Thanks, though.

**Comment by KyoukanGG** [comment] 2020-10-10 21:15
>     1. adb devices _#be sure device is recognized_
>     2. adb reboot bootloader
>     3. fastboot getvar all _#to check which slot is active **a** or **b**_
>        https://i.imgur.com/4RGzBLE.jpg
>     4. fastboot set_active _**a** or **b**_
>     5. fastboot flash boot magisk_patched.img
>     6. fastboot reboot

By default fastboot is flashing to the active slot, but I went ahead and followed this procedure anyways, to the same outcome. Bootlooped until flashing back the original boot.img.

**Comment by drakax1** [comment] 2020-10-10 23:27
> > Took me less than 30sec to get it on my Pixel 3a:
> > [snip]
> > Hope it'll help.
> 
> Unfortunately, it did not do the trick. I already had been flashing to the active slot.
> It bootloops until the stock boot image gets flashed. I do not have any modules installed (per advice above).
> 
> Thanks, though.
> 
> EDIT: I also tried the BETA channel with the same bootloop results.

I'm using the **Canary** channel.
http://imgur.com/a/KeOMWA3

**Comment by TheSysWiz** [comment] 2020-10-10 23:55
> > > Took me less than 30sec to get it on my Pixel 3a:
> > > [snip]
> > > Hope it'll help.
> > 
> > 
> > Unfortunately, it did not do the trick. I already had been flashing to the active slot.
> > It bootloops until the stock boot image gets flashed. I do not have any modules installed (per advice above).
> > Thanks, though.
> > EDIT: I also tried the BETA channel with the same bootloop results.
> 
> I'm using the **Canary** channel.
> http://imgur.com/a/KeOMWA3

As am I.  What I meant is that for extra punishment, in addition to trying the above with the CANARY channel, I also tried the BETA channel to see if it would work for my phone.  Nada.

**Comment by Geo25rey** [comment] 2020-10-11 00:59
@TheSysWiz I understand your pain. I had the same issue; it took me a few days to fix it. 

The only way I was able to root my pixel 3a was using a prepatched boot.img found [here](https://drive.google.com/drive/folders/1wH7pvsHYznbDJ_vTsb_dWBNJBDcx2wHx) ([source](https://forum.xda-developers.com/pixel-3a/how-to/root-3a-t3929053)). Once, I booted, not flashed, the prepatched boot.img, I installed Magisk using the direct method and it worked fine with the Canary channel.

Note: When I say "booted", I mean running `fastboot boot patched_boot.img` When I say "flashed", I mean running `fastboot flash boot patched_boot.img`

**Comment by Geo25rey** [comment] 2020-10-11 01:05
My guess to why this is happening is only rooted devices can consistently patch boot.img's. Maybe a Magisk dependency works different on stock Android 11 vs on rooted. For those who patched the Android 11 boot.img on Android 10 stock or rooted, I'd like to hear your experiences.

**Comment by drakax1** [comment] 2020-10-11 08:21
That's weird!

Try:
- removing all Magisk modules directly from Magisk manager.
- uninstall Magisk manager
- download and (re)install Magisk manager **Beta** from [here](https://magiskmanager.com/magisk-beta#Download_Magisk_Beta_210_Latest_Version_For_Android)
- go to `bootloader` and flash stock `boot.img` to **both** slots __a_ & __b_
- reboot system and from here try again my steps from previous post.

**Comment by TheSysWiz** [comment] 2020-10-11 15:44
Well. I have tried many variations of all of the above advice.  Ranging from flashing both slots, to just _booting_ the patched image, to booting with TWRP and installing the zip from there.  I do not have any modules installed.  I have tried all of this with both the BETA and CAN versions of Magisk.  I am out of ideas.  :(

**Comment by TheSysWiz** [comment] 2020-10-13 02:48
Persistence paid off.  It turns out that the --remove-modules command either didn't work the first time, or it left something that caused the bootloop.  I tried running it again and after the reboot, it made it all the way in.  I used the latest CAN build for both the manager and magisk. Whew.

**Comment by zombieschlafsack** [comment] 2020-10-13 06:30
Hi guys, I'm not sure if that helps but I've managed to get it working on my Pixel 3a sargo with the October Patch 2020:

1. Boot into Android
2. Install Magisk Canary APK (obviously remove any other version first)
3. Patch boot.img via Magisk app and copy to local "fastboot.exe" folder (boot.img extracted from factory image "11.0.0 (RP1A.201005.004, Oct 2020)")
4. REMOVE all screen-locking features like fingerprint and PIN (I've set it to "swipe to unlock")
5. adb reboot-bootloader
6. fastboot set_active X (X = b, in my case)
7. fastboot flash boot magisk_patched.img
8. fastboot reboot
9. Done

Side note: Removing the modules from Magisk did not work for me. Everytime I've tried I got an error that Magisk could not be found. Also, I'm coming from a working Android 10 vanilla version with Magisk root and installed modules. After the above process my previously installed Magisk modules are still there.

**Comment by nexus-replicant** [comment] 2020-10-13 20:43
I used the following steps based on the suggestions by Geo25rey to update my Pixel 2xl. It seems to sidestep the module issue.

Android version: 11.0.0 (RP1A.201005.004, Oct 2020)
Magisk Manager version: 8.0.2 (307) (11)
Magisk version: 21.0 (21000)
Stock recovery

- Download Android 11 factory image and extract boot.img file
- adb push boot.img /sdcard/Download
- install Magisk using the "Select and patch a file" option
- Once completed, magisk_patched.img will be in /sdcard/Download
- adb pull /sdcard/Download/magisk_patched.img
- adb reboot bootloader
- fastboot boot magisk_patched.img    (this is the crucial difference! Do not flash! Boot using magisk_patched.img)
- Open Magisk Manager - It should show Magisk as installed
- Install Magisk using the "Direct Install (recommended)" option  (this step flashes Magisk)
- Reboot to test.

Thank you Geo25rey and everyone else contributing to the resolution of this issue!

**Comment by fancy-rabbit** [comment] 2020-10-14 01:54
> I used the following steps based on the suggestions by Geo25rey to update my Pixel 2xl. It seems to sidestep the module issue.
> 
> Android version: 11.0.0 (RP1A.201005.004, Oct 2020)
> Magisk Manager version: 8.0.2 (307) (11)
> Magisk version: 21.0 (21000)
> Stock recovery
> 
> * Download Android 11 factory image and extract boot.img file
> * adb push boot.img /sdcard/Download
> * install Magisk using the "Select and patch a file" option
> * Once completed, magisk_patched.img will be in /sdcard/Download
> * adb pull /sdcard/Download/magisk_patched.img
> * adb reboot bootloader
> * fastboot boot magisk_patched.img    (this is the crucial difference! Do not flash! Boot using magisk_patched.img)
> * Open Magisk Manager - It should show Magisk as installed
> * Install Magisk using the "Direct Install (recommended)" option  (this step flashes Magisk)
> * Reboot to test.
> 
> Thank you Geo25rey and everyone else contributing to the resolution of this issue!

this works on my pixel3 with A11 October Patch

**Comment by Louissenny** [comment] 2020-10-16 00:29
> I used the following steps based on the suggestions by Geo25rey to update my Pixel 2xl. It seems to sidestep the module issue.
> 
> Android version: 11.0.0 (RP1A.201005.004, Oct 2020)
> Magisk Manager version: 8.0.2 (307) (11)
> Magisk version: 21.0 (21000)
> Stock recovery
> 
> * Download Android 11 factory image and extract boot.img file
> * adb push boot.img /sdcard/Download
> * install Magisk using the "Select and patch a file" option
> * Once completed, magisk_patched.img will be in /sdcard/Download
> * adb pull /sdcard/Download/magisk_patched.img
> * adb reboot bootloader
> * fastboot boot magisk_patched.img    (this is the crucial difference! Do not flash! Boot using magisk_patched.img)
> * Open Magisk Manager - It should show Magisk as installed
> * Install Magisk using the "Direct Install (recommended)" option  (this step flashes Magisk)
> * Reboot to test.
> 
> Thank you Geo25rey and everyone else contributing to the resolution of this issue!

This works on my pixel 2xl too. Thanks buddy!

**Closed** 2020-10-16 09:14 UTC

**Comment by gabortim** [comment] 2020-11-13 20:41
Has anyone tried nexus-replicant's [method](https://github.com/topjohnwu/Magisk/issues/3292#issuecomment-707997803) on a Pixel 2 XL after a factory image flash? I did, and it didn't work :(

I noticed one thing. Before trying anything, I set the theme black. Usually, when the Android theme is black, the boot logo's background is also black. However, when I tried `fastboot boot magisk_patched.img` the background became white (and a few seconds later went back to bootloader).

Maybe there is a mounting/decrypting issue?

```
Device: Google Pixel 2 XL (taimen)
Factory image: 11.0.0 (RP1A.201005.004, Oct 2020)
├─ bootloader-taimen-tmz30m.img (SHA256: 1611909410df9e2ae3504318a0076f03a4af03f2ece167565746ab2f907d639b)
└─ magisk-patched.img (SHA256: c5b66bdb3ab46c2d76f3ccd940dbaa91c07e4ffee3abca0d079fa903697d67a5)

Magisk: 21.1 (21100)
Manager: 8.0.3 (314) from this GitHub repo
```
