### ISSUE TITLE
Manager GUI glitches in 279 canary on pre Android 10

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#2598] opened 2020-03-28 09:42 UTC
GUI is totaly broken in the 279 canary.
Log: [log.txt](https://github.com/topjohnwu/Magisk/files/4396908/log.txt)

Screenshot:
![Screenshot_20200328-113705](https://user-images.githubusercontent.com/16293419/77820148-ba631280-70e8-11ea-804e-5822062babde.png)

**Comment by osm0sis** [comment] 2020-03-28 13:53
Duplicate of #2506?

**Comment by Displax** [comment] 2020-03-28 16:44
> Duplicate of #2506.
Nope, it's not duplicate. It's regression from canary 268, where UI is ok.
Now it is two different bug's, first in flashing log and second in all interface.

**Comment by topjohnwu** [comment] 2020-03-28 20:49
@Displax what device and Android version are you running on?

**Comment by Displax** [comment] 2020-03-28 20:53
@topjohnwu Xiaomi Mi A1, Android 8.1 original ROM (Android ONE)

**Comment by KaMyKaSii** [comment] 2020-03-28 21:45
Same here on ZenFone 4 with stock Android 9
https://gofile.io/?c=7VCyGJ
[screenflikering.txt](https://github.com/topjohnwu/Magisk/files/4397964/screenflikering.txt)

**Closed** 2020-03-29 13:10 UTC
Labels: bug, confirmed
