### ISSUE TITLE
Oppo Realme 3 bootloop with Magisk 19.3 Canary

### ISSUE THREAD

**Issue by fawazahmed0** [topjohnwu/Magisk#1534] opened 2019-05-31 10:42 UTC
I have tried patching boot.img with the latest canary 19.3 , but still the phone bootloops.
I have patched using Magisk canary debug app.

Here is the link to stock boot image (A only system as root, no ramdisk in boot.img):

https://drive.google.com/open?id=17kuagLCpxKDtasfw4C0rS2o67mq-j_wg

System Ramdisk(Extracted from system.img):

https://drive.google.com/file/d/1zyvpnLDDTuWMvV8DYXjQylwQqWOpbyVq/view?usp=sharing

Partition Dump:
https://forum.xda-developers.com/realme-3/development/files-partition-dump-realme-3-t3931069

Device: Realme 3 RMX1825 (Android 9) ( A only system as root)

**Comment by fawazahmed0** [comment] 2019-05-31 11:09
[last_kmsg.log](https://github.com/topjohnwu/Magisk/files/3241009/last_kmsg.log)

Got this log from /proc/last_kmsg

**Comment by fawazahmed0** [comment] 2019-05-31 13:46
[dmesg.txt](https://github.com/topjohnwu/Magisk/files/3241467/dmesg.txt)
kernel dmesg log from stock boot image  (Normal kernel log)

**Comment by fawazahmed0** [comment] 2019-05-31 14:07
@topjohnwu Seems like selinux issue, magiskinit not detecting selinux

**Comment by fawazahmed0** [comment] 2019-05-31 19:25
Flashed GSI, to make sure my stock ramdisk init was not the culprit, even in GSI same kernel panic log.

**Comment by aIecxs** [comment] 2019-06-22 00:03
@fawazahmed0 is boot.img as only file sufficient for rooting? i guess we must provide a full ROM to Magisk Manager in order to get all partitions patched, or at least boot + recovery + vbmeta (like for [Samsung](https://topjohnwu.github.io/Magisk/install.html#additional-info))
the problem is we only have recovery.cpio.gz (which is afaik not the same like recovery.img)

**Comment by fawazahmed0** [comment] 2019-06-22 06:14
@aIecxs  my phone does not have vbmeta partition, I guess that might not work for my phone

**Comment by aIecxs** [comment] 2019-06-22 16:12
according to this thread i believe it becomes useless trying to patch a boot.img since Pie, but i am not sure [https://forum.xda-developers.com/showthread.php?t=2073775&page=218](https://forum.xda-developers.com/showthread.php?t=2073775&page=218)

**Comment by fawazahmed0** [comment] 2019-06-22 16:55
@aIecxs  Yeah, from Pie onwards, the boot.img does not contain ramdisk (System as root devices). Magisk started supported A-only System as root devices from version 19

> v19.0
- [General] Remove usage of magisk.img
- [General] Add 64 bit magisk binary for native 64 bit support
- [General] Support A only system-as-root devices that released with Android 9.0

**Comment by aIecxs** [comment] 2019-06-22 17:53
so, whats the purpose of trying to patch empty boot.img? Does Magisk Manager still something? I have noticed it places a init binary inside, i wonder if it is ever executed when ramdisk is empty?

**Comment by aIecxs** [comment] 2019-06-22 21:45
I think you can close this issue
[https://topjohnwu.github.io/Magisk/install.html#magisk-in-recovery](https://topjohnwu.github.io/Magisk/install.html#magisk-in-recovery)

**Comment by fawazahmed0** [comment] 2019-06-23 06:41
@aIecxs The init does gets executed, magisk patches the kernel to load the init binary from boot.img, this init binary will load the magisk root and also execute the stock init inside system.img

**Comment by topjohnwu** [comment] 2019-06-26 17:26
Please try the latest canary. Report again if it doesn't fix the issue.

**Closed by topjohnwu** 2019-06-26 17:26 UTC

**Comment by fawazahmed0** [comment] 2019-06-27 16:06
@topjohnwu Confirmed it's working, I think now GSI's will also support magisk. Thanks
