### ISSUE TITLE
Magisk newer than v21.0 can't properly patch the boot image

### ISSUE THREAD

**Issue by Lishoo** [topjohnwu/Magisk#3722] opened 2021-01-17 13:24 UTC
Hi, I'v got a LG g6 h870 bootloader unlocked and magisk patched boot.img with version 20.4.
Some time ago I've got a notification that an update is available so I gave it a try, the version was 21.2 and I tried to install it directly (recommended), the patch ended with success but after reboot there was a bootloop, I still have the previously patched boot.img so I flashed it back and everything was ok.
Few days later I've got once again the notification that a newer version is available it was the v21.3, this time I've patched manually the boot.img and tried to flash it with the fastboot command, but the result was the same, still bootloop.

The original boot.img size is 22 632KB
The boot.img patched with the v20.4(working) is 22 854KB
The boot.img patched with the v21.2, v21.3 and the canary is always about 10 230 KB (+- 4KB depending what option are selected)

I'v tried to patch the stock boot.img and the magiskpatched_boot.img but the result is always the same.

![Screenshot_20210117-135655](https://user-images.githubusercontent.com/1045996/104844228-4a1fba80-58cf-11eb-8d63-a34152aeafd4.png)

[magisk_patched_working.zip](https://github.com/topjohnwu/Magisk/files/5826144/magisk_patched_working.zip)
[orginal_boot.zip](https://github.com/topjohnwu/Magisk/files/5826146/orginal_boot.zip)
[magisk_patched_7WZM0.zip](https://github.com/topjohnwu/Magisk/files/5826157/magisk_patched_7WZM0.zip)

[magisk_install_log_2021-01-17T133430Z.log](https://github.com/topjohnwu/Magisk/files/5826148/magisk_install_log_2021-01-17T133430Z.log)
[magisk_install_log_2021-01-17T134934Z.log](https://github.com/topjohnwu/Magisk/files/5826149/magisk_install_log_2021-01-17T134934Z.log)
[magisk_install_log_2021-01-17T135018Z.log](https://github.com/topjohnwu/Magisk/files/5826151/magisk_install_log_2021-01-17T135018Z.log)
[magisk_install_log_2021-01-17T135048Z.log](https://github.com/topjohnwu/Magisk/files/5826152/magisk_install_log_2021-01-17T135048Z.log)

I hope you can fix that issue soon :)

UPDATE
I just checked the version 21.0 and it boots up correctly, so I update the title, the 21.1 is the first that won't boot.

**Comment by Frotty** [comment] 2021-01-17 15:06
I've got the same problem with my Pixel 4a, bootloops when I flash patched boot images with any recent version.

**Comment by Haus3master** [comment] 2021-01-17 15:12
I think there is something about the 'vbmeta' being empty or blanked out our something to look out for, look up on how to set up Magisk for your specific device (I read somewhere that some devices might require to do something with vbmeta to boot the patched image, I'm still not sure)...
PS: Just make sure there boot image of your device is being patched by the device itself, because it pulls some info about our device and patches it accordingly... (If you patch the boot image of phone A with phone B, and if phone B is different to phone A, then your boot image won't work, to put it simply, if you patch the boot image of a galaxy S10 on a pixel 3, the boot image won't work, you have to patch the boot image of the galaxy S10 on the galaxy S10 itself...)

**Comment by Frotty** [comment] 2021-01-17 15:14
@Haus3master I'm patching the file on the phone I am flashing it (obviously?)

**Comment by EduApps-CDG** [comment] 2021-01-18 03:22
Same here, but for me 21.2 is working, and 21.3+ not

**Comment by DrinkTaiTea** [comment] 2021-01-21 12:49
I have a similar issue with my Huawei Mate 9 MHA-L29 which uses a Kirin 960 chipset. 20.4 worked fine, but upgrading using TWRP to install the ZIP shows success but doesn't actually patch. Magisk Manager will show nothing as installed. I tried the most recent 21.4 but the issue remains.

**Comment by japanesephundroid** [comment] 2021-01-24 18:12
> I made some investigation and checked that replacing the file in the Magisk-v21.4.zip/arm/magiskboot with the magiskboot from v21.0 and flashing that one fixes the problem.

I can confirm that doing this enabled me installing Magisk and fixing this issue described here:
https://github.com/topjohnwu/Magisk/issues/3635
that was closed because of insufficient debug information.

(LG V20, Android 8.0 stock)

**Comment by davidgro** [comment] 2021-01-26 23:42
Is that workaround effectively the same thing as just installing version 21.0? Anyone know how much of the framework code that changed in newer versions ends up in that file?

**Comment by Lishoo** [comment] 2021-02-03 00:33
I'v finally made my own build and done the fix
![Screenshot_20210203-011917](https://user-images.githubusercontent.com/1045996/106680954-cbf63000-65bf-11eb-87bc-833e03e50c13.png)

**Comment by davidgro** [comment] 2021-02-03 18:31
@Lishoo Please reopen this until your pull request is actually merged. Until that happens this issue is still happening for everyone on certain phones.

**Comment by Lishoo** [comment] 2021-02-04 12:31
https://github.com/topjohnwu/Magisk/issues/3770

**Comment by llucax** [comment] 2021-02-04 20:20
I tried the patched version from #3812 PR (downloading the artifact built by GA Actions: https://github.com/topjohnwu/Magisk/suites/1955232499/artifacts/38733760) and it worked. This might be a temporary solution for people stuck with this bug.

**Closed** 2021-02-08 01:41 UTC

**Comment by Frotty** [comment] 2021-02-10 20:00
I'm still getting boot loops with my Pixel 4a on latest canary :/
