### ISSUE TITLE
No root, Magisk 18.0

### ISSUE THREAD

**Issue by Deviltrucker** [topjohnwu/Magisk#884] opened 2018-12-18 20:30 UTC
Apps that require root don't detect it
Logs:
12-18 21:05:11.842   259   259 I Magisk  : * Creating /sbin overlay
12-18 21:05:11.892   266   266 I Magisk  : Magisk v18.0(18000) daemon started
12-18 21:05:11.902   266   267 I Magisk  : ** post-fs-data mode running
12-18 21:05:11.902   266   267 I Magisk  : * Initializing Magisk environment
12-18 21:05:11.902   266   267 I Magisk  : * Mounting mirrors
12-18 21:05:11.902   266   267 I Magisk  : mount: /sbin/.magisk/mirror/system
12-18 21:05:11.902   266   267 I Magisk  : link: /sbin/.magisk/mirror/vendor
12-18 21:05:11.902   266   267 I Magisk  : bind_mount: /sbin/.magisk/mirror/bin
12-18 21:05:11.902   266   267 I Magisk  : * Setting up internal busybox
12-18 21:05:11.972   273   273 I Magisk  : Magisk v18.0(18000) logger started
12-18 21:05:12.032   266   267 I Magisk  : Create /data/adb/magisk.img with size 64M
12-18 21:05:12.112   266   267 I Magisk  : * Mounting /data/adb/magisk.img
12-18 21:05:12.352   266   267 I Magisk  : * Running post-fs-data.d scripts
12-18 21:05:12.352   266   267 I Magisk  : * Running module post-fs-data scripts
12-18 21:05:12.352   266   267 I Magisk  : * Loading modules
12-18 21:05:12.482   266   286 I Magisk  : * Starting MagiskHide
12-18 21:05:12.482   266   286 I Magisk  : hide_utils: Hiding sensitive props
12-18 21:05:12.482   266   286 I Magisk  : hide_list add: [com.google.android.gms/.droidguard.DroidGuardService]
12-18 21:05:12.583   266   286 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
12-18 21:05:13.383   266   346 I Magisk  : ** late_start service mode running
12-18 21:05:13.393   266   346 I Magisk  : * Running service.d scripts
12-18 21:05:13.443   266   346 I Magisk  : * Running module service scripts
12-18 21:05:13.984   266   349 I Magisk  : * Starting MagiskHide
12-18 21:05:13.984   266   349 I Magisk  : hide_utils: Hiding sensitive props
12-18 21:05:13.984   266   349 I Magisk  : hide_list: [com.google.android.gms/.droidguard.DroidGuardService]
12-18 21:05:14.044   266   349 E Magisk  : proc_monitor: Your kernel doesn't support mount namespace :(
12-18 21:05:41.433   266  2351 E Magisk  : su: cannot find manager
12-18 21:05:44.547   266  2650 E Magisk  : su: cannot find manager
12-18 21:06:26.662   266  4843 E Magisk  : su: cannot find manager
12-18 21:06:30.766   266  5041 E Magisk  : su: cannot find manager
12-18 21:08:04.056  9187  9187 W Magisk  : su: request rejected (10201->0)
12-18 21:10:46.349 11230 11230 W Magisk  : su: request rejected (10188->0)
12-18 21:20:22.724 19943 19943 E Magisk  : write failed with 32: Broken pipe
12-18 21:20:41.554 20196 20196 E Magisk  : write failed with 32: Broken pipe

**Comment by bmg002** [comment] 2018-12-18 20:39
I am expecting this will get closed as it is not a bug in Magisk.  The error is clearly listed in the log:
Your kernel doesn't support mount namespace :(

You need a newer kernel.

**Comment by Deviltrucker** [comment] 2018-12-18 20:44
Well, it's a HTC One so no kernel can do that, I've used ElementalX

**Comment by Deviltrucker** [comment] 2018-12-19 15:18
> @Didgeridoohan Well I did a clean install, still the same

**Comment by bmg002** [comment] 2018-12-19 16:57
Thanks for correcting me and sorry about the misinformation; I thought that mount namespace was required for more than just magisk hide.

As a thought, have you granted magisk manager all of the permissions it can in your phone settings including allow draw over other apps?  I know that allow draw over other apps one bit me a few times on MIUI.  On my phone, it would deny it and I would need to go into magisk manager to allow it after the first denial and then it was all good for any new apps requesting root UNLESS I allowed magisk to draw over other apps.  I never checked the logs when I had issues with it not prompting, because I was able to resolve them in other ways on my own, but I probably should have looked at the logs.

**Comment by dumcoh** [comment] 2018-12-22 21:50
I have the same problem in v18.0: no superuser, superuser apps list is empty, superuser log is empty. In v17.1 this work. I tried to reinstall Manager, no effect...
I use HTC ONE m7 with stock kernel + mount namespaces patch.
Any ideas?
Log (Canary): [magisk.log](https://github.com/topjohnwu/Magisk/files/2705573/magisk.log)

**Comment by Deviltrucker** [comment] 2018-12-23 10:07
>@dumcoh mount namespaces patch?

**Comment by dumcoh** [comment] 2018-12-23 17:05
@Deviltrucker Yes.
"MagiskHide relies on ns proc mnt file descriptor introduced in Linux 3.8. Even if you are running a kernel lower than 3.8, it is very likely this feature is already backported. If your kernel lacks this feature, you can build (or ask your custom kernel dev) with some additional patches. The relevant patches are: set CONFIG_NAMESPACES=y in defconfig, and apply [this patch](https://patchwork.kernel.org/patch/201482/). More info: [Namespace file descriptors](https://lwn.net/Articles/406684/) (2010 original article)"

**Comment by topjohnwu** [comment] 2018-12-24 09:40
@Deviltrucker you have to properly install Magisk Manager. It cannot be placed in external storage, or adapted storage.

**Closed by topjohnwu** 2018-12-24 09:40 UTC

**Comment by Deviltrucker** [comment] 2018-12-24 11:37
>@topjohnwu Yeah it's properly installed, I've done a clean install many times. I haven't touched anything

- 

- 

- didn't

 touched anything

**Comment by Didgeridoohan** [comment] 2018-12-24 12:01
@Deviltrucker It might have gotten installed to external/adoptable storage by default. Please check and make sure it's installed to the internal storage.

**Comment by Deviltrucker** [comment] 2018-12-24 13:18
@Didgeridoohan I'm sure I'm not using adaptable storage haha

**Comment by Deviltrucker** [comment] 2018-12-25 20:58
@Didgeridoohan Magisk got a lot of changes it may be that, I've reinstalled it many times, 
I don't have a SD card slot so I can say it's properly installed on the internal and only storage on the phone.

**Comment by saeed2011** [comment] 2019-01-09 11:56
I was have the same proplem the solution is to allow magisk manger to run in background
Exclude it from doze 
Thanks 😊

**Comment by Jasi2169** [comment] 2019-04-26 02:27
Doesnot fix the issue still its here from very long

**Comment by Jasi2169** [comment] 2019-04-26 14:12
try this @Deviltrucker 

https://forum.xda-developers.com/apps/magisk/magisk-root-granter-v1-0-t3925037

**Comment by Deviltrucker** [comment] 2019-04-26 15:19
@saeed2011 Lollipop doesn't have doze and I don't use anything like greenify to kill that would be stupid.

**Comment by Deviltrucker** [comment] 2019-04-26 15:20
@Jasi2169 It was fixed

**Comment by Jasi2169** [comment] 2019-04-26 18:04
I do use greenify but magisk manager is not selected in it also in battery optimizations it is whitelisted so dont know issue even i run the magisk manager and press home button so it stays in background still popup doesnot come, had to create app which edit magiskdb for the app

**Comment by eliafino** [comment] 2019-11-24 10:46
> try this @Deviltrucker
> 
> https://forum.xda-developers.com/apps/magisk/magisk-root-granter-v1-0-t3925037

Virus inside
