### ISSUE TITLE
Problems with new Design

### ISSUE THREAD

**Issue by Metamogul** [topjohnwu/Magisk#3249] opened 2020-10-04 13:10 UTC
Hey John Wu, thank you very much for your continous efforts to develop and improve Magisk - one of the most helpful tools for the Android platform ever. I see that you've put a lot of work into the new design. However, I find some of the new design aspects irritating:

- The menu bar keeps disappearing, sometimes the app will open without any menu at all (because it disappeared before and the app is still open in RAM). Missing the navigation seems somehow disfunctional and I can't find a good reason why the app should have no menu.
- The implementation of the main menu at the bottom of the screen is somehow new an stylish, but not very consistent with most other Android applications and doesn't seem to over a better way of navigating. It doesn't improve on usability. Even more, when not disappearing, it's overlapping with other screen content that might be of interest. Having a slide-in-from-the-left menu as before doesn't seem so wrong and is the most familiar concept. Furthermore, it only uses screenspace when needed and is not obstructing the view on other elements of interest.
- The use of non-standard fonts as before makes the app not blend in so well with the rest of the Android eco system. Not a major issue, but  irritating to the eye nevertheless. The app doesn't feel so familiar anymore and more foreign to the rest of the system.
- Varying thickness of lines in icons (e.g. the icons in the top bar are fatter than the ones in the bottom bar; the home house in the bottom bar has way more visual weight than the bug), buttons and fonts (different weights, sizes and fonts all over the app) introduce a certain amount of visual inconsistency. Visually, the app seems to have lost a lot of cohesion.
- The use of all those rounded-edges-background bubbles in the settings menu doesn't make much sense to me. The menu feels a little cluttered now.

Would it be possible to bring back the established design, maybe as an option in the settings, or to improve on this design to tidy up and focues the home screen a little like you tried with this new design? Or to rework the existing one, for example to implement more of the material design principles?

**Comment by osm0sis** [comment] 2020-10-04 19:39
New design is here to stay, but there's always room for improvement. I'll let @diareuse address specific points and close or label this enhancement as he wishes.

**Comment by diareuse** [comment] 2020-10-05 07:38
Bringing back the verbose design from previous version is not an option as it's been stated multiple times that it's beyond our capabilities as far as our free time goes, the whole solution is free after all.

I agree with you on multiple points and will try to improve upon the current state as it's objectively not ideal.

**Comment by Madis0** [comment] 2020-10-09 13:29
Regarding the bottom bar, how about using a more standard-looking one like Play Store and F-Droid? (full width, titles below, permanently visible)
That would improve consistency and make the top title bar redundant, too.

More specifically:

- Reboot option could be between "remove Magisk" and about section
- Settings could be the fifth option of the bottom bar
- Module refresh could just be done by dragging from the top
- Log buttons could be at the top like now

**Comment by jokinpaha** [comment] 2020-10-25 06:46
I just got an Android 11 update on my OnePlus 8 Pro and installed Magisk before reboot. Now as I am trying to manage modules etc. I noticed that I can't access menu at all. For what I gather from these posts there is supposed to be a menu bar at the bottom of Magisk Manager but for me it doesn't appear at all. 
![Screenshot_20201025-084535](https://user-images.githubusercontent.com/42548314/97100665-81027d80-169e-11eb-8f27-d820b7a9686b.jpg)

**Comment by diareuse** [comment] 2020-10-25 06:49
> ...there is supposed to be a menu bar at the bottom of Magisk Manager but for me it doesn't appear at all.

Menu is invisible for users who don't have Magisk installed. Your screenshot clearly says Installed: N/A, so I'd look into that first 🙂

**Comment by jokinpaha** [comment] 2020-10-25 07:19
> > ...there is supposed to be a menu bar at the bottom of Magisk Manager but for me it doesn't appear at all.
> 
> Menu is invisible for users who don't have Magisk installed. Your screenshot clearly says Installed: N/A, so I'd look into that first 🙂

So it seems. Apparently Magisk patching didn't stick on OTA update. I downloaded and installed OTA and before reboot run MagiskManager and patched inactive slot. MagiskManager then asked for reboot and now I don't have Magisk installed. I tought that this was an UI issue but it seems that I lost Magisk. Now that TWRP is not supported on OP 8/8 Pro I don't know how to get it back. 

But on the UI side, maybe the menu bar could be greyed out when Magisk is not installed. Hiding it leads to thinking that it is missing and/or that there is an UI issue.

**Comment by diareuse** [comment] 2020-10-25 07:23
You can still patch boot image in app and then flash it via fastboot 🙂 (correct me if I'm wrong, not familiar with OP8)
It was grayed out until recently. 🤷 Thanks for the input though

**Comment by topjohnwu** [comment] 2020-10-25 13:35
@jokinpaha I explicitly requested to hide the menu bar when no Magisk is installed because it doesn't make any sense

**Comment by DorCoMaNdO** [comment] 2020-10-28 21:42
I should've probably browsed existing issues before posting mine, but I just posted #3426 asking for the modules menu to be accessible without Magisk installed, this is because I booted a stock boot image in an attempt to resolve a bootloop caused by a module I activated, but I couldn't use the manager to turn it off or uninstall it, so I've had to use ADB to remove all the modules instead.
On another note, are there other commands one could use via ADB shell to list modules and remove selected ones?

**Comment by unixandria-xda** [comment] 2020-10-29 01:45
> I should've probably browsed existing issues before posting mine, but I just posted #3426 asking for the modules menu to be accessible without Magisk installed, this is because I booted a stock boot image in an attempt to resolve a bootloop caused by a module I activated, but I couldn't use the manager to turn it off or uninstall it, so I've had to use ADB to remove all the modules instead.
> On another note, are there other commands one could use via ADB shell to list modules and remove selected ones?

No. Weirdly even though adb is in the name, it can't be accessed via adb (a technical note: when using adb everything is done via `shell` user not actually under adb context)

**Comment by osm0sis** [comment] 2021-11-08 14:15
I think the concerns in the original post here seem pretty much addressed in the latest canaries. The settings style actually happens to fit more with Material You, so it stays as well.

**Closed by osm0sis** 2021-11-08 14:15 UTC
Labels: enhancement
