### ISSUE TITLE
Android 11 gets stuck after boot

### ISSUE THREAD

**Issue by DoganM95** [topjohnwu/Magisk#3277] opened 2020-10-07 06:43 UTC
**Device**: Pixel 3 XL - (RP1A.200720.009, Sep 2020)
**Magisk**: installed
**Packages installed**: none

**Scenario:**
The phone boots with magisk installed (no packages installed). After entering the PIN it gets to the home-screen but apps won't open, they just show their logo forever. home button may still work, clicking it gets me to home screen and at this point the phone is stuck and does not respond to any input anymore. screen won't turn off/on using power button, reboot menu won't show up. **BUT** the live-wallpaper is still moving..

The freezing is not a matter of where i navigate, it is a matter of time (around 20 seconds after PIN entry)

**Temporary solution:**
Flashing the stock `boot.img` turns everything back to normal, booting it and flashing `magisk_patched.img` again works for a while. but as soon as the phone turns off e.g. for an hour the same "getting stuck" drama starts again.

This issue seems related to #3171 indirectly, but i am not using systemless hosts.

**Comment by V10lator** [comment] 2020-10-07 11:21
Same for me on a Honor 9 Lite (LLD-L21) with either Resurrection Remix OS 7.0.1 Beta 1 or AEX Beta 1 P1 (Minimal GApps).
I was able to install Magisk in the past but this time it ends in a bootloop when trying to reboot to recovery. I followed the instructions at https://topjohnwu.github.io/Magisk/install.html

For me it shows the blue splash, then the "Your device has been unlocked and can't be trusted" screen, then it loops back to the blue splash and from there it boots into erecovery.

Now I tried a hardcore way:
- Download TWRP for the honor 9 lite.
- Flash it to recovery_ramdisk, then boot it.
- adb push the unmodified stock recovery and the newest magisk zip file to /tmp/.
flash the original recovery with `dd if=/tmp/RECOVERY_RAMDIS.img of=/dev/block/bootdevice/by-name/recovery_ramdisk && rm /tmp/RECOVERY_RAMDIS.img`
- Do the following:
```
# twrp install /tmp/Magisk-v21.0.zip
Installing zip file '/tmp/Magisk-v21.0.zip'
Checking for Digest file...
Skipping Digest check: no Digest file found
***********************
 Magisk 21.0 Installer
***********************
- Mounting /system
- Mounting /vendor
- Device is system-as-root
- Mounting /apex/com.android.conscrypt
- Mounting /apex/com.android.media
- Mounting /apex/com.android.media.swcodec
- Mounting /apex/com.android.resolv
- Mounting /apex/com.android.runtime.debug
- Mounting /apex/com.android.tzdata
- System-as-root, keep dm/avb-verity
- Target image: /dev/block/mmcblk0p33
- Device platform: arm64
- Constructing environment
- Unpacking boot image
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
- Repacking boot image
- Flashing new boot image
- Unmounting partitions
- Done
Done processing script file
```
- `adb reboot`
- Reboot to recovery

But that's still a stock recovery, no boot into Magisk happening.

**Comment by PerfectSlayer** [comment] 2020-10-16 12:01
Hi all,

First, the manager seems to have issue patching the boot.img file.
On first try, it only creates a 0 byte file, even if the log seems okay.
On the second try, when a `magisk_patched.img` already exists, it well created a 25m file. The 2nd log is the same.

Even using the 25m patched boot file, the device can't boot.

Configuration:
* Pixel 2 (walleye)
* Factory rom (walleye-rp1a.201005.004-factory)
* Manager 8.0.2 (307)

**Comment by Chillchef** [comment] 2020-10-16 15:39
Pixel2 (walleye)
Magisk canary
since magisk 20.4:
Flashing patched boot.img (from factory image.walleye-rp1a.201005.004.zip) works perfect.
but: Randomly crashed systemUI, often crash the system settings app, extreme battery drain, device heating up like a hand warmer.
Back to original firmware,all fine,patch with magisk,same errors. Problems since magisk 20.4.

**Comment by shacharr** [comment] 2020-10-19 00:42
Maybe this is a duplicate of #3171 ? Similar symptoms, and Pixel series devices as the common factor.

**Comment by shmshd** [comment] 2020-10-19 14:19
@Chillchef Did you try clean factory image install since the issue?

**Comment by soridal** [comment] 2020-10-22 01:50
Exactly same issue for me.
Almost gets stuck after boot or ramdomly.

Pixel 3XL, RP1A.2001.005.004
Magisk : stable, beta and canary with android 11.

**Comment by chicknsoup** [comment] 2020-10-23 08:59
Same issue on Mi9T using latest weekly xiaomi.eu version

**Closed** 2020-10-25 13:32 UTC

**Comment by Natanji** [comment] 2020-10-25 14:34
Hey @topjohnwu why did you close this? This is not a complaint, I'd just like to understand since a lot of people seem to be affected by this problem.

**Comment by soridal** [comment] 2020-10-31 21:49
Closed this issue..
Is there any solution?

**Comment by PerfectSlayer** [comment] 2020-11-01 06:32
For the record, the canary version fixed the issue for me. Thanks!

**Comment by DoganM95** [comment] 2020-11-08 21:44
Nope, newest version (21006) didn't fix the issue for me.
@topjohnwu Getting stuck issue still persists. Although it takes a bit longer now to get stuck (1-2 minutes)

**Comment by DoganM95** [comment] 2022-04-30 15:06
@topjohnwu this issue still persists by the way. I don't understand why you would just close this ticket without any test/fix.

**Comment by shacharr** [comment] 2022-04-30 18:34
The most dominant regression with Android 11 was a bug in the f2fs file system driver included with the original device os. As patching this bug requires compiling a specific kernel for each device impacted, magisk cannot do much to solve it. There is a change in place to avoid as much as possible touching f2fs, but it is still possible for magisk, when combined with certain apps and magisk hide enabled, to trigger the os bug. The behavior you described (live wallpaper active but apps are not starting any more) seems to match the bug (the filesystem dead locks, and anything using file system APIs is stuck, while code not interacting with the file system keeps on going), which is most likely why @topjohnwu closed the issue.
