### ISSUE TITLE
Bootloop on sony xperia 1 II after Using Magisk 23 patch the boot.img and fastboot falsh it

### ISSUE THREAD

**Issue by capteng33** [topjohnwu/Magisk#4408] opened 2021-06-01 12:11 UTC
I patched boot image and fastboot it，but I met a bootloop.  So I tried the way 

> https://github.com/topjohnwu/Magisk/issues/3752 said

`1. Patch 58.1.A.5.159 boot.img with magisk`
`2. use Image Kitchen and unpack boot.img`
`3. Locate fstab.qcom and edit with notepad++ remove the system_ext line and save`
`4. Repack and flash the new .img ,fastboot flash boot_a & boot_b boot.img`

Unfortunately，there is still a BOOTLOOP.
Is there any solution to this issue？

Device: sony xperia 1 II
Android version: Android11 58.1.A.5.159-R28B
Magisk version name: v23.0
Magisk version code: 23001

**Comment by badmaan** [comment] 2021-07-02 11:31
Anyone might need it, patched and working boot image from XQ-AT51_Customized EU_58.1.A.5.280-R20B . https://drive.google.com/file/d/1Tu793D-Kke36IEkInuMD1o2aDJihyMtP/view?usp=sharing

**Comment by SolidTux** [comment] 2021-07-29 15:03
I have the same problem version `XQ-AS52_Customized EEA_58.1.A.5.330`

**Comment by pojavluncher2021** [comment] 2021-08-08 07:35
Will installing magisk and rebooting work? Will it make a boot loop or no? just curious. btw what to do next if magisk raw image is installed?

**Comment by dnw3039** [comment] 2021-08-16 02:55
I also had bootloop after installing Magisk 23 on a Galaxy Tab S2 running linageOS.

**Comment by osm0sis** [comment] 2021-08-21 09:35
I don't think we have enough info here. No boot image, no logs. If @badmaan has a viable workaround maybe he can post the method?

**Comment by badmaan** [comment] 2021-08-21 09:39
- Download the stock rom with xperifirm.
- Use unsin to convert boot image.
- Unpack it with android image kitchen.
- Edit fstab and remove system_ext and repack the boot image.
- Patch the image-new.img with magisk, and flash it through fastboot.

**Comment by osm0sis** [comment] 2021-08-21 09:42
So I guess the OP just did something wrong with AIK then? I'll mark this as duplicate of the other Sony system_ext fstab issue. 👍

**Comment by badmaan** [comment] 2021-08-21 09:42
> So I guess the OP just did something wrong with AIK then? I'll mark this as duplicate of the other Sony system_ext fstab issue. 👍

Probably yes.

**Comment by osm0sis** [comment] 2021-08-21 09:46
#3752

**Closed by osm0sis** 2021-08-21 09:46 UTC
Labels: duplicate
