### ISSUE TITLE
Now hide manager will auto update the last version,no choice

### ISSUE THREAD

**Issue by KisThFir** [topjohnwu/Magisk#3319] opened 2020-10-11 01:57 UTC
Can I have a choice? I want to hide the same version manager

**Comment by zgfg** [comment] 2020-10-11 08:02
There are few issues already opened about hiding Magisk Manager, no need for one more, like this. Anyway:

1) Latest Manager versions for Stable and Beta are 8.0.2 307, you can hide/repackage with no problem and after repackaging you will stay on the same Manager 8.0.2 307.
If your device is Xiaomi with MIUI, you MUST enable Install via USB under Developers menu - otherwise repackaging will immediately fail

2) Latest Canary Magisk Manager is 308, it can be also repackaged to stay on the same 308 version but due to the bug #3297, you need to follow the workaround method:
https://forum.xda-developers.com/showpost.php?p=83680873&postcount=42033

**Comment by KisThFir** [comment] 2020-10-11 08:26
> There are few issues already opened about hiding Magisk Manager, no need for one more, like this. Anyway:
> 
> 1. Latest Manager versions for Stable and Beta are 8.0.2 307, you can hide/repackage with no problem and after repackaging you will stay on the same Manager 8.0.2 307.
>    If your device is Xiaomi with MIUI, you MUST enable Install via USB under Developers menu - otherwise repackaging will immediately fail
> 2. Latest Canary Magisk Manager is 308, it can be also repackaged to stay on the same 308 version but due to the bug #3297, you need to follow the workaround method:
>    https://forum.xda-developers.com/showpost.php?p=83680873&postcount=42033

First of all, thank you for your help, but what I want is the hide manager of the same version at 7.5.1,Because the new version 8.0.2 is unstable for me.

**Comment by Didgeridoohan** [comment] 2020-10-11 09:26
The Manager has always used the latest available version for hiding. If you want to use a different Manager you need to set a custom channel that points to the Manager version you want.

Github history makes it so you can actually find the old update channel and use that, and that's been covered many times on both Github and XDA. You'll probably find it if you search around.

Either way, this is not a bug and should not have been brought up here. Please close the issue so that John or Chris doesn't have to.

**Comment by zgfg** [comment] 2020-10-11 09:41
Then you need to find on GitHub stable.json commit correspondin to the release of Magisk 20.4/Manager 7.5.1, - this one will be:
https://raw.githubusercontent.com/topjohnwu/magisk_files/63555595ffa9b079f3a411dd2c00a80a3d985ccc/stable.json

Starting from Manager 7.5.1, change the Update channel to Custom, putting the URL as above

Check does it correctly show Magisk 20.4 and Manager 7.5.1 as ' latest' and execute Hide Magisk Manager (it was long ago, I hope there was no issues with hiding thal old Manager 7.5.1)

https://raw.githubusercontent.com/topjohnwu/magisk_files/63555595ffa9b079f3a411dd2c00a80a3d985ccc/stable.json

**Comment by KisThFir** [comment] 2020-10-11 10:04
> Then you need to find on GitHub stable.json commit corresponding to the release of Magisk 20.4/Manager 7.5.1 - this one will be:
> https://raw.githubusercontent.com/topjohnwu/magisk_files/63555595ffa9b079f3a411dd2c00a80a3d985ccc/stable.json
> 
> Starting from Manager 7.5.1, change the Update channel to Custom, putting the URL as above
> 
> Check does it correctly show Magisk 20.4 and Manager 7.5.1 as ' latest' and execute Hide Magisk Manager (it was long ago, I hope there was no issues with hiding thal old Manager 7.5.1)

Thanks,I have tried this before I asked, It doesn't work.

**Comment by Didgeridoohan** [comment] 2020-10-11 10:53
@KisThFir Then you're probably doing something wrong somewhere. Using the provided link as the custom channel should do exactly what you want.

Again: please close the issue. It's not a bug.

**Closed** 2020-10-11 11:50 UTC
