### ISSUE TITLE
Nothing Phone (1) OS 1.5.3 freezes and ramdumps during boot after boot.img is patched

### ISSUE THREAD

**Issue by LukeSkyD** [topjohnwu/Magisk#6780] opened 2023-03-22 15:29 UTC
With unlocked bootloader and stock boot the phone works ok; with a patched boot img freezes and/or ramdumps during use are common.
Sometimes they happen right after boot, other times they can take a while.
This happens with and without modules installed, with or without zygisk as users have reported.
In the crashLog file i encountered a freeze, no ramdump.

Device: Nothing Phone (1)
Android version: 13
Nothing OS Version: 1.5.3 and 1.5.3 HOTFIX are affected, both EEA and Global variant of the phone, <= 1.5.2 versions work fine
Magisk version name:  25.2 but also [d251c288](https://github.com/topjohnwu/Magisk/actions/runs/4488819172)
Magisk version code: 25205, [25210](https://github.com/topjohnwu/Magisk/actions/runs/4488819172)

[crashLog.txt](https://github.com/topjohnwu/Magisk/files/11041668/crashLog.txt)

<details>
<summary>Photo of a user reported ramdump</summary>
<img src="https://user-images.githubusercontent.com/100560115/226953164-caaec2ee-8c52-46d9-877d-f70df7246038.png">
</details>

EDIT:
Here are some boot images:
[1.5.2 stock](https://mega.nz/file/AIQygAiB#IAFs1ZR9ne6sgv1xmIWzFn--ARXhMddjFIALdC7iteQ)
[1.5.2 magisk](https://mega.nz/file/vkpQwKAC#CJGYCn0dy2GytmQIwiYDc0ieNooWOXGI9Gdbden06Y0)
(they are both working)

[1.5.3 stock](https://mega.nz/file/sFw1wD4S#FCAbo0OFKrGatn0moAISkE89CYVCACv-13wSpxT967s)
[1.5.3 magisk](https://mega.nz/file/VYgBGLYA#XPfOQ76ReJJpkxup0gp5mfobonce5R76x52S28DR5BI)

[1.5.3.hotfix stock](https://mega.nz/file/D4AAVC4A#XUrMqJdAYa7uB_piL1J898L07eRRLZC8XS_5c7xVqe4)
[1.5.3.hotfix magisk](https://mega.nz/file/ilxA0IYQ#I4P9r9If0jdbtBB5ksQTxVOngpqjTdThEO2rs1VGSrs)
(magisk patched boot freezes)

EDIT 2:
In my naivity i thought it was a problem with the ramdisk, so i packed a custom boot img with 1.5.2 magisk patched ramdisk and 1.5.3.hotfix boot and kernel, still crashed.
I've noticed the phone crashing a lot more with app like discord opened in background. Also discord disconnects my client easily if i multitask opening other apps.

Using the phone slowly seems to mitigate the problem, like it seems the phone boots things before it actually loaded them correctly.
Example: the phone crashes a lot faster if at boot i immediately unlock, open discord and join a voice server with a bluetooth headset, exit while still connected and open like a magazine app.

I don't get crashes only at apps' startup, even during normal use, like yt in background with some music at a certain time the music stops like the buffering but without the loading circle, the phone is still usable for 2 seconds and then freeze.

I checked the ram usage and it never goes over 3.5GB or very rarely so it doesn't seem like a memory leak is the cause.

**Comment by Whatsek** [comment] 2023-03-22 20:34
I have the same problem, on my nothing phone 1 after the latest 1.5.3 update. Unlocked bootloader, Magisk with 3 modules. I amusing this config on this phone from the beginning, without any problems, so it has something to do with the 1.5.3 update.

**Comment by pannal** [comment] 2023-03-23 00:52
Same here, restored original boot imgs, now the phone is stable again. Sadly there's no way to downgrade to 1.5.2 AFAIK.

**Comment by yujincheng08** [comment] 2023-03-23 11:25
maybe you trigger a crash and share the [bugreport](https://developer.android.com/studio/debug/bug-report)? Cannot see anything useful from the log tho.

**Comment by yujincheng08** [comment] 2023-03-23 11:54
BTW, can you adb when the phone freezes? If so, you'd better capture bugreport during freeze.

**Comment by pannal** [comment] 2023-03-23 13:11
Just tried that. ADB still works when the whole system is frozen - I managed to start capturing a bugreport, but it stuck at 0%. ADB shell was still possible afterwards, but then the dumpstatez service seems to have crashed:

```
C:\WINDOWS\system32>adb bugreport F:\__ANDROID\nothing1\bugreports
^C 0%] generating bugreport-SpacewarEEA-TKQ1.220915.002-2023-03-23-14-05-57.zip
C:\WINDOWS\system32>adb devices
List of devices attached
P2126A001028    device


C:\WINDOWS\system32>adb shell
Spacewar:/ $ ls
acct        config         dev              lost+found  oem          second_stage_resources  system_ext
apex        d              etc              metadata    postinstall  storage                 vendor
bin         data           init             mnt         proc         sys                     vendor_dlkm
bugreports  data_mirror    init.environ.rc  odm         product      system
cache       debug_ramdisk  linkerconfig     odm_dlkm    sdcard       system_dlkm
Spacewar:/ $ exit

C:\WINDOWS\system32>adb bugreport F:\__ANDROID\nothing1\bugreports
adb: device failed to take a zipped bugreport: Failed to connect to dumpstatez service: Connection refused

C:\WINDOWS\system32>adb shell
Spacewar:/ $ exit

C:\WINDOWS\system32>adb bugreport F:\__ANDROID\nothing1\bugreports
adb: device failed to take a zipped bugreport: Failed to connect to dumpstatez service: Connection refused
```

Once a magisk-patched boot img is used, _any_ process that uses a lot of resources seems to crash almost immediately - SystemUI with it. I've triggered the freeze by using ReVanced to patch a YT apk - it froze after about 5 seconds, UI completely stuck and unusable (the above is from that time).

**Comment by dxdvostfr** [comment] 2023-03-23 18:16
Same problem here.

**Comment by canyie** [comment] 2023-03-24 02:16
Can you get me some logs by `adb shell su -c dmesg > kernel.log` and `adb shell su -c getprop > prop.log`  when it freezes?

**Comment by HE7086** [comment] 2023-03-24 19:09
I have the exact same problem on 1.5.3 with hotfix, and logcat looks exactly the same, so here are my logs attached:

[kernel.log](https://github.com/topjohnwu/Magisk/files/11065640/kernel.log)
[prop.log](https://github.com/topjohnwu/Magisk/files/11065641/prop.log)

The way I trigger this is just randomly open many apps, as the discord method mentioned previously didn't work well for me.

Also I think this is related to memory, since memory usage during freeze is unusually high (normally it's around 4GiB used)
```
❯ adb shell    
Spacewar:/ $ free -h
                total        used        free      shared     buffers
Mem:              11G         11G        249M         74M        1.0M
-/+ buffers/cache:            11G        250M
Swap:            4.0G        1.1G        2.8G
Spacewar:/ $
```
It is worth noting that when freezing the device sometimes showed up as offline in adb, and the only way to interact with it is to long press the power button to reboot.

Hope these help.

**Comment by LukeSkyD** [comment] 2023-03-24 20:54
> Since adb is accessible when problem happens, can you get me some logs by `adb shell su -c dmesg > kernel.log` and `adb shell su -c getprop > prop.log` when it freezes?

Even if the device is in the adb devices list, the logs created are empty.
The phone doesn't answer back, it's completely frozen.

**Comment by pannal** [comment] 2023-03-24 22:56
> I have the exact same problem on 1.5.3 with hotfix, and logcat looks exactly the same, so here are my logs attached (without zygisk):
> 
> [kernel.log](https://github.com/topjohnwu/Magisk/files/11065640/kernel.log) [prop.log](https://github.com/topjohnwu/Magisk/files/11065641/prop.log)
> 
> The way I trigger this is just randomly open many apps, as the discord method mentioned previously didn't work well for me.
> 
> Also I think this is related to memory, since memory usage during freeze is unusually high (normally it's around 4GiB used)
> 
> ```
> ❯ adb shell    
> Spacewar:/ $ free -h
>                 total        used        free      shared     buffers
> Mem:              11G         11G        249M         74M        1.0M
> -/+ buffers/cache:            11G        250M
> Swap:            4.0G        1.1G        2.8G
> Spacewar:/ $
> ```
> 
> It is worth noting that when freezing the device sometimes showed up as offline in adb, and the only way to interact with it is to long press the power button to reboot.
> 
> Hope these help.

In my case the freeze is _always_ the whole system. Don't know why, but my apps don't crash - the whole phone freezes when it does.

**Comment by HE7086** [comment] 2023-03-25 11:14
> In my case the freeze is _always_ the whole system. Don't know why, but my apps don't crash - the whole phone freezes when it does.

Yeah that's also my case, I suspect that the systemui got stuck because of OOM. Tried to restart the systemui from adb but it also stuck.

**Comment by LukeSkyD** [comment] 2023-03-26 10:16
> Since adb is accessible when problem happens, can you get me some logs by `adb shell su -c dmesg > kernel.log` and `adb shell su -c getprop > prop.log` when it freezes?

Nothing
When the phone freezes the phone outputs nothing
I've only have a logcat produced after the phone rebooted itself because before it is not seen.

[out2.log](https://github.com/topjohnwu/Magisk/files/11071281/out2.log)

I've tried for three days to get any log but now i need a working phone and to use banking apps.

It's much easier to get a logcat at freeze with zygisk and the log file is filled with super critical pressure event polling check, the "suspicious" error in the screenshot a user provided in one of my previous messages.

**Comment by SelfRef** [comment] 2023-03-26 17:13
Two interesting situations I had were when I used Spotify and device froze but music still played via bluetooth speaker and I could change songs via remote device so both bluetooth stack and app still worked.

The second situation was while using camera app - the whole system froze but live preview in camera app was working - this was the only time app was showing some kind of UI update after freeze.

**Comment by Niecks90** [comment] 2023-03-28 12:58
Same issue here, version 1.5.3 fresh installed with patched boot.

Multiples freezes (on Camera app, etc...), hard reboot is the only way to get phone works back.

**Comment by Niecks90** [comment] 2023-03-28 16:04
There is this in changelog of 1.5.3 maybe it's the cause of the issue
_New memory management algorithm that reduces app restart times by over 35% and lowers CPU consumption to improve overall battery life. Improved system stability._

**Comment by amit548** [comment] 2023-03-28 23:39
I have facing the same problem and I downgrade the OS 1.5.3 to 1.5.2

**Comment by aleqz** [comment] 2023-03-29 08:18
> I have facing the same problem and I downgrade the OS 1.5.3 to 1.5.2

Did you lose all your data?
What was the the tutorial you followed?
Thanks

**Comment by pannal** [comment] 2023-03-29 12:44
> There is this in changelog of 1.5.3 maybe it's the cause of the issue _New memory management algorithm that reduces app restart times by over 35% and lowers CPU consumption to improve overall battery life. Improved system stability._

That would make a lot of sense IMHO. Most logs posted here had some kind of OOM issues.

Is anyone actively looking into this ticket? All up-to-date Nothing Phone 1's are affected.

**Comment by TheNotOnly** [comment] 2023-03-31 10:16
> > There is this in changelog of 1.5.3 maybe it's the cause of the issue _New memory management algorithm that reduces app restart times by over 35% and lowers CPU consumption to improve overall battery life. Improved system stability._
> 
> That would make a lot of sense IMHO. Most logs posted here had some kind of OOM issues.
> 
> Is anyone actively looking into this ticket? All up-to-date Nothing Phone 1's are affected.

Might be a memory leak. I remember seeing the ram full and logcat showing lots of processes restarting over and over until the ramdump occurs.

**Comment by amit548** [comment] 2023-03-31 10:40
> > I have facing the same problem and I downgrade the OS 1.5.3 to 1.5.2
> 
> Did you lose all your data? What was the the tutorial you followed? Thanks

I just use fastboot to flash full 1.1.7 version

**Comment by vvb2060** [comment] 2023-03-31 11:37
If anyone finds the reason, please open a new issue.

**Comment by pannal** [comment] 2023-03-31 12:12
> If anyone finds the reason, please open a new issue.

Wait, how does closing this issue help here? What info do you need? We've tried to comply with the log requests as well as possible. If it's not enough, please point us in the right direction.

The only thing that'll happen is that people who have the same issue (_everyone_ on Nothing Phone 1 who tries to root) comes and creates a new duplicate ticket.

**Comment by dxdvostfr** [comment] 2023-03-31 12:14
> > If anyone finds the reason, please open a new issue.
> 
> Wait, how does closing this issue help here? What info do you need? We've tried to comply with the log requests as well as possible. If it's not enough, please point us in the right direction.
> 
> The only thing that'll happen is that people who have the same issue (_everyone_ on Nothing Phone 1 who tries to root) comes and creates a new duplicate ticket.

Yeah right

**Comment by vvb2060** [comment] 2023-03-31 12:19
Sorry, we are not in a position to resolve this issue.  Not even sure how it relates to Magisk.

**Comment by pannal** [comment] 2023-03-31 12:21
And the logs don't show anything useful? 

> Not even sure how it relates to Magisk.
Well, the phone crashes when Magisk is used with firmware 1.5.3. It doesn't, when Magisk isn't installed. That's the only relation there is, really.

**Comment by LukeSkyD** [comment] 2023-03-31 12:56
> Sorry, we are not in a position to resolve this issue. Not even sure how it relates to Magisk.

Magisk is patching the boot image in a way that triggers problems in the os
It is not know if it is a problem caused by nothing os devs or magisk wrongly patching a new or different implementation of the boot image
Or the os checking for modifications and crashing.

It is not know if the new NP's ram implementation will be an isolated situation or will have ripercussions in the future.

It's not a problem that appears during normal use with a stock image.

It affects people with JUST the magisk patched boot img, NO MODULES, NO ZYGISK, NO ANYTHING.
Im available for further testing, everyone is but no help has come from the devs.

There is a compatibility issue between magisk and the phone, the cause has not been found, you cannot excluse magisk from the possible causes.

**Comment by Whatsek** [comment] 2023-03-31 17:33
My temporary workaround: https://forum.xda-developers.com/t/nothing-phone-1-rom-ota-nothing-os-repo-of-nothing-os.4464039/post-88357311

**Comment by canyie** [comment] 2023-03-31 17:48
Can anyone try this build? [app-debug.zip](https://github.com/topjohnwu/Magisk/files/11124576/app-debug.zip)

I've removed init.rc patching from source code, so you will see Magisk NOT INSTALLED. Just test if this bug happens.
Let's see which part of magisk triggers this weird bug!

**Comment by Whatsek** [comment] 2023-03-31 18:19
> Can someone try this build? [app-debug.zip](https://github.com/topjohnwu/Magisk/files/11124576/app-debug.zip)
> 
> I've removed init.rc patching from source code, so you will see Magisk NOT INSTALLED. Just test if this bug happens. Let's see which part of magisk triggers this weird bug!

I cantry this in half an hour: So I boot with a patched 1.5.3, install this version, en then do a direct install and reboot. Correct?

**Comment by gwolf2u** [comment] 2023-03-31 18:22
> > Can someone try this build? [app-debug.zip](https://github.com/topjohnwu/Magisk/files/11124576/app-debug.zip)
> > I've removed init.rc patching from source code, so you will see Magisk NOT INSTALLED. Just test if this bug happens. Let's see which part of magisk triggers this weird bug!
> 
> I can try this in half an hour: So I boot with a patched 1.5.3, install this version, en then do a direct install and reboot. Correct?

install the apk from inside zip
patch stock boot.img and boot with it
then patch boot withing magisk (as procedure)

**Comment by LukeSkyD** [comment] 2023-03-31 18:34
> 

booting the newly patched boot img does not give my the option to directly install in magisk, so i've installed the newer apk, but booted a previously patched boot img, then opened magisk and did direct install.

Now magisk shows as not installed but it should have the modified boot img

PS: thank you for reopening the issue

**Comment by ShiiroSan** [comment] 2023-03-31 19:47
> Can someone try this build? [app-debug.zip](https://github.com/topjohnwu/Magisk/files/11124576/app-debug.zip)
> 
> I've removed init.rc patching from source code, so you will see Magisk NOT INSTALLED. Just test if this bug happens. Let's see which part of magisk triggers this weird bug!

Not able to produce any logs requiring su. I guess it's because init.rc is removed (?). 
Even tho, I tried many demanding ram things (playing games, patching things via revanced manager, opening numerous apps) and no freeze so far.

**Comment by Whatsek** [comment] 2023-03-31 19:51
> > > Can someone try this build? [app-debug.zip](https://github.com/topjohnwu/Magisk/files/11124576/app-debug.zip)
> > > I've removed init.rc patching from source code, so you will see Magisk NOT INSTALLED. Just test if this bug happens. Let's see which part of magisk triggers this weird bug!
> > 
> > 
> > I can try this in half an hour: So I boot with a patched 1.5.3, install this version, en then do a direct install and reboot. Correct?
> 
> install the apk from inside zip patch stock boot.img and boot with it then patch boot withing magisk (as procedure)

First two steps succeed, third step cant be done, because magisk isn`t installed, so only "choose a file" method is availble.
Will keep using the phone with this boot.img now.

**Comment by canyie** [comment] 2023-04-01 03:39
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/11128377/app-debug.zip)
And how about this? Install the apk inside zip, open app, patch boot image, flash newly patched image via fastboot, then reboot. 
You will still see Magisk NOT INSTALLED on this build

**Comment by canyie** [comment] 2023-04-01 08:21
After removing `mount_mirror` and `load_modules`, the device works fine for several hours. It seems this issue is triggered by magic mounting. Maybe something like #3171

**Comment by LukeSkyD** [comment] 2023-04-01 08:46
> After removing `mount_mirror` and `load_modules`, the device works fine for several hours. It seems this issue is triggered by magic mounting. Maybe something like #3171

No issue with the first build posted, should i try the second one even if the comment is hidden?

**Comment by canyie** [comment] 2023-04-01 09:31
> > After removing `mount_mirror` and `load_modules`, the device works fine for several hours. It seems this issue is triggered by magic mounting. Maybe something like #3171
> 
> No freezes with the first build posted, should i try the second one even if the comment is hidden?

No need, I have privately asked a Nothing Phone user to test and he have confirmed that the build also randomly freezes.
I guess one of the following commit causes it:
https://github.com/NothingOSS/android_kernel_msm-5.4_nothing_sm7325/commit/9278b64d56c7fe1c33768c3ecdface56201f785e
https://github.com/NothingOSS/android_kernel_msm-5.4_nothing_sm7325/commit/ed56a0636bd0e3a3def144daab31f020f7a44558

**Comment by aviraxp** [comment] 2023-04-01 16:15
After investigation (actually assumption), it could be related to Nothing's backport of multi-gen LRU feature in kernel. Can you please run following command in rooted terminal:
`resetprop persist.sys.mglru_enable false`
Reboot and check if issue persists.

Multi-gen LRU will roll out to mainstream devices on Android 14.

**Comment by LukeSkyD** [comment] 2023-04-01 22:36
> After investigation (actually assumption), it could be related to Nothing's backport of multi-gen LRU feature in kernel. Can you please run following command in rooted terminal: `resetprop persist.sys.mglru_enable false` Reboot and check if issue persists.
> 
> Multi-gen LRU will roll out to mainstream devices on Android 14.

My phone just crashed... But seems to be more stable even with zygisk enabled

**Comment by aviraxp** [comment] 2023-04-02 05:42
> > After investigation (actually assumption), it could be related to Nothing's backport of multi-gen LRU feature in kernel. Can you please run following command in rooted terminal: `resetprop persist.sys.mglru_enable false` Reboot and check if issue persists.
> > Multi-gen LRU will roll out to mainstream devices on Android 14.
> 
> My phone just crashed... But seems to be more stable even with zygisk enabled

> 

what's the output of `cat /sys/kernel/mm/lru_gen/enabled`?

**Comment by LukeSkyD** [comment] 2023-04-02 06:17
> cat /sys/kernel/mm/lru_gen/enabled

0x0003

**Comment by aviraxp** [comment] 2023-04-02 06:49
> > cat /sys/kernel/mm/lru_gen/enabled
> 
> 0x0003

You didn't disable MGLRU then. Could make a script to resetprop 'resetprop persist.sys.mglru_enable false' in magisk.

**Comment by gwolf2u** [comment] 2023-04-02 07:05
after reboot resets to 0X0003
magisk module needed for sure
testing myself now also

**Comment by LukeSkyD** [comment] 2023-04-02 11:58
> > > cat /sys/kernel/mm/lru_gen/enabled
> > 
> > 
> > 0x0003
> 
> You didn't disable MGLRU then. Could make a script to resetprop 'resetprop persist.sys.mglru_enable false' in magisk.

it does not persist after reboot, having a script in post-fs-data.d correctly sets it to 0.

I'll try and let you know.

**Comment by gwolf2u** [comment] 2023-04-02 12:07
as of my testing, having prop restset via post-fs, value is false 0x0000 up until you enter pin/unlock
right after it's set to 0x0003

**Comment by LukeSkyD** [comment] 2023-04-02 12:10
> as of my testing, having prop restset via post-fs, value is false 0x0000 up until you enter pin/unlock right after it's set to 0x0003

mine is 0x000 even after unlock, getprop shows it false.

**Comment by gwolf2u** [comment] 2023-04-02 12:14
how are you adding script?
personally made magisk module (maybe that's the issue)

**Comment by LukeSkyD** [comment] 2023-04-02 14:10
> how are you adding script? personally made magisk module (maybe that's the issue)

I created an .sh script on pc, pushed to the phone and then with termux copied it to /data/adb/post-fs-data.d
chmod +x scriptname and rebooted

Then i tried doing a magisk module which didn't set the persist.sys.mglru_enable property to false and now even with the older script resetprops does not set anything

i also tried it with the verbose option but it's not outputting anything. Magisk shows it executing tho

**Comment by Niecks90** [comment] 2023-04-02 14:19
> > how are you adding script? personally made magisk module (maybe that's the issue)
> 
> I created an .sh script on pc, pushed to the phone and then with termux copied it to /data/adb/post-fs-data.d chmod +x scriptname and rebooted
> 
> Then i tried doing a magisk module which didn't set the persist.sys.mglru_enable property to false and now even with the older script resetprops does not set anything
> 
> i also tried it with the verbose option but it's not outputting anything. Magisk shows it executing tho
> 
> UPDATE: i tried rebooting into bootloader and then into system again, now with only the script in post-fs-data.d i again have the property set to false.

You don't have freeze anymore with this workaround?
Can you share your script pls?

**Comment by LukeSkyD** [comment] 2023-04-02 14:31
> > > how are you adding script? personally made magisk module (maybe that's the issue)
> > 
> > 
> > I created an .sh script on pc, pushed to the phone and then with termux copied it to /data/adb/post-fs-data.d chmod +x scriptname and rebooted
> > Then i tried doing a magisk module which didn't set the persist.sys.mglru_enable property to false and now even with the older script resetprops does not set anything
> > i also tried it with the verbose option but it's not outputting anything. Magisk shows it executing tho
> > UPDATE: i tried rebooting into bootloader and then into system again, now with only the script in post-fs-data.d i again have the property set to false.
> 
> You don't have freeze anymore with this workaround? Can you share your script pls?

Here's my Magisk module, it's working (at least for me).
Follow the guide in the readme

https://github.com/LukeSkyD/NP1-MGLRU-FIX

**Comment by gwolf2u** [comment] 2023-04-02 15:34
> > > > how are you adding script? personally made magisk module (maybe that's the issue)
> > > 
> > > 
> > > I created an .sh script on pc, pushed to the phone and then with termux copied it to /data/adb/post-fs-data.d chmod +x scriptname and rebooted
> > > Then i tried doing a magisk module which didn't set the persist.sys.mglru_enable property to false and now even with the older script resetprops does not set anything
> > > i also tried it with the verbose option but it's not outputting anything. Magisk shows it executing tho
> > > UPDATE: i tried rebooting into bootloader and then into system again, now with only the script in post-fs-data.d i again have the property set to false.
> > 
> > 
> > You don't have freeze anymore with this workaround? Can you share your script pls?
> 
> Here's my Magisk module, it's working (at least for me). Follow the guide in the readme
> 
> https://github.com/LukeSkyD/NP1-MGLRU-FIX

your module acts exactly as mine
rebooting
`cat /sys/kernel/mm/lru_gen/enabled -> 0x0000`
entered pin / fingerprint
`cat /sys/kernel/mm/lru_gen/enabled -> 0x0001` for split second then `0x0003`

so for me doesn't work
however, entering command `resetprop persist.sys.mglru_enable false` seems to make system run fine without issues
so as far as I can tell @aviraxp was right

now all rest is for magisk "experts" to find a good way to fix this

**Comment by LukeSkyD** [comment] 2023-04-02 15:39
> > > > > how are you adding script? personally made magisk module (maybe that's the issue)
> > > > 
> > > > 
> > > > I created an .sh script on pc, pushed to the phone and then with termux copied it to /data/adb/post-fs-data.d chmod +x scriptname and rebooted
> > > > Then i tried doing a magisk module which didn't set the persist.sys.mglru_enable property to false and now even with the older script resetprops does not set anything
> > > > i also tried it with the verbose option but it's not outputting anything. Magisk shows it executing tho
> > > > UPDATE: i tried rebooting into bootloader and then into system again, now with only the script in post-fs-data.d i again have the property set to false.
> > > 
> > > 
> > > You don't have freeze anymore with this workaround? Can you share your script pls?
> > 
> > 
> > Here's my Magisk module, it's working (at least for me). Follow the guide in the readme
> > https://github.com/LukeSkyD/NP1-MGLRU-FIX
> 
> your module acts exactly as mine rebooting `cat /sys/kernel/mm/lru_gen/enabled -> 0x0000` entered pin / fingerprint `cat /sys/kernel/mm/lru_gen/enabled -> 0x0001` for split second then `0x0003`
> 
> so for me doesn't work however, entering command `resetprop persist.sys.mglru_enable false` seems to make system run fine without issues so as far as I can tell @aviraxp was right
> 
> now all rest is for magisk "experts" to find a good way to fix this

We are gettin off topic with this but mine stays at zero, try to check for other modules or settings in your phone.

Anyway if freezes or crashes are encountered i will update this thread.

If 24h passes without issue i'll also let you know

**Comment by Nixola** [comment] 2023-04-02 22:10
Hi, I just wanted to mention disabling mglru seems to work on my phone, though the Magisk module doesn't (same issue as gwolf2u). It's only been a few hours without crashes, but since the longest I've went with Magisk on the latest firmware was about 5 minutes before having to force a reboot, I'd at the very least call it an improvement.

**Comment by LukeSkyD** [comment] 2023-04-02 22:40
> Hi, I just wanted to mention disabling mglru seems to work on my phone, though the Magisk module doesn't (same issue as gwolf2u). It's only been a few hours without crashes, but since the longest I've went with Magisk on the latest firmware was about 5 minutes before having to force a reboot, I'd at the very least call it an improvement.

Try this new version if it keeps changing maybe magisk is logging something about it

https://github.com/LukeSkyD/NP1-MGLRU-FIX/releases/tag/Release

Remember to perform a cold boot

Still no crashes for now, I've rebooted the phone one time for the module's update, seems like MGLRU is the culprit.

**Comment by aviraxp** [comment] 2023-04-03 02:05
Multiple devices and kernel have ported mglru but most of them are 5.10 kernel devices. Not sure if Nothing do it right, or it is a compality issue.

**Comment by LukeSkyD** [comment] 2023-04-03 06:02
> Multiple devices and kernel have ported mglru but unlike np1, most of them are 5.10 kernel devices. Not sure if Nothing ported it right, or it is a real compality issue.
> 
> I would suspect it is actually related to some weird cgroup issue as magiskd switched cgroup to prevent itself from being killed.

```uname -r``` returns ```5.4.197-qgki-g2efe4411886f```

```/sys/kernel/debug``` does not exists tho, is there another way to find any useful log about mglru or cgroup?

**Comment by yujincheng08** [comment] 2023-04-03 06:06
Based on the current investigation, I wonder if there's something Magisk should do about it. For NP users, maybe a custom module for this is more helpful. 🤔

**Comment by LukeSkyD** [comment] 2023-04-03 13:39
So far only two people out of around 50 reported freezes with mglru disabled
One was running an emulator app and got multiple freezes but i don't expected a system with a key feature disabled to be 100% stable in all environments.
The other opened the camera and froze.

The module only mitigates the problem.

So Nothing's implementation of mglru is the problem.
But i don't know if its a problem of the boot img or magisk not handling memory correctly
Should i test something else?

**Comment by aviraxp** [comment] 2023-04-03 14:43
Multiple custom kernels with MGLRU does not have issues (mostly 5.10+ kernel). So I will suggest that Nothing did sth wrong. Actually Nothing gets patches from a Google port of MGLRU (https://android-review.googlesource.com/c/kernel/common/+/2324610/5). MGLRU is new and many fixes are not ported in this chain.

**Comment by gwolf2u** [comment] 2023-04-03 16:51
there seems to be some trigger in the system that sets the prop to true again resulting in a crash
I've made a different magisk module that checkes for prop status every 30 seconds (because sometimes the crash occurs after a minute, so let's be safe) and resets back to false
feel free to use it guys if interested
https://github.com/gwolf2u/MGLRU-Disabler/releases/tag/4.0

**Comment by aviraxp** [comment] 2023-04-04 03:08
> there seems to be some trigger in the system that sets the prop to true again resulting in a crash
> I've made a different magisk module that checkes for prop status every 30 seconds (because sometimes the crash occurs after a minute, so let's be safe) and resets back to false
> feel free to use it guys if interested
> https://github.com/gwolf2u/MGLRU-Disabler/releases/tag/4.0

How about chown that 'enabled' node...

**Closed** 2023-04-04 03:32 UTC
Labels: wontfix, not our issue

**Comment by yujincheng08** [comment] 2023-05-05 11:16
1.5.4 should have fixed this issue.

**Comment by LukeSkyD** [comment] 2023-05-05 11:49
Lru_gen/enabled is set to 1, not 3 anymore

I've been using .4 for around 18h and no crashes or freezes so far, no crashes reported by the community either
