### ISSUE TITLE
wifi not work a10 ip config failed

### ISSUE THREAD

**Issue by zinhuofc** [topjohnwu/Magisk#7903] opened 2024-03-10 21:48 UTC
[2024-03-10-19-03-18[1].txt](https://github.com/topjohnwu/Magisk/files/14551878/2024-03-10-19-03-18.1.txt)

Device:redmi 7 
Android version: 10
Magisk version name: 27.0
Magisk version code:27001

**Comment by canyie** [comment] 2024-03-11 01:55
Duplicate of #7764

**Closed by canyie** 2024-03-11 01:55 UTC
