### ISSUE TITLE
Zygisk breaks manager app detecting Magisk install

### ISSUE THREAD

**Issue by AndrewChqng** [topjohnwu/Magisk#5699] opened 2022-04-07 19:51 UTC
Device: MIBOX 3
Android version: 5.1.1

Magisk version name: 24.3
Magisk version code: 24305
[magisk.log](https://github.com/topjohnwu/Magisk/files/8446038/magisk.log)
[boot-logcat.log](https://github.com/topjohnwu/Magisk/files/8446056/boot-logcat.log)

After enabling Zygisk (on 24.3 and canary) has resulted in this: 

```

shell@JurassicPark:/ $ su
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8000001
WARNING: linker: su: unused DT entry: type 0x6ffffef5 arg 0x107c
WARNING: linker: su: unused DT entry: type 0x6ffffffe arg 0x103c
WARNING: linker: su: unused DT entry: type 0x6fffffff arg 0x2
root@JurassicPark:/ # magisk
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8000001
WARNING: linker: magisk: unused DT entry: type 0x6ffffef5 arg 0x107c
WARNING: linker: magisk: unused DT entry: type 0x6ffffffe arg 0x103c
WARNING: linker: magisk: unused DT entry: type 0x6fffffff arg 0x2
```
```
adb install D:\Downloads\FoxMmm-0.4.2.apk
Performing Push Install
D:\Downloads\FoxMmm-0.4.2.apk: 1 file pushed, 0 skipped. 70.3 MB/s (2794325 bytes in 0.038s)
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8000001
WARNING: linker: app_process: unused DT entry: type 0x6ffffef5 arg 0x107c
WARNING: linker: app_process: unused DT entry: type 0x6ffffffe arg 0x103c
WARNING: linker: app_process: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8000001
WARNING: linker: zygisk: unused DT entry: type 0x6ffffef5 arg 0x107c
WARNING: linker: zygisk: unused DT entry: type 0x6ffffffe arg 0x103c
WARNING: linker: zygisk: unused DT entry: type 0x6fffffff arg 0x2
```

Main issue is causes Magisk app to stop detecting it's installed, even though I can still access magisk through shell and apps I've granted root to previously can still access root. I can't turn off Zygisk as only non-rooted options are available in the manager

 Thanks for the hard work from everyone though! It's appreciated all the effort that has been gone through

**Comment by yujincheng08** [comment] 2022-04-08 17:19
Duplicate of #5589

**Closed by yujincheng08** 2022-04-08 17:19 UTC
