### ISSUE TITLE
Endless boot after flashing patched boot.img

### ISSUE THREAD

**Issue by SquadCraftFTW** [topjohnwu/Magisk#5653] opened 2022-03-28 00:30 UTC
Having issues trying to successfully boot (phone stuck on logo) after flashing a patched boot.img on the latest version of canary, as well as the latest stable version (24.3). I made sure this wasn't simply an issue with me being impatient, so I waited for 20 minutes to boot at one point. Had to flash stock boot.img to fix this issue. 
I also tried to compile a dmesg.log (I've never done this before) but it came out empty so I won't include it. 
I had magisk installed beforehand on A11, but after the update I'm unable to get magisk to work. 

Device: F2 Pro
Android version: 12 (EU/13.0.2)
Magisk version name: Canary
Magisk version code: 24304

Attachments:

[magisk_install_log_2022-03-28T00_48_14.log](https://github.com/topjohnwu/Magisk/files/8358843/magisk_install_log_2022-03-28T00_48_14.log)
[magisk_log_2022-03-28T00_50_14.log](https://github.com/topjohnwu/Magisk/files/8358842/magisk_log_2022-03-28T00_50_14.log)
[boot.zip](https://github.com/topjohnwu/Magisk/files/8358847/boot.zip)
[mounts.log](https://github.com/topjohnwu/Magisk/files/8358850/mounts.log)

**Comment by yujincheng08** [comment] 2022-03-28 17:37
Duplicate of #5624

**Closed by yujincheng08** 2022-03-28 17:37 UTC
