### ISSUE TITLE
Magisk Hide not working

### ISSUE THREAD

**Issue by lijun0326** [topjohnwu/Magisk#1142] opened 2019-02-27 13:28 UTC
Reproduce:
1. Revoke su permission to Terminal
2. Add Terminal in Magisk Hide
3. Execute `/sbin/su` or `which su`, it can detect su binary.
![photo_2019-02-27_21-18-21](https://user-images.githubusercontent.com/17663689/53493233-d5beb100-3ad5-11e9-9967-1c2de8c3cd6c.jpg)
![photo_2019-02-27_21-18-22](https://user-images.githubusercontent.com/17663689/53493234-d5beb100-3ad5-11e9-999a-9f7a0123127e.jpg)
Version: Magisk v18.1, Magisk Manager v7.0.0
Device: Oneplus 6, Oxygen OS, Jan security patch.
After upgrade to v7.0 & v18.0, there are lots of weird bugs, idk whether it can be reproduce on other device because this is the only Android device I have.

**Comment by huyizheng** [comment] 2019-02-27 14:03
这是一个API 22的应用，你是不是拒绝了它的存储权限？
如果你拒绝它的存储权限，那么它的进程的挂载命名空间不会与zygote分离，导致magisk没法对它隐藏。
As this app is at API 22, did you disable its storage permission?
If you disable its storage permission, then the mount namespace of its process will not be separated from zygote, which means that magisk can't be hidden to it.

**Comment by lijun0326** [comment] 2019-02-27 14:07
@huyizheng 刚才试了下把存储空间权限打开，但是不管用。

**Comment by Didgeridoohan** [comment] 2019-02-27 15:18
Only report bugs based on the current code... Magisk v18.0 and v18.1 have bug concerning MagiskHide that has been fixed upstream.

Unless you can reproduce the issue on the current Canary build, please close the issue since it's not relevant to the current code.

**Closed** 2019-02-27 21:20 UTC
