### ISSUE TITLE
所有wifi ip配置错误  无法连接

### ISSUE THREAD

**Issue by wiseman815** [topjohnwu/Magisk#8137] opened 2024-06-18 09:59 UTC
Device:OnePlus 7pro
![Screenshot_20240618-172208](https://github.com/topjohnwu/Magisk/assets/39221181/bb6265b8-4bc5-4a9b-bd2c-cef93778e594)

Android version:10
Magisk version name:27.0
Magisk version code:27002
![Screenshot_20240618-172151](https://github.com/topjohnwu/Magisk/assets/39221181/32e4c4ad-939d-480e-97d9-582a0855c58a)

**Comment by yujincheng08** [comment] 2024-06-18 12:29
Duplicate of #7764

**Closed by yujincheng08** 2024-06-18 12:29 UTC

**Comment by vellrya** [comment] 2024-08-27 10:19
Were you able to activate wi-fi on version 27? It says that the bug [was fixed](https://github.com/topjohnwu/Magisk/issues/7764#issuecomment-2006587688) in builds after 19 March, but on OnePlus 7 Pro with Android 12 it's impossible to connect wi-fi even on version 27007.

**Comment by wiseman815** [comment] 2024-08-28 06:41
> Were you able to activate wi-fi on version 27? It says that the bug [was fixed](https://github.com/topjohnwu/Magisk/issues/7764#issuecomment-2006587688) in builds after 19 March, but on OnePlus 7 Pro with Android 12 it's impossible to connect wi-fi even on version 27007.

I'm currently using alpha's version 27002 and the wifi is working
