### ISSUE TITLE
Vivo Y31, 25.101 magiskinit can't mount init.rc, no problem here with 24.3

### ISSUE THREAD

**Issue by romanovj** [topjohnwu/Magisk#6081] opened 2022-07-09 16:24 UTC
02-08 17:20:33.870 0 0 W magiskinit: Mount [.magisk/rootdir/system/etc/init/hw/init.rc] -> [/system/etc/init/hw/init.rc]
02-08 17:20:33.870 0 0 I do_mount pid: 1 comm:magiskinit mount .magisk/rootdir/system/etc/init/hw/init.rc at hw/init.rc, flags:4096
02-08 17:20:33.870 0 0 W magiskinit: mount .magisk/rootdir/system/etc/init/hw/init.rc->/system/etc/init/hw/init.rc failed with 1: Operation not permitted
02-08 17:20:37.082 0 0 I init : Parsing file /system/etc/init/hw/init.rc...

Device: Vivo Y31
Android version: A12.1
Magisk version name: 9183a0a6
Magisk version code: 25101

On Vivo Y31 24.3 magisk can't mount on /system or /vendor, so I wrote .rc scripts for overlayfs on /system (no problems with working with layers) and other stuff, but at least there were no problems with mounting init.rc and su daemon.
[log.txt](https://github.com/topjohnwu/Magisk/files/9077507/log.txt)

**Comment by yujincheng08** [comment] 2022-07-09 18:45
Duplicate of #5148

**Comment by yujincheng08** [comment] 2022-07-09 18:46
Vivo kernel restricts bind mounting `init.rc` to inject magisk service and thus `magiskd` cannot be launched.

**Comment by romanovj** [comment] 2022-07-09 19:01
> Vivo kernel restricts bind mounting `init.rc` to inject magisk service and thus `magiskd` cannot be launched.

not on vivo y31, look what it is

02-08 22:51:50.660     0     0 I [07-09 18:55:35] init: starting service 'exec 24 (/system/bin/mount /sbin/.magisk/zygisk/app_process32 /system/bin/app_process32)'...
02-08 22:51:50.662     0     0 I [07-09 18:55:35] init: SVC_EXEC service 'exec 24 (/system/bin/mount /sbin/.magisk/zygisk/app_process32 /system/bin/app_process32)' pid 1013 (uid 0 gid 0+0 context u:r:su:s0) started; waiting..

02-08 22:51:50.683     0     0 I [07-09 18:55:35] init: starting service 'exec 25 (/system/bin/mount /sbin/.magisk/zygisk/app_process64 /system/bin/app_process64)'...
02-08 22:51:50.685     0     0 I [07-09 18:55:35] init: SVC_EXEC service 'exec 25 (/system/bin/mount /sbin/.magisk/zygisk/app_process64 /system/bin/app_process64)' pid 1017 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...

**Comment by yujincheng08** [comment] 2022-07-09 19:04
Plz check #5148. Vivo kernel also check the task path. Magisk 25+ changes magiskinit path to `/data/magiskinit` and may thus trigger the restriction. Anyway, it won't be fixed.

**Comment by romanovj** [comment] 2022-07-09 19:05
> Plz check #5148. Vivo kernel also checks the task path. Magisk 25+ changes magiskinit path to `/data/magiskinit` and may thus trigger the restriction. Anyway, it won't be fixed.

yeah, wontfix... looks like I need to revert changes here

**Closed** 2022-07-09 19:12 UTC

**Comment by romanovj** [comment] 2022-07-09 19:15
> Plz check #5148. Vivo kernel also checks the task path. Magisk 25+ changes magiskinit path to `/data/magiskinit` and may thus trigger the restriction. Anyway, it won't be fixed.

Actually there are different sets of restrictions on vivo phones, my kernel only prevents mounting /system and /vendor, also I can't work with boot patition from Android.

No problems with injecting code in init.rc, no problems with su daemon. In init.rc I can mount overlayfs on top on /system and change everything (near). I can mount etc.

So overall everything is good with 24.3

**Comment by romanovj** [comment] 2022-07-11 02:00
> Vivo kernel restricts bind mounting `init.rc` to inject magisk service and thus `magiskd` cannot be launched.

is it possible to use overlayfs to hijack init.rc?

**Comment by romanovj** [comment] 2022-07-15 09:50
> Plz check #5148. Vivo kernel also checks the task path. Magisk 25+ changes magiskinit path to `/data/magiskinit` and may thus trigger the restriction. Anyway, it won't be fixed.

Are there good guides how to make initramfs for debugging?
