### ISSUE TITLE
Magisk 21.2 cannot be installed on Sony Z1c with Android 10 Lineage 17.1

### ISSUE THREAD

**Issue by tramp20** [topjohnwu/Magisk#3636] opened 2021-01-02 14:00 UTC
1.  Description
    The last Magisk version that could be correct installed was 20.4.
    All versions after 20.4 fail (from the first canaries to 21.2 magisk-debug_6d88d8ad).

    1.1 Flashing magisk-debug_6d88d8ad.zip from TWRP twrp-3.4.0-1-amami does nothing (ended without visible errors): neither Magisk (shows installed N/A) nor Magisk Manager are installed.
    1.2 Patching the boot.img in the (manually installed) Manager 8.04 (app-debug_6d88d8ad.apk) and then flashed with fastboot shows Magisk "installed N/A" too.
The manager app-debug_6d88d8ad.apk shows 8.0.4 as installed.

    Device
    Sony Z1c (from 2014)
    Installed N/A
    RAMdisk Yes
    A/B no
    SAR yes
    crypto N/A
    Android 10 custom ROM lineage-17.1-20201218-UNOFFICIAL-amami-signed
    XDA thread ROM maintainer 115ek:
    https://forum.xda-developers.com/t/rom-unofficial-10-0-signed-ota-lineage-os-17-1-for-xperia-z1-compact.4007983/
    Download ROM:
    https://sourceforge.net/projects/lin17/files/amami/LineageOS_17_signed/

XDA thread TWRP maintainer 115ek:
https://forum.xda-developers.com/t/recovery-unofficial-amami-twrp-3-4-0.3960699/

XDA members Didgeridoohan and pndwal tried to help me and sent me to you.

    Logs
    recovery log after installing from TWRP
    installation log from patching in Manager
    unpatched boot.img

All are downloadable at https://www.magentacloud.de/share/dpmvvzlh4z

NB: I really had the latest canaries installed as akkim31 closed my first posting.

**Comment by Didgeridoohan** [comment] 2021-01-02 14:25
Just to be clear, your other issue wasn't closed by anyone but you... It was simply being referenced from another issue that in itself had been closed.

**Comment by tramp20** [comment] 2021-01-07 14:38
Hi,
nobody can help me?
I used canaries and provided logs as recommended: what shall I do?
Are the boot.img from LOS 17.1 and 18.1 defect, why are TWRP and MM not able to patch it (the last good Magisk version was 20.4)?

**Comment by Didgeridoohan** [comment] 2021-01-07 15:55
What you shall do? Wait.

Take a look in the list of issues. The oldest active one is over a year old...

If your described problem is one that can be fixed, it'll likely be fixed eventually. But, since @topjohnwu is a very busy dude it might take some time. If you're lucky, it might be that one of the other collaborators that contribute to Magisk take a look and finds a fix, but it'll still be John that merges those changes and that only happens when he has the time.

Patience.

**Comment by Fox2Code** [comment] 2021-01-07 16:43
I saw the `init` file inside `boot.img` and it's a symlink to thr `init.real` file.
Maybe Magisk don't handle `init` being a symlink very well?
Or maybe the kernel execute `init.real` directly instead of `init` causing Magisk to not work properly?
I'm sure it's due to this that Magisk does not work correctly.

**Comment by tramp20** [comment] 2021-01-08 05:34
@Fox2Code 
I sent your posting to the ROM developper, perhaps he can find something.

**Comment by 115ek** [comment] 2021-01-09 10:09
Hey. @tramp20 contacted me. Maybe I can give some insights:

The init setup on legacy sony devices is a bit different.
Basically, the following components in the ramdisk are involved:

- `/init` (symlink to `/bin/init_sony`)
- `/init.real` ("real" android init)
- `/bin/init_sony` (this was `/sbin/init_sony` on android < 11)

So what is happening now is:

1. Kernel loads the ramdisk and starts `/init` which actually starts `/bin/init_sony`
2. `/bin/init_sony` does some special stuff (checking if recovery should be entered, etc...)
3. `/bin/init_sony` unlinks `/init` and renames `/init.real` to `/init`
4. `/bin/init_sony` starts `/init`

For further details: This is the source of `init_sony`: https://github.com/LineageOS/android_device_sony_common/blob/lineage-18.1/init/init_main.cpp

I assume magisk is using a quite similar approach when patching the boot.img: Injecting itself as the "real" init, doing some stuff and afterwards simply calling the original android init.

**Comment by 115ek** [comment] 2021-01-09 11:25
Another finding:
I patched a boot.img manually and the manipulation seems successful. An `init` binary is added as well as a `.backup` folder.
So from my understanding the procedure (when magisk is installed) is the following:

1. Kernel loads the ramdisk and starts `/init` which actually is the magisk binary manipulating some things to allow root access
2. The magisk init then calls the backed up "original" init `/.backup/init` which in fact is a symlink to `/bin/init_sony`
3. `/bin/init_sony` does some special stuff (checking if recovery should be entered, etc...)
4. `/bin/init_sony` unlinks `/init` (which is the magisk one here) and renames `/init.real` to `/init`
5. `/bin/init_sony` starts `/init`

From my understanding this should be fine. It seems the procedure works - at least the device still boots.
I'd guess the modifications done by the magisk init somehow get overwritten by the following `/bin/init_sony`. 
However, I'm not quite sure what the magisk init really modifies.

**Comment by tramp20** [comment] 2021-01-09 11:25
Thanks @115ek.
To make it clear to all:
Magisk 20.4 was the last version I could install on LOS 17.1 (patching in MM or flashing in TWRP).
All following Magisk versions fail on LOS 17.1 and 18.1.

**Comment by ingomueller-net** [comment] 2021-01-12 09:15
I have a similar problem with Huawei P10 using the latest official version of Android 8: I could install v21.2 via MM without errors, but couldn't see it installed in MM after reboot (or use root anywhere else). Reinstalling via TWRP resulted in the same situation. I reinstalled v20.4, which works again.

**Comment by topjohnwu** [comment] 2021-01-14 13:31
This looks like something needs to be specifically handled differently

**Comment by efouladi** [comment] 2021-01-15 18:41
Same here with z3c

**Comment by innerspacepilot** [comment] 2021-01-18 12:57
Same with Xperia Z1, Lineage OS 17.1

**Comment by tramp20** [comment] 2021-01-18 13:14
No change with Magisk 21.4 and MM 8.0.7 :-(

**Comment by SiliconExarch** [comment] 2021-01-21 03:27
> Same here with z3c on LineageOS 17.1

In my experience flashing 20.4 followed by 21.4 works on z3c and is preferable to using 20.4 since that breaks the rear camera on my refurbished handset.

**Comment by micro-Ark** [comment] 2021-02-01 21:36
I had the same problem on my Z1C after upgrading from Magisk 20.4.
I think I found the problem (at least for my phone): It seems like, for some reason, versions > 20.4 no longer patch the Device Tree to enforce ramdisk usage, as a _diff_ of the installation logs shows:
```
Patch log of Magisk 20.4                         |    Patch log of Magisk 21.4
-------------------------------------------------|-------------------------------------------------
Parsing boot image: [boot.img]                        Parsing boot image: [boot.img]
    ....                                                  ....
Dump cpio: [ramdisk.cpio]                             Dump cpio: [ramdisk.cpio]
Loading dtbs from [extra]                             Loading dtbs from [extra]
QCDT v1                                          <
Found fstab in dtb.0000                          <
Found entry [system] in fstab                    <
Changing mnt_point to /system_root               <
Found fstab in dtb.0001                          <
Found entry [system] in fstab                    <
Changing mnt_point to /system_root               <
Parsing boot image: [boot.img]                        Parsing boot image: [boot.img]
    ....                                                  ....
```

I followed these steps as a workaround:

1. Patch `boot.img` once with 20.4 and once with 21.4.
2. Unpack the patched images (using `magiskboot unpack -h magisk_{20.4|21.4}_patched_boot.img`, adapt file names).
3. Copy the _extra_ file (containing the Device Tree) from the folder containing the unpacked 20.4-patched image to the folder containing the unpacked 21.4-patched image, overwriting the _extra_ file in this folder.
4. Repack the 21.4-patched image with the replaced _extra_ file (change into folder containing the unpacked 21.4-patched image and run `magisk_21.4_patched_boot.img`).
5. Flash the re-packed 21.4-patched image (containing the replaced _extra_ file) to the _boot_ partition (I used `fastboot flash boot new-boot.img`).

This worked for me - I have root again, and Magisk Manager shows Magisk 21.4 installed :-).

**Comment by tramp20** [comment] 2021-02-12 09:24
@micro-Ark
please could you upload your selfmade boot.img to DropBox or GoogleDrive or OneDrive?
I am not able to change my boot.img :-(

Thank you.

**Comment by micro-Ark** [comment] 2021-02-15 22:05
> please could you upload your selfmade boot.img to DropBox or GoogleDrive or OneDrive?

@tramp20
Sure - here you are:
[https://drive.google.com/file/d/1KF4O2jdTPTH9kaJRZbGEIrVQMaAiNQ1b/view?usp=sharing
](https://drive.google.com/file/d/1KF4O2jdTPTH9kaJRZbGEIrVQMaAiNQ1b/view?usp=sharing
)

This is the "boot.img" of LineageOS 17.1 (build from 2021-01-14) for Sony Xperia Z1 Compact (amami), patched with Magisk 21.4, and fixed as described above.
I hope this works for you.

**Comment by tramp20** [comment] 2021-02-16 10:54
@micro-Ark
your workaround could be the solution :-)
I started with a completely new flashed (all partitions with Sony EMMA) Z1c, installed the LOS ROM, flashed your boot.img and installed the Magisk Manager 8.07 and had now root.
Even update Magisk to canary 21.410 worked.
So you should "only" convince topjohnwu to include your solution :-)

Thank you.

Now I need only the same fix (and a boot.img) for LOS 18.1.

**Comment by micro-Ark** [comment] 2021-02-16 20:54
@tramp20
Glad to hear it :-)! I believe topjohnwu is following his open issues and will try to fix them when he finds the time, so no need to push from my side ;-).

As to the boot.img for LOS 18.1: I will see if I can fit that in during the next couple of days.

**Comment by tramp20** [comment] 2021-02-17 07:58
> 
> 
 
> As to the boot.img for LOS 18.1: I will see if I can fit that in during the next couple of days.

Fine, thank you.

**Comment by micro-Ark** [comment] 2021-02-21 21:12
> Now I need only the same fix (and a boot.img) for LOS 18.1.

Sorry - it took me longer than expected, I encountered some difficulties. Magisk 21.4 does not patch the DeviceTree of LOS 18.1's boot image (no surprise there...), but Magisk 20.4 fails to patch it, either. That's odd, since the DeviceTrees of LOS17.1 and LOS18.1 are bit-identical.
Now _because_ the DeviceTrees are identical, I packed a patched LOS17.1 DeviceTree into the patched LOS18.1 `boot.img`. I cannot say if this is right; I guess Magisk 20.4 has some reason to patch the DeviceTree of LOS17, but not the one of LOS18. I cannot test the fixed `boot.img`either since I do not run LOS18.1 and currently do not have a spare device for testing.

So **big disclaimer**: I do not take any warranty on this image - use it at your own risk. I don't think anything bad could happen (the only thing added is `mnt_point = "/system_root"` to the system partition's entry, hence I assume the worst thing that could happen is it won't boot at all), but you never know...

Anyway, if you'd like to give it a try, here's the link:
[https://drive.google.com/file/d/1uYk_Uk0PJW4YROiJqzAdrnDbZD6e1J74/view?usp=sharing](https://drive.google.com/file/d/1uYk_Uk0PJW4YROiJqzAdrnDbZD6e1J74/view?usp=sharing)

If you decide to try it out, I would be very interested to hear if it works :-)

**Comment by tramp20** [comment] 2021-02-22 02:59
> 
> 
> If you decide to try it out, I would be very interested to hear if it works :-)

Thank you for your hard work.
I have a spare Z1c and I will test your boot.img and report here :-)

**Comment by tramp20** [comment] 2021-02-22 12:45
> 

> If you decide to try it out, I would be very interested to hear if it works :-)

Sorry, I have a bootloop now: the system boots only to "SONY" (no LOS animation) and repeats this, but I can start TWRP if I press Vol_down.

Flashing the img as always:
F:\FastBoot>fastboot flash:raw boot lin18.1-20210101-amami-magisk21.4_patched_fixed.img
Sending 'boot' (8524 KB)                           OKAY [  0.270s]
Writing 'boot'                                            OKAY [  0.584s]
Finished. Total time: 0.964s

**Comment by micro-Ark** [comment] 2021-02-22 20:52
> Sorry, I have a bootloop now: the system boots only to "SONY" (no LOS animation) and repeats this, but I can start TWRP if I press Vol_down.

Sorry to hear about it :-(. That confirms my initial hunch that the problem is not DeviceTree-related this time.

As I understand the boot process under Magisk, the RAM disk containing Magisk is mounted to `/system`, so the bootloader loads the filesystem containing the files that will enable Magisk instead of the "real" (i.e. LineageOS's) `system` partition. The files inside this filesystem work Magisk's magic to provide an overlay,  containing the `su` binary, to the "real" `system` partition. Part of this process is remounting the `system` partition at `/system` to allow the normal booting process to continue. The `mnt_point` entry in the DeviceTree moves the mount point of the "real" `system` partition to `/system_root`, so the Magisk-enabling filesystem can be mounted at `/system` instead.
What happens with the failed-to-fix image is, I think, that the Magisk-enabling RAM disk fails to mount at `/system`, so by moving the mount point of the "real" `system`partition to `system_root`, the boot process is left without any partition mounted at `/system` at all, and will hence reset the device. Et voila - we have a bootloop.

I will have a quick look into the RAM disk contents of the patched LOS18 `boot.img` to check if something immediately catches my eye, but chances are that this will require a deeper investigation. Sorry :-(...

**Comment by tramp20** [comment] 2021-02-23 03:43
Sorry that you have a lot of work.
I cannot help except testing, I am 78 years old and cannot program :-(

**Comment by micro-Ark** [comment] 2021-02-23 21:20
Hm, the RAM disk contents look okay to me. Obviously LOS18 moved Sony's `init` and tools from `/sbin` to `/bin`, but Magisk detects that and sets the symlink accordingly. This should not be a problem. The rest of the filesystem looks unsuspicious. I cannot see an immediate reason why it should _not_ work :-(.
I don't know if there is much left that I can do. I will have a look into Magisk's source in the next couple of days. I'll report back when I find something.

**Comment by bleckdeth** [comment] 2021-02-24 13:55
Same with Xperia V, Lineage OS 18.1 phone boot only in fastboot.
Rom https://forum.xda-developers.com/t/rom-beta-11-lineageos-18-1-for-xperia-t-tx-v.4212387/
i try 21-22 versions.
Maybe this help
https://github.com/CoolDUp/Android_system_as_root_2SI_agent

**Comment by michaelaw320** [comment] 2021-03-05 15:02
Experiencing the same problem as well with AICP on Z1c.

Fresh AICP install, then I tried to install Magisk v22.0 (and canary) in all ways (formatted all data and system, each installation begins with fresh stock AICP image and its boot.img):
- Install from apk -> patch boot.img extracted from AICP zip, flashed via fastboot the patched img
    btw, I noticed that the instruction in Readme does not work, `fastboot flash boot magisk.img` returns error, it needs to be `fastboot flash:raw boot magisk.img` in my case
- Rename v22.0.apk to .zip then install it from TWRP

Both seems to patch the boot image, but the app couldn't find magisk is installed and system itself didn't detect magisk at all (can't `su`)
Reinstalling zip from TWRP confirms that the boot image has been magisk patched.

So, directly installing version above 20.4 does not work.

I found a way to make v22.0 work on fresh installation of the OS.
Steps:
1. Wipe the device, start fresh
2. Install fresh AICP from TWRP
3. Install Magisk v20.4.zip -> Confirm the message that it is patching the stock boot image
4. Install Magisk v22.0.zip -> Confirm the message that it is patching previously magisk patched boot image
5. Boot normally, install the apk
6. Magisk is working, and app is showing Installed 22.0 (22000)

**Comment by osm0sis** [comment] 2021-03-07 16:25
Any change with 22003?

**Comment by tramp20** [comment] 2021-03-08 12:45
> 
> 
> Any change with 22003?

Sorry no 👎 
Nothing changed compared to the start of my thread.

1. Wiped all, uninstalled Magisk with magisk.zip
2. fresh install LOS 17.1
3. install Magisk 22.003
3.1 installed Magisk.zip with TWRP: neither Magisk app nor Magisk are installed (recovery.log attached)
3.2 installed Magisk.apk (after uninstall Magisk.zip and reboot ofc), then patched the boot.img from LOS 17.1 ROM. Flashed this patched boot.img with fastboot. Again after reboot Magisk N/A.
Magisk_install_log.log with errors attached.


The solution to get Magisk 22.00x installed over a previous installed Magisk 20.4 does no longer help with LOS 18.1 because Magisk 20.4 cannot be installed.

[FastBoot_tramp20_22.003.zip](https://github.com/topjohnwu/Magisk/files/6101371/FastBoot_tramp20_22.003.zip)

**Comment by bleckdeth** [comment] 2021-03-08 13:37
On Xperia V witch Lineage OS 18.1 i try to move /ramdisk/init.real in /ramdisk/.backup
folder and rename to init, then put magiskinit to /ramdisk and rename to init.real.
Then i delete /ramdisk/bin/ramdisk-recovery.cpio
because witch ramdisk-recovery.cpio phone not boot.
And phone boot and magisk working.
I tried Magisk 21.4

**Comment by tramp20** [comment] 2021-03-08 14:01
@bleckdeth 
Sorry that is too high for me :-(

**Comment by bleckdeth** [comment] 2021-03-08 17:31
Hi tramp20 post your unpatched los 18 boot.img.

**Comment by tramp20** [comment] 2021-03-09 05:10
> 
> 
> Hi tramp20 post your unpatched los 18 boot.img.

Thank you for your help.
URL of the last ROM:
https://sourceforge.net/projects/lin18/files/amami/LineageOS_18_unsigned/lineage-18.1-20210101-UNOFFICIAL-amami.zip/download

Only boot.img from here:
https://www.magentacloud.de/lnk/RqvSMowD

**Comment by bleckdeth** [comment] 2021-03-09 08:51
First install in TWRP Magisk-v21.4
then install this image-new.img

https://disk.yandex.ua/d/T5oXIcg6_R9z2g

**Comment by bleckdeth** [comment] 2021-03-09 09:59
If not boot try this
https://disk.yandex.ua/d/IzqYXQZ6q70XMA

**Comment by tramp20** [comment] 2021-03-09 13:22
> 
> 
> First install in TWRP Magisk-v21.4
> then install this image-new.img

Thanks, I am just trying. Should I boot after installing Magisk-v21.4 or immediately flash your boot.img with fastboot?

**Comment by bleckdeth** [comment] 2021-03-09 14:36
In some old Sony devices need replace "init.real" not "init", and put init.real as init
to .backup folder in ramdisk.

**Comment by tramp20** [comment] 2021-03-09 15:12
There are some problems after updating Magisk to 22.004:
SwiftBackup cannot read its backup directory on the ext. SDCard but it find it
I cannot boot to recovery any longer, it seems that TWRP is broken.

I will continue tomorrow.

**Comment by bleckdeth** [comment] 2021-03-09 19:08
HI tramp20 flash my boot from fastboot for TWRP woks.
For update Magisk need repack boot.img again.

**Comment by bleckdeth** [comment] 2021-03-09 23:04
Tramp20 this boot  for 2204
https://disk.yandex.ua/d/GFik8mUVmvKKFw

**Comment by tramp20** [comment] 2021-03-10 06:26
@bleckdeth 
Thanks,
I have my Z1c up and running again with Magisk 21.4 and will stay with this version the next time.
I read here many problems with the newer versions. 
Please could you make a boot.img with 22.0?
Who has to change something to solve this "bug", topjohnwu or the LOS ROM maintainers?

**Comment by tramp20** [comment] 2021-03-10 06:27
@bleckdeth
> 
> Tramp20 this boot for 2204
Thank you very much.
I have to flash stock rom 5.1.1 with EMMA to get rid of all changes from yesterday (I have experiences with this tool).

Then I will flash TWRP and restore LOS 18.1 and start again.

>For update Magisk need repack boot.img again

Does this mean I never can update Magisk and the kernel with a new ROM without a new boot.img from you?

**Comment by bleckdeth** [comment] 2021-03-10 09:27
Tramp20 i posted boot for last canary 22.004.
https://disk.yandex.ua/d/GFik8mUVmvKKFw
I don't know, this "bug" present on Xperia V and Xperia SP with Lineage OS 18.1.

**Comment by micro-Ark** [comment] 2021-03-14 21:45
@bleckdeth :

> In some old Sony devices need replace "init.real" not "init", and put init.real as init
> to .backup folder in ramdisk.

Great that you got it working - thank you very much!

If you don't mind my curiosity: Do you know _why_ this works? I am no Android developer and still trying to figure out the boot process. I would have thought `/init` to be the first command run by the kernel, so replacing this with `magiskinit` (as Magisk's patching process does) made sense in my mind. In your image, `/init` is a symlink to `/bin/sony_init`, which I assumed to be Sony's OS loader. Does `/bin/sony_init`call `init.real` (and hence Magisk)?

**Comment by tramp20** [comment] 2021-03-15 10:17
@bleckdeth 
There must be a bug:
After wipe all/factory reset and installation of LOS 18.1:

1.
install magisk22004.zip in TWRP
flash your boot-2204.img 
Result: restart to recovery is OK (LED is violet and then Vol-down)
           Magisk is NOT running

2.
flash your boot-2204.img
install magisk22004.zip in TWRP
Result: restart to recovery is not working
           Magisk is running

Instead of installing Magisk22004.zip I tried patching the boot img in Magisk app (Manager) with the same results.

**Comment by bleckdeth** [comment] 2021-03-15 12:57
HI tramp20 maybe I made a mistake.
install Magisk-22004 in recovery after flash this
https://disk.yandex.ua/d/0j2jlCFFk2MhnQ
Magisk patch "init" but in Sony devices init is sony_init and after patch
recovery not working.
In Sony, first stage need "sony_init" after sony_init call init.real.
If replacing init.real with magiskinit magisk Initialized and then
call init in .backup folder.

**Comment by tramp20** [comment] 2021-03-15 14:07
> 
> 
> HI tramp20 maybe I made a mistake.

Thank you, I will try this tomorrow and report, soory I have no time now.

**Comment by osm0sis** [comment] 2021-03-15 20:27
Seems like there's enough info here now that @topjohnwu should be able to add support for these Sony devices as an exception in the installer and magiskinit. Thanks for troubleshooting!

**Comment by tramp20** [comment] 2021-03-16 06:39
> 
> 
> HI tramp20 maybe I made a mistake.
> install Magisk-22004 in recovery after flash this


Hi,
your patched boot.img works now perfect :-)
Important: an existing Magisk has to be uninstalled before !!

Please could you send me your e-mail address (to tramp20 at arcor.de)? If someone decide here to close this thread without a solution I cannot find you for a new boot img version.

Do you really have to make a new boot.img for every new Magisk build?

Thank you very much.

**Comment by bleckdeth** [comment] 2021-03-16 09:45
Tramp20 can you testing this?
Uninstall Magisk.
Open Magisk install archive and replace /assets/boot_patch.sh
with this file
https://disk.yandex.ua/d/7uNxGlfm0nfsFA
then flash unpatched boot
and install Magisk again.

**Comment by bleckdeth** [comment] 2021-03-16 10:01
I edit "boot_patch.sh"
and  replace line 151 to
"add 0750 init.real magiskinit" \
and add line 159
"mv .backup/init.real .backup/init" \
in theory, it should work without repacking
in Sony with "sony_init"

**Comment by tramp20** [comment] 2021-03-16 11:26
> 
> 
> Tramp20 can you testing this?

This patch works wonderful :-)
Thank you for this ingeniously simple patch.

Important hint: after uninstalling Magisk in TWRP we have to uninstall the app (=manager) manually to avoid big troubles!

So we can "patch" a new Magisk build as long topjohnwu has no own solution for Xperia?

And for my understanding can we make this change with Magisk 21.407 to avoid the detour over installing 20.4 first?

**Comment by chhus** [comment] 2021-04-15 15:26
> I edit "boot_patch.sh"
> and replace line 151 to
> "add 0750 init.real magiskinit"
> and add line 159
> "mv .backup/init.real .backup/init"
> in theory, it should work without repacking
> in Sony with "sony_init"

Thank you, @bleckdeth 

I applied this edits to the boot_patch.sh in Magisk 22.1 (it's a bit different from Magisk 21) on LineageOS 18.1 and it works. Tested on Sony Xperia Z2 Tablet

**Comment by tbertels** [comment] 2021-04-18 10:29
> I edit "boot_patch.sh"
> and replace line 151 to
> "add 0750 init.real magiskinit"
> and add line 159
> "mv .backup/init.real .backup/init"
> in theory, it should work without repacking
> in Sony with "sony_init"

Indeed, thank you @bleckdeth!

Here's the modified [Magisk-v22.1_mod_sony.zip](https://github.com/topjohnwu/Magisk/files/6330986/Magisk-v22.1_mod_sony.zip) (the apk is inside the zip file).

**Comment by ascendant512** [comment] 2021-06-11 02:56
Edited `scripts/boot_patch.sh` to change this at line 161:
`./magiskboot cpio ramdisk.cpio \
"add 0750 init.real magiskinit" \
"mkdir 0750 overlay.d" \
"mkdir 0750 overlay.d/sbin" \
"$SKIP32 add 0644 overlay.d/sbin/magisk32.xz magisk32.xz" \
"$SKIP64 add 0644 overlay.d/sbin/magisk64.xz magisk64.xz" \
"patch" \
"backup ramdisk.cpio.orig" \
"mkdir 000 .backup" \
"mv .backup/init.real .backup/init" \
"add 000 .backup/.magisk config"`
Built and installed to get working Magisk on my z3c running CarbonROM Android 10

**Comment by osm0sis** [comment] 2021-06-11 03:12
So would a good solve for this be to look for init.real and use it instead of init in that script? We could probably test for it and set $init as a variable.

**Comment by osm0sis** [comment] 2021-06-11 04:11
Since you guys worked this one out pretty much on your own does one of you want to make the pull request to do the above? If not then I can take a look next week sometime.

**Comment by ejgr-mtsiw** [comment] 2021-07-17 14:00
I don't know if it's still .relevant, but bleckdeth  changes solved my problem too (Xperia Z3, LineageOs 18.1, Magisk 23.0)

**Comment by blaloc7** [comment] 2021-07-19 10:33
yes, for me 

yes, for me too....
I have built a boot_patch.sh for v23.0, which checks, if it is a sony device (Z1 Comapct D5503 - for more devices additional lines are needed), so this script can still be used for installation on devices of other manufacturers

[boot_patch.sh.txt](https://github.com/topjohnwu/Magisk/files/6840061/boot_patch.sh.txt)


> 
> 
> I don't know if it's still .relevant, but bleckdeth changes solved my problem too (Xperia Z3, LineageOs 18.1, Magisk 23.0)

**Comment by tbertels** [comment] 2021-07-19 15:28
> yes, for me too....
> I have built a boot_patch.sh for v23.0, which checks, if it is a sony device (Z1 Comapct D5503 - for more devices additional lines are needed), so this script can still be used for installation on devices of other manufacturers
> 
> [boot_patch.sh.txt](https://github.com/topjohnwu/Magisk/files/6840061/boot_patch.sh.txt)

Unless I'm wrong, the = should be replaced by == in the if conditions
`if [ $gpdev = 'D5503' ]; then sony_fix=true; fi`
->
`if [ $gpdev == 'D5503' ]; then sony_fix=true; fi`

> I don't know if it's still .relevant, but bleckdeth changes solved my problem too (Xperia Z3, LineageOs 18.1, Magisk 23.0)

It seems to only work with an unpatched boot image.
If I try to update an already (Magisk) patched boot image, I get a boot loop.
Did someone else succeed in updating an already patched boot image with this fix?

**Comment by osm0sis** [comment] 2021-07-19 20:05
A whitelist of boards isn't a good fix, instead it should look for the ramdisk files that will make this necessary, like sony_init and init.real or whatever. That's my plan anyway, just haven't had time to look into yet.

**Comment by morphiak** [comment] 2021-08-04 04:08
Confirm working with Xperia Z3 LineageOS 17.1 with microG using patch as per ascendant512 and TWRP install from SD. I simply edited in place in my Magisk-v23.0.zip, adb pushed and all is good.
Thanks for the hard work.

**Comment by diresi** [comment] 2021-08-16 19:17
> I don't know if it's still .relevant, but bleckdeth changes solved my problem too (Xperia Z3, LineageOs 18.1, Magisk 23.0)

Same versions work with @bleckdeth change on the Xperia Z3 Compact (z3c). Thanks!

**Comment by osm0sis** [comment] 2021-11-03 18:14
Not fixed by the committed C++ rewrite of my script-based fix. 🙁

**Comment by osm0sis** [comment] 2021-11-03 19:06
> I'll doctor one up for you with my original script-based fix for testing, and I guess we'll reopen the issue.

Update to latest app Canary, then flash this zip manually the modules page:
[app-debug-2c44e1bb-hack.zip](https://github.com/topjohnwu/Magisk/files/7470121/app-debug-2c44e1bb-hack.zip)

**Comment by tramp20** [comment] 2021-11-04 04:22
Thanks for all your efforts.
But nothing has changed: device does not boot, display stays black, no LED, I am not able to boot to TWRP.
I have to flash the boot.img again.

**Comment by osm0sis** [comment] 2021-11-04 12:14
Alright, so we'll have to walk back the other changes to see what broke it.

**Comment by osm0sis** [comment] 2021-11-04 12:18
@tramp20 can you start by taking 23001 and manually modifying it with my changes so we're sure that's all still good? https://github.com/topjohnwu/Magisk/commit/80d7ce0fa9110188a82eedad80cf1c39badc6cb0

**Comment by tramp20** [comment] 2021-11-04 13:35
@osm0sis
I simply replaced the 23001 boot_patch.sh and uninstaller.sh files with your universal patched files.
After a factory reset and restoring a TWRP backup without Magisk and installing the patched 23001.zip my Z1c booted correct.
But Magisk is not installed (N/A), the same as without the patch of bleckdeth.
So something is wrong with your patch (I cannot help) :-(

**Comment by osm0sis** [comment] 2021-11-04 13:51
Other things changed, so you'll want to patch 23001 manually

**Comment by tramp20** [comment] 2021-11-04 14:26
Without understanding much of your patches in boot_patch.sh (I am an old (79) man ):
I compared this file in 23001 (unpatched) and 23001 (with bleckdeth patch)  with your patch and I am almost sure that I did not make a mistake. For me there are no other changes.
Please can you send me a changed boot_patch.sh for 23001?

I believe the" mv .backup/init.real .backup/init"  was the important patch from bleckdeth.
So is in your changed line #178  "$SKIPSONY mv .backup/init.real .backup/init" the "$SKIPSONY correct set in line #166 ("unset SKIPSONY")?

**Comment by williamsavage304** [comment] 2021-11-04 14:28
Stop
Sent from Yahoo Mail on Android 
 
  On Thu, Nov 4, 2021 at 7:27 AM, ***@***.***> wrote:   



Without understanding much of your patches in boot_patch.sh (I am an old (79) man ):
I compared this file in 23001 (unpatched) and 23001 (with bleckdeth patch) with your patch and I am almost sure that I did not make a mistake. For me there are no other changes.
Please can you send me a changed boot_patch.sh for 23001?

I believe the" mv .backup/init.real .backup/init" was the important patch from bleckdeth.
So is in your changed line #178 "$SKIPSONY mv .backup/init.real .backup/init" the "$SKIPSONY correct set in line #166 ("unset SKIPSONY")?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by osm0sis** [comment] 2021-11-04 19:53
Ahhh, you were into something there!

In @topjohnwu's rewrite he moved the detection logic into `magiskboot cpio ramdisk.cpio test` where STATUS gets set here: https://github.com/topjohnwu/Magisk/blob/6663fd3526f6a104755b2beed7ad2e81f01a81c7/scripts/boot_patch.sh#L112

In the script side of his rewrite this then gets checked and INIT set to init.real here:
https://github.com/topjohnwu/Magisk/commit/6663fd3526f6a104755b2beed7ad2e81f01a81c7#diff-a9e111d3040894b7173076652cb767b2b6706f0d703d67cfa1cb4b871b13ba75R140

BUT he typoed and it says status instead of STATUS, so it'll always fail! 😅

**Comment by osm0sis** [comment] 2021-11-04 20:33
@tramp20 Try with 23012 and manually change that line to `if [ $((STATUS & 4)) -ne 0 ]; then`, and then we'll just hope the rest of the magiskinit-side changes work as intended. 😉

**Comment by tramp20** [comment] 2021-11-05 06:06
No success.
I changed in 23012 status to STATUS but no booting again (display stays black).
Then I tried to patch the boot_patch.sh in 23001: the Z1c boots correct but Magisk is not installed (N/A) and no stub.

Please could you change the old 23001 boot_patch.sh with your patches for me?
I am not sure if I did this correct without understanding the code :-(

**Comment by osm0sis** [comment] 2021-11-05 20:06
Well I'm a little at a loss since @bleckdeth and my script-based changes are basically the same.

https://github.com/topjohnwu/Magisk/issues/3636#issuecomment-859224940
Vs.
https://github.com/topjohnwu/Magisk/commit/80d7ce0fa9110188a82eedad80cf1c39badc6cb0

And I've verified the init.real detection works... I'll try manually patching Magisk for you, yeah.

**Comment by osm0sis** [comment] 2021-11-05 20:34
I think we'll follow along in  #4885 now, we've got someone grabbing logs there from the failed boot.

**Closed by osm0sis** 2021-11-05 20:34 UTC
Labels: confirmed
