### ISSUE TITLE
No Zygisk / Modules icon grayed out on FireTV 2nd gen Cube (Amlogic S922x)

### ISSUE THREAD

**Issue by finnzz** [topjohnwu/Magisk#6042] opened 2022-06-26 07:51 UTC
Device: FireTV 2nd gen Cube
Android version: Android 9 (FireOS 7)
Magisk version name: Canary 9183a0a6
Magisk version code: (25101) (D)
Amlogic s922x SOC, slot-A only, SAR, no super partition device

I have tried a few canary builds after v24300, as well as v25000, v25100, and today's canary build.  I have flashed the Magisk patched boot.img to the boot paritition in fastboot.  Magisk superuser rights work properly, but I can't get Zygisk to work, and the modules icon remains grayed out.  I've checked and unchecked Zygisk under settings a couple times.

I'm don't think it's related, but the Cube native boot.img does not have a ramdisk.  However like some Xiaomi devices, the Cube does accept and use a ramdisk placed in the boot.img.  After patching the boot.img with Magisk, ramdisk switched to a yes status.

Also a patch was added in 24.300+ to ignore illegal androidboot.slot_suffix=normal.  I don't know if simply ignoring the suffix rather than classify the device as an '_a' device complicates anything? 
https://github.com/topjohnwu/Magisk/issues/5806

I'm including my boot image, boot-up log, and magisk log.

[magisk.zip](https://github.com/topjohnwu/Magisk/files/8986175/magisk.zip)

**Comment by canyie** [comment] 2022-06-26 10:16
Can you capture a log via `adb logcat` at boot?

**Comment by finnzz** [comment] 2022-06-26 13:10
> Can you capture a log via `adb logcat` at boot?

Sure, here you go
[bootup-logcat.zip](https://github.com/topjohnwu/Magisk/files/8986676/bootup-logcat.zip)

**Comment by canyie** [comment] 2022-06-26 13:16
Looks you started grabbing too late... You may need to set log buffer size to max in developer options, and connect your device to PC before it boots. Use `adb wait-for-device logcat` in that case.

**Comment by finnzz** [comment] 2022-06-26 13:59
> Looks you started grabbing too late... You may need to set log buffer size to max in developer options, and connect your device to PC before it boots. Use `adb wait-for-device logcat` in that case.

I did use 'adb -d logcat'.  I just checked the original boot.img, and both don't connect over ADB until 
`--------- beginning of system`

I don't know if there is another way to get earlier logs?

**Comment by canyie** [comment] 2022-06-26 14:03
> and both don't connect over ADB until
--------- beginning of system

That's ok, just send the thing you've got

**Comment by finnzz** [comment] 2022-06-26 14:19
> > and both don't connect over ADB until
> > --------- beginning of system
> 
> That's ok, just send the thing you've got

Do you want me to redo the catalog from above?

> Sure, here you go
> [bootup-logcat.zip](https://github.com/topjohnwu/Magisk/files/8986676/bootup-logcat.zip)

This log starts at
` --------- beginning of system`
And continues for 40s

**Comment by canyie** [comment] 2022-06-27 03:45
> Do you want me to redo the logcat from above?

Yes, please redo it

**Comment by finnzz** [comment] 2022-06-27 04:05
> > Do you want me to redo the logcat from above?
> 
> Yes, please redo it
Ok, here you go

[logcat-repeat.zip](https://github.com/topjohnwu/Magisk/files/8988592/logcat-repeat.zip)

**Comment by yujincheng08** [comment] 2022-06-27 09:49
A Magisk module that can help you save the log
required Magisk 20.4+
The log is saved to /cache/bootlog by default
If /cache does not exist, save to /data/local/bootlog
If you don't want to kill the logcat process after boot completed, you can create a file named boot.lcs to /data/local/logcatcher/ .

When the system boot normally and /data/local/logcatcher/boot.lcs is not detected, the logs will be packaged and copied to the Download folder

Recent Updates:
* Stop catching logs delayed until unlock the phone
* Select log buffer as main,system,crash by [Rikka](https://github.com/RikkaW)
* Fix version
* Add "MODEL"
* Automatic uninstallation of older versions
* Improve unlock detection

[Log Catcher-v22.5(27) (2).zip](https://github.com/topjohnwu/Magisk/files/8990757/Log.Catcher-v22.5.27.2.zip)

**Comment by finnzz** [comment] 2022-06-27 10:15
> A Magisk module that can help you save the log required Magisk 20.4+ The log is saved to /cache/bootlog by default If /cache does not exist, save to /data/local/bootlog If you don't want to kill the logcat process after boot completed, you can create a file named boot.lcs to /data/local/logcatcher/ .

Thank you, but I'm not sure how i would install a Magisk module to catch logs, since issue I'm having is that Magisk zygisk and modules features are not working?

Also as I mentioned above, it appears that logging starts before I have even started logcat.  I can wait until the OS has almost loaded, and logcat will provide me with any logs generated since system startup.

`--------- beginning of system` appears to be as early as logging is possible.

**Comment by yujincheng08** [comment] 2022-06-27 10:45
If you dont want to follow the instruction from us, I would close this issue.

**Comment by finnzz** [comment] 2022-06-27 11:01
> If you dont want to follow the instruction from us, I would close this issue.

I'm sorry, I'm really not trying to be difficult.  I think there has been a miscommunication somewhere.  I am genuinely asking how to install the logcatcher module?  The magisk module icon is grayed on my device.

**Comment by yujincheng08** [comment] 2022-06-27 11:02
`magisk --install-module /path/to/zip`

**Comment by finnzz** [comment] 2022-06-27 11:19
> magisk --install-module /path/to/zip

Ok, I ran the module install
```
magisk --install-module Log.Catcher-v22.5.27.2.zip
```
No error, no confirmation of success either.  I still do not have a `/data/adb/modules` folder.  I even tried manually creating a modules folder and running the module install again, but the modules folder was still empty.

Just in case, I rebooted the device and checked /cache, but there is no `/cache/bootlog`, and no `/data/local/bootlog`

**Comment by yujincheng08** [comment] 2022-06-27 11:40
place the module zip in `/data/local/tmp`

**Comment by finnzz** [comment] 2022-06-27 11:49
> place the module zip in `/data/local/tmp`

ok I ran
```
magisk --install-module /data/local/tmp/Log.Catcher.zip
```
but i'm still getting error 127.  I checked `whoami` and I am `root`

**Comment by yujincheng08** [comment] 2022-06-27 12:14
I think your system has something incompatibility.


Try the following in root shell:
```bash
OUTFD=1 ZIPFILE='/data/local/tmp/Log.Catcher.zip' ASH_STANDALONE=1 $(magisk --path)/.magisk/busybox/busybox sh -c '
. /data/adb/magisk/util_functions.sh
install_module
exit 0'
```

**Comment by yujincheng08** [comment] 2022-06-27 12:29
So the problem is that your installation missed `busybox` in `magisk --path`.

**Comment by finnzz** [comment] 2022-06-27 12:34
yea this is all that comes up:
```
1|raven:/sbin/.magisk # magisk --path                                                                                                        
/sbin
```
Is there anything I can do on my end to try to resolve this?

**Comment by canyie** [comment] 2022-06-27 12:47
`ls -lZR /data/adb`

**Comment by finnzz** [comment] 2022-06-27 12:51
> ls -lZR /data/adb

```
raven:/ # ls -lZR /data/adb
/data/adb:
total 308
drwxr-xr-x 3 root    root          u:object_r:adb_data_file:s0   4096 2022-06-21 22:11 magisk
-rw------- 1 root    root          u:object_r:adb_data_file:s0  40960 2022-06-22 03:43 magisk.db
-rw-r--r-- 1 u0_a181 u0_a181_cache u:object_r:adb_data_file:s0 270080 2022-06-19 04:08 mmc

/data/adb/magisk:
total 2380
-rwxr-xr-x 1 root root u:object_r:adb_data_file:s0    3530 2022-06-21 22:11 addon.d.sh
-rwxr-xr-x 1 root root u:object_r:adb_data_file:s0    5954 2022-06-21 22:11 boot_patch.sh
-rwxr-xr-x 1 root root u:object_r:adb_data_file:s0 1461400 1979-11-30 00:00 busybox
drwxr-xr-x 2 root root u:object_r:adb_data_file:s0    4096 2022-06-21 22:11 chromeos
-rwxr-xr-x 1 root root u:object_r:adb_data_file:s0  148256 1979-11-30 00:00 magisk32
-rwxr-xr-x 1 root root u:object_r:adb_data_file:s0  316776 1979-11-30 00:00 magiskboot
-rwxr-xr-x 1 root root u:object_r:adb_data_file:s0  251412 1979-11-30 00:00 magiskinit
-rwxr-xr-x 1 root root u:object_r:adb_data_file:s0  205252 1979-11-30 00:00 magiskpolicy
-rwxr-xr-x 1 root root u:object_r:adb_data_file:s0   23892 2022-06-21 22:11 util_functions.sh

/data/adb/magisk/chromeos:
total 544
-rwxr-xr-x 1 root root u:object_r:adb_data_file:s0 548140 2022-06-21 22:11 futility
-rwxr-xr-x 1 root root u:object_r:adb_data_file:s0   1208 2022-06-21 22:11 kernel.keyblock
-rwxr-xr-x 1 root root u:object_r:adb_data_file:s0   1199 2022-06-21 22:11 kernel_data_key.vbprivk
```

**Comment by canyie** [comment] 2022-06-27 12:58
Try to run `magisk --restorecon` and reboot?

**Comment by finnzz** [comment] 2022-06-27 13:21
>try:
```
raven:/data/adb/magisk # OUTFD=1 ZIPFILE='/data/local/tmp/Log.Catcher.zip' ASH_STANDALONE=1 /data/adb/magisk/busybox sh -c '
> . /data/adb/magisk/util_functions.sh
> install_module
> exit 0'
- Current boot slot: normal
- Device is system-as-root
Archive:  /data/local/tmp/Log.Catcher.zip
  inflating: module.prop
*************
 Log Catcher 
 by Howard 
*************
*******************
 Powered by Magisk 
*******************
Archive:  /data/local/tmp/Log.Catcher.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/local/tmp/Log.Catcher.zip
  inflating: customize.sh
  inflating: module.prop
  inflating: post-fs-data.sh
  inflating: README.md
  inflating: service.sh
  inflating: util.sh
- Done
```
That installed, and then I rebooted the device.  But I'm not seeing any log in` /data/local/bootlog` or `/cache/bootlog`.  The icons module is still grayed out in magisk manager.

```
raven:/ # ls -lZR /data/adb
/data/adb:
total 316
drwxr-xr-x 3 root    root          u:object_r:magisk_file:s0     4096 2022-06-21 22:11 magisk
-rw------- 1 root    root          u:object_r:adb_data_file:s0  40960 2022-06-22 03:43 magisk.db
-rw-r--r-- 1 u0_a181 u0_a181_cache u:object_r:adb_data_file:s0 270080 2022-06-19 04:08 mmc
drwxrwxrwx 3 root    root          u:object_r:system_file:s0     4096 2022-06-21 22:16 modules
drwxrwxrwx 3 root    root          u:object_r:adb_data_file:s0   4096 2022-06-21 22:16 modules_update

/data/adb/magisk:
total 2380
-rwxr-xr-x 1 root root u:object_r:magisk_file:s0    3530 2022-06-21 22:11 addon.d.sh
-rwxr-xr-x 1 root root u:object_r:magisk_file:s0    5954 2022-06-21 22:11 boot_patch.sh
-rwxr-xr-x 1 root root u:object_r:magisk_file:s0 1461400 1979-11-30 00:00 busybox
drwxr-xr-x 2 root root u:object_r:magisk_file:s0    4096 2022-06-21 22:11 chromeos
-rwxr-xr-x 1 root root u:object_r:magisk_file:s0  148256 1979-11-30 00:00 magisk32
-rwxr-xr-x 1 root root u:object_r:magisk_file:s0  316776 1979-11-30 00:00 magiskboot
-rwxr-xr-x 1 root root u:object_r:magisk_file:s0  251412 1979-11-30 00:00 magiskinit
-rwxr-xr-x 1 root root u:object_r:magisk_file:s0  205252 1979-11-30 00:00 magiskpolicy
-rwxr-xr-x 1 root root u:object_r:magisk_file:s0   23892 2022-06-21 22:11 util_functions.sh

/data/adb/magisk/chromeos:
total 544
-rwxr-xr-x 1 root root u:object_r:magisk_file:s0 548140 2022-06-21 22:11 futility
-rwxr-xr-x 1 root root u:object_r:magisk_file:s0   1208 2022-06-21 22:11 kernel.keyblock
-rwxr-xr-x 1 root root u:object_r:magisk_file:s0   1199 2022-06-21 22:11 kernel_data_key.vbprivk

/data/adb/modules:
total 4
drwxrwxrwx 2 root root u:object_r:system_file:s0 4096 2022-06-21 22:16 hwr_logcat

/data/adb/modules/hwr_logcat:
total 4
-rw-r--r-- 1 root root u:object_r:system_file:s0 151 2022-06-21 22:16 module.prop
-rw-r--r-- 1 root root u:object_r:system_file:s0   0 2022-06-21 22:16 update

/data/adb/modules_update:
total 4
drwxr-xr-x 2 root root u:object_r:system_file:s0 4096 2022-06-21 22:16 hwr_logcat

/data/adb/modules_update/hwr_logcat:
total 16
-rw-r--r-- 1 root root u:object_r:system_file:s0  151 2022-06-21 22:16 module.prop
-rw-r--r-- 1 root root u:object_r:system_file:s0 2040 2022-06-21 22:16 post-fs-data.sh
-rw-r--r-- 1 root root u:object_r:system_file:s0  963 2022-06-21 22:16 service.sh
-rw-r--r-- 1 root root u:object_r:system_file:s0  720 2022-06-21 22:16 util.sh
```

**Comment by vvb2060** [comment] 2022-06-28 05:20
https://android.googlesource.com/platform/system/libsysprop/+/refs/tags/android-12.0.0_r34/srcs/api/PlatformProperties-latest.txt#93

```
  prop {
    api_name: "state"
    type: Enum
    scope: Internal
    prop_name: "ro.crypto.state"
    enum_values: "encrypted|unencrypted|unsupported"
  }
```

https://github.com/topjohnwu/Magisk/blob/0b26882fceb675044721fda32c31ea027e93ffe1/native/jni/core/bootstages.cpp#L189-L198

**Comment by yujincheng08** [comment] 2022-06-28 05:20
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/8997905/app-debug.zip)
Try this ver

**Comment by finnzz** [comment] 2022-06-28 06:07
Thank you @yujincheng08 @canyie @vvb2060 +1: :+1: :+1: 

Yes, this appears to have solved the issue.  Zygisk is a 'yes' status, and modules are appearing.  LogCatcher is generating log files in `cache/bootlog`, and Magisk's log indicates it's doing more now too.

[magisk.log](https://github.com/topjohnwu/Magisk/files/8998124/magisk.log)
![modules](https://user-images.githubusercontent.com/7779543/176105411-7464d313-f587-4d30-a4fd-337da81ecadf.png)
![zygisk](https://user-images.githubusercontent.com/7779543/176105412-ad32f381-e093-473d-99cc-d1da5e8d146e.png)

**Comment by MadTooth** [comment] 2022-06-30 15:03
Very Nice Very Good

**Closed** 2022-07-01 02:32 UTC
Labels: confirmed
