### ISSUE TITLE
Magisk Manager (canary) - Inactive confirm dialog

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#3131] opened 2020-09-03 19:56 UTC
With Automatic Response - Grant for Superuser access Magisk shows inactive Confirm dialogue and there is no Dismiss timeout for it. User must press Back button to hide it.

**Comment by palmbeach05** [comment] 2020-09-03 21:06
i can confirm this issue does exist.

**Comment by osm0sis** [comment] 2020-09-03 21:37
I believe this is a duplicate of #2944. Please follow along there. :+1:

**Closed by osm0sis** 2020-09-03 21:37 UTC
Labels: duplicate
