### ISSUE TITLE
Canary 22005: Magisk log empty, Manager crashes when installing/updating module

### ISSUE THREAD

**Issue by bege10** [topjohnwu/Magisk#4081] opened 2021-03-22 20:09 UTC
1. The Magisk log is empty. This may have been already with stable build 22, I haven't looked at the log for a while.
2. The Magisk Manager crashes after the download when trying to install or update any module. Installing from storage works.

Device: Fairphone 3
Android version: /e/OS 0.15 (based on Android 10, LineageOS, microG)
Magisk version name: "f152b4c2"
Magisk version code: 22005

attached is a catlog excerpt "magisk" from the attempt to install a module.
[logreader_2021-03-22_20-59.log](https://github.com/topjohnwu/Magisk/files/6185021/logreader_2021-03-22_20-59.log)

**Comment by Didgeridoohan** [comment] 2021-03-22 20:17
At least partly a duplicate of #4044.

**Comment by bege10** [comment] 2021-03-22 20:22
> At least partly a duplicate of #4044.

Sorry, saw it too late.

**Comment by osm0sis** [comment] 2021-03-23 11:54
Can you roll back and see where the log issue started for you?

**Closed** 2021-03-24 10:23 UTC

**Comment by Didgeridoohan** [comment] 2021-03-24 15:21
@bege10 You need to first rollback the app. Then you can install the 22000 build from there.

Rolling back might always bring complications, so be prepared to uninstall any Magisk you have installed first if you experience issues.

**Comment by bege10** [comment] 2021-03-24 15:39
> 
> 
> @bege10 You need to first rollback the app. Then you can install the 22000 build from there.
> 
> Rolling back might always bring complications, so be prepared to uninstall any Magisk you have installed first if you experience issues.

@Didgeridoohan I tried again to roll back, first from inside the app, then the apk. Both fail (app not installed), version remains 22005. Then I tried to uninstall Magisk completely from inside the app: nothing happens. 😕

**Comment by Didgeridoohan** [comment] 2021-03-24 16:05
@bege10 Besides what @osm0sis said, you cant directly install the 22000 app over the 22005 app, you have to uninstall it first and then install the apk manually.

Don't know about the uninstall thing though...
