### ISSUE TITLE
Bootloop with patched boot.img - Nvidia Shield TV Pie Update

### ISSUE THREAD

**Issue by MrNobody206** [topjohnwu/Magisk#1750] opened 2019-08-07 06:10 UTC
Hey. Since the update from Oreo to Pie, it is no longer possible to use Magisk on Nvidia Shield TV 2017. When I flash the patched image in fastboot and restart, I hang in the bootloop. If I flash the normal boot.img it works again.

I haven't found a way to create a log yet. If you know one I will try.

**Comment by topjohnwu** [comment] 2019-08-07 10:08
I'm pretty sure it is caused by incompatible modules installed....

**Comment by MrNobody206** [comment] 2019-08-07 15:01
i dont have any module installed. I already flashed clean. A lot of nvidia shield user reported this problem now.

**Comment by tam1m** [comment] 2019-08-07 16:22
This issue should be reopened. Magisk does not work on the latest Nvidia Shield system update. It has nothing to do with modules. Flashing a Magisk patched boot image onto a clean Shield TV, puts it into a bootloop.

**Comment by TheyCallMeZ** [comment] 2019-08-13 23:54
I'm having the same issue on the pixel 3a. Did a full factory reset and even tried getting the full tom update from Google directly to get to as stock as possible.

**Comment by ilovecookieee** [comment] 2019-08-14 09:52
Same issue for me on Samsung J810f. I followed the instruction on patching the AP_[XXX].tar.md5. Bootloops after updating the binary in magisk manager.

**Comment by SilentFez** [comment] 2019-08-31 22:04
"We’ve confirmed the images are user images and not user debug (rooted). They will be fixed early this week."
https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/307650/800-dev-image-no-root/2243743/

Apparently no updateed images have been put out yet.

**Comment by topjohnwu** [comment] 2019-09-01 04:28
If the case is A-only system-as-root, #1674 
If the case is NVIDIA providing incorrect images, then it is not Magisk's fault

**Closed by topjohnwu** 2019-09-01 04:28 UTC

**Comment by elliwigy** [comment] 2019-09-01 07:33
I dont see how that is tied to the issue at hand. The images that the other user said were wrong is not 100% accurate.

Nvidia posted stock user images and listed them as "dev" images. 

This does not change the fact that Magisk does not properly patch the STOCK non dev firmware released by Nvidia. 

Of course dev images have a root shell by default making it easier to root but what if someone doesmt want to use developer firmware and simply wants stock rooted? Stock rooted typically runs smoother than debug/eng firmware especially if the standard Shield gets bogged down.

I know this isnt a top priority and doesnt have any demand compared to other devices but it would be nice to have a solution and a working alternative on stock firmware. 

I suppose there isnt much to do if you decide to keep it closed. It will give me something to do but I wanted to be clear the issue is still not resolved.

**Comment by jinx10000** [comment] 2019-09-01 18:43
I agree, I don't use the dev pre-rooted images and Magisk has always worked. 

I don't know if A-only System as Root is the problem or if this was added by the update.

**Comment by jeffbeckerimp81** [comment] 2019-09-07 20:46
By gym

**Comment by elliwigy** [comment] 2019-09-07 21:26
Yea, even if they release the dev images anytime soon we will still most likely not be able to magisk patch either stock or eng firmware and will likely only have a root shell.. might end up having to do some sort of system root instead of systemless..

The ramdisk appears to be on/in system.img and is separate from the recovery ramdisk and boot.img appears to just be a kernel. To avoid issues modifying the system ramdisk one would need to get a bit clever if we are going to have a "systemless" root.. My guess is somehow patch it into vendor.. 

So far I am missing somethin as im still having trouble booting with anything outside of boot and recovery images being modified

**Comment by elliwigy** [comment] 2019-09-21 05:25
seems it was inadvertently fixed with latest update.. ramdisk is merged into system.img on latest shield update which latest magisk now supports.

**Comment by thekiefs** [comment] 2019-10-23 03:41
@elliwigy I tried patching Nvidia Shield 8.0 with Magisk 20 but got the boot loop. Are you sure this is fixed?

**Comment by s3phir0th115** [comment] 2019-11-05 00:10
I've tried installing Magisk by patching the boot.img both with the stock and the dev rooted images' respective boot.img, and every time it hangs on the Nvidia logo and doesn't fully boot.
This is with the 8.0.0 version and Magisk 20.1, and also the latest canary build made earlier today.
