### ISSUE TITLE
Phone stuck in fastboot after Magisk recovery flashing

### ISSUE THREAD

**Issue by arturino009** [topjohnwu/Magisk#5646] opened 2022-03-24 16:06 UTC
Device: Xiaomi Mi 9T
Android version: 11 RKQ1.200826.002
MIUI version: 12.1.1.0(RFJEUXM)
Magisk version name: 3dc7d77e
Magisk version code: 24304

So I tried to root my phone lately, but with no success. I have no ramdisk, so I found the stock recovery image, flashed it with Magisk app, then flashed phones recovery with the new image. But when I try to enter recovery mode on my phone, it just boots straight back to fastboot. Only other way is to boot normally, but then I get no root, and recovery gets restored to stock recovery.
I've been trying different methods and different versions, but I just can't get it to work. I can provide any logs I can. Attached a "cat /proc/mounts" [log.txt](https://github.com/topjohnwu/Magisk/files/8343321/log.txt).

**Comment by yujincheng08** [comment] 2022-03-24 17:30
xiaomi devices should patch boot instead of recovery

**Comment by arturino009** [comment] 2022-03-24 19:12
Well if I flash boot the phone just doesn't boot at all. Stuck in MIUI logo. Here's logcat of bootloop 
[log.txt](https://github.com/topjohnwu/Magisk/files/8344669/log.txt)

**Comment by arturino009** [comment] 2022-03-24 19:44
I tried flashing stock vbmeta with vbmeta --disable-verity --disable-verification vbmeta.img and I guess something changed? Because now when i boot into patched recovery I don't go to fastboot, just a regular bootloop (stuck at logo). Logcat of first seconds:
[log4.txt](https://github.com/topjohnwu/Magisk/files/8344869/log4.txt)
.

**Comment by osm0sis** [comment] 2022-03-24 23:27
Where's the recovery.log from the flash?

**Comment by yujincheng08** [comment] 2022-03-25 02:48
Duplicate of #5624

**Closed by yujincheng08** 2022-03-25 02:48 UTC

**Comment by yujincheng08** [comment] 2022-03-25 03:12
```
04-04 02:52:54.631   657   659 E Magisk  : mount /dev/3tZf/.magisk/modules/ViPER4AndroidFX/system/system/vendor/lib/libstdc++.so->/system/vendor/lib/libstdc++.so failed with 2: No such file or directory
```

**Comment by pndwal** [comment] 2022-03-27 05:57
> Duplicate of #5624

Really?... But user is trying to install to recovery as you originally commented and apparently never got modules installed! ... Can this be a multi module issue? 🤔

**Comment by arturino009** [comment] 2022-03-27 11:19
I don't know if it was a duplicate, but issue truly was that a module was causing a bootloop. Deleteing all modules with adb shell while in a bootloop fixed it.
