### ISSUE TITLE
Magisk app cannot finish installation because file on jsdelivr is down

### ISSUE THREAD

**Issue by ohyeaah** [topjohnwu/Magisk#7594] opened 2023-12-05 14:31 UTC
What I did:

```
git clone --recurse-submodules https://github.com/topjohnwu/Magisk.git
cd Magisk
./build.py all
./build.py avd_patch /home/user1/Android/Sdk/my-system-images/android-34/google_apis/x86_64/ramdisk.img
```

That worked fine. Then I performed a cold boot and then I opened the Magisk app because `/system/xbin/su` was still the stock su and not MagiskSU. I clicked Ok (see screenshot).

But nothing happended and on logcat there's an error. It says:

`java.io.FileNotFoundException: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@7235d30bc73c16c953b1bc16e41bad1c962878c9/app-debug.apk`

Some lines are following but they are of no interest because when you open [the file](https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@7235d30bc73c16c953b1bc16e41bad1c962878c9/app-debug.apk) in a browser you will see this error:

`File size exceeded the configured limit of 20 MB.`

![Screenshot_20231205_152327](https://github.com/topjohnwu/Magisk/assets/56166150/a9e0be0c-71e5-4c9b-9e61-4a4e361d5a80)

Device: Android Emulator (own build)
Android version: VanillaIceCream (API level 34)
Magisk version name: v26.4
Magisk version code: 26402
(I am using the master repo. Everything up to commit d47e70cfaaa4f5cba6841fb8da5c3976cbba09eb (included))

**Comment by gudenau** [comment] 2023-12-05 14:41
https://github.com/topjohnwu/Magisk/assets/5642329/b41bbbd2-a5ff-420b-b9f8-55d22a3dc75b

I'm not sure if the root cause is the same, but I can't update Magisk myself.

**Comment by thx1200** [comment] 2023-12-05 16:57
I'm having a very similar issue.

https://github.com/topjohnwu/Magisk/assets/5454591/161f500b-8fe4-4ac4-ac47-1d16716b7678

**Comment by vvb2060** [comment] 2023-12-05 20:52
Duplicate of #7592

**Closed by vvb2060** 2023-12-05 20:52 UTC
