### ISSUE TITLE
Compression method of ramdisk in Pixel 6 boot image is incorrect

### ISSUE THREAD

**Issue by charlye30** [topjohnwu/Magisk#6441] opened 2022-12-13 11:20 UTC
After switching to the beta version can't patch boot img and succesfully get root, with the stable version works.

Device: Pixel 6a
Android version: Android 13 QPR2 Beta 1 (T2B1.221118.006)
Magisk version name: 25.2
Magisk version code: 25205

**Comment by SammCheese** [comment] 2022-12-13 11:27
Confirmed on Pixel 6 (T2B1.221118.006)
Magisk version: 25205

**Comment by m-pastuszek** [comment] 2022-12-13 12:39
Yep, Pixel 6 (oriole) also affected.
Tried patching vendor_boot.img also, but still don't works.

Magisk Canary a468fd94

**Comment by canyie** [comment] 2022-12-13 13:34
Please upload bugreport
https://developer.android.com/studio/debug/bug-report

**Comment by pKrysenko** [comment] 2022-12-13 13:48
Pixel 6 pro
[bugreport-raven-T2B1.221118.006-2022-12-13-15-44-44.zip](https://github.com/topjohnwu/Magisk/files/10218484/bugreport-raven-T2B1.221118.006-2022-12-13-15-44-44.zip)
[magisk_log_2022-12-13T15.44.28.log](https://github.com/topjohnwu/Magisk/files/10218487/magisk_log_2022-12-13T15.44.28.log)

**Comment by canyie** [comment] 2022-12-13 14:08
Hmm, nothing about Magisk can be found in your log, it behaves like boot is not patched.
And I found something interesting, someone successfully rooted a Pixel 6 by patching and flashing the boot image from Pixel 7 instead. That one said that Google published a broken boot image which cannot even boot (so device always refuse the new image and rollback to the old one?)

**Comment by pKrysenko** [comment] 2022-12-13 14:17
> Hmm, nothing about Magisk can be found in your log, it behaves like boot is not patched. And I found something interesting, someone successfully rooted a Pixel 6 by patching and flashing the boot image from Pixel 7 instead. That one said that Google published a broken boot image which cannot even boot (so device always refuse the new image and rollback to the old one?)

I can confirm. Just patched a boot from p7pro and patched it. It successfully boota on p6ro and root works. Many thanks, seems like google really broke something

**Comment by m-pastuszek** [comment] 2022-12-13 14:17
@canyie, it's actually big LOL.
Patching boot image from Pixel 7 and flashing it on Pixel 6 works!

Tested with latest Canary.

**Comment by H3llblazer** [comment] 2022-12-13 14:44
> @canyie, it's actually big LOL.
> Patching boot image from Pixel 7 and flashing it on Pixel 6 works!
> 
> Tested with latest Canary.

Can you please share the patched boot you used? 

I need one for pixel 6 not the PRO.

**Comment by m-pastuszek** [comment] 2022-12-13 17:07
> > @canyie, it's actually big LOL.
> > Patching boot image from Pixel 7 and flashing it on Pixel 6 works!
> > Tested with latest Canary.
> 
> Can you please share the patched boot img you used?
> 
> I need one for pixel 6 not the PRO.

Sure, this is the one that I flashed on my Pixel 6.

[magisk_patched-25205_Pixel7.zip](https://github.com/topjohnwu/Magisk/files/10220340/magisk_patched-25205_Pixel7.zip)

**Comment by H3llblazer** [comment] 2022-12-13 19:04
> > > @canyie, it's actually big LOL.
> > > Patching boot image from Pixel 7 and flashing it on Pixel 6 works!
> > > Tested with latest Canary.
> > 
> > Can you please share the patched boot img you used?
> > 
> > I need one for pixel 6 not the PRO.
> 
> Sure, this is the one that I flashed on my Pixel 6.
> But if You want to check it first, just use `fastboot boot <pathed_boot.img>`.
> 
> **For Pixel 6 ONLY**
> 
> [magisk_patched-25205_Pixel7.zip](https://github.com/topjohnwu/Magisk/files/10220340/magisk_patched-25205_Pixel7.zip)
> 

I tried that and it seems like it didn't work. I see others who have had success with this method so i know it's possible. Maybe it's the bad cable I'm using or something. Also tried to repatch the image on my second try , no buano.

I'll download the factory zip and give this another try later today.

**Comment by AllenChangMusic** [comment] 2022-12-13 21:25
> > > > @canyie, it's actually big LOL.
> > > > Patching boot image from Pixel 7 and flashing it on Pixel 6 works!
> > > > Tested with latest Canary.
> > > 
> > > 
> > > Can you please share the patched boot img you used?
> > > I need one for pixel 6 not the PRO.
> > 
> > 
> > Sure, this is the one that I flashed on my Pixel 6.
> > But if You want to check it first, just use `fastboot boot <pathed_boot.img>`.
> > **For Pixel 6 ONLY**
> > [magisk_patched-25205_Pixel7.zip](https://github.com/topjohnwu/Magisk/files/10220340/magisk_patched-25205_Pixel7.zip)
> 
> I tried that and it seems like it didn't work. I see others who have had success with this method so i know it's possible. Maybe it's the bad cable I'm using or something. Also tried to repatch the image on my second try , no buano.
> 
> I'll download the factory zip and give this another try later today. Thanks
> 
> Edit: seems like the flash did work but magisk app still shows super user tab in grey. I tried to uninstall and reinstall the app. A good old reboot even. No Bueno.
> 
> Can we report this to Google via the feedback app, would they attend to such matters??

You could potentially try to flash the patched boot.img from the December QPR1. It should patch and allow you to boot.

**Comment by Aboodhassand** [comment] 2022-12-13 21:29
> After switching to the beta version can't patch boot img and succesfully get root, with the stable version works.
> 
> Device: Pixel 6a Android version: Android 13 QPR2 Beta 1 (T2B1.221118.006) Magisk version name: 25.2 Magisk version code: 25205

**Comment by m-pastuszek** [comment] 2022-12-13 21:51
> > > > @canyie, it's actually big LOL.
> > > > Patching boot image from Pixel 7 and flashing it on Pixel 6 works!
> > > > Tested with latest Canary.
> > > 
> > > 
> > > Can you please share the patched boot img you used?
> > > I need one for pixel 6 not the PRO.
> > 
> > 
> > Sure, this is the one that I flashed on my Pixel 6.
> > But if You want to check it first, just use `fastboot boot <pathed_boot.img>`.
> > **For Pixel 6 ONLY**
> > [magisk_patched-25205_Pixel7.zip](https://github.com/topjohnwu/Magisk/files/10220340/magisk_patched-25205_Pixel7.zip)
> 
> I tried that and it seems like it didn't work. I see others who have had success with this method so i know it's possible. Maybe it's the bad cable I'm using or something. Also tried to repatch the image on my second try , no buano.
> 
> I'll download the factory zip and give this another try later today. Thanks
> 
> Edit: seems like the flash did work but magisk app still shows super user tab in grey. I tried to uninstall and reinstall the app. A good old reboot even. No Bueno.
> 
> Can we report this to Google via the feedback app, would they attend to such matters??

Can You try flash stock boot image, reboot, and then patched one again? I had someone on pm, for him this worked.

**Comment by H3llblazer** [comment] 2022-12-14 06:15
>  > I tried that and it seems like it didn't work. I see others who have had success with this method so i know it's possible. Maybe it's the bad cable I'm using or something. Also tried to repatch the image on my second try , no buano.
> > 
> > I'll download the factory zip and give this another try later today. Thanks
> > 
> > Edit: seems like the flash did work but magisk app still shows super user tab in grey. I tried to uninstall and reinstall the app. A good old reboot even. No Bueno.
> > 
> > Can we report this to Google via the feedback app, would they attend to such matters??
> 
> @H3llblazer  Can You try flash stock boot image, reboot, and then patched one again? I had someone on pm, for him this worked.

Stock boot image from QPR2? 
I'll try this and report back if it was a success

Steps to test:
1.flash stock boot from QPR2
2.reboot
3.flash pixel 7 patched boot.

**Comment by SammCheese** [comment] 2022-12-14 06:36
Can confirm the patched Pixel 7 boot.img from @m-pastuszek successfully roots my Pixel 6

**Comment by yujincheng08** [comment] 2022-12-14 16:24
Could anyone send the stock init_boot.img?

**Comment by Hondo77** [comment] 2022-12-14 17:20
> Could anyone send the stock init_boot.img?

Here is the stock init_boot.img from the Pixel 7 Pro running QPR2 Beta 1. I don't believe the Pixel 6 series has an init_boot.img. Had to zip it up to attach it.


[init_boot.zip](https://github.com/topjohnwu/Magisk/files/10230180/init_boot.zip)

**Comment by yujincheng08** [comment] 2022-12-15 08:19
Then please also provice the stock boot image from pixel 6

**Comment by pndwal** [comment] 2022-12-15 08:26
> > Could anyone send the stock init_boot.img?
> 
> Here is the stock init_boot.img from the Pixel 7 Pro running QPR2 Beta 1. I don't believe the Pixel 6 series has an init_boot.img. Had to zip it up to attach it.
> 
> I'm guessing you were talking about the Pixel 6 though, but anyway, just in case...
> 
> [init_boot.zip](https://github.com/topjohnwu/Magisk/files/10230180/init_boot.zip)

Correct; P6 has 2 GKI boot images but boot.img retains generic ramdisk (vendor ramdisks are removed)... P7 has 4 and generic ramdisk is now moved to init_boot.img...

I believe P7 boot.img (kernel only and lacking ramdisk) works with P6 after patching because 1) kernel is compatible by some fluke (sources are very similar), and 2) Magisk manually adds basic ramdisk when missing for magiskinit injection (so P7 boot image has ramdisk restored after patching)...

To be clear, by patching and using P7 boot.img, P6 is loading a Magisk-added ramdisk containing Magisk different from P7 ... P7 uses a patched ramdisk in init_boot.img which P6 doesn't have AFAIK...

**Comment by SammCheese** [comment] 2022-12-15 09:21
> Then please also provice the stock boot image from pixel 6

latest boot.img from my Pixel 6
[boot.zip](https://github.com/topjohnwu/Magisk/files/10235539/boot.zip)

**Comment by amritpal2489** [comment] 2022-12-15 18:30
Can some one provide patched boot image for Pixel 6 Pro from 7P?

**Comment by Kastilo** [comment] 2022-12-15 20:37
> Can some one provide patched boot image for Pixel 6 Pro from 7P?

[magisk_patched_boot.img](https://drive.google.com/file/d/1LNoinLpNYIQWycK9WqQVJPV83N2BEqMR/view?usp=drivesdk)

**Comment by amritpal2489** [comment] 2022-12-16 03:18
> > Can some one provide patched boot image for Pixel 6 Pro from 7P?
> 
> [magisk_patched_boot.img](https://drive.google.com/file/d/1LNoinLpNYIQWycK9WqQVJPV83N2BEqMR/view?usp=drivesdk)

Thanks but this did not work. I think this is 6pro patched boot img only and not 7 pro

**Comment by amritpal2489** [comment] 2022-12-16 19:48
Can some one provide patched boot image for Pixel 6 Pro from P7P which gives root access through Magisk?

**Comment by AllenChangMusic** [comment] 2022-12-16 19:50
> Can some one provide patched boot image for Pixel 6 Pro from P7P which gives root access through Magisk?

It will take far less time for you to patch it yourself. Cheers

**Comment by amritpal2489** [comment] 2022-12-16 19:57
> > Can some one provide patched boot image for Pixel 6 Pro from P7P which gives root access through Magisk?
> 
> It will take far less time for you to patch it yourself. Cheers

I tried but my 6p failed to boot with that

**Comment by amritpal2489** [comment] 2022-12-17 11:08
Can somebody provide me Pixel 7 Pro's magisk patched boot img from the latest QPR2 Beta 1 update?
The one which succesfully roots the Pixel 6 Pro

**Comment by rly907** [comment] 2022-12-17 17:20
Does any of this help rooting the pixel 6a beta?

**Comment by pndwal** [comment] 2022-12-18 12:08
> Does any of this help rooting the pixel 6a beta?

Guessing Edit 2 here:
https://github.com/topjohnwu/Magisk/issues/6441#issuecomment-1350458251
might be good for all models... 😀

**Comment by Gaelscoileanna** [comment] 2022-12-19 02:09
I have a 6a rooted with magisk. I updated yo the beta yesterday and it even kept the root and SU privileges.

**Comment by aussiebro** [comment] 2022-12-20 09:41
So will this issue happen in future top John wu? What caused this. I'm using 64bit rom p6 and the p7s boot image patched lol. It doesn't sound right tho having different phones file. I hope you fix

**Comment by lssong99** [comment] 2022-12-21 09:59
For anyone wants a patched boot.img *ONLY* for Pixel 6 Pro, I verified this works:

https://drive.google.com/file/d/1LNoinLpNYIQWycK9WqQVJPV83N2BEqMR/view?usp=drivesdk

This image is not from me but from @Kastilo (https://github.com/topjohnwu/Magisk/issues/6441#issuecomment-1353678284). This image is patched with a Pixel 7 series.

**Comment by john-uirbe** [comment] 2022-12-29 03:42
thanks it worked for my pixel 6pro

**Comment by Nereuxofficial** [comment] 2023-01-04 23:27
> 

Doesnt work for me at least with fastboot boot IMAGE_NAME
Is there anything special required?

**Comment by Kastilo** [comment] 2023-01-05 17:25
> > 
> 
> Doesnt work for me at least with fastboot boot IMAGE_NAME Is there anything special required?

That shouldn't be the case, but it seems the issue with resolved with the January 2023 update, was able to patch the default Pixel 6 Pro boot image without issue so it might have just been a borked update on Google's end

**Comment by Hondo77** [comment] 2023-01-05 17:53
> > > 
> > 
> > 
> > Doesnt work for me at least with fastboot boot IMAGE_NAME Is there anything special required?
> 
> That shouldn't be the case, but it seems the issue with resolved with the January 2023 update, was able to patch the default Pixel 6 Pro boot image without issue so it might have just been a borked update on Google's end

The issue is with the QPR2 betas, or at least Beta 1 so far. There is no issue when using stable builds like the January update you mention.

**Comment by lssong99** [comment] 2023-01-06 06:47
> > 
> 
> Doesnt work for me at least with fastboot boot IMAGE_NAME Is there anything special required?

What doesn't work in your case?

If you are talking about using Magisk direct patch boot.img of Pixel 6 (Pro) QPR2b1 factory image, then nothing you could do to make this work at this moment.

If you are talking about using the Pixel 7 Pro image posted by https://github.com/topjohnwu/Magisk/issues/6441#issuecomment-1361102484 here, then it should just work by flashing with `fastboot flash boot xxx.img` without any options. (Maybe update your fastboot binary?)

**Comment by Nereuxofficial** [comment] 2023-01-06 07:03
> > > 
> > 
> > Doesnt work for me at least with fastboot boot IMAGE_NAME Is there anything special required?
> 
> What doesn't work in your case?
> 
> If you are talking about using Magisk direct patch boot.img of Pixel 6 (Pro) QPR2b1 factory image, then nothing you could do to make this work at this moment.
> 
> If you are talking about using the Pixel 7 Pro image posted by https://github.com/topjohnwu/Magisk/issues/6441#issuecomment-1361102484 here, then it should just work by flashing with `fastboot flash boot xxx.img` without any options. (Maybe update your fastboot binary?)

I was talking about the latter, which didn't work on my Pixel 6 Pro. The fastboot binary was the latest one on Arch Linux so should be pretty up to date

**Comment by lssong99** [comment] 2023-01-06 14:47
> > > > 
> > > 
> > > 
> > > Doesnt work for me at least with fastboot boot IMAGE_NAME Is there anything special required?
> > 
> > 
> > What doesn't work in your case?
> > If you are talking about using Magisk direct patch boot.img of Pixel 6 (Pro) QPR2b1 factory image, then nothing you could do to make this work at this moment.
> > If you are talking about using the Pixel 7 Pro image posted by [#6441 (comment)](https://github.com/topjohnwu/Magisk/issues/6441#issuecomment-1361102484) here, then it should just work by flashing with `fastboot flash boot xxx.img` without any options. (Maybe update your fastboot binary?)
> 
> I was talking about the latter, which didn't work on my Pixel 6 Pro. The fastboot binary was the latest one on Arch Linux so should be pretty up to date

It should work without issue. I suggest change another PC with non-USB C interface. I did have strange issues with USB C under Windows. Anyway redownload them image and use different PC (and OS) is the only thing I could recommend.

I have also patched the image with latest Magisk and it works like charm.

**Comment by KieronQuinn** [comment] 2023-01-09 18:34
For the record, exact same situation with QPR2 B2. Magisk doesn't work on the P6P image, patching the P7P image and using that works fine. 

Patched Pixel 7 Pro image for use on the Pixel 6 Pro: https://drive.google.com/file/d/1bpcj6JntADL5-gcMPH5kbjW541ZfrwAI/view?usp=sharing

**Comment by tlxxxsracer** [comment] 2023-01-09 19:07
Confirmed same thing on QPR2 B2 for Pixel 6a.

**Comment by tlxxxsracer** [comment] 2023-01-09 19:13
Flashed the patched P7 boot on Pixel 6a, but now Magisk keeps disappearing when I open it. Running Canary. But the device has root though.

**Comment by SammCheese** [comment] 2023-01-10 01:26
Patched  QRP2 B2 Pixel 7 image for **PIXEL 6 ONLY**.

[magisk_patched-25206_pixel7_for_6.zip](https://github.com/topjohnwu/Magisk/files/10378141/magisk_patched-25206_pixel7_for_6.zip)

**Comment by raven2411** [comment] 2023-01-10 09:18
> Patched QRP2 B2 Pixel 7 image for **PIXEL 6 ONLY**.
> 
> [magisk_patched-25206_pixel7_for_6.zip](https://github.com/topjohnwu/Magisk/files/10378141/magisk_patched-25206_pixel7_for_6.zip)


not working for me P6 in QPR2 B2

**Comment by BlazeCodeDev** [comment] 2023-01-10 10:21
> For the record, exact same situation with QPR2 B2. Magisk doesn't work on the P6P image, patching the P7P image and using that works fine.
> 
> Patched Pixel 7 Pro image for use on the Pixel 6 Pro: https://drive.google.com/file/d/1bpcj6JntADL5-gcMPH5kbjW541ZfrwAI/view?usp=sharing

This causes my P6Pro to reboot as soon as I try to open any app

**Comment by SammCheese** [comment] 2023-01-10 11:03
Thats odd, it works just fine for me

> > Patched QRP2 B2 Pixel 7 image for **PIXEL 6 ONLY**.
> > [magisk_patched-25206_pixel7_for_6.zip](https://github.com/topjohnwu/Magisk/files/10378141/magisk_patched-25206_pixel7_for_6.zip)
> 
> not working for me P6 in QPR2 B2

**Comment by Jilfeye** [comment] 2023-01-10 11:16
Then how ?

**Comment by mosin** [comment] 2023-01-10 11:18
> Then how ?
Just flashing the patched P7P boot image i.e. fastboot flash boot 
fastboot flash boot magisk_patched-25206_lBM7l.img

**Comment by xor-public** [comment] 2023-01-10 14:07
> For the record, exact same situation with QPR2 B2. Magisk doesn't work on the P6P image, patching the P7P image and using that works fine.
> 
> Patched Pixel 7 Pro image for use on the Pixel 6 Pro: https://drive.google.com/file/d/1bpcj6JntADL5-gcMPH5kbjW541ZfrwAI/view?usp=sharing

not working for me

**Comment by KieronQuinn** [comment] 2023-01-10 14:49
> For the record, exact same situation with QPR2 B2. Magisk doesn't work on the P6P image, patching the P7P image and using that works fine.
> 
> Patched Pixel 7 Pro image for use on the Pixel 6 Pro: https://drive.google.com/file/d/1bpcj6JntADL5-gcMPH5kbjW541ZfrwAI/view?usp=sharing

I realised I was still running this from `fastboot boot`, rebooted and installed it properly. Still works fine. No idea what you're all doing to get bootloops and apps crashing.

**Comment by lssong99** [comment] 2023-01-10 15:11
For people still have problem patch P6 Pro or P6, my step as follows:
1. Download both P6P+P7P (or P6+P7) factory image.
2. Extract the boot.img from P7P/P7 and patch the boot.img with any phone with latest canary Magisk (let's call this P7_patched.img)
3. Flash-all your P6P/P6 as before with P6P/P6 factory image.
4. After the system upgrade successfully (no-root), you could `fastboot flash boot P7_patched.img` and your P6P/P6 should work.

What is important is P6P can only use P7P, while P6 can only P7 boot.img.

As for P6a, sorry, I don't have P6a so doesn't know if Magisk works with P6a or not (or which image you could use since no P7a exist today.)

**Comment by BlazeCodeDev** [comment] 2023-01-10 15:18
> For people still have problem root QPR2B2 P6 Pro or P6, my step as follows:
> 
>     1. Download both P6P+P7P (or P6+P7) factory image.
> 
>     2. Extract the boot.img from P7P/P7 and patch the boot.img with any phone with latest canary Magisk (let's call this P7_patched.img)
> 
>     3. Flash-all your P6P/P6 as before with P6P/P6 factory image.
> 
>     4. After the system upgrade and boot successfully (no-root), you could enter bootloader then `fastboot flash boot P7_patched.img` and your P6P/P6 should work. (for safety, you could first try `fastboot boot P7_patched.img` to see if it works or not. However, you still need to flash P7_patched.img by fastboot if everything seems okay.)
> 
> 
> What is important is P6P can only use P7P, while P6 can only P7 boot.img.
> 
> As for P6a, sorry, I don't have P6a so doesn't know if Magisk works with P6a or not (or which image you could use since no P7a exist today.)

Thats exactly what I did earlier. As soon as I tried to open the Magisk app it crashed and rebooted. I'll try it again later today and uninstall the app before patching.

**Comment by john-uirbe** [comment] 2023-01-11 16:13
Thanks to me it works without any problem.

**Comment by canyie** [comment] 2023-01-13 08:40
```
Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers

Supplied image: boot.img

Removing old work folders and files . . .

Setting up work folders . . .

Image type: AOSP

Signature with "AVBv2" type detected.

Splitting image to "split_img/" . . .

ANDROID! magic found at: 0
BOARD_KERNEL_CMDLINE
BOARD_PAGE_SIZE 4096
BOARD_HEADER_VERSION 4
BOARD_HEADER_SIZE 1584

Unpacking ramdisk to "ramdisk/" . . .

Compression used: gzip
5732 blocks

Done!
```
Could anyone send me the **STOCK** `boot.img` and `vendor_boot.img` from Google Pixel 6 series?

**Comment by skvalex** [comment] 2023-01-13 08:59
@canyie here are images for Pixel 6a:
[bluejay-t2b2.221216.006-boot-vendor.zip](https://github.com/topjohnwu/Magisk/files/10409787/bluejay-t2b2.221216.006-boot-vendor.zip)
[bluejay-t2b2.221216.006-boot.zip](https://github.com/topjohnwu/Magisk/files/10409800/bluejay-t2b2.221216.006-boot.zip)

**Comment by canyie** [comment] 2023-01-13 09:26
Oh I think I know what the real problem is. Manually fixed the Pixel 6a boot image @skvalex provided, could you test if it works?
[magisk_patched-25206_MbW9Q.zip](https://github.com/topjohnwu/Magisk/files/10410110/magisk_patched-25206_MbW9Q.zip)

**Comment by skvalex** [comment] 2023-01-13 09:39
@canyie it works!

<details>
  <summary>Screenshot</summary>

![photo_2023-01-13 16 37 36](https://user-images.githubusercontent.com/2552728/212287633-44878cb4-3d6a-4d4a-851a-28ff8236bb56.jpeg)

</details>

**Comment by yujincheng08** [comment] 2023-01-13 10:30
The problem seems to lie in that the ramdisks of vendor boot and generic boot have different compression algorithms, and the bootloader actually does not use the generic boot ramdisk.

Let's see how @topjohnwu sees this. Since `magiskboot` may not support patching vendor boot while this issue requires a vendor boot patching.

Maybe Google does it on purpose to simulate the init_boot, or it's just an unexpected mistake. If the next release fixes this issue, it may be a wontfox.

**Comment by pndwal** [comment] 2023-01-13 11:11
I saw this fix:
https://github.com/topjohnwu/Magisk/commit/985249c3d0bccff479f8c1efd5967922ab8d855e
worked largely worked due to unifying boot ramdisk compression method in v4 GKIs to use lz4 (legacy)... So seems it was genetic ramdisk in boot.img that needed the patch in that case?... Even if this is dissimilar, it may help...

**Comment by canyie** [comment] 2023-01-13 12:24
Yeah, always compress it as lz4-l will help, but we need a way to detect it.
Now the boot.img contains a ramdisk with incorrect compression. According to [official documents](https://source.android.com/docs/core/architecture/partitions/vendor-boot-partitions?hl=en#bootloader-support), I believe it is not expected.

> Because the generic ramdisk and vendor ramdisk get concatenated, 
they must be in the same format.
 The GKI boot image uses an lz4-compressed generic ramdisk,
 so a device that is GKI-compliant must use an lz4-compressed vendor ramdisk. 
The configuration for this is shown below.

**Comment by Hondo77** [comment] 2023-01-13 13:50
For what it's worth, QPR2 doesn't go stable until March 6. Will be at least one more beta release before then, so we may not know for sure if it is intended/expected until March.

**Comment by badhabitwb** [comment] 2023-01-13 21:33
> Oh I think I know what the real problem is. Manually fixed the Pixel 6a boot image @skvalex provided, could you test if it works? [magisk_patched-25206_MbW9Q.zip](https://github.com/topjohnwu/Magisk/files/10410110/magisk_patched-25206_MbW9Q.zip)

Can you work your magic on the p6 pro image? tia

**Comment by pndwal** [comment] 2023-01-14 00:06
So at least only boot.img (with the generic ramdisk) needs patching (again)...

> Yeah, always compress it as lz4-l will help, but we need a way to detect it...

I understand a detection/analysis mechanism even for boot.img (or for init_boot.img W/ A13 LV) may be difficult to implement, but I'm not understanding this:

> ... `magiskboot` is likely not going to support patching vendor boot while this issue requires a vendor boot patching.

since so far vendor boot has (correctly?) used lz4-l... So do we really need vendor boot patching?

> Maybe Google does it on purpose to simulate the init_boot, 

... So is A13 init_boot.img also using compression other than lz4-l?

> ...or it's just an unexpected mistake. If the next release fixes this issue, it may be a wontfox.

Yup... Guessing also it may be a beta oversight... (+ we all love won't fox issues! 😜)

**Comment by betterclever** [comment] 2023-01-20 20:37
confirming that this problem persists on Android 13 QPR2 Beta 2.1 Build T2B2.221216.008 as well on my Pixel 6 Pro.

Haven't tried out using the patched boot image from Pixel 7 Pro, not sure if it is safe enough!

**Comment by badhabitwb** [comment] 2023-01-20 20:41
> confirming that this problem persists on Android 13 QPR2 Beta 2.1 Build T2B2.221216.008 as well on my Pixel 6 Pro.
> 
> Haven't tried out using the patched boot image from Pixel 7 Pro, not sure if it is safe enough!

Fwiw it's working fine with the p7p image on my p6p.

**Comment by Hondo77** [comment] 2023-01-20 21:15
QPR2 Beta 2.1 is a very minor update with 2 fixes as far as I can see, so not surprising this problem continues to exist on this build. When QPR2 stable is released in March we will find out for sure whether the changes causing the problem are intended or not.

**Comment by BlazeCodeDev** [comment] 2023-01-21 12:03
I flashed the patched P7Pro image onto my P6Pro, as soon as I open Magisk manager it crashes and uninstalls itself.

`Failed to open APK '/data/app/~~Q5ECAOrx31RY8KrgceeMzA==/com.topjohnwu.magisk-8IoHzI-IKY3RY0GcOJ47aw==/base.apk': I/O error`

Has anybody encountered this issue? I tried creating the folders to paste the apk there, but I do not have sufficient permissions.

**Comment by badhabitwb** [comment] 2023-01-21 17:21
> I flashed the patched P7Pro image onto my P6Pro, as soon as I open Magisk manager it crashes and uninstalls itself.
> 
> `Failed to open APK '/data/app/~~Q5ECAOrx31RY8KrgceeMzA==/com.topjohnwu.magisk-8IoHzI-IKY3RY0GcOJ47aw==/base.apk': I/O error`
> 
> Has anybody encountered this issue? I tried creating the folders to paste the apk there, but I do not have sufficient permissions.
> 
> Edit: Just to clarify root is working, only magisk manager is crashing

No issues on mine but I usually patch the image before I do the update and do a clean install afterwards.

**Comment by chrispilot2293** [comment] 2023-01-24 06:41
So against my better judgement i updated my rooted pixel 6 to 221216.008 from about 2 months agos build, and am now stuck without root even though I made sure to follow the same procedure for updating that I always do, what do I need to do to get magisk working again?

**Comment by BlazeCodeDev** [comment] 2023-01-24 13:01
> So against my better judgement i updated my rooted pixel 6 to 221216.008 from about 2 months agos build, and am now stuck without root even though I made sure to follow the same procedure for updating that I always do, what do I need to do to get magisk working again? 

Just flash the new image as usual, but don't patch the Pixel 6 boot image, instead patch the P7 boot image and flash that. This will work for now.

In case you use AndroidFrashTool make sure to not accidentally select the 64 bit only image, this will cause bootloops after flashing the boot image

**Comment by chrispilot2293** [comment] 2023-01-24 17:41
> > So against my better judgement i updated my rooted pixel 6 to 221216.008 from about 2 months agos build, and am now stuck without root even though I made sure to follow the same procedure for updating that I always do, what do I need to do to get magisk working again?
> 
> Just flash the new image as usual, but don't patch the Pixel 6 boot image, instead patch the P7 boot image and flash that. This will work for now.
> 
> In case you use AndroidFlashTool make sure to not accidentally select the 64 bit only image, this will cause bootloops after flashing the boot image

Am now rooted using the panther boot image, thanks, now to reconfigure all my shit that got messed up by booting rootless! >_<

**Comment by Hondo77** [comment] 2023-02-01 20:18
Saw a report from one user that patching Pixel 6 series' boot image now working again on QPR2 Beta 3 that was released today.

**Comment by badhabitwb** [comment] 2023-02-01 20:53
> Saw a report from one user that patching Pixel 6 series' boot image now working again on QPR2 Beta 3 that was released today.

It's working fine on my p6p this time with qpr2 b3

**Closed** 2023-02-01 20:58 UTC
Labels: wontfix, not our issue

**Comment by KieronQuinn** [comment] 2023-02-08 20:05
For anyone wondering, it seems the fix in QPR2 B3 isn't merged into the Android 14 DP1, so you will need to use the same method as above for that version. Hopefully it'll be merged in DP2.

**Comment by canyie** [comment] 2023-02-09 04:16
Then I think this issue should be pinned until Google fixes it 🤔

**Comment by Displax** [comment] 2023-02-09 19:19
Google just didn't merge fix for this from QPR2 to DP14 yet.

**Comment by Hondo77** [comment] 2023-03-08 19:14
Fix still not merged on A14 DP2. Had to use the Pixel 7 boot image to root.

**Comment by KieronQuinn** [comment] 2023-03-15 22:53
Issue seems to have returned in 13 QPR3. I guess the reason it never made it into A14 was because it was reverted for some reason.

**Comment by CalebJohnathen** [comment] 2023-03-15 23:39
> Issue seems to have returned in 13 QPR3. I guess the reason it never made it into A14 was because it was reverted for some reason.

Using the pixel 7 boot.img doesn't work either. I'm starting to think this is intentional.

**Comment by KieronQuinn** [comment] 2023-03-15 23:41
The 7 Pro image works on the 6 Pro thankfully, but that's not a good sign if it's not working on the regular devices.

**Comment by CalebJohnathen** [comment] 2023-03-15 23:53
> The 7 Pro image works on the 6 Pro thankfully, but that's not a good sign if it's not working on the regular devices.

thats weird, im using the 6 pro and its not working

**Comment by badhabitwb** [comment] 2023-03-16 00:40
> 

How'd you get it working?

**Comment by flobo09** [comment] 2023-03-16 04:13
Same issue with the regular Pixel 6 non pro on A14 DP2. Using the Pixel 7 boot does NOT work. 

No way to root as the moment.

**Comment by badhabitwb** [comment] 2023-03-16 21:23
P7p boot image and Canary 25206 worked for me on my p6p. The newer versions of Magisk didn't. I just got mine working again.

**Comment by nezorflame** [comment] 2023-03-17 21:37
> > Issue seems to have returned in 13 QPR3. I guess the reason it never made it into A14 was because it was reverted for some reason.
> 
> Using the pixel 7 boot.img doesn't work either. I'm starting to think this is intentional.

No, it does work. Just patched Pixel 7 image with latest Canary and it worked for my P6.

**Comment by flobo09** [comment] 2023-03-17 22:58
People seems to be confusing the 2 issues. 

on QPR3, you can use the P7 boot and it works
on A14DP2, there is a new issue and it doesn't (even building magisk with the latest commit integrated that are supposed to fix A14 support).

**Comment by vvb2060** [comment] 2023-03-18 05:24
```patch
From 80c5d6a8d55ef8d821b3b2885593123e053193a8 Mon Sep 17 00:00:00 2001
From: vvb2060 <vvb2060@gmail.com>
Date: Thu, 9 Feb 2023 12:29:21 +0800
Subject: [PATCH] Force ramdisk format to lz4_legacy for v4

---
 native/src/boot/bootimg.cpp | 9 +++++++--
 1 file changed, 7 insertions(+), 2 deletions(-)

diff --git a/native/src/boot/bootimg.cpp b/native/src/boot/bootimg.cpp
index 5b84e23ed..79aefc23d 100644
--- a/native/src/boot/bootimg.cpp
+++ b/native/src/boot/bootimg.cpp
@@ -624,8 +624,13 @@ void repack(const char *src_img, const char *out_img, bool skip_comp) {
     }
     if (access(RAMDISK_FILE, R_OK) == 0) {
         auto m = mmap_data(RAMDISK_FILE);
-        if (!skip_comp && !COMPRESSED_ANY(check_fmt(m.buf, m.sz)) && COMPRESSED(boot.r_fmt)) {
-            hdr->ramdisk_size() = compress(boot.r_fmt, fd, m.buf, m.sz);
+        auto r_fmt = boot.r_fmt;
+        if (!skip_comp && !hdr->is_vendor && hdr->header_version() == 4 && r_fmt != LZ4_LEGACY) {
+            fprintf(stderr, "RAMDISK_FMT: [%s] -> [%s]\n", fmt2name[r_fmt], fmt2name[LZ4_LEGACY]);
+            r_fmt = LZ4_LEGACY;
+        }
+        if (!skip_comp && !COMPRESSED_ANY(check_fmt(m.buf, m.sz)) && COMPRESSED(r_fmt)) {
+            hdr->ramdisk_size() = compress(r_fmt, fd, m.buf, m.sz);
         } else {
             hdr->ramdisk_size() = xwrite(fd, m.buf, m.sz);
         }

```

This is a patch from Magisk alpha, and you can use this patch in your own builds if needed. This patch will not be merged, as it is Google's own bug.
