### ISSUE TITLE
After Flash Patched boot.img Magisk not installed

### ISSUE THREAD

**Issue by ASIMKHAN222** [topjohnwu/Magisk#5437] opened 2022-02-11 12:53 UTC
Device: vivo s1
Android version: 11
Magisk version name: magisk canary 25
Magisk version code: 24102

i patched boot.img with latest canary after flash boot.img via fastboot i reboot the device but magisk is not installed
my device have
MT6768 Chipset

Attaching some files;
**Magisk install log**
[magisk_install_log_2022-02-10T00_03_57[2].log](https://github.com/topjohnwu/Magisk/files/8048750/magisk_install_log_2022-02-10T00_03_57.2.log)
**Magisk log**
[magisk_log_2022-02-11T17_06_07[1].log](https://github.com/topjohnwu/Magisk/files/8048659/magisk_log_2022-02-11T17_06_07.1.log)

**stock boot.img**
[boot[1].zip](https://github.com/topjohnwu/Magisk/files/8048690/boot.1.zip)

**Comment by canyie** [comment] 2022-02-11 13:10
Seems Magisk is working but does not mount /system
```
[init.svc.UJOzq6Pi]: [stopped]
[init.svc.Yi86JkCAtCpN]: [stopped]
[init.svc.xP3Bw7bdrFX]: [stopped]
3647 3645 0:21 / /dev/uqVV rw,relatime master:4 - tmpfs tmpfs rw,seclabel,size=1911908k,nr_inodes=477977,mode=755
3648 3647 0:38 / /dev/uqVV/.magisk/pts rw,nosuid,noexec,relatime master:11 - devpts devpts rw,seclabel,mode=600,ptmxmode=000
3649 3647 259:6 / /dev/uqVV/.magisk/mirror/vendor ro,relatime master:12 - ext4 /dev/uqVV/.magisk/block/vendor ro,seclabel
3650 3647 259:9 / /dev/uqVV/.magisk/mirror/data rw,relatime master:13 - ext4 /dev/uqVV/.magisk/block/data rw,seclabel,discard,noauto_da_alloc,inlinecrypt,resuid=10010,resgid=1065,errors=panic,data=ordered
3651 3647 259:7 / /dev/uqVV/.magisk/mirror/system_root ro,relatime master:40 - ext4 /dev/uqVV/.magisk/block/system_root ro,seclabel
3652 3647 259:9 /adb/modules /dev/uqVV/.magisk/modules rw,relatime master:13 - ext4 /dev/uqVV/.magisk/block/data rw,seclabel,discard,noauto_da_alloc,inlinecrypt,resuid=10010,resgid=1065,errors=panic,data=ordered
```

**Comment by yujincheng08** [comment] 2022-02-11 13:11
Need a full bootlog

**Comment by canyie** [comment] 2022-02-11 13:12
Oh, that's a vivo device. I believe this is a duplicate of #5148.

**Comment by ASIMKHAN222** [comment] 2022-02-12 07:30
> Need a full bootlog

[logcat.txt](https://github.com/topjohnwu/Magisk/files/8052994/logcat.txt)

**Comment by yujincheng08** [comment] 2022-02-12 07:34
> > Need a full bootlog
> 
> [logcat.txt](https://github.com/topjohnwu/Magisk/files/8052994/logcat.txt)

Too late. We need a logcat since phone boots.

**Comment by ASIMKHAN222** [comment] 2022-02-12 07:41
> Seems Magisk is working but does not mount> ```



> Seems Magisk is working but does not mount /system
> 
> ```
> [init.svc.UJOzq6Pi]: [stopped]
> [init.svc.Yi86JkCAtCpN]: [stopped]
> [init.svc.xP3Bw7bdrFX]: [stopped]
> 3647 3645 0:21 / /dev/uqVV rw,relatime master:4 - tmpfs tmpfs rw,seclabel,size=1911908k,nr_inodes=477977,mode=755
> 3648 3647 0:38 / /dev/uqVV/.magisk/pts rw,nosuid,noexec,relatime master:11 - devpts devpts rw,seclabel,mode=600,ptmxmode=000
> 3649 3647 259:6 / /dev/uqVV/.magisk/mirror/vendor ro,relatime master:12 - ext4 /dev/uqVV/.magisk/block/vendor ro,seclabel
> 3650 3647 259:9 / /dev/uqVV/.magisk/mirror/data rw,relatime master:13 - ext4 /dev/uqVV/.magisk/block/data rw,seclabel,discard,noauto_da_alloc,inlinecrypt,resuid=10010,resgid=1065,errors=panic,data=ordered
> 3651 3647 259:7 / /dev/uqVV/.magisk/mirror/system_root ro,relatime master:40 - ext4 /dev/uqVV/.magisk/block/system_root ro,seclabel
> 3652 3647 259:9 /adb/modules /dev/uqVV/.magisk/modules rw,relatime master:13 - ext4 /dev/uqVV/.magisk/block/data rw,seclabel,discard,noauto_da_alloc,inlinecrypt,resuid=10010,resgid=1065,errors=panic,data=ordered
> ```

so what should i now?
i am trying to Root My Device from since 3 months
but failed.
How can i Get Proper Access of Root?
can you help me please

**Comment by ASIMKHAN222** [comment] 2022-02-12 07:47
> Too late. We need a logcat since phone boots.

how to get that log again?

**Comment by yujincheng08** [comment] 2022-02-12 07:57
Shut down the phone, run `adb wait-for-device logcat > log`, and then start up the phone. After the phone starts, stop the command and send `log`.

**Comment by ASIMKHAN222** [comment] 2022-02-12 08:34
> Shut down the phone, run `adb wait-for-device logcat > log`, and then start up the phone. After the phone starts, stop the command and send `log`.

[log.txt](https://github.com/topjohnwu/Magisk/files/8053061/log.txt)

**Comment by yujincheng08** [comment] 2022-02-12 08:47
still too late

**Comment by yujincheng08** [comment] 2022-02-12 08:47
Please increase your log buffer size to a large one

**Comment by ASIMKHAN222** [comment] 2022-02-12 11:00
> Please increase your log buffer size to a large one

[bootlog.txt](https://github.com/topjohnwu/Magisk/files/8053227/bootlog.txt)

**Comment by yujincheng08** [comment] 2022-02-12 11:34
Your log only takes 1M so I think you didn't change your buffer size correctly.

**Comment by ASIMKHAN222** [comment] 2022-02-12 14:01
> Your log only takes 1M so I think you didn't change your buffer size correctly.

okay. i shut down device,
then run this cmd  ``adb wait-for-device logcat > log.txt``
and start device i got this
[log1.txt](https://github.com/topjohnwu/Magisk/files/8053530/log1.txt)

i increased buffer size from developer option

**Comment by yujincheng08** [comment] 2022-02-12 15:57
Maybe you should also need to set the log level to verbose in dev option.

**Comment by Hurairah0** [comment] 2022-02-16 08:42
I have also same problem on my Vivo device.Plz solve it

**Comment by ASIMKHAN222** [comment] 2022-02-16 09:44
> Maybe you should also need to set the log level to verbose in dev option.

Sorry I tried Too Much But Not Succeed.
I Also Tried That Cmd to Get BootLog on Another An oppo Device and Yes It's Working.
But On My Vivo Device It's Failed.
Seems its Only my vivo Device Fault.😑

Have You Any Other Idea?

**Comment by yujincheng08** [comment] 2022-02-16 09:48
I notice your device does not produce debug log. Maybe thats the problem.

**Comment by aIecxs** [comment] 2022-02-19 14:48
similar issue after several downgrades - solved by uninstall + delete /data/adb

**Comment by ASIMKHAN222** [comment] 2022-02-22 18:18
> similar issue after several downgrades - solved by uninstall + delete /data/adb
please guide how to find or access that /data/adb ?

**Comment by aIecxs** [comment] 2022-02-22 19:44
what do you mean? It's the directory where Magisk place stuff. boot in TWRP and remove it

**Comment by patpolster** [comment] 2022-02-22 21:29
> Seems Magisk is working but does not mount /system
> 
> ```
> [init.svc.UJOzq6Pi]: [stopped]
> [init.svc.Yi86JkCAtCpN]: [stopped]
> [init.svc.xP3Bw7bdrFX]: [stopped]
> 3647 3645 0:21 / /dev/uqVV rw,relatime master:4 - tmpfs tmpfs rw,seclabel,size=1911908k,nr_inodes=477977,mode=755
> 3648 3647 0:38 / /dev/uqVV/.magisk/pts rw,nosuid,noexec,relatime master:11 - devpts devpts rw,seclabel,mode=600,ptmxmode=000
> 3649 3647 259:6 / /dev/uqVV/.magisk/mirror/vendor ro,relatime master:12 - ext4 /dev/uqVV/.magisk/block/vendor ro,seclabel
> 3650 3647 259:9 / /dev/uqVV/.magisk/mirror/data rw,relatime master:13 - ext4 /dev/uqVV/.magisk/block/data rw,seclabel,discard,noauto_da_alloc,inlinecrypt,resuid=10010,resgid=1065,errors=panic,data=ordered
> 3651 3647 259:7 / /dev/uqVV/.magisk/mirror/system_root ro,relatime master:40 - ext4 /dev/uqVV/.magisk/block/system_root ro,seclabel
> 3652 3647 259:9 /adb/modules /dev/uqVV/.magisk/modules rw,relatime master:13 - ext4 /dev/uqVV/.magisk/block/data rw,seclabel,discard,noauto_da_alloc,inlinecrypt,resuid=10010,resgid=1065,errors=panic,data=ordered
> ```

**Comment by ASIMKHAN222** [comment] 2022-02-23 07:26
> what do you mean? It's the directory where Magisk place stuff. boot in TWRP and remove it

My device have not any custom recovery, i tried to get but didn't find any compitable Recovery.

**Comment by aIecxs** [comment] 2022-02-23 07:42
just do factory reset? afaik for Mediatek chipset one can just port TWRP from other device

**Comment by ASIMKHAN222** [comment] 2022-02-24 18:55
> just do factory reset? afaik for Mediatek chipset one can just port TWRP from other device

Tried factory Reset Many times But Not worth..
also  tried to port TWRP for my Device but not Succeed.
i also tried Hovatek mediatek Auto TWRP porter good tool for many but not Worked For MT6768 Chipset.
when i flash recovery and try to go to TWRP mode
its just stuck at vivo logo and booted to bootloader/fastboot after a few minutes
i observed there is NO one single TWRP available for MT6768 Chipset.

If you can help
this is recovery logcat after flashing TWRP
[recoverylogcat.txt](https://github.com/topjohnwu/Magisk/files/8135052/recoverylogcat.txt)

**Comment by aIecxs** [comment] 2022-02-25 07:55
If you already factory reset your device it means you already deleted /data/adb therefore your issue is different from mine.
mine was `No daemon is currently running!` after Magisk downgrade

**Comment by ASIMKHAN222** [comment] 2022-03-07 17:18
> Maybe you flashed it to boot_a instead of boot_b?

No Device is A/Only

**Comment by yujincheng08** [comment] 2022-03-22 05:22
> Maybe you should also need to set the log level to verbose in dev option.

**Comment by shivagnihotri** [comment] 2022-03-26 06:18
> Shut down the phone, run `adb wait-for-device logcat > log`, and then start up the phone. After the phone starts, stop the command and send `log`.

Good morning and greetings from Germany to everyone! I am facing the same Issue on my wonderful [SHIFT6mq](https://shop.shiftphones.com/shift6mq.html) running LineageOS 18.1 and hope that my [SHIFT6mq.log](https://github.com/topjohnwu/Magisk/files/8354799/SHIFT6mq.log) will help to confirm and solve this Issue. Namasté. :pray:

**Comment by canyie** [comment] 2022-03-30 09:21
@shivagnihotri I cannot find anything about Magisk in your log, so I think your issue is new. Maybe you should open a new issue for that.

**Closed** 2022-03-30 17:46 UTC
Labels: not enough info
