### ISSUE TITLE
Magisk cannot grant superuser to an application when "Ask for User Authorization" is enabled.

### ISSUE THREAD

**Issue by ccyybn** [topjohnwu/Magisk#8003] opened 2024-04-19 16:00 UTC
Device: Oneplus 7 Pro
Android version: 12
Magisk version name: debug
Magisk version code: 27002

(ColorOS V12.1)

It looks like Magisk didn't know I had already passed the fingerprint or password authorization, and then the superuser request timed out and was rejected.
If I turn off "Request User Authorization" everything works fine.
```
04-19 23:33:45.010 12195 12195 D :  zygisk64: pre  specialize [com.speedsoftware.rootexplorer]
04-19 23:33:45.021 12195 12195 D :  zygisk64: post specialize [com.speedsoftware.rootexplorer]
04-19 23:33:45.414   865   867 D :  su: request from uid=[10753], pid=[12243], client=[14]
04-19 23:33:46.927 12279 12279 D :  zygisk64: pre  specialize [com.oplus.sau]
04-19 23:33:46.950 12279 12279 D :  zygisk64: post specialize [com.oplus.sau]
04-19 23:33:47.217 12325 12325 D :  zygisk64: pre  specialize [com.coloros.phonemanager:idleoptimize]
04-19 23:33:47.243 12325 12325 D :  zygisk64: post specialize [com.coloros.phonemanager:idleoptimize]
04-19 23:33:47.386 12344 12344 D :  zygisk64: pre  specialize [com.android.settings]
04-19 23:33:47.400 12344 12344 D :  zygisk64: post specialize [com.android.settings]
04-19 23:33:47.502 12371 12371 D :  zygisk64: pre  specialize [com.oplus.ota]
04-19 23:33:47.527 12371 12371 D :  zygisk64: post specialize [com.oplus.ota]
04-19 23:33:48.086 12450 12450 D :  zygisk64: pre  specialize [com.oplus.safecenter]
04-19 23:33:48.102 12450 12450 D :  zygisk64: post specialize [com.oplus.safecenter]
04-19 23:33:57.487   865 12280 D :  su: request from uid=[10753], pid=[12522], client=[16]
04-19 23:33:57.504   865 12529 D :  su: request from uid=[10753], pid=[12528], client=[18]
04-19 23:34:09.378   865 12637 D :  su: request from uid=[10753], pid=[12636], client=[20]
04-19 23:34:55.458   865   867 W :  su: request rejected (10753)
04-19 23:35:07.551   865 12529 W :  su: request rejected (10753)
04-19 23:35:07.566   865 12280 W :  su: request rejected (10753)
```

**Comment by ccyybn** [comment] 2024-04-19 16:24
https://github.com/topjohnwu/Magisk/assets/7237501/7947e981-4e54-4e31-9a39-b9b58c169048

**Comment by vvb2060** [comment] 2024-04-19 17:53
Duplicate of #7770

**Closed by vvb2060** 2024-04-19 17:53 UTC
