### ISSUE TITLE
Samsung Galaxy A30 Magisk installation doesn't work well, `userdata` partition down the size!

### ISSUE THREAD

**Issue by hawk8FR** [topjohnwu/Magisk#6192] opened 2022-08-14 20:29 UTC
Device: A305GT Brazil ZTO
Android version: 11R (One UI 3.1) NEWER
Baseband nº (AP/PDA)/CSC: A305GTVJS8CVG1/A305GTOWO8CVA1 NEWER
Ramdisk: NO
Magisk version name: Stable
Magisk version code: 25201

I have no one to turn to and I just a poor/noob user that want to help the community when report a bug. And I know that issue is strictly related with Magisk installation. Without further ado, let me explain.

Since 23 Magisk version with Android 10, I have trouble to install Magisk when following the [default instructions](https://topjohnwu.github.io/Magisk/install.html) , appear the version code at home page, just 'Installed **N/A** '. Although, I was able to install successfully following [this](https://www.recovery-mode.com/root/samsung-galaxy-a30-root-bti1-firmware-with-magisk-v21-0-android-10.html) . As you can see, basically I used the flash zip with TWRP when rename the magisk app .apk to .zip. In the end, in 'Installed' area shows de version code normally, it means the install worked well.

Otherwise, since 24.x alpha & stable (zygisk-based) w/ Android 10 or 11, that's not possible anymore, neither with default instuctions as well. Instead, in this case using Android 11, after several attempts w/ several wipe data, I found a solution when patch the TWRP.img, w/ Magisk Installer app, when check the “Recovery Mode” option. The Magisk installation works well in a way, just need sometimes, after routine reboot, hijack the recovery mode or simple reboot one, two or more times (at 2 methods). Also during the reboot, after show bootloader notif warning, 2 seconds after during shows device logo w/ modified SO warning, it need hold volume up button (NO enter recovery mode) until the device vibrates.

And now, since 25.x stable, neither that's not possible anymore, The 'Installed' info showing always **N/A** . So tired, I've tried everything.

Nonetheless, there's a curious fact since 24.x stable version (until recent version): I did the install using default instructions for Samsung devices w/ NO Ramdisk as always and apparently works well at showing 'Installed' code version, if it wasn't for the fact that my storage down from 64gb to 16gb!! That's insane! For some reason, the installation unnecessarily rezise my `userdata` partition to down, making it practically impossible to use the device these days, when installing many apps we need for example. As expected, I searched over Web and I found a solution [here](https://www.hovatek.com/forum/thread-32750.html) . In my case, I just modified and recreate the `userdata`, formatting exactly as it was before, etx4 and etc. Despite showing any issues in partition, it needed to recreate it. Using only the TWRP without adb commands it's possible to rezise the `userdata` the partition back to original too.

Despite after I fixed the unexpected resize, the Magisk installation is gone again, sadly! In view of that, I'll back to 24.3 w/ TWRP patched w/ Magisk Installer, the only way to use the most updated Magisk until now. Until the developers find a definitive solution for that. And we, the community, will do our best to provide the necessary support. Financial support for example. Then give me your PayPal. I'll share the file attachments. w/ issues evidences by MediaFire folder link. Thanks for advance.

Note: ALL the images and TAR/MD5 files flash processes was made in Odin in Windows 10. All the default ROM files came from Sammobile or other reliable sources.

[attachments link](https://www.mediafire.com/folder/5jf3eqptfc526/topjohnwu-Magisk_unexpected_resize)

**Comment by hawk8FR** [comment] 2022-08-15 00:22
[UPDATE] I tried a wipe/factory reset with stock recovery for `userdata` back to original size. It's done (back to 64gb) but the Magisk installation fails as always. I also tried wipe cache partition but nothing.

**Comment by canyie** [comment] 2022-08-15 00:27
Have you enabled Zygisk before upgrading to v25? Sounds like a duplicate of #6095. The latest CI build may help you. https://github.com/topjohnwu/Magisk/actions/runs/2823053216

**Comment by hawk8FR** [comment] 2022-08-15 00:32
the upgrade for me it's only possible by factory/wipe data and re-flashing ROM and images with Odin. Everytime make a simple upgrade by Magisk Manager the system crashes and needing wipe all the same. The #6095 case this is not for me.

**Comment by hawk8FR** [comment] 2022-08-15 00:36
How can I use these tools?
https://github.com/topjohnwu/Magisk/actions/runs/2823053216
This is the CI build? I'm end user/poor xD

**Comment by pndwal** [comment] 2022-08-15 15:54
Check: 
When Odin flashing
- Flashing all 4 binaries?
-  transferring files using ADP pull, not MTP?

**Comment by hawk8FR** [comment] 2022-08-15 21:28
@pndwal answering your questions:

- I flashed always ALL 4 binaries. When the unexpected resize happens (ALWAYS), I try flash only TWRP recovery patched with Magisk Manager, according my initial text here.
- I ALWAYS transfer files using `adb` `push` and `pull` commands, according [Official Installation Guide](https://topjohnwu.github.io/Magisk/install.html#patching-images).

My main issue is not necessary the 'Installed' status (root) and yes the unexpected resize when following [Samsung installation instructions](https://topjohnwu.github.io/Magisk/install.html#samsung-system-as-root), according the opening comment.

**Comment by pndwal** [comment] 2022-08-15 23:15
👍...
Did you try the CI built? ... Symptoms don't have to be the same across devices for same issue... Canyie will have scrutinized your logs to see issue... Hers will be the best guess...

**Comment by hawk8FR** [comment] 2022-08-16 00:00
@pndwal As I said at @canyie, I just nonprofessional and even don't know What is CI built. Thanks to you and Canyie for your attentions, we gonna find a solution together!

**Comment by pndwal** [comment] 2022-08-16 01:56
Same same... Continuous integration build...

Click the link she gave, scroll to bottom, download artifacts zip, extract and try Magisk build in that... Use debug (for verbose logs etc and certificate check not enforced)...

**Comment by pndwal** [comment] 2022-08-16 02:07
Key fixes merged are:
topjohnwu pushed a commit that referenced this issue [9 days ago](https://github.com/topjohnwu/Magisk/issues/6095#ref-commit-52ba6d1)
@canyie
[Don't let remote errors crash Zygisk](https://github.com/topjohnwu/Magisk/commit/52ba6d11bca116008d8df0c53ffa4942f4f5dc5c) …
[52ba6d1](https://github.com/topjohnwu/Magisk/commit/52ba6d11bca116008d8df0c53ffa4942f4f5dc5c)
Fix https://github.com/topjohnwu/Magisk/issues/6095

and
topjohnwu pushed a commit that referenced this issue [8 days ago](https://github.com/topjohnwu/Magisk/issues/6095#ref-commit-1735a71)
@canyie
[Use ANDROID_DLEXT_FORCE_LOAD to load second stage if possible](https://github.com/topjohnwu/Magisk/commit/1735a713cbb05fdca3abad243f1223e5262071a0) …
[1735a71](https://github.com/topjohnwu/Magisk/commit/1735a713cbb05fdca3abad243f1223e5262071a0)
Fix https://github.com/topjohnwu/Magisk/issues/6095

**Comment by pndwal** [comment] 2022-08-16 04:09
... just scanned your issue again... Noticed 

> Since 23 Magisk version with Android 10, I have trouble to install Magisk when following the [default instructions](https://topjohnwu.github.io/Magisk/install.html) , appear the version code at home page, just 'Installed N/A '. Although, I was able to install successfully following [this](https://www.recovery-mode.com/root/samsung-galaxy-a30-root-bti1-firmware-with-magisk-v21-0-android-10.html) . As you can see, basically I used the flash zip with TWRP when rename the magisk app .apk to .zip. In the end, in 'Installed' area shows de version code normally, it means the install worked well.
> Otherwise, since 24.x alpha & stable (zygisk-based) w/ Android 10 or 11, that's not possible anymore...

Interesting that you can use .zip install at all as this always installs Magisk in boot partition; indicates Magisk installation w/o recovery mode selected should work on your as if ramdisk=yes... Unless a bootloader update has changed this since... Nb. Most Xiaomi and a few Sammy devices w/ Ramdisk=no have compatible bootloaders and allow Magisk in boot...

Regarding default (for your A-only legacy SAR device) Magisk in Recovery partition:

Are you following official instructions for twrp w/ magisk? includes:

> You are therefore strongly advised to first root your device with Magisk and then pre-root a TWRP image before flashing it to recovery....
https://twrp.me/samsung/samsunggalaxya30.html

... In other words, you root twice... Doc. Gives further reasons / cautions...

Is Installed=N/A simply due to failure to boot to recovery mode? Note:

You need to enter modes inc. recovery with the new key-combo requirement on Sammy devices (OneUI) to also have usb connection active... (This changed with Android 11, now you need to plug the USB-C / micro-USB cable along with the combination buttons... Use an active PC connection, or, reportedly, a usb headset will do.)

**Comment by vvb2060** [comment] 2023-03-14 07:49
https://github.com/topjohnwu/Magisk/blob/fe6b658c028e30f2972dd854b02ef2dd9a99d5b7/docs/install.md?plain=1#L128

Nothing to do with Magisk, we can't fix odin's issues.

**Closed by vvb2060** 2023-03-14 07:49 UTC
Labels: needs investigation

**Comment by canyie** [comment] 2023-03-14 07:51
Btw, you can try flashing by [heimdall](https://www.glassechidna.com.au/heimdall/) instead of Odin
