### ISSUE TITLE
Storage Options are grayed out in apps

### ISSUE THREAD

**Issue by bggold** [topjohnwu/Magisk#1109] opened 2019-02-20 21:11 UTC
With Magisk Hide enabled since build v18.2-e5940168(18105) in app storage options the clear storage and clear cache are grayed out.  Also storage size and cache size are all reporting 0. 

Does not happen with Magisk Hide disabled.

So far confirmed on Feb update with stock and several custom roms and all custom kernels.

Does not appear to happen if running Jan kernel or any custom kernel build before Feb source was available.

Have not confirmed if it is occurring with Jan update.

Thanks

**Comment by jancm** [comment] 2019-02-21 02:51
Can confirm that kernels built on January sources don't display the issue whereas February sources do. (Kirisakura_Bluecross_2.0.4_Release vs Kirisakura_Bluecross_2.0.5_Release)

**Comment by keyute** [comment] 2019-03-07 17:26
I have also experienced this issue on the latest canary build as of this writing, March security update pixel 3 xl stock rom

**Comment by topjohnwu** [comment] 2019-03-08 03:07
Yeah, but I dunno why LOL, need to check what's going on

**Comment by HamsterHam88** [comment] 2019-03-09 17:04
Confirmed on latest canary version on my Crosshatch running DU.

**Comment by Unspec7** [comment] 2019-04-02 04:09
Confirmed on March security update on Pixel 3 XL

**Comment by jancm** [comment] 2019-04-02 17:52
April security update + Magisk 19 + Kirisakura kernel (which is unchanged from March) and this issue appears to be resolved.
I didn't check when I first installed v19 but I suspect that's where the fix came from.

**Comment by monzta** [comment] 2019-04-05 09:24
This started to happen for me after a recent factory reset, April update and installing Magisk 19 on my Pixel 3. This time I installed it via TWRP for the first time, before I used to do it via patched boot image. I don't know if I had this issue right away after flashing Magisk or after playing around with Magisk Hide. Currently I have hidden Google Play, Google Pay, Google Play Services (`com.google.android.gms.unstable` switch only) and a few other non-Google apps. Let me know if I can help in any way!

**Comment by yung40oz84** [comment] 2019-04-07 15:38
Ok so I have this odd bug. Whenever I install the systemless hosts module from the Magisk settings and reboot my device ALL my apps say no user data, and no cache, and the options to clear that are greyed out. I tested this multiple times, using only that module, doing modules 1 by 1, etc. so I am 100% certain it is that module. It also happens with the edge sense module, and Ainur audio module as well. This happens also on Magisk 19.0 and the Canary builds. I did not test 18.1 Magisk. I attached images of what it looks like before and after the module is installed and also the logs. Please let me know if anything else is needed.

This is April factory image, stock kernel, Pixel 3 XL, so it's not resolved. But for me it only happens when those specific modules are installed. The only thing I hide is the 2 Google play services needed for pay to work. I posted logs on the XDA canary thread if needed.

**Comment by bggold** [comment] 2019-04-07 15:51
This is a bug with magiskhide and topjohnwu is aware and has confirmed it.  There is an issue already open for it.

Disable magisk hide and it does not do it just as a test.

**Comment by jancm** [comment] 2019-04-09 03:55
I was wrong, Magisk 19 did not solve the issue. However Kirisakura starting with version 2.1.2 (current is 2.2.0) fixes this issue. Stock still shows the issue.

**Comment by yung40oz84** [comment] 2019-04-09 19:02
Yes that you are right about. I am also running Kirisakura 2.2.0 and it is fixed with that kernel. Stock kernel it is broke on Magisk 19.0 and Canary

**Comment by topjohnwu** [comment] 2019-04-11 03:50
This issue only occurs on stock kernel on Pixel 3 (XL). I have no idea what breaks it.

**Comment by Unspec7** [comment] 2019-04-13 02:40
> 
> 
> This issue only occurs on stock kernel on Pixel 3 (XL). I have no idea what breaks it.

I am running elementalx 1.06 and it is broken.

**Comment by Duh-Cynic** [comment] 2019-04-13 19:56
> > This issue only occurs on stock kernel on Pixel 3 (XL). I have no idea what breaks it.
> 
> I am running elementalx 1.06 and it is broken.

And on ex 1.0.6. runs fine on kirisakura 2.2.0

**Comment by Jasi2169** [comment] 2019-04-27 06:06
EXTRA INFO :- no issue on samsung stock pie roms april 01 security patch

**Comment by kcschan** [comment] 2019-05-07 05:32
Magisk version: 19.1(19100)
Magisk manager version: 7.1.2(208)

This issue occurs on Pixel 3XL with April patch(9.0.0 (PQ2A.190405.003, Apr 2019)), while it is not observed on Pixel2 with April patch(9.0.0 (PQ2A.190405.003, Apr 2019)).

This issue dissappears if magisk Hide is turned off.

I will upgrade to May patch to see whether this issue could be disappeared with magisk hide enabled.

**Comment by kcschan** [comment] 2019-05-07 07:10
After upgrading to May patch:

PQ3A.190505.002 for Pixel 3XL
PQ3A.190505.001 for Pixel 2

This issue is acts the same as before(occurs in Pixel 3XL with magisk hide enabled only)

**Comment by AaronKeener** [comment] 2019-06-04 04:18
Just a quick thought, maybe the Pixel 3's Titan M chip has something to do w/ this issue ?

**Comment by topjohnwu** [comment] 2019-06-05 17:34
@AaronKeener no, it is something to do with the F2FS driver in Pixel's kernel

**Comment by AaronKeener** [comment] 2019-06-05 17:41
Oh, kinda problematic tho

**Comment by HamsterHam88** [comment] 2019-06-05 17:55
If you flash Kirisakura kernel the storage options work again. Only way to fix it I've found.

**Comment by monzta** [comment] 2019-06-05 18:03
Or not enabling the systemless hosts module works as well.

**Comment by vonDubenshire** [comment] 2019-06-23 05:26
This still exists. New to Magisk and found this thread today.

**Comment by bengalih** [comment] 2019-06-24 04:10
Also having this issue on the June update running 19.3 Magisk and 7.3.2 Manager.
Only have the YouTube Module installed, but do have Hide enabled.
Disabling Hide and rebooting solves the issue.

Work around is 3rd party app like TitaniumBackup which can wipe data (i.e. Clear Storage).

Would be interested in an update if this is something that is looking at being fixed soon or has an underlying issue that can't be resolved?

I don't really want to move to an alternate kernel, but am concerned about core OS features being disabled by the Magisk options.

**Comment by Didgeridoohan** [comment] 2019-06-24 08:25
@bengalih Take a look at the labels for the issue: "Confirmed" and "wontfix". The latter label should answer your question.

**Comment by topjohnwu** [comment] 2019-07-01 02:26
This kernel bug is fixed upstream in F2FS, and confirmed no longer exist on Android Q, so there is nothing I need to fix this issue.

**Closed by topjohnwu** 2019-07-01 02:26 UTC
Labels: Confirmed, wontfix
