### ISSUE TITLE
New UI confusing?

### ISSUE THREAD

**Issue by gene-pavlovsky** [topjohnwu/Magisk#3944] opened 2021-02-26 09:55 UTC
I've been using Magisk for a couple of years already. After initial setup everything was smooth and I didn't have to touch it or adjust any setting. I've had to add a banking app (BIL DigiCash) to the MagiskHide list, otherwise it would refuse to start because it somehow detected my device is rooted. As I remember, the Hide list was selected in the slide-out menu on the left.

A few days ago I've had an issue while upgrading to Magisk 22.0, my LG V30 got stuck in fastboot mode. I managed to get to TWRP and fix the issue by flashing Magisk uninstaller, stock ROM (without wiping), and then Magisk 22.0. Just the Magisk settings got lost in the process. With the new UI, I've had a difficult time figuring out how to access the Hide list. I was about to give up when I noticed those small icons in the bottom (which are only visible when the Home screen is scrolled to the top).

Maybe it's just me being stupid or outdated, and this is the trendy/modern way of doing things, but wasn't the old slide-out menu more intuitive?

**Comment by palmbeach05** [comment] 2021-02-26 18:20
The UI has been that way for a while now. I think, and its entirely up to topjohnwu, but perhaps have the shortcuts tray (that's just what I call it) visible at the bottom of the screen at all times instead of just when one scrolls up. But then again, as the tray shows up at the slightest scroll up movement, its kind of hard to miss something popping up on your screen, even in dark mode

**Comment by techIndia-hacker** [comment] 2021-02-27 09:13
Close this kind of issues. He doesn't really take user feedback😂

**Comment by Haus3master** [comment] 2021-02-27 12:39
> Close this kind of issues. He doesn't really take user feedback😂

He does, but, since he already mentioned that the manager ui is not being developed by him, so, I guess we really can't blame @topjohnwu for this, and, anyways, of people request it and support this project enough to put more time into it, then we might see a difference...

**Comment by karibertils** [comment] 2021-03-01 11:12
For me root is working fine. But I am also having issues finding MagiskHide and other features... Any ideas where they are?

![Screenshot_20210301-110834_Magisk](https://user-images.githubusercontent.com/5122320/109489412-be2cb100-7a7e-11eb-8fc8-9f195be5ee78.png)
![Screenshot_20210301-110827_Magisk](https://user-images.githubusercontent.com/5122320/109489421-c08f0b00-7a7e-11eb-8fee-9c61f6eb98e7.png)

**Comment by gene-pavlovsky** [comment] 2021-03-01 11:23
> For me root is working fine. But I am also having issues finding MagiskHide and other features... Any ideas where they are?

Your giant screenshots hurt my eyes...
You have to be on the home page (not the settings), scroll to the top, you will see a row of small icons on the bottom, these are for navigating between pages. The second icon allows you to access the hide list.

**Comment by karibertils** [comment] 2021-03-01 11:42
Sorry about that @gene-pavlovsky, didn't realize how big they were. I resized them now.

The only thing I can access at the top is the settings gear icon. Scrolling up/down does not work on either page.

**Comment by Didgeridoohan** [comment] 2021-03-01 12:04
@karibertils Your screenshot shows that Magisk isn't installed (N/A). If root access still works despite that you probably have two Magisk apps installed: https://www.didgeridoohan.com/magisk/Magisk#hn_There_are_two_Magisk_app

**Comment by gene-pavlovsky** [comment] 2021-03-01 12:20
@karibertils
![Capture+_2021-03-01-12-44-48](https://user-images.githubusercontent.com/2841193/109496404-e4f3e300-7a90-11eb-8df0-64d40b69fcd3.png)

Here's the UI I'm talking about

**Comment by karibertils** [comment] 2021-03-01 12:23
@gene-pavlovsky Yep that menu doesn't show. Must be because because of the ```Installed: N/A```

@Didgeridoohan That makes sense, It did happen after I somehow lost root when I had repackaged Magisk installed. I did then uninstall the repackaged Magisk app. Went to TWRP and installed Magisk again. Since then root worked again, but the options are missing.

The old repackaged Magisk is nowhere to be seen, but seems parts of it are still installed & conflicting with current Magisk.

I have tried flashing uninstall.zip to remove Magisk and then reinstalled, which of course did not help. I have also tried removing /data/adb/magisk.db and various other files I believe are leftovers and reinstalled Magisk. Which also did not help.

Any ideas how to cleanup this mess ?

**Comment by gene-pavlovsky** [comment] 2021-03-01 13:24
@karibertils I've got a boot loop trying to install the 22.0 update. What fixed the issue for me was to flash Magisk uninstaller, flash (stock) ROM again (without wiping anything), flash Magisk 22.0 (apk renamed to zip), wipe cache/dalvik, reboot. If you need further help, perhaps open another issue? Let's keep this one on topic :)

**Comment by RikkaW** [comment] 2021-03-04 05:47
![image](https://user-images.githubusercontent.com/12999176/109917202-df480880-7cef-11eb-99fc-f19334ea5d51.png)
Some attempts 😋

**Comment by androidacy** [comment] 2021-03-24 16:16
> @gene-pavlovsky Yep that menu doesn't show. Must be because of the `Installed: N/A`
> 
> @Didgeridoohan That makes sense, It did happen after I somehow lost root when I had repackaged Magisk installed. I did then uninstall the repackaged Magisk app. Went to TWRP and installed Magisk again. Since then root worked again, but the options are missing.
> 
> The old repackaged Magisk is nowhere to be seen, but seems parts of it are still installed & conflicting with current Magisk.
> 
> I have tried flashing uninstall.zip to remove Magisk and then reinstalled, which of course did not help. I have also tried removing /data/adb/magisk.db and various other files I believe are leftovers and reinstalled Magisk. Which also did not help.
> 
> Any ideas how to cleanup this mess ?

You can fix that by deleting any magisk packages, removing /data/adb/magisk.db and rebooting.

The problem is that the new repackaged magisk's info gets into the db without the new package being ready and working

**Comment by osm0sis** [comment] 2021-03-24 17:38
#3249

**Closed by osm0sis** 2021-03-24 17:38 UTC
Labels: duplicate
